### ISSUE TITLE
Forgotten Realms Campaign Setting list Suffering Properties under Strength Domain

### ISSUE THREAD

**Issue by michalgm** [BahamutDragon/pcgen#1000]
In the book, strength domain just lists the deities, and no spells. However, the source list file is listing the power (pain touch) + domain spells (bane, endurance, etc) for the Suffering domain, which appears next in the book. I think the strength line should just be removed entirely so it picks up the player's handbook version.

**Comment by BahamutDragon** [comment]
Removed the entry.
