### ISSUE TITLE
Players Handbook 2 Shield Specilization

### ISSUE THREAD

**Issue by tonybrown3** [BahamutDragon/pcgen#1002]
I can not get Shield Specialization to change my AC on the character sheet.  From what i see it does not work with LIST.  If i remove that and put ShieldProfLight it works for light shields.  But I have not found any variation of CHOOSE, CHOICE, or BONUS:VAR that will allow me to change that bonus focus while the program is running.

**Comment by BahamutDragon** [comment]
Should be fixed in 6.08 now. I'll push to master in a few minutes.
