### ISSUE TITLE
5e Artificer spell slot problems

### ISSUE THREAD

**Issue by FoxShot** [BahamutDragon/pcgen#1003]
I've been trying to root out the problem with the available spell slots in the rftlw_abilities.lst and could just narrow it down to Caster Spell Slots ~ Artificer not working for some reason. The SpellSlotsLVLX wont get the values assigned.

Also because there is no Artificer ~ Spellcasting Ability the defining of the ArtificerCastX variables wont work. Previously for every casters in PH (except cleric) the variables are assigned to just the Spellcasting.

I've spent few days on learning and trying to fix this but I've decided to brute force the slots for now as I'm creating a PC artificer and need them now.

**Comment by BahamutDragon** [comment]
Fixed and pushed to both branches.
