### ISSUE TITLE
3.5 Eberron education feat not working 

### ISSUE THREAD

**Issue by Greg0rL** [BahamutDragon/pcgen#1004]
After picking the feat education at level 1, the knowledge skills do not change to being class skills, and as far as I can tell there is no way to set the two knowledge skills that I want to have the +1 bonus on.

Pictures added for reference.

![image](https://user-images.githubusercontent.com/71985246/94372999-26571f80-00fa-11eb-96f3-833ecfc6ab61.png)
![image](https://user-images.githubusercontent.com/71985246/94373017-438bee00-00fa-11eb-9b13-e9c2f7f31f31.png)

**Comment by BahamutDragon** [comment]
Fixed on both branches.
