### ISSUE TITLE
All PCs in the Eberon 35e Campain Setting Races File are missing MOVE, FACE and REACH  

### ISSUE THREAD

**Issue by swtrse** [BahamutDragon/pcgen#1009]
File: data\35e\wizards_of_the_coast\campaign_settings\eberron\campaign\ecs_races.lst

MOVE, FACE and REACH entries are missing for all Races in the file.
The MOVE for Warforged is even set to 0 explicitly.

This is most noticable in the -18 modifier at the Jump skill.

Suggestion:
Add  "MOVE:Walk,30	FACE:5	REACH:5" to each of the races.

**Comment by BahamutDragon** [comment]
Fixed.
