### ISSUE TITLE
[5e][Bug] Triton Innate Spell Missing Description

### ISSUE THREAD

**Issue by Proxxy0** [BahamutDragon/pcgen#1011]
When you reach 5th level as a Triton, you are given the spell Wall of Water as a part of your racial traits. While you are given the spell once you create a triton at 5th level, the entire description, as well as the range and casting time, are completely missing.

**Comment by Proxxy0** [comment]
Here is a screenshot of the Triton Innate Spellcasting abilities table: 
![image](https://user-images.githubusercontent.com/24647397/99703816-92ecfb80-2a65-11eb-868a-89fde46d35b5.png)

**Comment by BahamutDragon** [comment]
The only difference is Wall Of Water vs. Wall of Water. Those should not be case sensitive. 

Please test the PR I pushed in.

**Comment by Proxxy0** [comment]
I pulled it and reopened the character, but it doesn't look like it changed anything.

The Triton Innate Spellcasting abilities table after reloading the sources looks like this:
![image](https://user-images.githubusercontent.com/24647397/99884209-661e1d00-2bfa-11eb-9c0b-f0ac2f6af9ab.png)

I checked the files to make sure I pulled the right branch (and pulled it successfully), and all the edits were there. Could it be due to multiple instances of the same key? The spell should be pulling from EE, but it looks like it's trying to pull from Xanthar's (just a thought).

**Comment by BahamutDragon** [comment]
I am getting the correct display with the master branch using 6.09.05 - 
![image](https://user-images.githubusercontent.com/4307487/100161371-28bdc780-2e66-11eb-9138-61600d1ae6fd.png)

**Comment by Proxxy0** [comment]
I have reinstalled both PCGen and the master branch, but it is still blank for me, on both new and old Triton characters.

Maybe it's an issue with what sources are being used?

I have attached the Triton character file that sparked this issue.
[Lucien Snow.zip](https://github.com/BahamutDragon/pcgen/files/5593825/Lucien.Snow.zip)

**Comment by BahamutDragon** [comment]
After cleaning up all the load errors, this is what I see when I open the character:

![image](https://user-images.githubusercontent.com/4307487/103181865-eb7c9900-485a-11eb-92d5-4ea5b8903431.png)

I believe all the errors I had to clean up may have contributed to your issue.

**Comment by Proxxy0** [comment]
Thanks a ton! Everything seems to be working now. I absolutely love this project/community.
