### ISSUE TITLE
Wrong familiar selection for 3.5e Dread Necromacer from Heroes of Horror

### ISSUE THREAD

**Issue by tivv** [BahamutDragon/pcgen#1013]
It proposes a standard list and should propose Dread Necromancer ones (imp, etc). File seems to have the list but it's not picked up for whatever reason
```
COMPANIONLIST:Familiar|Familiar (Demon (Quasit)),Familiar (Devil (Imp)),Familiar (Ghostly Visage),Familiar (Vargouille)
```

**Comment by BahamutDragon** [comment]
Set a disable flag to remove the old familiar list, fixed the category and type to allow the player to choose the familiar.

Please test and confirm.

**Comment by tivv** [comment]
Unfortunately now the list is empty

**Comment by BahamutDragon** [comment]
Try again, this forces the selection.

**Comment by tivv** [comment]
Still same. Anything I can try / get logs?
![image](https://user-images.githubusercontent.com/425183/100043979-5d2c7780-2dc3-11eb-8356-f54dd938f8b8.png)

**Comment by tivv** [comment]
Also I don't see any diff between 
c3111e0 and 
1647005:
```
tivv@tivv-dell:~/pcgen/Bahamut/pcgen$ git diff c3111e028e7efed44306ee402ea61c850e1b9586 16470051d061767a85b28bc1fdfdb43de632e7bd -- data/35e/wizards_of_the_coast/core/players_handbook/ph_abilities.lst data/35e/wizards_of_the_coast/supplement/heroes_of_horror/hh_abilities.lst
tivv@tivv-dell:~/pcgen/Bahamut/pcgen$ 
```

**Comment by BahamutDragon** [comment]
Can you provide your character file? I would like to test this and see what is happening.

**Comment by tivv** [comment]
Sure, see attached

[for.zip](https://github.com/BahamutDragon/pcgen/files/5591799/for.zip)

**Comment by BahamutDragon** [comment]
I load up the character and go to add a familiar and this is what I get: 
![image](https://user-images.githubusercontent.com/4307487/100157241-10967a00-2e5f-11eb-8e57-b821496b3752.png)

**Comment by tivv** [comment]
Which PCGEN version / this repo commit are you on?

**Comment by tivv** [comment]
Found! With d1dba45c95ddd8e50b8b8fca10dc669462063a6a it works. This commit was not referenced in the bug, so I was testing with c3111e0 that do not have changes

**Comment by tivv** [comment]
For reference: it works on the https://github.com/BahamutDragon/pcgen/tree/6.08 branch

**Comment by tivv** [comment]
The only minor glitch is that it asks for HP roll on creation even though HP is defined automatically as 50% of masters. It calculates HP right anyway

**Comment by BahamutDragon** [comment]
That's a preference setting perhaps, but a program issue. I do not control the UI mechanics.

**Comment by tivv** [comment]
Yep, I've checked with a regular wizard familiar. It also asks for HP roll, so it's a general pcgen glitch.
