### ISSUE TITLE
[3.5] Silver Badge of Larethian should increase caster level

### ISSUE THREAD

**Issue by tivv** [BahamutDragon/pcgen#1014]
It's description says 

> When displayed while casting Protection domain or abjuration spells, a silver badge of Larethian increases your effective caster level by 1.)

But it does not look like this quality is applied when it's equiped.
It's from data/35e/wizards_of_the_coast/supplement/complete_champion/cc_equip.lst

**Comment by BahamutDragon** [comment]
Updated to include the bonus.
