### ISSUE TITLE
Book Request 5E - Curse of Strahd

### ISSUE THREAD

**Issue by Thorngage** [BahamutDragon/pcgen#1015]
Hi Bahamut!
I don't know if this was already requested or if this is even the right place to ask this stuff, but I would love to see the Curse of Strahd Added to the repository.
I contributed a bit on the project in the past with small fixes and I would do it myself, if I had the slightest idea on how to implement a whole book.

I hope you're having amazing Holidays!

**Comment by BahamutDragon** [comment]
Adventure modules rarely have much to add. In this case a new background, a few items, and some trinkets.

**Comment by BahamutDragon** [comment]
I have not tested this quite yet, but there you go.

**Comment by Thorngage** [comment]
Awesome, thanks!

**Comment by BahamutDragon** [comment]
Pushed another patch to fix the errors. Should be good.
