### ISSUE TITLE
5e_Changeling Skills for Barbarians

### ISSUE THREAD

**Issue by Thorngage** [BahamutDragon/pcgen#1017]
At the moment, if you create a Barbarian character, you get prompted to choos the Changeling Instincts Skills. I think I found the problem, in line 11 of the file 
- data\5e\wizards_of_the_coast\supplement\unearthed_arcana\races_of_eberron\ua_abilitycategories.lst

Where it specifies the pool of the Instincts to be a POOL_Barbarian_Skill

Modifying that removes the choice from the barbarian but breaks the choice for changeling characters, and I don't know enough about code to learn how to fix that. Also, I modified it into POOL_Changeling_Skill (probably doesn't exist), but now I notice that when I create a changeling character, in addition to having the Instincts empty, I also see empty choices for Barbarian Skill, Class feature and primal path...

I'm sorry I couldn't fix it on my own

**Comment by BahamutDragon** [comment]
Just remove it. Should work now.

**Comment by Thorngage** [comment]
Awesome, Thanks!
