### ISSUE TITLE
5e Soulknife Rogue Subclass Request 

### ISSUE THREAD

**Issue by KatsuKarazaki** [BahamutDragon/pcgen#1018]
Hey, I was wanting to ask if you could add the rogue subclass Soulknife by Tasha's Cauldron of Everything? I wanted to use PCgen to build my backup character and the subclass I wanted to use was unavailable. I couldn't find a pdf but there is a Wikidot page for the subclass.                 http://dnd5e.wikidot.com/rogue:soulknife

**Comment by BahamutDragon** [comment]
Added
