### ISSUE TITLE
pcgen fails to load sources

### ISSUE THREAD

**Issue by upspiral89** [BahamutDragon/pcgen#1019]
I've tried to load the 6.08 branch on the same version of pcgen but while it's loading the sources the process fails on mm_kits.lst

Here's my log file

18:22:45.494 INFO Thread-4 SourceFileLoader:534 Loading game Bahamut35e and sources [Dungeons & Dragons - Core Books, Secrets of Sarlona, Expanded Psionics Handbook, Fiend Folio, Fiendish Codex II, Faiths and Pantheons, Into the Dragon's Lair, Pool of Radiance, Attack on Myth Drannor, Frostburn, Heroes of Battle, Heroes of Horror, Libris Mortis: The Book of the Dead, Magic Item Compendium, Magic of Incarnum, Miniatures Handbook, Monster Manual II, Monster Manual III, Player's Handbook II, Races of Destiny, Races of Eberron, Races of Stone, Sandstorm, Savage Species, Spellbook Archive, Spell Compendium, Stormwrack, Arms and Equipment Guide, Book of Exalted Deeds, Book of Vile Darkness, Complete Adventurer, Complete Arcane, Complete Champion, Complete Divine, Complete Mage, Complete Psionic, Complete Scoundrel, Swiftblade, The Mind's Eye, Tome of Battle: The Book of Nine Swords, Tome of Magic, Unearthed Arcana (Complete), Dragonlance Campaign Setting, Eberron Campaign Setting, Ghostwalk (35e conversion), Oriental Adventures, Player's Guide to Faerun, Complete Warrior, Draconomicon, Dragon Magic, Drow of the Underdark, Dungeon Master's Guide II, Dungeonscape, Epic Level Handbook, Fey Feature, Champions of Ruin, City of Splendors: Waterdeep, Dragons of Faerun - Web Enhancement - City of Wyrmshadows, Lost Empires of Faerun, Magic of Faerun, Monster Compendium: Monsters of Faerun, Races of Faerun, Shining South, Unapproachable East, Underdark, Lords of Madness, Races of the Dragon, Races of the Wild, Cityscape: An Essential Guide to Urban Adventuring, Weapons of Legacy, Deities and Demigods, Champions of Valor].
18:22:45.968 LSTWARN Thread-4 Description:134 The % without a number in the description 'Once per day as a swift action, you can shroud yourself in a mantle of air. This effect grants you a +1 sacred (if your deity is good or neutral) or profane (if your deity is evil) bonus to AC. This bonus increases by 1 for every four character levels you possess (maximum +6 at 20th level). In addition, thrown and projectile weapons have an automatic 50% miss chance against you while the air mantle is active. This protection lasts for 1 minute. Special: You can select this feat multiple times, gaining one additional daily use each time you take it. Special: If you have the ability to turn or rebuke undead, you gain one additional daily use of this feat for each three daily turn or rebuke uses you expend.' should be either escaped e.g. %% or made into a parameter reference e.g. %1 .
18:22:45.970 LSTWARN Thread-4 Description:134 The % without a number in the description 'Whenever you cast a lst-level or higher conjuration (healing) spell, you not only heal your subject of hit point damage, but you also confer on it a carrier effect deriving from a domain to which you have access. If you have access to more than one of the following domains, choose which carrier effect to use each time you use this ability. Each of these carrier effects has a duration of 1 minute per level of the conjuration (healing) spell cast and an equivalent spell level. If you are using domains from publications other than the Player's Handbook, use the Domains from Publications Other Than the Player's Handbook sidebar on page 53 to determine an appropriate domain equivalency. 
Air: Electricity resistance 5. 
Animal: Scent ability. 
Chaos: +2 sacred (if your deity is good or neutral) or profane (if your deity is evil) bonus on a randomly determined ability score. 
Death: +4 on saving throws against death effects. 
Destruction: +2 sacred (if your deity is good or neutral) or profane (if your deity is evil) bonus on melee damage rolls. 
Earth: Acid resistance 5. 
Evil: DR 3/good. 
Eire: Fire resistance 5. 
Good: DR 3/evil. 
Healing: 1 temporary hit point per level or HD. These temporary hit points last for up to 1 hour. 
Knowledge: +2 insight bonus on skill and ability checks. 
Law: +4 sacred (if your deity is good or neutral) or profane (if your deity is evil) bonus on saving throws against mind-affecting spells or spell-like abilities. 
Luck: When rolling for damage, treat any die roll result of 1 as 2, unless 1 is the maximum result possible. 
Magic: +2 sacred (if your deity is good or neutral) or profane (if your deity is evil) bonus on saves against spells and spelllike abilities. 
Plant: Light fortification (25% chance to avoid extra damage from critical hits and sneak attacks). 
Protection: +2 sacred (if your deity is good or neutral) or profane (if your deity is evil) bonus to AC when fighting defensively. 
Strength: +2 on damage rolls with any melee attack. 
Sun: Low-light vision; +2 sacred (if your deity is good or neutral) or profane (if your deity is evil) bonus on Spot checks. 
Travel: +5-foot bonus to base land speed. 
Trickery: +6 sacred (if your deity is good or neutral) or profane (if your deity is evil) bonus on Bluff checks. 
War: +1 on attack rolls with weapons (not natural weapons). 
Water: +6 sacred (if your deity is good or neutral) or profane (if your deity is evil) bonus on Swim checks. 
Special: When you use a conjuration (healing) spell to deal damage to a target, you cannot confer one of these carrier effects on that target. 
Special: Different carrier effects can affect the same target concurrently, even if the domains are normally opposed in nature (Law/Chaos, Good/Evil, and so forth). 
Special: If your conjuration (healing) spell affects multiple creatures, you can choose only one carrier effect per casting. All targets are subject to that same effect.' should be either escaped e.g. %% or made into a parameter reference e.g. %1 .
18:22:45.971 LSTWARN Thread-4 Description:134 The % without a number in the description 'Once per day as an immediate action, you can force your body to take on plant characteristics. Your skin becomes brown and barklike, your hair becomes leafy, and your blood oozes like sap. This effect lasts for 1 minute. While in this form, your natural armor bonus increases by 2. In addition, you gain light fortification (25% chance to ignore extra damage from critical hits and sneak attacks). The resistance chance granted by this fortification effect increases to 50% when you attain 10th level and to 75% when you attain 15th level. At 20th level, you gain heavy fortification (immune to critical hits and sneak attack damage) while in this form. 
Special: You can select this feat multiple times, gaining one additional daily use each time you take it. 
Special: If you have the ability to turn or rebuke undead, you gain one additional daily use of this feat for each two daily turn or rebuke uses you expend.' should be either escaped e.g. %% or made into a parameter reference e.g. %1 .
18:22:45.971 LSTWARN Thread-4 Description:134 The % without a number in the description 'Once per day as an immediate action, you can force your body to take on plant characteristics. Your skin becomes brown and barklike, your hair becomes leafy, and your blood oozes like sap. This effect lasts for 1 minute. While in this form, your natural armor bonus increases by 2. In addition, you gain light fortification (25% chance to ignore extra damage from critical hits and sneak attacks). The resistance chance granted by this fortification effect increases to 50% when you attain 10th level and to 75% when you attain 15th level. At 20th level, you gain heavy fortification (immune to critical hits and sneak attack damage) while in this form. 
Special: You can select this feat multiple times, gaining one additional daily use each time you take it. 
Special: If you have the ability to turn or rebuke undead, you gain one additional daily use of this feat for each two daily turn or rebuke uses you expend.' should be either escaped e.g. %% or made into a parameter reference e.g. %1 .
18:22:45.971 LSTWARN Thread-4 Description:134 The % without a number in the description 'Once per day as an immediate action, you can force your body to take on plant characteristics. Your skin becomes brown and barklike, your hair becomes leafy, and your blood oozes like sap. This effect lasts for 1 minute. While in this form, your natural armor bonus increases by 2. In addition, you gain light fortification (25% chance to ignore extra damage from critical hits and sneak attacks). The resistance chance granted by this fortification effect increases to 50% when you attain 10th level and to 75% when you attain 15th level. At 20th level, you gain heavy fortification (immune to critical hits and sneak attack damage) while in this form. 
Special: You can select this feat multiple times, gaining one additional daily use each time you take it. 
Special: If you have the ability to turn or rebuke undead, you gain one additional daily use of this feat for each two daily turn or rebuke uses you expend.' should be either escaped e.g. %% or made into a parameter reference e.g. %1 .
18:22:45.972 LSTWARN Thread-4 Description:134 The % without a number in the description 'As long as you have a 3rd-level or higher darkness spell available to cast, shadows and darkness appear to obey your will. As a standard action, you can direct these shadows to obscure the vision of one foe within 30 feet. If your target fails a Will save, its attacks have a miss chance equal to 5% per level of the highest-level darkness spell you have available to cast. This effect lasts until the beginning of your next action. 
Creatures that do not rely on sight are unaffected by this effect, and those with Blind-Fight or similar abilities can fight as they normally would. 
As a secondary benefit, you gain darkvision out to 10 feet. If you already have darkvision, its range increases by 10 feet.' should be either escaped e.g. %% or made into a parameter reference e.g. %1 .
18:22:46.675 LSTERROR Thread-4 LstUtils:147 PRERACE arguments may not start with , : ,1,Gloaming (Source: file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/campaign_settings/forgotten_realms/underdark/und_abilities.lst )
18:22:46.675 LSTERROR Thread-4 LstUtils:147 Failed in parsing typeStr: PRERACE ,1,Gloaming for pcgen.core.Ability Gloaming Region
18:22:46.675 LSTERROR Thread-4 LstUtils:147 Illegal Token 'PRERACE' ',1,Gloaming' for pcgen.core.Ability Gloaming Region in file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/campaign_settings/forgotten_realms/underdark/und_abilities.lst
18:22:46.678 SEVERE Thread-4 LstObjectFileLoader:419 Errore durante il parsing del file file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/campaign_settings/forgotten_realms/underdark/und_feats.lst linea 23: null
java.lang.NullPointerException
	at pcgen.rules.persistence.token.PreCompatibilityToken.parseToken(PreCompatibilityToken.java:63)
	at pcgen.rules.persistence.token.PreCompatibilityToken.parseToken(PreCompatibilityToken.java:34)
	at pcgen.rules.persistence.TokenSupport.processClassTokens(TokenSupport.java:132)
	at pcgen.rules.persistence.TokenSupport.processToken(TokenSupport.java:115)
	at pcgen.rules.context.LoadContextInst.processToken(LoadContextInst.java:338)
	at pcgen.rules.context.RuntimeLoadContext.processToken(RuntimeLoadContext.java:20)
	at pcgen.persistence.lst.LstUtils.processToken(LstUtils.java:139)
	at pcgen.persistence.lst.AbilityLoader.parseLine(AbilityLoader.java:106)
	at pcgen.persistence.lst.AbilityLoader.parseLine(AbilityLoader.java:35)
	at pcgen.persistence.lst.LstObjectFileLoader.loadLstFile(LstObjectFileLoader.java:402)
	at pcgen.persistence.lst.LstObjectFileLoader.loadLstFiles(LstObjectFileLoader.java:99)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:631)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:490)
	at pcgen.persistence.SourceFileLoader.execute(SourceFileLoader.java:244)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:72)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:40)
	at pcgen.gui2.util.SwingWorker$1.run(SwingWorker.java:160)
	at java.base/java.lang.Thread.run(Unknown Source)

18:22:46.678 SEVERE Thread-4 LstObjectFileLoader:421 Errors.LstFileLoader.Ignoring: null not defined.
18:22:47.683 LSTERROR Thread-4 LstUtils:147 Illegal Token 'LANG' 'BONUS|TYPE=Spoken' for pcgen.core.Race Gloaming in file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/campaign_settings/forgotten_realms/underdark/und_races.lst
18:22:52.230 SEVERE Thread-4 AbstractReferenceManufacturer:878 More than one ClassSkillList with key/name Air Shugenja was built
18:22:52.231 SEVERE Thread-4 AbstractReferenceManufacturer:892 Sources: file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/supplement/races_of_the_wild/rw_classes.lst, file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/supplement/races_of_the_wild/rw_classes.lst
18:22:52.231 SEVERE Thread-4 AbstractReferenceManufacturer:878 More than one ClassSkillList with key/name Water Shugenja was built
18:22:52.231 SEVERE Thread-4 AbstractReferenceManufacturer:892 Sources: file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/supplement/races_of_the_wild/rw_classes.lst, file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/supplement/races_of_the_wild/rw_classes.lst
18:22:52.231 SEVERE Thread-4 AbstractReferenceManufacturer:878 More than one ClassSkillList with key/name Earth Shugenja was built
18:22:52.231 SEVERE Thread-4 AbstractReferenceManufacturer:892 Sources: file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/supplement/races_of_the_wild/rw_classes.lst, file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/supplement/races_of_the_wild/rw_classes.lst
18:22:52.231 SEVERE Thread-4 AbstractReferenceManufacturer:878 More than one ClassSkillList with key/name Fire Shugenja was built
18:22:52.231 SEVERE Thread-4 AbstractReferenceManufacturer:892 Sources: file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/supplement/races_of_the_wild/rw_classes.lst, file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/supplement/races_of_the_wild/rw_classes.lst
18:22:52.249 SEVERE Thread-4 AbstractReferenceManufacturer:878 More than one ClassSpellList with key/name Air Shugenja was built
18:22:52.250 SEVERE Thread-4 AbstractReferenceManufacturer:892 Sources: file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/supplement/races_of_the_wild/rw_classes.lst, file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/supplement/races_of_the_wild/rw_classes.lst
18:22:52.250 SEVERE Thread-4 AbstractReferenceManufacturer:878 More than one ClassSpellList with key/name Water Shugenja was built
18:22:52.250 SEVERE Thread-4 AbstractReferenceManufacturer:892 Sources: file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/supplement/races_of_the_wild/rw_classes.lst, file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/supplement/races_of_the_wild/rw_classes.lst
18:22:52.250 SEVERE Thread-4 AbstractReferenceManufacturer:878 More than one ClassSpellList with key/name Earth Shugenja was built
18:22:52.250 SEVERE Thread-4 AbstractReferenceManufacturer:892 Sources: file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/supplement/races_of_the_wild/rw_classes.lst, file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/supplement/races_of_the_wild/rw_classes.lst
18:22:52.250 SEVERE Thread-4 AbstractReferenceManufacturer:878 More than one ClassSpellList with key/name Fire Shugenja was built
18:22:52.250 SEVERE Thread-4 AbstractReferenceManufacturer:892 Sources: file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/supplement/races_of_the_wild/rw_classes.lst, file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/supplement/races_of_the_wild/rw_classes.lst
18:22:52.300 SEVERE Thread-4 CDOMFactory:105 Unconstructed Reference: Race Androsphinx
18:22:52.300 SEVERE Thread-4 TrackingReferenceContext:102   Was used in file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/supplement/miniatures_handbook/mh_abilities.lst in tokens: [plugin.lsttokens.CompanionListLst]
18:22:52.301 SEVERE Thread-4 CDOMFactory:105 Unconstructed Reference: Race Gynosphinx
18:22:52.301 SEVERE Thread-4 TrackingReferenceContext:102   Was used in file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/supplement/miniatures_handbook/mh_abilities.lst in tokens: [plugin.lsttokens.CompanionListLst]
18:22:52.301 SEVERE Thread-4 CDOMFactory:105 Unconstructed Reference: Race Water Naga
18:22:52.302 SEVERE Thread-4 TrackingReferenceContext:102   Was used in file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/supplement/miniatures_handbook/mh_abilities.lst in tokens: [plugin.lsttokens.CompanionListLst]
18:22:52.304 SEVERE Thread-4 AbstractReferenceManufacturer:294 Error: No Skill objects of TYPE=Craft (Stonemasonry) were loaded but were referred to in the data
18:22:52.305 SEVERE Thread-4 TrackingReferenceContext:102   Was used in file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/core/players_handbook/ph_skills.lst in tokens: [plugin.lsttokens.tempbonus.PCToken]
18:22:52.386 SEVERE Thread-4 CDOMFactory:105 Unconstructed Reference: Language Elven (drow dialect)
18:22:52.387 SEVERE Thread-4 TrackingReferenceContext:102   Was used in file:/C:/Users/TheCh/AppData/Local/PCGen/6.08.00RC8/data/35e/wizards_of_the_coast/campaign_settings/forgotten_realms/underdark/und_templates.lst in tokens: [plugin.lsttokens.template.LangbonusToken]
18:22:59.542 SEVERE Thread-4 SourceFileLoader:526 Exception loading files.
java.lang.NullPointerException
	at pcgen.cdom.helper.AbilityTargetSelector.getChoiceClass(AbilityTargetSelector.java:231)
	at plugin.lsttokens.ChooseLst.process(ChooseLst.java:196)
	at plugin.lsttokens.ChooseLst.process(ChooseLst.java:47)
	at pcgen.rules.context.LoadContextInst.processPostRes(LoadContextInst.java:278)
	at pcgen.rules.context.LoadContextInst.resolvePostDeferredTokens(LoadContextInst.java:261)
	at pcgen.rules.context.RuntimeLoadContext.resolvePostDeferredTokens(RuntimeLoadContext.java:20)
	at pcgen.persistence.SourceFileLoader.finishLoad(SourceFileLoader.java:755)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:495)
	at pcgen.persistence.SourceFileLoader.execute(SourceFileLoader.java:244)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:72)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:40)
	at pcgen.gui2.util.SwingWorker$1.run(SwingWorker.java:160)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by BahamutDragon** [comment]
Fixed most of that. I would avoid the miniatures handbook, I do not think it is completed yet.

**Comment by upspiral89** [comment]
I've just found out that the error on mm_kits.lst is related to Champions of Valor, if I don't select it I can load every other source without problems but it crashes if I select it togheter with the other sources. The error dosn't happen either if I only select champions of valor and its related required sources, maybe it's a conflict between it and another source but I don't know wich one

**Comment by jfalconnet** [comment]
I had this one too in Champions of Valor. I solved it by replacing "50%" by "50%%".
I will try to pull request for that

**Comment by BahamutDragon** [comment]
If this is still an issue, open a new issue. Thank you.
