### ISSUE TITLE
Agile Shield Fighter

### ISSUE THREAD

**Issue by tonybrown3** [BahamutDragon/pcgen#1020]
As this is my second question to this forum, I very thankful for your quick and clean fix for my last shield issue.  This one I am not sure if it is something I am doing or if I am bumping up against a code issue.    As agile shield fighter allows for the bash and whack version of TWF.  I see that when I equip a shield in off hand the sheet tries to do a two weapon setup.  As shield is by default a off hand weapon by book rules it gets a -4 even in on hand.  But the program seems double dip and apply that -4 on hand (correct) then another -4 off hand (not correct). From what I see i think my on hand weapon is showing correctly in the 2W-P but the shield numbers are way off and it does not seem to be accounting for the feat correctly assuming my math is right.  

Also the Darkwood Shields are only equable in the shield slot.  Which brings me to my next question.  I have tried all the customizable options  while the program is running and can not get it to equip in my off hand only the shield slot.  Do I need to tweak the base file to fix that?  

Thanks.....

**Comment by BahamutDragon** [comment]
Do you have a source to cite that states this rule? 

I would have to say my rules knowledge is rusty. TWF is normally -6 and -10 respectively, If you have the correct feat, the penalty decreases.

**Comment by tonybrown3** [comment]
I responded to the email.. but in case it is stuck in a filter to junk some where..

I'll start with yes TWF is -6  and -10  per PHB table 8-10 p160

With TWF feat and a light weapon that drops to -2/-2

In the PHBII  Shield Specialization p82 adds to AC which you fixed thank you very much.  Off that you get Agile Shield Fighter p74 which reads like you shift to a -2/-2 when doing a full attack sword and shield. 

AGILE SHIELD FIGHTER
You are skilled in combining your shield bash attack with
an armed strike. When you use your shield in unison with
a weapon, your training allows you to score telling blows
with both.
Prerequisites: Proficiency with shields, Improved Shield
Bash, Shield Specialization.
Benefit: When making a shield bash and armed strike
attack as part of a full attack action, you take a –2 penalty
on each attack. These penalties replace the normal ones you
incur for fighting with two weapons.
Special: A fighter can select Agile Shield Fighter as one
of his fighter bonus feats.

I "think" i extracted that info about -4 on shields from some phrasing in the PHB.

PHB p125  This section in in all the shield descriptions

Shield Bash Attacks: You can bash an opponent with a heavy shield,
**using it as an off-hand weapon**. See Table 7–5: Weapons for the
damage dealt by a shield bash. Used this way, a heavy shield is a mar-
tial bludgeoning weapon. For the purpose of penalties on attack
rolls, treat a heavy shield as a one-handed weapon.

If taken literately, if you use a shield in your on hand it still counts as off hand for penalties for attack.    But re reading it, i think the writer is assuming you would not be using it as your primary weapon.  Much like I am assuming that is saying shield are only usable in off hand.  So you can take that for what it is worth.

<img width="935" alt="attack" src="https://user-images.githubusercontent.com/16314612/107984026-ff0fca80-6f94-11eb-8ea2-afc12b2a325e.PNG">

**Comment by BahamutDragon** [comment]
Mate,

This took some doing, but I think this is what you are looking to achieve:
![image](https://user-images.githubusercontent.com/4307487/123358500-71cf1a80-d520-11eb-9851-9298cff3bd9f.png)
