### ISSUE TITLE
How do you represent a bardic effect on a recipient character?

### ISSUE THREAD

**Issue by cernenwein** [BahamutDragon/pcgen#1021]
we have a bard who is a skald variety.  when they use, Inspired Rage (Su), how can I represent this on my character sheet?

Is it already coded, or is this a request?   any clue where I would start , if I tried to add this myself?

Pathfinder 1.0

https://www.d20pfsrd.com/classes/hybrid-classes/Skald/#TOC-Inspired-Rage-Su-

**Comment by BahamutDragon** [comment]
Hi mate, have you loaded the latest sources from the pcgen team? Advanced Class Handbook is part of their release which includes the hybrid classes.
