### ISSUE TITLE
Does not get domain specific spells and + "domains remains to be selected

### ISSUE THREAD

**Issue by mywonderchild** [BahamutDragon/pcgen#1022]
Ruleset: 5e
Dataset: players+dungeonmaster+MM
Made a nature domain cleric, get message about "domains remains to be selected", even though domain is selected.
No domain spell is shown in spell list.

Zip file contains char file as well as pics of errors/pcgen version.
[pcgenerror.zip](https://github.com/BahamutDragon/pcgen/files/6054900/pcgenerror.zip)

**Comment by BahamutDragon** [comment]
Using the 6.09 version, I see the correct results. Here's the PDF export.

[Thrydwulf.pdf](https://github.com/BahamutDragon/pcgen/files/6681451/Thrydwulf.pdf)
