### ISSUE TITLE
Centaur Race but Centaur Class

### ISSUE THREAD

**Issue by Athinar** [BahamutDragon/pcgen#1030]
3.5
I'm playing a Centaur, 5th level Centaur and 1 level of Druid (Races of the Wild) RW, problem is the Size at 1st level Centaur Class  is "Large" and not "Medium" and when the character gains the 6th of Centaur the Size increases to "Huge"

If I mod the MM_races.lst to decrease the size to M, nothing happens

ss_races.lst and classes are marked out "#" for the centaur
BONUS:SIZEMOD|NUMBER|1????? can this be set to 0 at 1st Centaur Level

**Comment by BahamutDragon** [comment]
@Athinar Races of the Wild has the class. 

I gave you a new race Centaur (Playable) that will level correctly. I did a quick conversion for the race itself. Are you using Master (6.09) or 6.08?

**Comment by Athinar** [comment]
6.09


Sent from my Verizon, Samsung Galaxy smartphone

Get Outlook for Android

**Comment by Athinar** [comment]
You have not added the Class correctly, Space is 5, the Class "Centaur" does not get the starting Stats of a Centaur but slowly gets them with leveling, Walk starts at 40 at 1st level

1st: 2 Dex, -2 Int, +1 NA, Feat, 2 hooves 1d4
2nd: 2 Str, +2 Wis
3rd: 2 Str, 2 Con, +2 NA
4th: Feat, 2 Str, 2 Dex
5th: 2 Str, 2 Con, Walk 50, +3 NA
6th: Large, 2 hooves 1d6

**Comment by Athinar** [comment]
IGNORELEVEL:STAT|CL, should this be uncommented?

**Comment by Athinar** [comment]
Removed the Stat changes in the Race (Playable) and the Natural Armour changes
Added the Stats increase and Natural Armour per the centaur level
Problem with STR and CON increase at 6th Centaur, increased by 16 and 8, should not have changed

**Comment by BahamutDragon** [comment]
Medium to Large should increase STR by 8, Con by 4, and unless altered, drops the Dex by -2.

**Comment by BahamutDragon** [comment]
I made a few modifications. Give this a go and verify it appears to be correct for you.
