### ISSUE TITLE
Bio settings AGESET

### ISSUE THREAD

**Issue by FerretDave** [BahamutDragon/pcgen#1038]
using 6.08 branch, loading 35e Bahamut PH, and the Players Guide to Faerun (and PH2, MoF, CAr, champions of valor and some other minor ones, if that makes a difference) and I'm getting errors on AGESET (and a HANDED defaultvariable that I thought was already fixed...)

Looks like we've got inconsistent AGESET biosettings through the sources, and I'm not sure which should be the correct ones to change the rest to match.

Can you standardise these to avoid the load errors please?

22:58:52.11 LSTERROR Thread-2 CDOMControlLoader:146 DEFAULTVARIABLEVALUE found an unsupported format: HANDED (Source: file:/C:/Utils/GitHub/pcgen/data/35e/wizards_of_the_coast/core/universal_rules/ur__datacontrols.lst )
22:58:52.11 LSTERROR Thread-2 CDOMControlLoader:146 Failed in parsing typeStr: DEFAULTVARIABLEVALUE HANDED|Right for pcgen.cdom.content.DefaultVarValue HANDED Right
22:58:52.12 LSTERROR Thread-2 CDOMControlLoader:146 Illegal Token 'DEFAULTVARIABLEVALUE' 'HANDED|Right' for pcgen.cdom.content.DefaultVarValue HANDED Right in file:/C:/Utils/GitHub/pcgen/data/35e/wizards_of_the_coast/core/universal_rules/ur__datacontrols.lst
22:58:55.469 SEVERE Thread-2 BioSet:634 Found second (non-identical) AGESET in Bio Settings file:/C:/Utils/GitHub/pcgen/data/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst for Region: None Index: 0 using the existing 0|Adulthood
22:58:55.470 SEVERE Thread-2 BioSet:634 Found second (non-identical) AGESET in Bio Settings file:/C:/Utils/GitHub/pcgen/data/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst for Region: None Index: 1 using the existing 1|Middle Age	STAT|STR,CON,DEX|-1	STAT|INT,WIS,CHA|1
22:58:55.470 SEVERE Thread-2 BioSet:634 Found second (non-identical) AGESET in Bio Settings file:/C:/Utils/GitHub/pcgen/data/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst for Region: None Index: 2 using the existing 2|Old	STAT|STR,CON,DEX|-3	STAT|INT,WIS,CHA|2
22:58:55.470 SEVERE Thread-2 BioSet:634 Found second (non-identical) AGESET in Bio Settings file:/C:/Utils/GitHub/pcgen/data/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst for Region: None Index: 3 using the existing 3|Venerable	STAT|STR,CON,DEX|-6	STAT|INT,WIS,CHA|3
22:58:55.471 SEVERE Thread-2 BioSetLoader:97 Incompatible Index for AGESET in Bio Settings file:/C:/Utils/GitHub/pcgen/data/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst: 2 and 4 for Old
22:58:55.471 SEVERE Thread-2 BioSetLoader:97 Incompatible Index for AGESET in Bio Settings file:/C:/Utils/GitHub/pcgen/data/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst: 3 and 5 for Venerable
22:58:55.472 SEVERE Thread-2 BioSetLoader:97 Incompatible Index for AGESET in Bio Settings file:/C:/Utils/GitHub/pcgen/data/35e/wizards_of_the_coast/campaign_settings/forgotten_realms/players_guide_to_faerun/pg_biosettings.lst: 4 and 2 for Old
22:58:55.472 SEVERE Thread-2 BioSetLoader:97 Incompatible Index for AGESET in Bio Settings file:/C:/Utils/GitHub/pcgen/data/35e/wizards_of_the_coast/campaign_settings/forgotten_realms/players_guide_to_faerun/pg_biosettings.lst: 5 and 3 for Venerable

**Comment by BahamutDragon** [comment]
Mate,

My data is consistent across both 6.08 and Master:
AGESET:0|Undefined
AGESET:1|Youth
AGESET:2|Adult
AGESET:3|Middle-Aged
AGESET:4|Old
AGESET:5|Venerable

Do you have a Bio folder set up in your system folder? That is where I would expect a conflict to be found.

**Comment by BahamutDragon** [comment]
The HANDED is commented out for 6.08. It sounds like the problem is dirty data on your end. Try a fresh download and see if the issue is fixed.

**Comment by FerretDave** [comment]
Greetings,

I reckon I may have copied the gamemode from master rather than 6.08
branch...
refreshed completely and get an almost clean startup now.
Just get two illegal token errors, but minor in comparison to all I *was*
getting! Thanks for the advice.

20:38:10.781 INFO main Main:138 Starting PCGen v6.08.00 RC8
20:38:10.825 INFO main LanguageBundle:134 Initialising language bundle with
locale en_US.
20:38:12.307 LSTERROR main LstUtils:147 Illegal Token 'ALIGNMENTFEATURE'
'YES' for pcgen.cdom.inst.CodeControl Controller in
file:/C:/Utils/PCGen/6.08.00RC8/system/gameModes/Bahamut35e/codeControl.lst
20:38:12.307 LSTERROR main LstUtils:147 Illegal Token 'DOMAINFEATURE' 'YES'
for pcgen.cdom.inst.CodeControl Controller in
file:/C:/Utils/PCGen/6.08.00RC8/system/gameModes/Bahamut35e/codeControl.lst
20:38:17.489 INFO Thread-2 SourceFileLoader:534 Loading game Bahamut35e and
sources [Campaign: Petes Tuesday TearingOfTheWeave game].

Cheers
Dave

**Comment by FerretDave** [comment]
And recopied the game mode and no longer get the below ! Must have copied
it *again* before I switched to 6.08 branch!...
