### ISSUE TITLE
New Character Sheets (OS)

### ISSUE THREAD

**Issue by BahamutDragon** [BahamutDragon/pcgen#104]
Hi mates,

Do we have any who have the skills to design new character sheets? 
The three major formats are: 
TXT (txt, xml)
PDF (xml, xsl, xslt, fo)
HTM (htm, html)

I have a need to make one for Dragon Age, Starwars: Edge of the Empire and D&D 5e.

Especially Edge of the Empire as that redesigns weapon output.

Contact me or respond to this issue.

**Comment by Peajee** [comment]
It would also be awesome to have some stylish character Sheet for D&D 5e!

**Comment by BahamutDragon** [comment]
Updated initial comment. 

Stylish is in the eye of the beholder. Do you have any examples of a stylish 5e sheet?

**Comment by Peajee** [comment]
Well, the Character Sheet from the Core rules is already pretty good. Personally I really like this design:

http://www.enworld.org/forum/rpgdownloads.php?s=a5c13236a30666ef8653a8eed012cccf&do=download&downloadid=1165

Although one would have to change certain things, design wise, to make it look good with the data generated by PCGen.

**Comment by BahamutDragon** [comment]
5e is an easier one to work on, and I found some annoyances on our group sheets. Had hoped someone else would take up this cause.

**Comment by BahamutDragon** [comment]
OS Changes for 5e - requires 5e gamemode update and outputsheet folder update to work for PDF.
Skills now show proficiency bonus and get a check mark.
Save names fit, location for check mark, though it is not working. HTM for 5e next.

**Comment by jason-allen-oneal** [comment]
I'd be willing to work on the HTML portion of the character sheets for 5e. I've been doing HTML work for years and would love to be able to contribute to an awesome project. :)

**Comment by BahamutDragon** [comment]
Active development is currently on the 6.04.01 branch. Let me verify the OS on the repo is current with the local changes.

**Comment by BahamutDragon** [comment]
Everything is in sync mate. Thanks in advance for the contribution!

**Comment by jason-allen-oneal** [comment]
Cool. I'll start digging through the code to get an idea of what's what.

**Comment by BahamutDragon** [comment]
Mate,

If it helps, the preview sheet has the coding you will want to duplicate. The .ftl is the pcgen new free template language, and what we should be emulating. I think the pcgen team chose wisely when they decided to implement it. 

For 5e - The major sections you want is the changed skills section, the save section and if you want to tackle the Armor Class section, remove the 3.5e specific naming conventions. In theory, it should be possible to port the changes from one to the other.

If you like the work, please consider helping out the requested Dragon Age and Star wars sheets. 

Would any images be desired for a mock up?

**Comment by jason-allen-oneal** [comment]
That's kind of what I'm doing right now: basically reverse engineering the
old sheet and rebuilding with a new format. I'm going with HTML5, but it
should just be a few syntax changes here and there. I don't think I'll need
any images, and if I do, I can whip something up in Photoshop for a
placeholder at least.
I'm a little behind where I wanted to be on the sheets because of work, but
I should have a working prototype in a couple of days, maybe a week.

**Comment by BahamutDragon** [comment]
Mate,

By old sheet, are you referencing the version with the |IIF| and |ENDIF| syntax, or the <#if> and </#if> syntax? 
If you have not already done so, I would suggest you get all the converted sheets that are already in the .ftl format from the pcgen website. The latest program version includes them. 

I was asking if you required images of the character sheets requested. We have a few links to 5e sheets. Some of the sheets out there are quite fancy. 

Will be nice to check out these new character sheets.

Best,

**Comment by jason-allen-oneal** [comment]
Unfortunately, I don't think I'm going to have time to work on the
character sheets. I've just had 2 new projects dropped into my lap for
work, so my time is going to be very limited. Sorry, mate.

**Comment by BahamutDragon** [comment]
@jason-allen-oneal checking in with you. Life get any better yet?

**Comment by jason-allen-oneal** [comment]
Haha. Things are a little more stable. Trying to finish off this huge
project I'm currently working on. I haven't even had time to play any D&D!
lol

**Comment by BahamutDragon** [comment]
Serious character sheet changes coming. After the PCGen team alters their sheets, I will adapt the sheets, and attempt to add new sheets at that time.

**Comment by kaiszer** [comment]
I didnt find any alternative for DnD 5e character sheet on the folders. There is already anything on development or I can help with something?
