### ISSUE TITLE
In 3.5 Forest Gnome is not created properly

### ISSUE THREAD

**Issue by tivv** [BahamutDragon/pcgen#1041]
I don't get Forest Gnome traits and all special abilities (including Speak with animals that should not be there) is listed twice.
PCGEN 6.08.00RC8
Steps: 
 * New character
 * Select race Gnome
 * In Feats & Abilities - Race Traits - Gnome Subrace select Forest
 * Check character sheet
![image](https://user-images.githubusercontent.com/425183/122718506-e1dc5880-d221-11eb-9c3c-7006e4a2c690.png)

**Comment by BahamutDragon** [comment]
Should be resolved now mate.

**Comment by tivv** [comment]
Hi. It's much better now. The only  thing that seems off is that "Speak with animals" should be replaced with "Pass without trace":
![image](https://user-images.githubusercontent.com/425183/123285802-3a318580-d4c2-11eb-8792-7fe8faac3ab4.png)

**Comment by tivv** [comment]
@BahamutDragon I can't reopen it, so tagging you. Thanks for your support!

**Comment by tivv** [comment]
Thank you! "Speak with animals" disappeared. "Walk without trace" does not show up in this section, but it's present in the special qualities list. I believe that's fine.

**Comment by BahamutDragon** [comment]
Fixed the Speak with animals and added Pass without Trace.

See image

![image](https://user-images.githubusercontent.com/4307487/123354106-ccb04400-d517-11eb-9a2a-0073b4383d8e.png)
