### ISSUE TITLE
New to PcGen and trying to resolve Issues but Debug Log remains blank

### ISSUE THREAD

**Issue by Runner-L** [BahamutDragon/pcgen#1043]
**I can not seem to run PCGen with BahamutDragon's 3rd party content**
I have been trying by adding source books little by little but PcGen keeps erroring out whenever I try to load his sourcebooks. I have tried to have the Logs open because the load keeps failing when ever loading gets to sa_kits.lst an error window pops up saying that campaigns failed to load however whether I click the red circle on the bottom or press f10  the debug log remains blank.

**To Reproduce**
1. Download and install 'PCGen 6.08.00RC8'
2. Download zip folder by BahamutDragon at 'https://github.com/BahamutDragon/pcgen'
3. Extract folder to desktop
4. Copy files into the correct folders
5. Launch Program and select Dungeons and Dragons - core books as the game type
6. Press CTRL+L then select advance tab
7. Click on 35e Bahamut's select all the sources applicable
8. Load sources, the error should no occur and the debug log should remain blank 

**Expected behavior**
A successful execution of PCGen with all 3rd party content displaying.

**Desktop (please complete the following information):**
 - Windows 10 Pro
 - Chrome
 - Version 20H2

**Additional context**
I have also reached out to PCGen's Github Page as well to try and resolve the issue.

**Comment by BahamutDragon** [comment]
Two methods exist to get the content onto your system.

    The easier method is to use the GITHUB download option - please note that the download will change based upon branch currently selected, allowing a choice of versions. (Master is for the latest version whether alpha, beta, rc or production, Branches that are using the versioning system of pcgen is meant to work with the same version of pcgen, example 6.04.01 branch is designed to be compatible with PCGen version 6.04.01) Save the zip folder to a valid pcgen recognized data folder of your choice. Unzip the contents. Load PCGen. See 'LOADING THESE SETS' Below.


That translates to: PCGen 6.08.00RC8 requires Branch 6.08 which is downloaded here: https://github.com/BahamutDragon/pcgen/archive/refs/heads/6.08.zip

**Comment by BahamutDragon** [comment]
6.09.xx uses Master branch.
