### ISSUE TITLE
Carts

### ISSUE THREAD

**Issue by Athinar** [BahamutDragon/pcgen#1048]
Do you know how to add a "Cart" to the Character and then add equipment to that Cart so the Character is not carrying the equipment; the Cart is both Transport and Container

**Comment by FerretDave** [comment]
Create a new 'container' (copy the 'backpack'), equip that as 'not carried'. Something like the below, though you may be better off copying the backpack line exactly and altering the parts to suit as you'll want to change the limits on what it can carry (assuming backpack has a limit, I know quivers specify the type and quantity they can carry, not sure if backpack *has* a limit... so you may be good with just the below).

backpack.COPY=Cart
Cart.MOD OUTPUTNAME=Cart<tab>SPROP:A cart for carrying

**Comment by Athinar** [comment]
do you mean to make a copy of the line "Backpack" in the "ph_equip.lst" in PCGen\6.09.05\data\35e\wizards_of_the_coast\core\players_handbook and rename it Cart?

**Comment by FerretDave** [comment]
either - copying the entire 'backpack' line and renaming it is a good starting point if you want to make numerous changes to it, while the latter - (*not* editing cart, but adding the two lines for COPY and MOD) works well if you only want to make a minor variant of an existing thing.

In either case, add the new lines into your own source lst file and add a pcc to add them (though TBH adding a new 'cart' to the existing ph_equip.lst and raising a pull request would likely be accepted, and we'd all get to use it then).

I've done similar with giving each player a 'saddlebags' that is flagged as not carried, and it's all on characters horse - so available, but not weighing anyone down (if we lose the horse, we lose the kit)

**Comment by Athinar** [comment]
Can you leave me example of the your_own_source.lst file and add a pcc and where to add it for the Saddlebags and Cart?

**Comment by Athinar** [comment]
My_Campaign.PCC 

CAMPAIGN:My_Campaign
GAMEMODE:35e|DnD35|FirstnameLastname35e

BOOKTYPE:Homebrew
GENRE:Fantasy
SETTING:My Homebrew Campaign
TYPE:Homebrew.MyCampaign
PUBNAMELONG:My Camppaign
PUBNAMESHORT:Homebrew
SOURCELONG:My Campaign
SOURCESHORT:My

#SHOWINMENU:YES
# Shows the Set in the basic loader
#STATUS:RELEASE
ISLICENSED:NO
ISOGL:NO
#PUBNAMEWEB:http://www.wizards.com/default.asp?x=dnd
#COPYRIGHT:Wizards of the Coast is the copyright holder. This is a set derived from both the OGL and actual Book.

EQUIPMENT:my_equipment.lst
EQUIPMOD:my_equipmods.lst

**Comment by Athinar** [comment]
my_equipment.lst
#D&D 3.0 weights

# Equipment Name			Unique Key				Type								Contains									Cost		Weight	Source Page		Bonus to skill					Quality and value																	Special Property
Backpack									TYPE:Goods.Container.General.Resizable		CONTAINS:30|Any							COST:2	WT:2		SOURCEPAGE:p.126
#SPROP:A backpack is a leather pack carried on the back, typically with straps to secure it.

###Block: Mount Gear
# Equipment Name		Unique Key						Type									Contains			Cost		Weight	Source Page				Special Property																																																																																				SORTKEY
Saddle, Pack (Exotic)	KEY:Saddle (Pack (Exotic))		TYPE:Mount.MountGear.Container			CONTAINS:UNLIM|Any	COST:15		WT:20				SOURCEPAGE:p.132			SPROP:An exotic saddle is like a normal saddle of the same sort except that it is designed for an unusual mount, such as a hippogriff. Exotic saddles come in military, pack, and riding styles.																																																						SORTKEY:Mounts
Saddle, Pack			KEY:Saddle (Pack)				TYPE:Mount.MountGear.Container			CONTAINS:UNLIM|Any	COST:5		WT:15				SOURCEPAGE:p.132			SPROP:A pack saddle holds gear and supplies, but not a rider. It holds as much gear as the mount can carry. (The Monster Manual has notes on how much mounts can carry.)																																																										SORTKEY:Mounts
Saddlebags												TYPE:Goods.Container.Mount.Resizable	CONTAINS:40|Any	COST:4	WT:8		SOURCEPAGE:Equipment

###Block: Transport
# Equipment Name	Type			Contains				Source Page		Special Property																																																																					SORTKEY
Carriage			TYPE:Transport	CONTAINS:1000|Any		SOURCEPAGE:p.132	SPROP:This four-wheeled vehicle can transport as many as four people within an enclosed cab, plus two drivers. In general, two horses (or other beasts of burden) draw it. A carriage comes with the harness needed to pull it.																																		SORTKEY:Transport
Cart				TYPE:Transport	CONTAINS:1000|Any		SOURCEPAGE:p.132	SPROP:This two-wheeled vehicle can be drawn by a single horse (or other beast of burden). It comes with a harness.									backpack.COPY=Cart																																													SORTKEY:Transport			backpack.COPY=Cart		Cart.MOD OUTPUTNAME=CartSPROP:A cart for carrying		
Sled				TYPE:Transport	CONTAINS:2000|Any		SOURCEPAGE:p.132	SPROP:This is a wagon on runners for moving through snow and over ice. In general, two horses (or other beasts of burden) draw it. A sled comes with the harness needed to pull it.																																										SORTKEY:Transport
Wagon				TYPE:Transport	CONTAINS:4000|Any		SOURCEPAGE:p.132	SPROP:This is a four-wheeled, open vehicle for transporting heavy loads. In general, two horses (or other beasts of burden) draw it. A wagon comes with the harness needed to pull it.																																									SORTKEY:Transport

**Comment by FerretDave** [comment]
looks like you've got it ;-)
Why not make those changes to the PH_equip.lst and raise a PR ?
