### ISSUE TITLE
I'm playing a Centaur, 5th level Centaur and 1 level of Druid (Races of the Wild) RW

### ISSUE THREAD

**Issue by Athinar** [BahamutDragon/pcgen#1052]
I'm playing a Centaur, 4th level Centaur, 2 level of Druid (Races of the Wild) RW, 1 level of Fighter and 1 Prestige Ranger

The DM is letting me change the Character to become a Prestige Ranger
1st Centaur (Endurance and Point Blank Shot)
2nd Centaur
3rd Centaur
1st Druid (Calm Animal)
4th Centaur (Track)
1st Fighter (Rapid Shot)
1st Prestige Ranger
Nature 4 Ranks
Survival 5 Ranks 

The Character has all the Required Abilities and Skills but I can not get the 1st level Prestige Ranger to work

Error "The Character does not qualify for Level 1"

The Character Sheet has Centaur4 Druid2 Fighter1 Prestige Ranger0

But I can add a Level of Ranger and remove the level of Ranger

**Comment by FerretDave** [comment]
When you select the class, there should be a description - including the PRErequisites in one of the tabs - anything shown in red will be a prereq that you don't meet.

Can't think of anywhere where an error with that text could actually appear, got a screenshot? - Also confirm all the sources and gamemode you're loading (and PCGen version)

**Comment by Athinar** [comment]
Version 6.09.05
Nothing in Red for the class
When the Class "Prestige Ranger"
[Ranger 24JUL21.docx](https://github.com/BahamutDragon/pcgen/files/6873042/Ranger.24JUL21.docx)
 is selected it adds the Class to the character sheet "Centaur4 Druid2 Fighter1 Prestige Ranger0"

**Comment by BahamutDragon** [comment]
Should be fixed for master. My quick test was druid 10.
