### ISSUE TITLE
Trying to add additional abilities 

### ISSUE THREAD

**Issue by drklassen** [BahamutDragon/pcgen#1054]
I'm using PCGEN 6.07.06 in 5e mode with 53 Core and Xanthar's Guide loaded.

My DM has stated that I can add a bonus language and bonus skill proficiency; when I go to the Feats & Abilities Section, there's a Tab called Rules with a Cantrip Add and a Rules categories and when I select Rules I can see all kinds of "Add additional..." options but when I try to select and add them I just get an error pop up saying "You cannot select any more abilities".

I assumed this was the place to add GM-granted bonuses but I also see that the Total and Remaining numbers are both 0 and for the life of me I can't see any way to increase that number.  Should there be something here that does that?

**Comment by BahamutDragon** [comment]
Quite an older version and likely not an up to date data set.

My copy for master shows the COST of those rules as "0" which implies you can take them as often without any cost. The 0 for the available can be edited according to my version of the data. Simply click in the available box and enter a desired number.

`ABILITYCATEGORY:Rules			VISIBLE:YES	EDITABLE:YES	EDITPOOL:YES		FRACTIONALPOOL:NO								CATEGORY:Special Ability			TYPE:Rules
`

`Add additional Cantrip					CATEGORY:Special Ability	TYPE:Rules	DESC:Adds additional Cantrip					STACK:YES	MULT:YES	CHOOSE:NOCHOICE	BONUS:VAR|POOL_Cantrip_Choice|1			COST:0
`

Although not as ascetically appealing, 6.09.05 is the version the master branch is supposed to support, while the 6.08 branch supports your 6.07+ though you may want to grab 6.08.00 unless you have a reason to avoid the version bump.

**Comment by drklassen** [comment]
AHA!  Thank you for that!  I did try editing the Available number but no luck.  I just tried editing the Remaining number, and success!

I really should upgrade, yes.  My only "reason" is laziness.

Thank you so much for this and all your work on these!
