### ISSUE TITLE
Bug: Elven high mage class features not appearing

### ISSUE THREAD

**Issue by jdavidnew0** [BahamutDragon/pcgen#1065]
While something really easy to simply keep in mind due to the nature of epic spellcasting I figured you's like to know that the class features aren't showing up on my character sheet

**Comment by BahamutDragon** [comment]
Requires some investigation.

**Comment by BahamutDragon** [comment]
Try pulling down the latest updates. After building a Wizard 23 I was able to take Elven High Mage and see the class features.

![image](https://user-images.githubusercontent.com/4307487/140847229-7d81b1d3-cd96-491a-ace6-485c80eff41f.png)

**Comment by BahamutDragon** [comment]
![image](https://user-images.githubusercontent.com/4307487/140847318-a1bef9ce-df9c-490c-bff9-c05a63851506.png)
