### ISSUE TITLE
Unable to create Shadow Companion in 3.5e

### ISSUE THREAD

**Issue by PhoenyxCullen** [BahamutDragon/pcgen#1078]
I'm having problems with a Shadowdancer LVL 3 and this set's data in creating a Shadow Companion from the Shadow Summon class feature. Am I doing this wrong? Any suggestions will be helpful, although, this group is sticking to 3.5e DnD. Below are 3 photos showing class progression, lack of anything selectable in the Shadow Companion section, and Books selected.

![image](https://user-images.githubusercontent.com/33883504/150869370-685bb433-53e4-4812-99ce-c97c927a5a13.png)
^ Showing character class progression.

![image](https://user-images.githubusercontent.com/33883504/150869513-45152058-f0c8-4813-9b5e-562ce935c76d.png)
^ Showing trying to make a new Shadow Companion for the Shadow Summon class feature.

![image](https://user-images.githubusercontent.com/33883504/150869804-ec09b528-076d-4a0e-bd69-60c5fed9e058.png)
^ Books selected, but I only need the Core books 1-3 (phb1, dmg1, mm1).

**Comment by BahamutDragon** [comment]
Well, easy fix. I'll have a patch for you in a few minutes mate!

**Comment by PhoenyxCullen** [comment]
Thank you.

**Comment by BahamutDragon** [comment]
Patch tested. Verified fixed on my side.

**Comment by PhoenyxCullen** [comment]
Bahamut,

It is working on my side now. Thank you.
Just curious, I'm looking at your commits and can't find what you
fixed. Was it a typo?
