### ISSUE TITLE
Darksun 3.5e doesn't load with the latest version of PCGen

### ISSUE THREAD

**Issue by Grummore** [BahamutDragon/pcgen#1079]
Title said it all.

I placed the darksun_35e in the data/35e folder of my PCGen (6.08.00RC8) and when I try to load it, it return me an error and ask me to check the log (which I don't know where to check).

Thanks.

**Comment by Grummore** [comment]
Added the log
[log.txt](https://github.com/BahamutDragon/pcgen/files/7943296/log.txt)
.

**Comment by BahamutDragon** [comment]
Download the correct version. PCGen 6.09.05 is technically the latest if you are using the master branch. For 6.08.xx support, you need to use the data from the 6.08 branch.

That's what this lovely message is basically saying:
11:16:21.724 LSTERROR main LstUtils:147 Illegal Token 'ALIGNMENTFEATURE' 'YES' for pcgen.cdom.inst.CodeControl Controller in file:/C:/PCGen/6.08.00RC8/6.08.00RC8/system/gameModes/Darksun35e/codeControl.lst
11:16:21.725 LSTERROR main LstUtils:147 Illegal Token 'DOMAINFEATURE' 'YES' for pcgen.cdom.inst.CodeControl Controller in file:/C:/PCGen/6.08.00RC8/6.08.00RC8/system/gameModes/Darksun35e/codeControl.lst

**Comment by Grummore** [comment]
Thanks, sorry for the delay! Completely forgot I asked!
