### ISSUE TITLE
I found a feature (  Bonded Spirit (Su)   [Paizo Inc. - Advanced Class Guide, p.106] )with a [Not Impemented] tag, can someone implement it?

### ISSUE THREAD

**Issue by cernenwein** [BahamutDragon/pcgen#1080]
Bonded Spirit (Su)  
[Paizo Inc. - Advanced Class Guide, p.106] 
     [NOT IMPLEMENTED]

**Comment by BahamutDragon** [comment]
Mate, you need to reach out to the official PCGen team. I only implement things that the official team does not support.

Cheers!
