### ISSUE TITLE
35e Bahamut mon_kits.lst crash

### ISSUE THREAD

**Issue by liquidspeaker** [BahamutDragon/pcgen#1084]
when loading the aforementioned set it loads all the way to mon_kits.lst and pops an error telling me to read the report (which doesnt show up) for details. on 3.09.5

**Comment by BahamutDragon** [comment]
Mate, I am going to need more details to even begin to debug this.

How about some basic details:
* What Version of PCGen are you running?
* What books are you attempting to load?
* Have you introduced any custom books/homebrew?
* Are there any errors? (Are you able to start PCGen using the command prompt method and screenshot the log there?)

**Comment by liquidspeaker** [comment]
im running 1.09.05
all the bahamut 3.5e set advanced selected
no new homebrew of my own that wasnt from your repo
no error, just says there was an exception

**Comment by liquidspeaker** [comment]
from what im told there seems to Looks like there's a CHOOSE:ABILITYSELECTION that's not set up correctly. but it doesnt say which book is casing it, i know the two that i get stuck at ar Mon_kit.lst and sa_(cant remember the rest)

**Comment by liquidspeaker** [comment]
i was using gen 6.05 and not modpack 6.08, it was an incompatibility issue.
