### ISSUE TITLE
Wrong comparison operator used for Attuned_Item_Max?

### ISSUE THREAD

**Issue by ArcherSmythe** [BahamutDragon/pcgen#1085]
According to the D&D 5e DMG (page 138, top-right paragraph), a character can be attuned to at most 3 items at the same time. I see that specified in dmg_abilities.lst:

`BONUS:VAR|Attuned_Item_Max|3|TYPE=Base`

However, when the Attuned_Item_Count is compared to the Attuned_Item_Max, the Less Than operator is used:

`PREVARLT:Attuned_Item_Count,Attuned_Item_Max`

I think that should that be changed to the following:

`PREVARLTEQ:Attuned_Item_Count,Attuned_Item_Max`

Otherwise, having 3 items attuned causes all three items to be listed in red.

It looks like this is also in PCGen's data/5e/wizards_of_the_coast/srd5/srd5_abilities.lst . I'll see if I can open a ticket with PCGen for that.

**Comment by BahamutDragon** [comment]
Updated.
