### ISSUE TITLE
Error Loading Bahamut 3.5 Modules

### ISSUE THREAD

**Issue by goozillah** [BahamutDragon/pcgen#1088]
Here is the list of modules I am loading into PCGen v6.08.oo RC8

![image](https://user-images.githubusercontent.com/103434017/163524385-7c0dd2da-574f-4e6d-8748-7d502390e5cd.png)

And here is the error that appears.

![image](https://user-images.githubusercontent.com/103434017/163524191-77240d55-5707-456f-aa24-ff603f5062c6.png)

**Comment by BahamutDragon** [comment]
That is the error when you have a mismatched data set version to pcgen version. Confirm you are only using the 6.08 branch for pcgen 6.08.x?

**Comment by dakota-white69** [comment]
hello,
I am trying to add your homebrew and i am getting this message. I can not find the file that its looking for.
![Capture](https://user-images.githubusercontent.com/96894333/181606406-ba26b9ce-5f69-4f63-82f3-e054a645a31c.JPG)

**Comment by BahamutDragon** [comment]
Are you using the right gamemode?

**Comment by Loryer00** [comment]
Hi @BahamutDragon,
I have the same problem too. I installed Gi correctly and I cloned your project on the pc in a folder that is not the PCGen installation folder.
Then I took the folders and copied/overwrote them with the PCGen installation ones.
Everything seemed to work until when I chose the sources and loaded them I got the error you see above.
I'll post you my Log, I hope you can help me, thanks
[PCGEN_LOG.txt](https://github.com/BahamutDragon/pcgen/files/11179098/PCGEN_LOG.txt)

**Comment by BahamutDragon** [comment]
Sorry for the delay. Same exact issue. You are using the MASTER Data designed for 6.09.xx in 6.08.xx which are not compatible. You need to download the 6.08 data to work with the 6.08 version of pcgen.

**Comment by Rhadymanthus** [comment]
Sorry to continue this thread, but I am suffering the same issue. I have tried installing 6.08.zip into both PCGen 6.08.00 RC08 and RC10.  When I select Game 3.5e In both cases I get the same error as displayed by the previous poster, i.e. most of the supplement sources are highlighted in red and return the error INCLUDESBOOKTYPE=Core35e when I try to load them.

Any help would be greatly appreciated as I dearly wish to continue using PCGen with all this fantastic expansion material.

**Comment by BahamutDragon** [comment]
To use the 3.5e content there are two options:
1) Copy the included system/gamemode content into your pcgen installation /system/gamemode folder and then select 'Bahamut35e' as the system when PCGen loads up, which will assure only sets that are compatible will be available.
or
2) Select the proper core sets (PH, DMG, and MM) which is all contained within the book loader named 'Dungeons & Dragons - Core Books'. 

The expansion books requires at minimum the proper core books to load regardless of using method 1 or 2.
