### ISSUE TITLE
Missing Warforged Feats

### ISSUE THREAD

**Issue by goozillah** [BahamutDragon/pcgen#1089]
Improved Damage appears, but Adamantine Body, Improved Fortification, Mithral Body, and Mithral Fluidity do not.

![image](https://user-images.githubusercontent.com/103434017/163525497-27b19732-c18b-429b-8d19-bdad7cc00442.png)

**Comment by BahamutDragon** [comment]
Did you select the First Level Feat pool?

![image](https://user-images.githubusercontent.com/4307487/163694022-ebf87dbf-cdc2-4057-84ac-b76d288edf49.png)

Next, the other two feats will not display since you have the QUALIFIED button depressed, which means only feats qualified will be displayed.
