### ISSUE TITLE
Marking attuned items as Carried causes the "This Character is Violating a Rule" message appear

### ISSUE THREAD

**Issue by ArcherSmythe** [BahamutDragon/pcgen#1090]
I have a character with a dagger and a shortbow, both of which require attunement. The only way to attune both items seems to be:

1. place one weapon in hand
2. attune it
3. move that one to the Carried category on the Equipment set
4. place the other in hand
5. attune it (to get the second weapon to appear as an option for Item Attunement in the Special Abilities frame of the Feats&Abilities->Character tab, you may need to click something other than Item Attunement, then click back to Item Attunement.)

Since the first weapon is now Carried, the VARiable and PREABILITY don't get applied, causing the rule violation warning to appear.

I've attached an example PCG (renamed to .TXT) with two attuned items. (It's also possible this just isn't worth worrying about, depending on how complicated any fix might be.)

[AttuneExample.txt](https://github.com/BahamutDragon/pcgen/files/8500827/AttuneExample.txt)

**Comment by BahamutDragon** [comment]
Allowed for selecting any attunement, adjusted how the restriction works, and clean up the interaction.
