### ISSUE TITLE
5e/Volo's Guide to Monsters: Lizardfolk has incorrect move speed

### ISSUE THREAD

**Issue by megatog615** [BahamutDragon/pcgen#1091]
Books loaded: Players' Handbook, Volo's Guide to Monsters

If you create a new character, select Lizardfolk, and roll stats, the _base_ move/walk speed is 60ft, which is incorrect. It seems that the data files also show 30ft move speed as well, so something is adding another 30ft.

At first I thought it might be adding the swim speed(30ft) on top somehow, but the Tritan race also has the same movement stats and it functions normally(30/30).

**Comment by BahamutDragon** [comment]
Fixed.
