### ISSUE TITLE
#.5 DIeties creation

### ISSUE THREAD

**Issue by liquidspeaker** [BahamutDragon/pcgen#1092]
can we get some way of creation our own custom dietities and demy gods using the "divine spark" and "awakened divine spark" as we for methods the ability to create an actual deity class in your brew? would be super helpful. Dieties and demigods kinda covers the idea of a spark, but having it attached to a character at effectively salient level -1 mortal would be neat. something they feel in them that drives them on without them knowing its there in game kind of thing, added to their sheets in GMGen so you an keep track for them?

**Comment by BahamutDragon** [comment]
Deity creation would have to be submitted to the actual PCGen team. I know of no method to have custom deities created inside the actual program. You would have to enter any deity by hand with the lst code. 

I do not do any work in GMGen, that is a separate program that the PCGen team appears to have stopped supporting. If you are asking for something on the character sheet, a spot already exists for the GM to enter notes that are not displayed within the PCGen program. 

The character sheets themselves already have Salient Deity Support built in. If that is not working, then open a ticket and I will double check my data sets.
