### ISSUE TITLE
Trouble with gameMode or... not?

### ISSUE THREAD

**Issue by Grummore** [BahamutDragon/pcgen#1094]
Hi!
Is it normal to find the Darksun setting in 3.5e, while it is supposed to be in 35e Bahamut's?

When I create a character with 3.5e/darksun35e, I sometime get an error. Is it because darksun should be with bahamut WITH his gamemode? Otherwise, if I use bahamut gamemode, I cannot find darksun.

![image](https://user-images.githubusercontent.com/9978645/173125758-c840f510-81be-4f0a-b8e8-bcda17584c9b.png)
![image](https://user-images.githubusercontent.com/9978645/173125810-ff3273aa-3979-4016-901a-7fe06a8d1cd1.png)

**Comment by BahamutDragon** [comment]
Darksun has its own gamemode called Darksun35e, make sure that is in the system/gamemodes folder for pcgen.
