### ISSUE TITLE
ph_equip.lst KEY field with commas - needs definition of correct fix

### ISSUE THREAD

**Issue by FerretDave** [BahamutDragon/pcgen#1102]
Errors on load (688)

loading just the core source books gives errors regarding prohibited character in a key:
17:07:45.665 INFO Thread-36 SourceFileLoader:534 Loading game Bahamut35e and sources [Dungeons & Dragons - Core Books].
17:07:47.383 LSTWARN Thread-36 AbstractReferenceManufacturer:766 Found Equipment with KEY: AUTOSIZELLongbow, Composite (+4) which contains a comma (prohibited character in a key)
17:07:47.383 LSTWARN Thread-36 AbstractReferenceManufacturer:766 Found Equipment with KEY: Mace, Light +1 which contains a comma (prohibited character in a key)
17:07:47.383 LSTWARN Thread-36 AbstractReferenceManufacturer:766 Found Equipment with KEY: Masterwork Sword, Short (Alchemical Silver) which contains a comma (prohibited character in a key)
17:07:47.383 LSTWARN Thread-36 AbstractReferenceManufacturer:766 Found Equipment with KEY: Masterwork Waraxe, Dwarven (Small) which contains a comma (prohibited character in a key)
17:07:47.383 LSTWARN Thread-36 AbstractReferenceManufacturer:766 Found Equipment with KEY: Sword, Short (Alchemical Silver) which contains a comma (prohibited character in a key)
17:07:47.383 LSTWARN Thread-36 AbstractReferenceManufacturer:766 Found Equipment with KEY: Sword, Short (Small/Alchemical Silver) which contains a comma (prohibited character in a key)

These appear related to KEY fields in ph_equip.lst -  by renaming the relevant KEY fields to remove the brackets "Longbow (Composite)" becomes "Longbow Composite", etc I can make these specific errors go away, however then get other Unconstructed references.
The errors above for magical/Masterworked variants are possibly from the GEAR in monster_manual/mm_kits.lst  ?

Changing the actual equipment name "Longbow, Composite" to remove the comma makes no differences, so it's definitely related to the key (which is obviously used elsewhere a lot).

Not sure of the best fix for these, using brackets is a standard across a lot of sources. Happy to make changes if you can confirm the best approach to resolve this.

**Comment by chainria** [comment]
Yeah, I think the commas were banned and all the sources moved to the brackets. So I guess ultimately a rework would be in order, even if it sucks.

However, these are only warnings and should not hinder using the source at all.

**Comment by FerretDave** [comment]
Thing is, the KEY does *not* have commas in ... it's something else (presumably gear?) that is taking that key and expanding it (adding 'Masterwork' etc) and adding the comma's automatically for the 'generated' item. No idea what kind of internal rule is taking the bracketed name and adding the commas to the Key itself.

**Comment by BahamutDragon** [comment]
If it is not in the repo then it cannot be fixed by myself. You would need to address this issue with the PCGen development team. I will see if there is something to be done on the data side.

**Comment by FerretDave** [comment]
sorry - this *is* your sources ...

**Comment by BahamutDragon** [comment]
Where in the repo is "AUTOSIZELLongbow"? I did a search of the 35e folder and found nothing by that reference. I would suspect these are custom created weapons stored in the custom lst files auto-generated by pcgen. If that is true, I stand by my statement that if it is not in my repo then it is not something readily fixed. 

However, just for testing, I made this alteration in the ph_equip file. Give that a try. Make a custom item using this and see if that removes the errors upon a save and restart.

`Axe (Throwing)		OUTPUTNAME:Axe, Throwing	KEY:Axe (Throwing)			PROFICIENCY:WEAPON|Axe (Throwing)			TYPE:Weapon.Container.Melee.Martial Ranged.Finesseable.Ranged.Thrown.Martial.Standard.Slashing.Axe								CONTAINS:UNLIM|Weapon Crystal=1											COST:8	WT:2							CRITMULT:x2	CRITRANGE:1							DAMAGE:1d6				EQMOD:STEEL						WIELD:Light						RANGE:10						SIZE:M	SOURCEPAGE:p.114																																																			SPROP:A throwing axe is lighter than a handaxe and balanced for throwing. Gnome fighters often use throwing axes for both melee and ranged attacks.
`

**Comment by FerretDave** [comment]
! Never thought to check the customsources/Bahamut35e/customEquipment.lst 
That did indeed contain the corrupt records... very sorry, removed that and all is well now.  Must have been created from an earlier version of the source and it kept the old/legacy format. Apologies. Definitely one to remember - remove that file when upgrading !
