### ISSUE TITLE
REQUESTING HELP: Implementing feat and Custom Item

### ISSUE THREAD

**Issue by uncreative54** [BahamutDragon/pcgen#1112]
First off, with my local GM homebrewing a rule, I added Dragonhide as an option for Kobolds, so ignore that particular change. It worked and needs no editing.

I know how to add a stat bonus to a feat. That was easy enough. As for the natural armor, that would just require switching the AC method, so that's essentially implemented already. The only complicated thing would be to add claws as unarmed attacks. The Tabaxi from Volo's guide have the same exact claws as an integrated ability along with the claws listed as an item, but I don't know how you would implement that ability as part of a feat. I copied the equipment file with the claws into XGTM and then added it to the pcc, but I have no idea how you would auto-equip them and add the weapon proficiency. Alternatively, I could attempt to add the effect of a Lizardfolk natural bite attack from VGM, with relevant re-naming (Looks like it wouldn't require any dependent files). But, again, I don't know how I'd turn code for an ability into a BONUS entry for a feat. Any help would be great!

Second, I would like to make a Masterwork Equipmentmod for gear like thieve's tools. This is a homebrew rule. The effect of Masterwork tools in variant rules is to double the proficiency bonus. As an alternative, I could just copy the code and make a standalone Masterwork Thieve's Tool. What code would allow a doubling of the proficiency bonus if they are a standalone item? If I can figure that out or be told the code, then I could just clone it for any other masterwork tools

[Unsuccessful file edits for DnD 5e [Dragon Hide feat & Masterwork mod, Standalone Masterwork Tools.txt](https://github.com/BahamutDragon/pcgen/files/9388562/Unsuccessful.file.edits.for.DnD.5e.Dragon.Hide.feat.Masterwork.mod.Standalone.Masterwork.Tools.txt)
.

**Comment by BahamutDragon** [comment]
# not * for comment out lines.

BONUS is a numerical alteration. It is not used to equip anything.
KIT would be how to equip a piece of equipment.
KIT:1|Tabaxi Claws

Then in a kit file, should be something like this:
STARTPACK:Tabaxi Claws
GEAR:Tabaxi Claws

Which means you will need the equipment listed:
Tabaxi Claws
   TYPE:Weapon.Melee.Slashing.Piercing
   DAMAGE:1dx
   PROFICIENCY:WEAPON|Tabaxi Claws

Which means you will need the proficiency file:
Tabaxi Claws
   TYPE:Exotic.Racial

Which means you'll want to do something like this in the claws feat:
AUTO:WEAPONPROF|Tabaxi Claws


NATURALATTACKS is used for non-iterative attacks that monsters typically gain. Any creature using this tag is granted proficiency automatically.


Doubling bonuses... Well, if you insist, there's the code to do it. Making an equipmod is a very clunky method... These are all abilities:

`Masterwork Tool Proficiency ~ Alchemist's Supplies		CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Alchemists_Supplies|Proficiency_Bonus|TYPE=Masterwork		
Masterwork Tool Proficiency ~ Brewer's Supplies			CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Brewers_Supplies|Proficiency_Bonus|TYPE=Masterwork		
Masterwork Tool Proficiency ~ Calligrapher's Supplies		CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Calligraphers_Supplies|Proficiency_Bonus|TYPE=Masterwork	
Masterwork Tool Proficiency ~ Carpenter's Tools			CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Carpenters_Tools|Proficiency_Bonus|TYPE=Masterwork		
Masterwork Tool Proficiency ~ Cartographer's Tools		CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Cartographers_Tools|Proficiency_Bonus|TYPE=Masterwork		
Masterwork Tool Proficiency ~ Cobbler's Tools			CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Cobblers_Tools|Proficiency_Bonus|TYPE=Masterwork			
Masterwork Tool Proficiency ~ Cook's Utensils			CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Cooks_Utensils|Proficiency_Bonus|TYPE=Masterwork			
Masterwork Tool Proficiency ~ Glassblower's Tools		CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Glassblowers_Tools|Proficiency_Bonus|TYPE=Masterwork		
Masterwork Tool Proficiency ~ Jeweler's Tools			CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Jewelers_Tools|Proficiency_Bonus|TYPE=Masterwork			
Masterwork Tool Proficiency ~ Leatherworker's Tools		CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Leatherworkers_Tools|Proficiency_Bonus|TYPE=Masterwork		
Masterwork Tool Proficiency ~ Mason's Tools			CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Masons_Tools|Proficiency_Bonus|TYPE=Masterwork			
Masterwork Tool Proficiency ~ Painter's Supplies		CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Painters_Supplies|Proficiency_Bonus|TYPE=Masterwork		
Masterwork Tool Proficiency ~ Potter's Tools			CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Potters_Tools|Proficiency_Bonus|TYPE=Masterwork			
Masterwork Tool Proficiency ~ Smith's Tools			CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Smiths_Tools|Proficiency_Bonus|TYPE=Masterwork			
Masterwork Tool Proficiency ~ Tinker's Tools			CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Tinkers_Tools|Proficiency_Bonus|TYPE=Masterwork			
Masterwork Tool Proficiency ~ Weaver's Tools			CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Weavers_Tools|Proficiency_Bonus|TYPE=Masterwork			
Masterwork Tool Proficiency ~ Woodcarver's Tools		CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Woodcarvers_Tools|Proficiency_Bonus|TYPE=Masterwork		
Masterwork Tool Proficiency ~ Disguise Kit			CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Disguise_Kit|Proficiency_Bonus|TYPE=Masterwork			
Masterwork Tool Proficiency ~ Forgery Kit				CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Forgery_Kit|Proficiency_Bonus|TYPE=Masterwork			
Masterwork Tool Proficiency ~ Dice Set				CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Dice_Set|Proficiency_Bonus|TYPE=Masterwork				
Masterwork Tool Proficiency ~ Dragonchess Set			CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Dragonchess_Set|Proficiency_Bonus|TYPE=Masterwork			
Masterwork Tool Proficiency ~ Playing Card Set			CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Playing_Card_Set|Proficiency_Bonus|TYPE=Masterwork		
Masterwork Tool Proficiency ~ Three-Dragon Ante Set		CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Three_Dragon_Ante_Set|Proficiency_Bonus|TYPE=Masterwork		
Masterwork Tool Proficiency ~ Bagpipes				CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Bagpipes|Proficiency_Bonus|TYPE=Masterwork				
Masterwork Tool Proficiency ~ Drum					CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Drum|Proficiency_Bonus|TYPE=Masterwork				
Masterwork Tool Proficiency ~ Dulcimer				CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Dulcimer|Proficiency_Bonus|TYPE=Masterwork				
Masterwork Tool Proficiency ~ Flute					CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Flute|Proficiency_Bonus|TYPE=Masterwork				
Masterwork Tool Proficiency ~ Lute					CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Lute|Proficiency_Bonus|TYPE=Masterwork				
Masterwork Tool Proficiency ~ Lyre					CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Lyre|Proficiency_Bonus|TYPE=Masterwork				
Masterwork Tool Proficiency ~ Horn					CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Horn|Proficiency_Bonus|TYPE=Masterwork				
Masterwork Tool Proficiency ~ Pan flute				CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Pan_flute|Proficiency_Bonus|TYPE=Masterwork				
Masterwork Tool Proficiency ~ Shawm					CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Shawm|Proficiency_Bonus|TYPE=Masterwork				
Masterwork Tool Proficiency ~ Viol					CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Viol|Proficiency_Bonus|TYPE=Masterwork				
Masterwork Tool Proficiency ~ Herbalism Kit			CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Herbalism_Kit|Proficiency_Bonus|TYPE=Masterwork			
Masterwork Tool Proficiency ~ Navigator's Tools			CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Navigators_Tools|Proficiency_Bonus|TYPE=Masterwork		
Masterwork Tool Proficiency ~ Poisoner's Kit			CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Poisoners_Kit|Proficiency_Bonus|TYPE=Masterwork			
Masterwork Tool Proficiency ~ Thieves' Tools			CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Thieves_Tools|Proficiency_Bonus|TYPE=Masterwork			
Masterwork Tool Proficiency ~ Vehicles (Land)			CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Vehicles_Land|Proficiency_Bonus|TYPE=Masterwork			
Masterwork Tool Proficiency ~ Vehicles (Water)			CATEGORY:Internal		TYPE:Masterwork Tool Proficiency	BONUS:VAR|ProfBonus_Vehicles_Water|Proficiency_Bonus|TYPE=Masterwork			
`

**Comment by uncreative54** [comment]
Thank you so much!
