### ISSUE TITLE
BOOK REQUEST: Mordenkainen Presents Monsters of the Multiverse

### ISSUE THREAD

**Issue by uncreative54** [BahamutDragon/pcgen#1113]
I was hoping to see some of the races from Fizban's Treasury of Dragons make it in. And if they do get entered, it would probably be worth tagging other races as Legacy, so that the Kobold in Volo's Guide to Monsters would now be Legacy Kobold. The Kobold had some pretty major changes that are unpopular for a lot of players running kobolds.

I sent a link to my google drive to your e-mail address, so you should be able to find the book in there.

**Comment by BahamutDragon** [comment]
Time is a limited resource these days. Was there a specific race or three you were invested in seeing? Also, a rule of thumb is to not alter previous entries. Having two kobold versions side-by-side is not all that hard.

**Comment by uncreative54** [comment]
So far I'm pretty happy with the 5e material. The Kobold I run right now is the legacy Kobold that's already in your data. So having the new Kobold in the system as Kobold [Updated] would likely be more helpful to other players.The Fizban request was more for data missing from the game, in order to make it more complete more than a request thar would help me run my current character.I absolutely so not expect you to spend all your time just monotonously adding every detail from every book.In fact, D20 Modern stuff is where, if the offer is helping me directly make my character function in pcgen, the most info is missing.In my D20 modern game I will be running a psionic agent and it appears that there's not really a psionic list in the data set because there isn't one in the SRD.If you can just /start/ a psionic list so I can see how it is formatted, especially with regards to psionics restricted to specific classes and then direct me to the file, I can help fill it in. The only psionics in the game are from the base book and the Arcana book. It's still a relatively long list, which is absolutely why I'm offering help.Let me know if that's something that fits your time allocations and where to find it once you've started it.Thanks!-JonSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Bahamut ***@***.***> Date: 9/18/22  3:56 PM  (GMT-07:00) To: BahamutDragon/pcgen ***@***.***> Cc: uncreative54 ***@***.***>, Author ***@***.***> Subject: Re: [BahamutDragon/pcgen] BOOK REQUEST: FIZBAN (Issue #1113) 
Time is a limited resource these days. Was there a specific race or three you were invested in seeing? Also, a rule of thumb is to not alter previous entries. Having two kobold versions side-by-side is not all that hard.

**Comment by BahamutDragon** [comment]
There are a total of 14 OCR entries of Kobold, none of them are alterations to the race. Your referral to legacy and new is confusing as nothing appears to change the kobold race. The book appears to focus on dragons, and dragonborn. So, again, what are you requesting from the book that you need?

d20 Modern and 5e are separate systems. Let's focus on each request and keep those separated please. Jumping books or systems just causes confusion and frankly wastes my time trying to unravel the mystery. If you want something specific in modern, then ask in a separate thread.

**Comment by uncreative54** [comment]
Oh you know what, I might have confused the language I used when referring to book releases. Fizban's treasury of dragons doesn't have the new Kobold, that's Mordenkainen Presents: Monsters of the Multiverse. After MP: MotM, online resources (dndbeyond.com) started referring to the Kobold race as defined in Volos Guide to Monsters as the Kobold (Legacy).I think I got my wires crossed and thought the new Kobold was in Fizban because Fizban is all about draconic races, of which Kobolds are one.I have a tendency to make "omnibus" posts that can wander between books.Considering that the Fizban alterations to dragonborn are likely complicated to make. As they essentially produce subraces, with your limited time, I'd say go for making the Kobold from Mordenkainen.-JonathanSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Bahamut ***@***.***> Date: 9/18/22  7:28 PM  (GMT-07:00) To: BahamutDragon/pcgen ***@***.***> Cc: uncreative54 ***@***.***>, Author ***@***.***> Subject: Re: [BahamutDragon/pcgen] BOOK REQUEST: FIZBAN (Issue #1113) 
There are a total of 14 OCR entries of Kobold, none of them are alterations to the race. Your referral to legacy and new is confusing as nothing appears to change the kobold race. The book appears to focus on dragons, and dragonborn. So, again, what are you requesting from the book that you need?
d20 Modern and 5e are separate systems. Let's focus on each request and keep those separated please. Jumping books or systems just causes confusion and frankly wastes my time trying to unravel the mystery. If you want something specific in modern, then ask in a separate thread.

**Comment by BahamutDragon** [comment]
Added Kobolds and granted a selector between the two versions. RAW, so please test.
