### ISSUE TITLE
5e - Sorcerer Cantrips - Missing?

### ISSUE THREAD

**Issue by chainria** [BahamutDragon/pcgen#1115]
I can't seem to find any other cantrips from the PH than Blade Ward, Fire Bolt and Mage Hand.

If I look into ph_spells.lst, I see a bunch of commented out MOD lines. Are those just not complete yet, or is there any other explanation why those are essentially disabled?

**Comment by BahamutDragon** [comment]
List shows:
Sorcerer Cantrip ~ Acid Splash		
Sorcerer Cantrip ~ Blade Ward		
Sorcerer Cantrip ~ Chill Touch		
Sorcerer Cantrip ~ Dancing Lights	
Sorcerer Cantrip ~ Fire Bolt		
Sorcerer Cantrip ~ Friends		
Sorcerer Cantrip ~ Light			
Sorcerer Cantrip ~ Mage Hand		
Sorcerer Cantrip ~ Mending		
Sorcerer Cantrip ~ Message		
Sorcerer Cantrip ~ Minor Illusion	
Sorcerer Cantrip ~ Poison Spray		
Sorcerer Cantrip ~ Prestidigitation	
Sorcerer Cantrip ~ Ray of Frost		
Sorcerer Cantrip ~ Shocking Grasp	
Sorcerer Cantrip ~ True Strike		

Which version is this against?

**Comment by chainria** [comment]
Oh, now I get it! So you have to choose them from Abilities > Character first? Yeah, somehow my brain must have lagged. Background: Our DM has approved new sourcebooks and therefore let us reroll our spell lists. So I wanted to take a look at the cantrips as well but couldn't find any new under Spells. But after searching for the text in the files, I found out how it works.

Thank you for the help!
