### ISSUE TITLE
5e spellcasters seem to lose spell slots as they level up

### ISSUE THREAD

**Issue by megatog615** [BahamutDragon/pcgen#1117]
I don't know if it's PCGen or these books(I am guessing it's the latter since they seem to control this) but for some reason, as I level my spellcaster character to 9th level(in this case, an artificer), my spell slots/known spells goes from 4/1st 4/2nd to 3/1st 5/2nd. I noticed this was happening while creating a Sorcerer a month ago as well, leading to me giving up on it and changing classes. Not really sure what's going on but this seems pretty serious.

**Comment by BahamutDragon** [comment]
Caster Spell Slots ~ Artificer	
CATEGORY:Internal		
BONUS:VAR|SpellSlotsLVL1|(2*(ArtificerLVL>=1))+(ArtificerLVL>=3)+(ArtificerLVL>=5)
	BONUS:VAR|SpellSlotsLVL2|(2*(ArtificerLVL>=5))+(ArtificerLVL>=7)
	BONUS:VAR|SpellSlotsLVL3|(2*(ArtificerLVL>=9))+(ArtificerLVL>=11)
	BONUS:VAR|SpellSlotsLVL4|(ArtificerLVL>=13)+(ArtificerLVL>=15)+(ArtificerLVL>=17)
	BONUS:VAR|SpellSlotsLVL5|(ArtificerLVL>=17)+(ArtificerLVL>=19)

That is the formula for calculating your values. 

Can you provide the impacted character files?

**Comment by chainria** [comment]
I play a sorcerer using 6.09.05 and my spell slots seem fine, just as a short information. I have 4/3/3/1 at Lvl. 7, which is in accordance to the source books / srd.

**Comment by megatog615** [comment]
Okay, sorry it took me a long time. Life issues have made this a low priority for me but now I can get back to it. I have levelled up an Eldritch Knight to level 10, but I cannot choose a new spell because the 'known spells' is now 1 for 1st level and 5 for 2nd level. At level 9 it was 2 1st level and 4 2nd level. When I choose a new spell for 2nd level, it complains that I cannot learn more spells and I have a bunch of 1st level spells in higher slots.
[bro.pcg.zip](https://github.com/BahamutDragon/pcgen/files/9856768/bro.pcg.zip)

**Comment by BahamutDragon** [comment]
To accommodate sorcerer spell casting, you need to enable the option to allow the use of higher level slots for lower level spells. 

![image](https://user-images.githubusercontent.com/4307487/198894130-683447c6-77ac-447d-8be7-68e65e2120b1.png)

**Comment by megatog615** [comment]
This doesn't appear to be working. Why should I be losing known spells as I level up? I don't think this is solved.

**Comment by BahamutDragon** [comment]
This is the Sorcerer: 
![image](https://user-images.githubusercontent.com/4307487/225436482-2c79214f-3c41-4ecf-97c3-0d5f9e286085.png)

Here's the text:
Spells Known of 1st Level and Higher
You know two 1st-level spells of your choice from the
sorcerer spell list.
The Spells Known column of the Sorcerer table
shows when you learn more sorcerer spells of your
choice. Each of these spells must be of a level for which
you have spell slots. For instance, when you reach 3rd
level in this class, you can learn one new spell of 1st
or 2nd level.
Additionally, when you gain a level in this class,
you can choose one of the sorcerer spells you know
and replace it with another spell from the sorcerer
spell list, which also must be of a level for which you
have spell slots.

How would you prefer to see that implemented?

**Comment by BahamutDragon** [comment]
Regarding the progression - Levels 1 and 2 are fine, they progress normally. At level 3 that's where things become 'tricky'. Sorcerer gains a new known spell, which obviously should be level 2 and I can remove a 1st level known and take a 2nd level known, though the player may opt to have 4 1st level spells known and power then with higher level slots. Which means out of 4 known, I can either split evenly between 1st and 2nd level, only have 1 for 2nd level or none for 2nd level. 

Alternatively, I can require the player to make the decision with each level where to assign each known, and let them manage that. Bit more work. It also might not display the new value without a save and reload potentially.

Or if you want fancy. I can force the player to determine whether to allow PCGen to do the progression set up automatically, or require the player to determine where the known level will apply.

Those are the only options I can come up with. That is why I opted to drop all the known into the highest level and allow the player to use the PCGen options to manage that as they desired. You are not losing any spells known. The warlock is set up in the exact same manner.

**Comment by BahamutDragon** [comment]
Okay, I'll work on making the user choose the known progression. Sorcerer is completed.

**Comment by BahamutDragon** [comment]
PH - Bard, Ranger and Sorcerer completed.

**Comment by BahamutDragon** [comment]
All 5e casters with a known component force a choice.
