### ISSUE TITLE
Ranger abilities from TCE: Fey Wanderer & Optional feats

### ISSUE THREAD

**Issue by Haaiku** [BahamutDragon/pcgen#1124]
Greetings!

Could you include the Fey Wanderer archetype of the Ranger? It's from TCE p.58
Deft Explorer & Primal Awareness would be great additions as well, from TCE p.56

Happy new year!

**Comment by BahamutDragon** [comment]
Yeah, I think we can get that added.

**Comment by BahamutDragon** [comment]
Added
