### ISSUE TITLE
(minor) - NPC Funds is missing / doesnt work for lv 13

### ISSUE THREAD

**Issue by FerretDave** [BahamutDragon/pcgen#1131]
Creating an NPC and adding NPC funds during initial character generation, the 'Kit Selection' dialog lists NPC Funds from Lv 1 through Lv 12, and then Lv 14 through to Lv 20.
Lv 13 is missing, but appears to be defined correctly in the lst file core/dungeon_masters_guide/dmg_kits.lst
(this is for 6.08.08 branch)

Also minor, it lists them in alphabetical rather than numeric order, which just looks odd, not sure if Kits can use a sort key ?

**Comment by BahamutDragon** [comment]
Should be fixed.

**Comment by FerretDave** [comment]
still not working (6.8.8 branch) I'm afraid.
