### ISSUE TITLE
6.08.00RC9 Stuck in startup "Loading Campaigns" at 100%

### ISSUE THREAD

**Issue by webdove** [BahamutDragon/pcgen#1135]
It never leaves the startup screen.
There is no recognizable .exe in the task manager.

![PCGEN Loading Campaigns](https://user-images.githubusercontent.com/77020755/217112724-8e59c71e-8a78-4022-a829-aaa05b17d615.png)

**Comment by FerretDave** [comment]
That'll be an issue for the main PCGen site (discord https://discord.com/channels/501255850636345375/501257389794787348 ) and not related to these sources - as you wont have been able to configure it to reference these yet.

**Comment by webdove** [comment]
It turns out that is a symptom of JAVA_HOME not being set as a system environmental variable.

 

It works now.

 

Thanks for helping.

 

Web

**Comment by webdove** [comment]
Am I correct in believing that recent WOTC content like Mordenkainen’s Monsters of the Multiverse are not accessible to PCGen?

**Comment by BahamutDragon** [comment]
Hi mate, 

Best to put new topics in separate requests. 

If you have a request, make it in a separate ticket. Just so you know, this repo is meant to host any valid PCGen content. I just do not have the available time as I once did. 

I am closing this original issue as resolved.
