### ISSUE TITLE
Warforged unable to take race specific armors

### ISSUE THREAD

**Issue by liquidspeaker** [BahamutDragon/pcgen#1141]
when untaken at CharGen, the warforged specific armors and core specifically show to be available, once taken the system registers that you now have broken one of the none of requirements by now having taken it, thus making it unavailable (red). this can be byspassed but it would be nice to see it fully emplemented.

**Comment by liquidspeaker** [comment]
5e btw with homebrew all enabled.

**Comment by BahamutDragon** [comment]
Fixed.
