### ISSUE TITLE
Warforged artificer

### ISSUE THREAD

**Issue by liquidspeaker** [BahamutDragon/pcgen#1142]
infusions have yet to seem to be added to class abilities.

**Comment by liquidspeaker** [comment]
5e as well

**Comment by BahamutDragon** [comment]
You need to clarify what you mean. Rising from the Last War I see:
_Artificer Infusion ~ Boots Of The Winding Path	
Artificer Infusion ~ Enhanced Arcane Focus		
Artificer Infusion ~ Enhanced Defense			
Artificer Infusion ~ Enhanced Weapon			
Artificer Infusion ~ Homunculus Servant		
Artificer Infusion ~ Radiant Weapon			
Artificer Infusion ~ Repeating Shot			
Artificer Infusion ~ Repulsion Shield			
Artificer Infusion ~ Resistant Armor			
Artificer Infusion ~ Returning Weapon_			

All seems to be properly coded and referenced.
