### ISSUE TITLE
5e D&D PHB Weapons missing critical multiplier

### ISSUE THREAD

**Issue by ArcherSmythe** [BahamutDragon/pcgen#1149]
This is a very low priority. I'm proposing that I do it as a learning experience for making future contributions. If you prefer I don't, either assign the ticket to someone else or reject it.

Basically, I'd like to add the CRITMULT: tag to all weapons in the 5E D&D PHB. Right now, these weapons show up as "20/x0" in the Critical field on PCGen character sheets.

**Comment by BahamutDragon** [comment]
PR accepted.
