### ISSUE TITLE
File Collisions with newer PCGen versions

### ISSUE THREAD

**Issue by chainria** [BahamutDragon/pcgen#1161]
First of all, thank you for maintaining this repository of information. I am using PCGen as well as your data set under Gentoo, with custom ebuilds. Since new releases have come out, I found that there are file collisions between the two. I don't see any difference between the files. Maybe these should be removed, since PCGen provides them as well?

 * Detected file collision(s):
 * 
 *      system/gameModes/default/compatibilityDataControl.lst
 *      system/gameModes/default/compatibilityGlobalModifier.lst
 *      system/gameModes/default/equipIcons.lst
 *      system/gameModes/default/paperInfo.lst
 *      system/gameModes/default/tips.txt
 *      system/gameModes/default/tips_fr.txt
 *      system/gameModes/default/bio/locations.lst
 *      system/gameModes/default/bio/traits.lst

I don't see any sense to keep them longer around, at least not in master.

Edit: I did a thorough comparison. The files all "have equal text, but are not binary equal."
Which means they are the same, but with different checksums. Can't find why.

This is against PCGen 6.09.06.

Against 6.08.00_rc10 it's only these differences:

diff -wru default/compatibilityDataControl.lst default.bahamut/compatibilityDataControl.lst
--- default/compatibilityDataControl.lst        2023-03-23 18:08:56.085451689 +0100
+++ default.bahamut/compatibilityDataControl.lst        2023-03-23 16:33:37.974993812 +0100
@@ -36,4 +36,7 @@
 DEFAULTVARIABLEVALUE:STRING|
 DEFAULTVARIABLEVALUE:DICE|0
 DEFAULTVARIABLEVALUE:ALIGNMENT|None
+DEFAULTVARIABLEVALUE:HANDED|Right
+DEFAULTVARIABLEVALUE:DEITY|None
+

**Comment by chainria** [comment]
I did a thorough comparison. The files all "have equal text, but are not binary equal."
Which means they are the same, but with different checksums. Can't find why.

**Comment by BahamutDragon** [comment]
Removed. Thanks mate!

**Comment by chainria** [comment]
Found another one:

 *      data/_universal/races.lst

Seems to be identical in 6.08_rc10.

Not sure about this one:
 *      data/_universal/datacontrols_no_align.lst
Basically the only difference is DEFAULTVARIABLEVALUE:HANDED|Right. But all the sources I could find code it in themselves?
