### ISSUE TITLE
5e Revised Ranger not functional

### ISSUE THREAD

**Issue by uncreative54** [BahamutDragon/pcgen#1163]
In looking at the revised ranger in the UA Revised Ranger files, I think the rr_classes.lst is missing the text required to actually get any of the class abilities, spells, etc. When you make a new character and add revised ranger levels, you get nothing beyond hit points and a message to select spells (Which are the only blocks present in the rr_classes.lst file), but it does not seem to actually link to ranger casting, as the known spells and prepared spells selections are completely blank.

**Comment by uncreative54** [comment]
Since this is related to the revised ranger, there is a revised ranger subclass in the "Three Subclasses" unearthed arcana, but the file in that folder is a placeholder. Would it be possible to get the three subclasses added in, or at least the revised ranger monster slayer subclass?

I think fixing the first post's revised ranger subclass might be a "relatively quick" one, since reading through the other lst files in the revised ranger folder seems to show all the abilities.

**Comment by uncreative54** [comment]
Also, I'm worried the abilities section for revised ranger won't point to the correct skills, skill selection, ranger spells known, ranger spell slots, saving throw proficiencies, etc. I think a lot of the basics are not getting pointed to.

In addition, the beast conclave revised ranger is suppose to get a ranger companion that gets the ranger's proficiency bonus added to AC, attacks, and damage. Dunno how difficult this is getting at this point.

Apologies, I'm trying to mess with the files myself and am making comments as I change things. I think that's all I'm going to personally mess around with.

For "easy" referencing to check if the revised ranger is getting all the proper stuff, here are links to the standard ranger and revised ranger.

Revised Ranger: http://dnd5e.wikidot.com/ranger-revised

Standard Ranger: http://dnd5e.wikidot.com/ranger

**Comment by BahamutDragon** [comment]
Made changes to fix the ranger. Should be functional now. And the standard selection, I do not recall my thoughts on it.
