### ISSUE TITLE
Ioun stones do not give bonuses

### ISSUE THREAD

**Issue by uncreative54** [BahamutDragon/pcgen#1164]
The ioun stones don't give the printed bonuses. I self-edited a bunch of them, but whenever the game gets updated, the changes get wiped.

Would it be possible to get the BONUS:STAT|***|2 to the agility (Dex), Fortitude (Con), Insight (Wis), Intellect (Int), Leadership (Cha), and Strength (duh) stones?  Also, I don't know if it would be equally as easy to add the AC +1 from the protection stone.

In addition, would it be possible to add the knave's eyepatch to the game?

http://dnd5e.wikidot.com/wondrous-items:knaves-eye-patch

**Comment by BahamutDragon** [comment]
Added.
