### ISSUE TITLE
5e / xgte: Drow High Magic not available

### ISSUE THREAD

**Issue by chainria** [BahamutDragon/pcgen#1165]
While helping out my DM, we spotted that it's not possible to take Drow High Magic right now.

Digging through the code revealed that Drow High Magic calls for the template "Elf Subrace ~ Drow", but this doesn't exist. I assume this should be "Elf Subrace ~ Dark" instead? Can provide a PR, will just have to set up a fork first in this case.

**Comment by BahamutDragon** [comment]
Fixed. Thanks!
