### ISSUE TITLE
Book of Exalted Deeds

### ISSUE THREAD

**Issue by Carmcritter** [BahamutDragon/pcgen#1166]
I do not fully understand how GitHub or PC Gen works, but I am trying to use Book of Exalted Deeds. 
The books seems to have loaded fine, and the feats show on the list, however once I have loaded the book both Human and Fighter Bonus Feats no longer populate.
Meaning.. I make a character as a human fighter and I can select 3 Feats at level one, but once I load BoED I only am allowed 1 Feat at level 1. If I unload the book, the error persists and I am no longer able to have Bonus Fighter or Human Feats.
I loaded it by copying the source to my homebrew files which is how I understood the "how to use this" message to read.

**Comment by BahamutDragon** [comment]
That is a very odd behavior. Can you upload a test character file that shows that problem?

**Comment by BahamutDragon** [comment]
I create a new character - Level 3 Human Fighter, and this is what I see:

![image](https://github.com/BahamutDragon/pcgen/assets/4307487/0d33ff4f-7e46-475e-b3a3-874251c20e69)

This is using only the Core Books and BoED.

![image](https://github.com/BahamutDragon/pcgen/assets/4307487/095fcdff-a2f6-42d4-b511-bed4a3c1f856)

Everything appears to be working correctly.

**Comment by Carmcritter** [comment]
Unfortunately no. I reinstalled because of an issue and now it won't even
let me load BED saying I'm missing the requisite book but as far as I can
tell I'm not.

**Comment by Carmcritter** [comment]
I took a better look(not used to the program)
There is no problem, it was user error. I didn't realize I needed to grab
all of your PHB, MM, DMG files. It makes sense now that I looked but I was
thinking it worked off the default.

Sorry to bother, thanks for responding.

**Comment by BahamutDragon** [comment]
Something is definitely broken. Trying to figure out where the break is.

**Comment by BahamutDragon** [comment]
Fixed over here: https://github.com/BahamutDragon/pcgen/issues/1169
