### ISSUE TITLE
Do you have to define this Type first?   TYPE:Minor Schema.Magic	

### ISSUE THREAD

**Issue by Athinar** [BahamutDragon/pcgen#1167]
Silver Ingot (Skill Enhancement/Minor Schema)		SPELLS:Magic Item|TIMES=1|CASTERLEVEL=1|Skill Enhancement		OUTPUTNAME:Silver Ingot (Skill Enhancement)		TYPE:Minor Schema.Magic		COST:400	WT:1	SOURCEPAGE:p.122

**Comment by BahamutDragon** [comment]
I am not sure what the question is. TYPE for equipment is something you add to help sort items in the UI and can sometimes be referenced by the code.

**Comment by Athinar** [comment]
Closed
