### ISSUE TITLE
Expanded Knowledge and Hidden Talen Feats.

### ISSUE THREAD

**Issue by Nodens-** [BahamutDragon/pcgen#1170]
Hello,

I have the issue seen in https://github.com/BahamutDragon/pcgen/issues/76 which I see as closed (completed). I am trying to add Astral Construct (Level 1 Power from Shaper) at level 3 via Expanded Knowledge to an Egoist Psionicist but the power is not listed at all. Is this a regression? Also is there a way to add it manually by editing the savefile?

Secondly the Hidden Talent feats are missing entirely although they are part of XPH as well. I can add them if I can also add the Dark Sun sources that come with PCGen but they don't work properly (They don't allow selecting a power).

**Comment by BahamutDragon** [comment]
#76 ties back to the code in PCGen which I do not have any control over. That was closed as it was no longer possible to address by myself at the time. Perhaps the code team there has fixed the code and it can be addressed.

Back to your items:
1) That sounds like incomplete programming. I will look at it.
2) It is best to separate concerns to avoid confusion. One issue (or related subset) per issue tracker to keep it simple.

**Comment by Nodens-** [comment]
My bad. I posted them in the same issue because they are both in XPH (as in XPH issue). Want me to make a separate issue for Hidden Talent?

Considering how good Astral Construct is, it's kinda standard for non-Shaper Psions to take it either with Hidden Talent or Expanded Knowledge. There should be some way to do this as it's almost essential. :)

**Comment by BahamutDragon** [comment]
Other than the fact after you take hidden talent you will need to save/close/reopen the character, this works as desired.
