### ISSUE TITLE
Eagle Size

### ISSUE THREAD

**Issue by Carmcritter** [BahamutDragon/pcgen#1171]
I was working on an Eagle Companion, already sent the file with Problem #1169 
When first made it, and added 2 HD for Druid level increases the size remained Small. I was going to include it in the issue above but the size was Medium when I looked at that time. Now I have logged back onto the character and the size is Small again.

**Comment by Carmcritter** [comment]
Apologies. This is for 3.5 DnD

**Comment by BahamutDragon** [comment]
The sizemod must be acting up. Let me remove the sizemod and the hitdiceadvancement and that should fix the problem.

**Comment by BahamutDragon** [comment]
Removed the size advanced from the companion races. Please test to validate proper behavior and close if it works.

**Comment by Carmcritter** [comment]
I am a little confused. Do I need to redownload all of the PHB files? are the files in the MM not needing fixed?

**Comment by BahamutDragon** [comment]
This is just the PHB files. Specifically, companionmods.lst and races.lst.

**Comment by Carmcritter** [comment]
Okay. I'll look into it later today and get back to you.
