### ISSUE TITLE
Chaos Monk from Dragon Magazine 335(Also in SRD)

### ISSUE THREAD

**Issue by Carmcritter** [BahamutDragon/pcgen#1172]
I noticed under the Paizo tab that there are a few Dragon Magazines. Any chance there is time to add Magazine 335, specifically the Chaos Monk. There are only a few level changes in features from the regular monk, and the alignment restriction change so I hope it helps that most of it is a copy from Monk.

**Comment by Carmcritter** [comment]
Apologies. This is for 3.5 DnD

**Comment by BahamutDragon** [comment]
I will have to track down that issue...

**Comment by BahamutDragon** [comment]
Chaos Monk alt selection added.

**Comment by Carmcritter** [comment]
Thanks!

**Comment by Carmcritter** [comment]
I am just now getting a chance to look at it. Is there something special I need to do to load it? I notice it says Alpha in red, was not sure if that was preventing me from using it or not. I have the latest version of PCGen.
