### ISSUE TITLE
Cannot create character using "Final Fantasy" (FFD20) dataset

### ISSUE THREAD

**Issue by pokemonpasta** [BahamutDragon/pcgen#1173]
Trying to create a character to test some things (I'm actually looking to update this dataset as the current implementation is quite old now, if you'd welcome a PR) but when I try to create a character I get

`Unable to create a new character. The error was: Cannot invoke "pcgen.base.solver.Modifier.process(pcgen.base.formula.EvaluationManager)" because "defaultModifier" is null.`

This only occurs on this dataset, other sets are working fine (which leads me to believe it's a data issue), and I've tried it with 6.08 data on 6.08.00RC10, and master data on 6.08.00RC8 and 6.08.00RC10 with the same results. This set is the only one loaded when I try this (trying to load core pf1e datasets at the same time just leads to ambiguous reference problems, so I assume this set is supposed to be loaded by itself)

**Steps to Replicate**
1. Run 6.08.00RC8 or 6.08.00RC10 versions of PCGen with master or 6.08 branch of this repo loaded
2. Load "Final Fantasy" dataset by itself
3. Create a new character

**Expected outcome**
New character windows opens as expected, with relevant data ready to use

**Actual outcome**
Error listed above, and no character window is opened

Log: https://pastebin.com/a9xiJRfD

**Comment by BahamutDragon** [comment]
That is only possible if you are using Master gamemodes while running 6.08 data. You need to change your gamemodes to 6.08 version.

**Comment by pokemonpasta** [comment]
As I mentioned above, I'm getting this issue when using 6.08 branch. I tried again on another fresh install of 6.08.00RC10 with 6.08 branch data and am still getting this error (gamemode files are the PCGen pathfinder files installed fresh with 6.08.00RC10, as the ffd20 source uses pathfinder1e as a gamemode)

**Comment by BahamutDragon** [comment]
Does a normal Pathfinder game give the error?

**Comment by pokemonpasta** [comment]
No, I can create regular pathfinder character fine (6.08.00RC10 with release data and gamemode)

**Comment by BahamutDragon** [comment]
Update and give that a try.

**Comment by pokemonpasta** [comment]
Still not working, but there's a different error this time which I suppose is progress

    Unable to create a new character. The error was: Cannot invoke "pcgen.cdom.base.CDOMObject.get(pcgen.cdom.enumeration.ObjectKey)" because "po" is null.

[Log](https://pastebin.com/3hpFdFuR)

**Comment by pokemonpasta** [comment]
I asked in the PCGen discord and apparently DEFAULTVARIABLEVALUE:DEITY needs a value too, so `DEFAULTVARIABLEVALUE:DEITY|None` might fix it

**Comment by Vest** [comment]
One more thing to add. There is a folder "_universal" with a small file races.lst. It has a <none selected> race that is always selected, when you create a new character.
I have checked random PCC files (especially Final Fantasy), and found out that you forgot to add this line:

```
RACE:*/_universal/races.lst
```
It must be included, otherwise PCGEN cannot select a None race :)

**Comment by BahamutDragon** [comment]
Issue found and addressed. Thanks mates for the deeper dive.
