### ISSUE TITLE
5e DnD Simple Issues  (Item add or minor feat modification)

### ISSUE THREAD

**Issue by uncreative54** [BahamutDragon/pcgen#1176]
Could you add the Knave's Eyepatch rare wondrous item

http://dnd5e.wikidot.com/wondrous-items:knaves-eye-patch

Could you add the feat "Metamagic Adept"

http://dnd5e.wikidot.com/feat:metamagic-adept

**Comment by BahamutDragon** [comment]
Both exist. Advanced Source Load Tasha's Cauldron of Everything, and Homebrew Support. I added the sorcery points.
