### ISSUE TITLE
5e feat error - Resilient

### ISSUE THREAD

**Issue by uncreative54** [BahamutDragon/pcgen#1178]
I have a 5e character and I selected the feat "resilient," then chose dex as the stat to gain the +1 and proficiency in dex saving throws.

It gave my character proficiency in every saving throw.

Not that I'm complaining mind you, but if someone audits my character, it should probably only get the proficiency associated with the selected stat.

**Comment by BahamutDragon** [comment]
Works for me just fine. The only reason I can think you would have all six selections is because you have enabled the feat requirements bypass house rule.
