### ISSUE TITLE
Add some monsters as races

### ISSUE THREAD

**Issue by uncreative54** [BahamutDragon/pcgen#1179]
Is it possible to complete/add the griffin into the monster selection? When digging through the files, it looks like most monsters aren't implemented. My nephew wants to play an "awakened" griffin and I see that a number of monsters are present as selectable races.

Griffin:

https://www.dndbeyond.com/monsters/16913-griffon

If you have some additional time:

T-Rex (As I'm sure that will come up at some point in my kid-friendly game). After all, Awaken is a spell kids love.

https://www.dndbeyond.com/monsters/17041-tyrannosaurus-rex

**Comment by uncreative54** [comment]
Also, this one might be a little more complicated, but a standard beholder would be nice. They make a great baddie, especially when given class levels, so it would be nice to have them selectable.

I'm posting it as a separate reply since it would arguably be the most complicated, having the most actions and abilities.

https://www.dndbeyond.com/monsters/17099-beholder

**Comment by BahamutDragon** [comment]
5e monsters are completely different from 5e characters, which makes coding monsters quite a challenge, one I have not really solved nor really had an inclination to tackle, since monsters are pretty static in the books and pretty much the purview of the Game Master. 

I will take a look Sunday to see what all would be involved.

**Comment by uncreative54** [comment]
If it's going to be a really large amount of time, then don't do it. Your free time is more important than my desires. Everybody deeply appreciates what you do here for pcgen users!

**Comment by BahamutDragon** [comment]
Monsters included.
