### ISSUE TITLE
Add a Red Dragonnel as a possible ranger companion

### ISSUE THREAD

**Issue by uncreative54** [BahamutDragon/pcgen#1180]
The Red Dragonnel from the dragonlance book would be a very cool selectable companion for a Drake Warden, Beast Conclave (revised ranger), or Beast Master Conclave (vanilla ranger). I snipped the stat block from my dragonlance sourcebook (They're called "Dragon Army Dragonnel" in the sourcebook, but they are Red Dragonnels if they aren't part of the dragon army).

![Screenshot 2023-06-22 021315](https://github.com/BahamutDragon/pcgen/assets/98443412/f7e04523-ed36-4e3f-a183-ebd33e9657d3)

**Comment by BahamutDragon** [comment]
Vanilla has this `Choose a beast that is no larger than Medium and that has a challenge rating of 1/4 or lower` I don't see anything that allows a CR 3 Dragon as an Animal companion in that write up.

And the Drake Warden isn't made yet.

**Comment by BahamutDragon** [comment]
Added the Red Dragonnel race.

**Comment by uncreative54** [comment]
Thank you so much!

Jonathan Heckmann
Affiliate Faculty of Biology
Metropolitan State University of Denver

**Comment by BahamutDragon** [comment]
Drake Warden has a specific small drake write up. Nothing else for me to work on here.
