### ISSUE TITLE
Revised Ranger missing features

### ISSUE THREAD

**Issue by uncreative54** [BahamutDragon/pcgen#1181]
The revised ranger is missing a lot of features. It got access to spells in the last fix, but the following are still missing:

Weapon & Armor proficiencies
A third skill proficiency (it only allows you to select two)
Ability score improvements
Revised ranger version of favored enemy
Revised ranger version of natural explorer
Fighting styles
Revised ranger primeval awareness

Missing access to ranger subclasses (Conclaves) - it should be able to select normal ranger subclasses as well as the three revised ranger subclasses.

Missing the revised ranger-specific conclaves entirely (Beast Conclave, Hunter Conclave, Deep Stalker Conclave, Monster slayer)

Greater favored enemy
Fleet of foot
Hide in plain sight
Vanish
Feral senses
Foe slayer

I guess all it really has at the moment is proper access to spells.

Link to revised ranger: http://dnd5e.wikidot.com/ranger-revised

------REVISED RANGER-SPECIFIC SUBCLASSES-----------

Beast Conclave: http://dnd5e.wikidot.com/ranger-revised:beast-ua

Hunter Conclave: http://dnd5e.wikidot.com/ranger-revised:hunter-ua

Deep Stalker Conclave: http://dnd5e.wikidot.com/ranger-revised:deep-stalker-ua

Monster Slayer: http://dnd5e.wikidot.com/ranger:monster-slayer-ua

**Comment by BahamutDragon** [comment]
One little comment had disabled everything. Should be fixed.
