### ISSUE TITLE
5e - VGM races absent

### ISSUE THREAD

**Issue by Thorngage** [BahamutDragon/pcgen#1188]
Some races from Volo's guide to Monsters, even being present in the sources, do not appear as a choice, their counterpart from the Monster Manual and Elemental Evil appear instead, with no choice between  (I know, the fact that the monsters capabilities are different from the Monster races is the stupidest thing in 5e)
Here a list:
Aasimar is fine
Firbolg is fine
Goliath only appears w/ EEPC source
Kenku's fine
Lizardfolk's fine (should there be a MM version too? IDK)
Tabaxi's fine
Triton's fine
Bugbear has both MM and VGM sources (wich I believe is as it was intended?)
Goblin is only with the MM version
Kobold is only present in Monsters of the Multiverse
Orc is only with the MM Version

I cannot thell other than the MM versions, if those that appear in other manuals are just identical or even Updated, but those that are present in the Monster Manual are definitely using some optional rule for monster PCs I am anaware of, instead of having the standard capabilities of the PC race

**Comment by BahamutDragon** [comment]
There you go, a bit of a massive rebuild. Probably broke a few things. But now each race will give a selection based on the sources loaded and the available coded up creatures. MM Kobold does not exist since I stopped around the demons. With a few common critters after sprinkled in. Monsters and NPCs have a different statblock, which means creating a proper output for just those.

**Comment by Thorngage** [comment]
I understand this was quite massive, indeed. Maybe I should have suggested just modifiyng the MM manual ones having (MM) after the name? so that the Volo's ones worked normally? In any case I'm doing some more testing but it looks like something broke, as I get no race adjustments to abilities from any race

**Comment by Thorngage** [comment]
Oh NVM I found out it's because you need to select the race twice, once in the races tab, and once in the feats>character Tab

**Comment by Thorngage** [comment]
It's true, the subrace options for Aasimar do not appear
