### ISSUE TITLE
5e - Monk attack bonus wrong

### ISSUE THREAD

**Issue by Thorngage** [BahamutDragon/pcgen#1190]
I don't know why, but when creating a monk character it looks like the ability bonus for melee _weapon_ attacks is calculated twice.
I have a 7th level monk with +3 strenght and unarmed attack has +6/+6 (correct) but a light hammer goes up to +9/+9
If i put a sicke there is the same, but darts are correct

**Comment by BahamutDragon** [comment]
Well, this is problematic... The type limiter is being ignored here. I will need to re-evaluate how to fix this.

**Comment by BahamutDragon** [comment]
I think this is fixed now.
