### ISSUE TITLE
5e - Request for Information: Forking/Creating Race/Subrace?

### ISSUE THREAD

**Issue by chainria** [BahamutDragon/pcgen#1203]
Thank you very much for the great sources. I am part of a group playing in a different setting.
It's getting more and more evident that we will need some elven subraces, mostly leaning on the current ones.
For instance let's take the Drow. How would I go and create my own flavour of Drow?
Is there some quick way to .COPY or maybe .MOD? or is there more I need to do.
I hope this is the right way to ask for something like this, if not please guide me in the right direction.
Thank you in advance!

**Comment by FerretDave** [comment]
Best bet is to copy some of the files and tweak the entries there to create your own sub race of elves (this is how drow etc are currently done).
Create a new PCC file to include your new file and load it as an additional source.
check out the entries in:
pcgen/data/35e/wizards_of_the_coast/campaign_settings/forgotten_realms/players_guide_to_faerun/pg_abilities.lst

Subraces are added as 'abilities'
