### ISSUE TITLE
6.08 SUBCLASS issue with Bard & Wizard

### ISSUE THREAD

**Issue by FerretDave** [BahamutDragon/pcgen#1209]
There's something wrong with the Bard subclass (and possibly with Wizard too).
 (Using 6.08.RC10, Loading game Bahamut35e and sources [Dungeons & Dragons - Core Books, The Complete Book of Eldritch Might].) from the 6.08 branch.

I don't get an option to select the Bard (CBoem) subclass under Class Features, nor am I prompted to select a subclass at initial character creation. However I can see CBoem features if I select the 'Bard class feature' in the top right pane, though cannot add any.

Whereas creating a wizard, I am prompted to select a school of magic to specify the subclass when first adding the wizard class, and under class features can see/select 'Wizard Subclass' in the bottom left pane with the list of schools then shown top left, though there is no option to 'reselect' it in the top right 'selected abilities' pane.

How do I now select the CBoem bard subclass? and for any subclass - should it be listed under 'class features' to change the select (just as race traits allows the reselection of sub-races).

**Comment by BahamutDragon** [comment]
Does the bard have any of the class features populating or the spellcasting progression? If yes, then the subclass is actually working, but the choice is being suppressed. The subclass for the Bard is the same general requirements as the base bard, no lawful alignments. 

Wizard subclass selection should not be prompting a school of magic until you've selected the subclass which are:
Abjurer, Conjurer, Diviner, Enchanter, Evoker, Illusionist, Necromancer, and Transmuter. Though the wizard does allow the base wizard class for the 'generalist'.


I can force a selection, but that moves things from the class into the abilities realm, something I would prefer to avoid.

**Comment by FerretDave** [comment]
Apologies, please ignore this. Looks like when I ran a test with a reduced dataset (rather than my full homebrew dataset) I managed to *NOT* load CboEM as a source... ahem... hence no Bard sub class options... sorry.

Creating a new wizard has a prompt for school specialisation choice (along with the usual popups for Feat 1st level / Funds / free clothing) - and that's setting the subclass.

I had memories of being able to select the subclass in the GUI (under class features), however that may have been a much older version, or confused with sub-race selection... 
all is well here, move along.
