### ISSUE TITLE
Number of known spells for Warlock class is wrong

### ISSUE THREAD

**Issue by SpaskeISO** [BahamutDragon/pcgen#1211]
When using the books provided in this repo, the number of known spells for Warlock is wrong. It always is zero the warlock level doesn't matter. When I use the SRD 5.1 that comes with the PCGen the number of known spells is as it should be, but then I can't add some books provided in this repo.
![javaw_fU5evuEFSW](https://github.com/BahamutDragon/pcgen/assets/129440390/65d98968-a8cc-4943-b616-1dae7601ad4c)

Edit: I tried Sorcerer for reference and also the Sorcerer has zero known spells and because of that no spells can be added.

**Comment by BahamutDragon** [comment]
This should be fixed now.
