### ISSUE TITLE
5e - College of Spirits Bard?

### ISSUE THREAD

**Issue by ElectricalHazards** [BahamutDragon/pcgen#1214]
Just wondering if there are any plans to include the college of spirits bard from Van Richten's Guide to Ravenloft book?

http://dnd5e.wikidot.com/bard:spirits

Cheers!

**Comment by BahamutDragon** [comment]
Hi mate, I add what is requested when the fancy takes me. A single college request should not be hard to muster.

**Comment by BahamutDragon** [comment]
College added.
