### ISSUE TITLE
[3.5] Issues with Ranged and Melee Weapon Mastery from PHB2

### ISSUE THREAD

**Issue by MrOnimous** [BahamutDragon/pcgen#1215]
Feats from PHB II 3.5

**Melee Weapon Mastery** is reducing the damage by 2 instead of increasing it

**Ranged Weapon Mastery** is not providing any change when selected. 

This is on 6.09

**Comment by BahamutDragon** [comment]
Odd. The proper behavior is no change for Melee Weapon Mastery. Which means the broad application itself is not working.

**Comment by BahamutDragon** [comment]
Here is a patch for the time being. I suspect I will have to redesign the system to make this work correctly. An unpleasant prospect since I had hoped the PCGen team would have their formula improvements in place by now.
