### ISSUE TITLE
TCoE: Artificer Specialist Not on Character Sheet

### ISSUE THREAD

**Issue by CodePhase** [BahamutDragon/pcgen#1216]
#1213 seems to be working for creating and compiling an Artificer character. There is now an issue where, when using Tasha's Cauldron of Everything (TCoE), the Artificer Specialist abilities that are selected at level 3 do not populate on the Character Sheet in pcgen.  The Artificer Specialist abilities from Eberron - Rising from the Last War (RftLW) do populate on the character sheet properly.

**Comment by BahamutDragon** [comment]
Specialist selection and all features associated will populate the sheet now. Both 6.08 and master.
