### ISSUE TITLE
3.5 UA 'environment' Half-Orc/Half-Elf racial subtypes don't work

### ISSUE THREAD

**Issue by loubranch** [BahamutDragon/pcgen#1217]
Poking around in the latest version of PCGen - 6.09.07, the hyphenated-name races' environmental (Arctic, Desert, Jungle) subraces don't work. Environmental race subtypes with non-hyphenated names such as Elf, Kobold, and Dwarf function normally. These are defined in Unearthed Arcana (UA) inside ua_abilities_race.lst. 

I think the issue might be the TYPE (eg: TYPE:Half-OrcSubrace.AltSubraceChoice) when looking at the selector within the pcgen UI - An example of one that appears in the subrace selector (frostblood) shows TYPE:HalfOrcSubrace. However, tweaking these values into a homebrew .lst file doesn't seem to solve the issue. 

To reproduce, create a new character in the 3.5 ruleset including Unearthed Arcana (Complete), select race 'Elf' and go to Race Traits, assign a Race Base. All the subrace options will appear. Change Race to Half-orc, go to Race traits, assign the proper race base, and few or no subrace options appear.

**Comment by BahamutDragon** [comment]
First pass. If you have a moment, see if that works for you @loubranch I expect Hobgoblin won't work, but the rest of the races should do okay.

**Comment by BahamutDragon** [comment]
Disregard the hobgoblin remark. My age is showing. In theory, all the races should function. I expect some clean up, but do not have the time to properly test yet.

**Comment by loubranch** [comment]
Improved - but still not specifically working for the half-orc and half-elf. I think I identified why. Looking at the entry for the one subrace (frostblood) that actually appears in the UI, I see **Type:HalfOrcSubrace**. But looking at for example the Desert half-orc in ua_abilities_race.lst, the entry shows **TYPE:Half-OrcSubrace.AltSubraceChoice**. When I made a revision in a custom .lst file to change the following parts of the subrace to **KEY: KEY:HalfOrc ~ Desert	TYPE:HalfOrcSubrace.AltSubraceChoice			PREMULT:1,[PREABILITY:1,CATEGORY=Internal,HalfOrc ~ Desert]**, combined with your new code I was able to select the Desert Half-Orc. So I think the half-elf/half-orc abilities in ua_abilities_race.lst need further modification to remove the '-' character in the Type field.

When I only changed the TYPE, it didn't seem to fix it, but when I updated the Key entry and the reference to the key it seemed to solve it.

**Comment by BahamutDragon** [comment]
I suspect you did not use the updated files. There are no hyphens in the TYPE I uploaded.

`Desert		KEY:Half-Orc ~ Desert	CATEGORY:Internal		TYPE:Racial Variants.AltSubraceChoice				PREABILITY:1,CATEGORY=Race,Half-Orc		PREMULT:1,[PREABILITY:1,CATEGORY=Internal,Half-Orc ~ Desert],[!PREABILITY:1,CATEGORY=Internal,TYPE.AltSubraceChoice]`
