### ISSUE TITLE
players_handbook 2 load issue

### ISSUE THREAD

**Issue by FerretDave** [BahamutDragon/pcgen#1218]
loading the 'players handbook 2' for 35e gives an error, and I'm afraid I'm not sure how to resolve - should the 'CHOOSE' be removed? Not sure what it does here.

CHOOSE:NOCHOICE requires both MULT:YES and STACK:YES, was STACK:NO on Ability Melee Weapon Mastery (Source: file:/C:/Utils/GitHub/pcgen/data/35e/wizards_of_the_coast/supplement/players_handbook_2/ph2_feats.lst )
CHOOSE:NOCHOICE requires both MULT:YES and STACK:YES, was STACK:NO on Ability Ranged Weapon Mastery (Source: file:/C:/Utils/GitHub/pcgen/data/35e/wizards_of_the_coast/supplement/players_handbook_2/ph2_feats.lst )

**Comment by BahamutDragon** [comment]
Fixed.

**Comment by FerretDave** [comment]
Thank you.
