### ISSUE TITLE
D&D 3.5 - Ironsoul Forgemaster BAB doesn't roll up

### ISSUE THREAD

**Issue by aaroncl123** [BahamutDragon/pcgen#1220]
I'm unsure if this is an issue for this group, or PCGEN 

As an example, L3 Warblade + L2 Incarnate has a BAB of +4 ... adding 10 Levels of Ironsoul Forgemaster does not increase the BAB (This should be +4 +7 as I read it) 

I think this is also happening to Fort / Ref / Will as well. I will confirm that. 
EDIT: Yes, Fort / Ref / Will are also not incrimenting

<img width="900" alt="Screenshot 2024-03-26 at 2 04 03 PM" src="https://github.com/BahamutDragon/pcgen/assets/153202208/2d43d1df-a087-4cf7-9c87-059210d8be3b">

**Comment by BahamutDragon** [comment]
The Base Attack and Save progressions were completely missing for this prestige class. This is now fixed.
