### ISSUE TITLE
5e TCoE Spells and Phantom Rouge

### ISSUE THREAD

**Issue by Seoman123** [BahamutDragon/pcgen#1223]
Thank you for your dedication, we love your work. 

I cant get the Spells from Tasha's Cauldron of Everything and cant find the Phantom Rouge from it. Although the Spell Descriptions seems to be already included. 
Is it possible to add the Spells of TCoE yet? Or am i just doing something wrong?

**Comment by BahamutDragon** [comment]
I have to assume you meant Phantom Rogue, which does not appear to be found in TCoE. A quick google search did not turn up anything useful for me. Can you confirm the source book and page number where this class is found?

I have enabled the spells and cantrips to be selected by the correct classes now.

**Comment by BahamutDragon** [comment]
I found it.

**Comment by BahamutDragon** [comment]
Added the Phantom Rogue
