### ISSUE TITLE
Spelljammer: Adventures in Space - Astral Elf Race

### ISSUE THREAD

**Issue by CodePhase** [BahamutDragon/pcgen#1225]
Hello,

I'm wondering if it's possible to add an entry from a book that is not implemented in PCGen yet: the Astral Elf race from Spelljammer: Adventures in Space.  This race has the following details (from [dnd5e.wikidot](http://dnd5e.wikidot.com/lineage:elf-astral)):

- **Ability Score Increase**: Increase one ability score by 2, and increase a different one by 1, or increase three different scores by 1. 
- **Creature Type**: You are a Humanoid. You are also considered an elf for any prerequisite or effect that requires you to be an elf.
- **Size**: You are Medium.
- **Speed**: Your walking speed is 30 feet.
- **Astral Fire**: You know one of the following cantrips of your choice: [Dancing Lights](http://dnd5e.wikidot.com/spell:dancing-lights), [Light](http://dnd5e.wikidot.com/spell:light), or [Sacred Flame](http://dnd5e.wikidot.com/spell:sacred-flame). Intelligence, Wisdom, or Charisma is your spellcasting ability for it (choose when you select this race).
- **Darkvision**: You can see dim light within 60 feet of yourself as if it were bright light, and in darkness as if it were dim light. You discern colors in darkness only as shades of gray.
- **Fey Ancestry**: You have advantage on saving throws you make to avoid or end the charmed condition on yourself.
- **Keen Senses**: You have proficiency in the Perception skill.
- **Starlight Step**: As a bonus action, you can magically teleport up to 30 feet to an unoccupied space you can see. You can use this trait a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest.
- **Astral Trance**: You don't need to sleep, and magic can't put you to sleep. You can finish a long rest in 4 hours if you spend those hours in a trancelike meditation, during which you remain conscious. Whenever you finish this trance, you gain proficiency in one skill of your choice and with one weapon or tool of your choice, selected from the Player's Handbook. You magically acquire these proficiencies by drawing them from shared elven memory and the experiences of entities on the Astral Plane, and you retain them until you finish your next long rest.
- **Languages**: You can speak, read, and write Common and one other language that you and your DM agree is appropriate.

I don't mind helping out implementing this or testing it, but I'm afraid I would have to learn a bit about how to do it to be able to lend a hand.  Thank you for all of your HARD WORK on this project!

**Comment by BahamutDragon** [comment]
Looks like a copy and paste of Plasmoid mixed into the Astral Elf. The ability score selection and languages is Plasmoid.

**Comment by BahamutDragon** [comment]
Astral Elf added to Astral Adventurer's Guide.

**Comment by CodePhase** [comment]
Thank you very much for implementing this so quickly!  I just tried it and I did find an issue though.  The 'Astral Fire DC' does not have any selections available.  I suppose it should allow me to choose among Intelligence, Wisdom, or Charisma.

**Comment by BahamutDragon** [comment]
Issue fixed. Was looking for the wrong category.

**Comment by CodePhase** [comment]
Sorry for the delay in testing this, but I can't select the Astral Elf race for the character.  It is not available in the Race dropdown or in the Race tab search.

**Comment by CodePhase** [comment]
Nevermind I wasn't doing it correctly. I realized I have to select Elf as the race and then Astral Elf as the subrace in Feats & Abilities -> Character -> Elf Subrace.
