### ISSUE TITLE
Alternative class features from Dragon Magazine #338 for Imbued Staff 

### ISSUE THREAD

**Issue by CmptrSaysNo** [BahamutDragon/pcgen#1226]
Hello, 

I want to request if this code could be made. 

This is for the Imbued Staff Alternative class features from Dragon Magazine #338.

Imbued Staff Feats
As an alternative to having a Familiar, a Sorcerer / Wizard may imbue some of his/her power to a staff. This Imbued Staff gains abilities as the Master goes up in
level (see the Creature Index for details). The following feats may also be applied. 

![Imbued Staff Feats](https://github.com/user-attachments/assets/281ba345-ee59-4bf5-bdce-f325b7d15ef1)

**Comment by BahamutDragon** [comment]
Request added.

**Comment by CmptrSaysNo** [comment]
I added the dm338.pcc and dm338_abilities_feat.lst to my files as Dragon Magazine 338. After loading the file, I could not find the opinion of the Imbued Staff. I have looked through the feats, and it doesn't show. 

![Screenshot 2024-07-31 134011](https://github.com/user-attachments/assets/0b9421c1-84be-40ce-9f4d-0fd812afc3d9)
![Screenshot 2024-07-31 133919](https://github.com/user-attachments/assets/88bee664-be5f-40a1-a347-0b6874cacdc4)
![Screenshot 2024-07-31 134038](https://github.com/user-attachments/assets/bfc6570e-b3d5-4c54-a445-b1f2b2ae8d65)
![Screenshot 2024-07-31 134324](https://github.com/user-attachments/assets/46eb3150-feba-45d7-ab60-d5704bb29147)

**Comment by BahamutDragon** [comment]
Feats are under feats (The first tab), not class. That's what you provided in your screenshot.

![352780657-281ba345-ee59-4bf5-bdce-f325b7d15ef1](https://github.com/user-attachments/assets/9411cef2-009a-450e-8e11-e3790611d6b0)

It seems your screenshots missed the actual alternate class feature. I managed to find that after some searching and put that in for you. 

The Alternate Class Feature is where you expect it. To use the staff, you need to use the equipment customizer on a quarterstaff and add the Imbued Staff to it.

**Comment by CmptrSaysNo** [comment]
First, 
Thank you for helping with adding this :)

I wanted to confirm that I am loading and using the update correctly. 

I have added screenshots of the steps building. 

![Screenshot 2024-08-03 133852](https://github.com/user-attachments/as
![Screenshot 2024-08-03 133942](https://github.com/user-attachments/assets/9c019dc9-baeb-4b09-8b76-2c3b2623a0c6)
sets/d911e6dc-9cfb-4859-8573-268688bdf06b)
![Screenshot 2024-08-03 134115](https://github.com/user-attachments/assets/13f1fe9e-ea28-4776-ad62-9bbb8ddb968f)
![Screenshot 2024-08-03 134214](https://github.com/user-attachments/assets/3da4729b-3ecf-40f8-9b0c-e6539570e6a3)
![Screenshot 2024-08-03 141417](https://github.com/user-attachments/assets/2d795eaf-7ee0-48cf-a647-07e76fe324b0)

**Comment by BahamutDragon** [comment]
Looks like I missed a type for the ACF to appear. Pull down the recent update.

`The Imbued Staff	KEY:The Imbued Staff (Sorcerer)	CATEGORY:ACF	COST:0	TYPE:ACF.The Imbued Staff.SorcererFamiliar	PRECLASS:1,Sorcerer=1
The Imbued Staff	KEY:The Imbued Staff (Wizard)		CATEGORY:ACF	COST:0	TYPE:ACF.The Imbued Staff.WizardFamiliar	PRECLASS:1,Wizard=1
`

The Imbued Staff will show up as an ACF option.
