### ISSUE TITLE
5e "Ranger Known Progression Selection" cannot be selected

### ISSUE THREAD

**Issue by tseeker** [BahamutDragon/pcgen#1227]
When a DND 5e ranger reaches level 2, it is impossible to select a known progression.

This can be solved by changing `TYPE` to `Ranger Known Progression` at lines 1755-1757 of `data/5e/wizards_of_the_coast/core/players_handbook/ph_abilities.lst`.

**Comment by BahamutDragon** [comment]
Thanks! Fixed.
