### ISSUE TITLE
3.5 Dragonlance Krynn Sub-Races not selectable

### ISSUE THREAD

**Issue by Griffon-Stormblade** [BahamutDragon/pcgen#1229]
When loading 3.5e DragonLance campaign setting unable to change Subrace to one of the Krynn/Dragonlance Subraces. Can only select PH subraces for Races that exist in PH and in DL campaign setting. Races specific to Krynn such as Kender am able to select subrace

![image](https://github.com/user-attachments/assets/be60926c-7bc4-4838-a0b9-f77687afa5c5)

![image](https://github.com/user-attachments/assets/bdb2834c-3af0-42f4-8b69-867743eadb4b)

**Comment by BahamutDragon** [comment]
Getting the selections fixed is easy. However, it appears the new races were never coded up with their racial traits. This will take me a day or two to add in the missing items.

**Comment by BahamutDragon** [comment]
Dragonlance Subraces should now be selectable.

**Comment by BahamutDragon** [comment]
This should be fully implemented, including the guild affiliation.
