### ISSUE TITLE
Dragonlance Subrace selection works BUT doesn't remove/override default EVERYTHING stays and it just adds on

### ISSUE THREAD

**Issue by Griffon-Stormblade** [BahamutDragon/pcgen#1230]
Its me again. So thanks for fixing the ability to choose the sub-race. Now it seems it doesn't override/remove the default subrace/racial traits it just adds. So effectively you can have all the subraces and their stat bonuses and traits...

Its kind of hard to explain 

![image](https://github.com/user-attachments/assets/65610fa8-22e7-473c-8c8e-ae0750c081bb)

then if you notice the stats bonuses and minuses all apply
![image](https://github.com/user-attachments/assets/14af0ad1-fd7c-4332-aeab-fca62d05845a)

all all the racial traits apply as well
![image](https://github.com/user-attachments/assets/b38cc510-d54c-48ed-9f7d-b13b52d74e20)

If I could wrap my head around the .lst files I might be able to sort out the problem. My brain says its a simple fix of setting subrace to overwrite but Im stuck. Thanks for all your help you ROCK!!

**Comment by BahamutDragon** [comment]
Should be fixed now.
