### ISSUE TITLE
Core Rules/PHB/Familiar Issue

### ISSUE THREAD

**Issue by RonCKFish** [BahamutDragon/pcgen#172]
Something is going on with the calculations for familiar (and probably other companions).  It appears that MASTERVAR("FamiliarLVL") returns 0 (I verified this in the Expression Calculator) so that Natural Armor and Intelligence updates are not syncing through.  I'm still running v6.04.00.  Was this fixed in 6.04.1?  Is anyone else seeing this problem?

Thanks,
Ron

**Comment by BahamutDragon** [comment]
Confirmed in 6.05.00. My jira submission is not going through on the pcgen website.

**Comment by BahamutDragon** [comment]
Tom Parker resolved Bug CODE-2804 as Fixed
mastervar("somevalue") returns 0
	
Change By: 	Tom Parker (21/Jan/15 2:02 PM)
Status: 	In Progress Resolved
Fix Version/s: 	6.05.01
Resolution: 	Fixed
