### ISSUE TITLE
core35e seems to be changed

### ISSUE THREAD

**Issue by rygarross** [BahamutDragon/pcgen#176]
Hi,
I am trying to install the data sets but it seems the requirements: includesbooktype=core35e was changed to  Booktype =Core Rules.  I maybe just doing something wrong.

Ross

**Comment by BahamutDragon** [comment]
Mate,

Which 'book' are you attempting to install or load? 

The sets provided are not install capable. I have instructions on how to use them on the main page in the readme.md file.

If you load my core multiset loader for 3.5 materials "Dungeons & Dragons - Core Books", the other sets I provide should work just fine.

**Comment by rygarross** [comment]
Thanks for the help these sets are great.  I had to install you 3.5 core set and not pcgens

**Comment by BahamutDragon** [comment]
Hi mate,

You are welcome. I will close this issue then.

Best,
