### ISSUE TITLE
Passive Perception, Outlander Features and extra Language in 5e

### ISSUE THREAD

**Issue by Peajee** [BahamutDragon/pcgen#177]
First of all: Awesome work!!
I was looking for a character Generator for D&D 5e for ages and only now found your excellent data for PCGen.

There are only three tiny problems I have encountered while working with it.

The first being that I cant seem to add an additional language when choosing a human, even though the PHB allows for such a freely chosen language.

The second problem I have is, that the passive perception doesnt seem to be calculated anywhere just as there is no distinct area in the Charactersheet to display Spellcastingstats (Ability, DC and Modifier).

And last but not least I have observed, that when choosing Outlander (I havent checked for other backgrounds yet) the Skill Proficiencies and the extra Features (Wanderer, Language and Equipment) arent added to the character Information.

Sadly I have no knowledge of how to edit PCGen files. Otherwise I would have simply edited them.

**Comment by BahamutDragon** [comment]
Hi Mate,

Thanks! 

I have done some recent work on the display of the proficiencies. For skills, you should see the proficiency bonus applied directly to the skills. Languages should be displayed on the character sheet itself. Are you not gaining any summary to-do for those?

Equipment is a bit harder to handle. Those give "packs" that is a pre-list of items. The only solution would be to resolve adding starting kits, which is a bit involved. I can investigate what can be done to improve the experience though.

The character sheet display is several different programming languages that are not LST based. All the user interface display uses htm. The pdf export uses three languages xml, xslt and fo. The basic text output is the easiest of the display mediums. I have been avoiding much output sheet work as the pcgen team is making some fairly significant changes. Best option till then is to place another ability that displays the information. The spell DC should be calculated on the spells.

Best,

**Comment by BahamutDragon** [comment]
Mate,

Corrected the language issue. Skills granted by any background is listed in the info pane. The rest will need to be explored to best options. Kits might be the method to handle the equipment. Passive Perception will likely be listed under the skills.

**Comment by BahamutDragon** [comment]
Equipment kits will be made as time permits.
Acolyte, Charlatan, Criminal, Entertainer and Outlander backgrounds now supply equipment.

**Comment by Peajee** [comment]
You Sir are amazing!

Your recent additions pretty much solved every problem I had with 5e and PCGen. As for Character Sheets it seems indeed wise to wait for the changes made by the PCGen guys. Until then copying the generated Data into a 5e CS seems to be the easiest solution to me.

One thing I observed, however, was that the extra languages are choosable from the respective Tab, but not by clicking "Add Bonus Language" in the overview Tab.

**Comment by Peajee** [comment]
I think there are also some things concerning advanced level abilities, like the Maneuvers of the Fighter Class not implemented correctly yet.

Is there a comprehensive Guide on how to edit those PCGen files so that I might be of any assistance?

**Comment by BahamutDragon** [comment]
Regarding program summary links. That would be a program issue beyond my control. You can raise the issue over on the pcgen issue tracker. 

Fair warning, many advanced items in the 5e set are not fully implemented yet. My home group is only 1st level. I have been learning the system and coding it up as we progress. Everything that isn't implemented, at least states what it does on the character sheet.

As an aside, I monitor the pcgen team discussions, and it sounds like some pretty hefty changes are happening in the next few months. I would rather implement something once, then have to mess with it twice. The pcgen guys let us know in advance that the usual conversion tools would not be feasible for these upcoming changes. Which means I have potentially a lot of work to keep up with the changes. Best not to add to the work load if I can help it. The work involves the BONUS tag changes, changing from JEP to a new formula system, the new FACT and FACTSET items which ties into the output sheet stuff.

For guides and how to assistance, that would be best handled by searching out the pcgen official channels. They have the program documentation, youtube has some videos, and they have a pretty excellent response time with direct inquiries on their social media and groups. I can explain a few things myself, but they are the best ones to get you up to speed on learning lst and the tools available to make coding easier.

Side note: The updates also included the Eladrin elf subrace and the Aasimar race

**Comment by Peajee** [comment]
Ok thanks for the answer and everything you've done so far. Keep up the good work!

**Comment by BahamutDragon** [comment]
Equipment kits finished.
