### ISSUE TITLE
Craft (poisonmaking) from Complete Adventurer

### ISSUE THREAD

**Issue by mberg24** [BahamutDragon/pcgen#186]
The skil seems missing from the Complete Adventurer supplement.  Moreover, the skill is listed as prerequisite for several prestige classes from the same book.

Looked in 6.04.01 but missing from master as well.

branch: 6.04.01 
pcgen/data/35e/wizards_of_the_coast/supplement/complete_adventurer/

**Comment by BahamutDragon** [comment]
Extra Tricks was missing, and added the Poisons from the chart to the equipment list.

**Comment by BahamutDragon** [comment]
Resolved in master and 6.04.01
