### ISSUE TITLE
5e - PH bugs

### ISSUE THREAD

**Issue by BahamutDragon** [BahamutDragon/pcgen#189]
- [x] No feat added when Feat was taken for ability increase.
- [x] No maneuver selection when Battlemaster was taken.
- [x] No options at all for selection of Assassin/Arcane Trickster/Thief 
- [x] And all polearms are 1-handed weapons.
- [x] Level proficiency doesn't seem to be adding to skills for fighter class.
- [x] Barbarian: no choice of primal path
- [x] Bard: No choice of college
- [x] Druid: No druid Circles at all
- [x] Fighter: Choice, but only Champion works. Battlemaster has no maneuvers, Eldritch has no spells
- [x] Paladin: No Oaths
- [x] Ranger: No Ranger Archetype at all
- [x] Rogue: No choice for Roguish Archetype
- [x] Sorcerer: Sorcerous origin cannot be selected, although they are both visible in the class feature list as special qualities. Metamagic is similar.

**Comment by intrstcrv** [comment]
Great work! Level proficiency doesn't seem to be adding to skills for fighter class.

**Comment by BahamutDragon** [comment]
Thanks mate, I will add that to my list of objects to fix.

**Comment by BahamutDragon** [comment]
@intrstcrv I redid the skills a bit about two weeks ago. Do you by any chance know if you are using the old version or new version, and if it is the Master or 6.04.01 branch version?

That would narrow down the bug if it was an old issue or newly introduced issue (new would mean all classes are definitely broken). I will test myself later tonight of course.

**Comment by intrstcrv** [comment]
ZIp file is called pcgen-master, downloaded from github.

**Comment by intrstcrv** [comment]
Though under source description it also says supports 6.4.1

**Comment by BahamutDragon** [comment]
Interesting. You are using 6.05.01 with it then? 

Currently there are two zips are available based upon the Branch drop down. 6.04.01 which is exclusively meant to be fully compatible with 6.04.01 version of pcgen. The master is the latest development changes suited to match whatever is the latest changes in pcgen. Expressed in their unstable release cycles of alpha, beta and rc.

The master branch should still work with 6.04.01, but I suspect that will change in the very near future.

**Comment by intrstcrv** [comment]
Actually, I'm using v6.04.01. Sorry, new to PCgen.  And I went through to
figure out which zip I downloaded, and it was master.

On Thu, Mar 26, 2015 at 9:44 PM, Bahamut <notifications@github.com> wrote:

> Interesting. You are using 6.05.01 with it then?
>
> Currently there are two zips are available based upon the Branch drop
> down. 6.04.01 which is exclusively meant to be fully compatible with
> 6.04.01 version of pcgen. The master is the latest development changes
> suited to match whatever is the latest changes in pcgen. Expressed in their
> unstable release cycles of alpha, beta and rc.
>
> The master branch should still work with 6.04.01, but I suspect that will
> change in the very near future.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BahamutDragon/pcgen/issues/189#issuecomment-86807891>.
>



-- 
- Intrstcrv <http://flavors.me/intrstcrv>

**Comment by BahamutDragon** [comment]
All updated and fixed

**Comment by BahamutDragon** [comment]
To get Eldritch Knight to work requires saving and closing the character, then load the character. Spell selections will be made available. Fixing that is a PCGen issue beyond my control.
