### ISSUE TITLE
3.5 - Issues with Ur-Priest and Sublime Chord

### ISSUE THREAD

**Issue by BahamutDragon** [BahamutDragon/pcgen#191]
From Chat Group post:
At first thought it was because of a bug with Savage Bard but since that's now solved in base pcgen I took a look at bv_classes.lst and car_classes.lst.

Both fail on the requirements to take the class despite the basic Savage Bard having all the requirements (for Ur-Priest it's the Fort/Will requirements that stay in the red, Sublime Chord doesn't account for bardic requirements from Savage and also misses on some skill requirements).

Those are manageable with a dirt fix but the big problem comes from neither of them accounting for Caster Levels from previous classes.

Ur-Priest doesn't add 1/2 CL of other caster classes and Sublime Chord doesn't add previous Arcane Caster Class levels (namely the Savage Bard).

Tried adding CL+(classlevel("Savage Bard)) to Sublime Chord but it didn't work.

For Ur-Priest CL+(("CL=Savage Bard")/2)+(("CL=Sublime Chord")/2) didn't do the trick either.

Any ideas?

**Comment by KingMoloch** [comment]
I'm still having this same problem, actually
