### ISSUE TITLE
Can't create dragon PC with certain dragon types

### ISSUE THREAD

**Issue by PsychoCircus** [BahamutDragon/pcgen#195]
Even with everything WOTC loaded, you can't effectively create some dragon types as dragon PCs.  These include dragons from mainly the Draconomicon

For example, you can't create a Shadow Dragon because it has no age category listings in the selection, when you select it, it has no Race Type, nothing other than Shadow Dragon, and universal rules.  With it set this way, you can't add levels of the dragon monster class to it because it thinks its not a dragon.  Even if you add the template Draconic Character (which doesn't make your race type a dragon anyway) you still can't do it.  

Just as a side question, besides the issue outlined above, is there a way to add the SRD templates (Assign Race Type, etc) to the material you've got?  Either add them in, or be able to add the SRD material in addition to your project?  There are several characters I would like to create that use things from various materials in your project that aren't in the SRD, but that require templates that are within the SRD but not in your material.  Thank you

**Comment by BahamutDragon** [comment]
SRD templates? Easily added. Be a bit though, suffering through allergies.

The Dragons have to be redesigned to use the newer system, which would explain the issue with the  Dragons in the Draconomicon. Though, they should be set up as dragon race type in any event.

**Comment by BahamutDragon** [comment]
The issue with the dragons you encountered is they were merely named placeholders, nothing else. The problem with limited time and several ongoing projects. To get the twelve dragons fixed properly is roughly a 4-6 hour project. 

To address the immediate issue, I have re-instituted an older version patch which you may download by grabbing the "Temp_Fix" branch (It is based off the 6.04.01 branch and includes the srd template request). This has the old method to handle dragons with each age category as part of the name and each dragon progressing in that specific dragon class. Fair warning, several abilities those dragons ask for do not exist, and loading will cause error messages for those missing items. My focus will not be to patch this method, but rather update the dragons to the new method. The placeholders now have an outputname to indicate their present incomplete state.

If you have the ability and time, some help in managing this project would be appreciated. Any preference on which dragon gets attention first? Will you be able to contribute any effort to this project?

Best,

**Comment by BahamutDragon** [comment]
6.04.01 patched.
