### ISSUE TITLE
Urban Companion ACF doesn't calculate companion's stats correctly

### ISSUE THREAD

**Issue by AlienDave** [BahamutDragon/pcgen#197]
In the rules, it says that the Urban Companion is like a Familiar, but has 75% of its master's HP.
When creating one in PCGen, it has 1HD, ie, up to 8HP.
(also may be lacking Familiar-style special abilities?)

**Comment by BahamutDragon** [comment]
Indeed the code does not appear to be working. It appears the companion code is not properly invoked by the bonusing of the animalcompanionlvl variable. Testing a fix to address the issue now.
