### ISSUE TITLE
Blessings of Knowledge feature does not give bonuses

### ISSUE THREAD

**Issue by zephyyrr** [BahamutDragon/pcgen#200]
In 5e the Cleric feature "Blessings of Knowledge" given to 1st level clerics of the Knowledge domain should provide two bonus skills of Arcana, History, Nature and Religion, double the proficiency bonus for these and provide two additional languages.
This is currently not the case. 

I have made most of these corrections in a fork, only missing the "double proficiency bonus" part since I am not yet experienced enough to know how to encode that.
Do you want me to issue a pull request or fix it yourself?

**Comment by BahamutDragon** [comment]
PR helps save time. I can add the double proficiency bonus after you submit the PR. Should be simple as "BONUS:SKILL|%LIST|Proficiency_Bonus" on the selection ability if you want to give it a go mate.

**Comment by BahamutDragon** [comment]
Decided to alter it a bit, since we needed the base proficiency. Updated in both master and 6.04.01.
