### ISSUE TITLE
Cannot increase TWO Ability Scores (5e)

### ISSUE THREAD

**Issue by vehrka** [BahamutDragon/pcgen#203]
Version: 6.04.01
Sources: data/5e/wizards_of_the_coast/core/players_handbook

I cannot increase (any) TWO Ability Score when reaching 4th level, seems it is restricted to just one even if it is a +1 Ability Score increase.

Please find attached the Level 3 Cleric that I was trying to update to 4th.

[Dorgan_Stonefaith_l3.pcg | uploaded via ZenHub](https://files.zenhub.io/554b78008fd825ae6d3e2154)

**Comment by BahamutDragon** [comment]
It would seem the FractionalPool suppport does not work with a pool value of 1. 
Altered, after some testing, to correctly give proper choices.

**Comment by vehrka** [comment]
Hi,

I tested it and now works properly.

Thank you very much!!
