### ISSUE TITLE
Cleric Domain Spells do not add spells outside the class list (5e)

### ISSUE THREAD

**Issue by vehrka** [BahamutDragon/pcgen#204]
Version: 6.04.01
Sources: data/5e/wizards_of_the_coast/core/players_handbook

When creating a Cleric with the War Domain the 1st level «Divine Favor» spell (which is a Paladin Spell) cannot be added as a Known Spell (it only lists the Cleric Spells)

**Comment by BahamutDragon** [comment]
Hi Mate,

Not able to replicate the reported issue. Loading the character provided, Divine Favor is able to be added manually. What I will do is force the spell to be added properly to side step the issue, and grant the spell to the list at the same time.

Note there is a "bug". Divine Favor does not appear until the spell list is refreshed - either reloading the PC, or leveling up. This would be a pcgen team issue, which is outside of my capability to address.

The pcgen team takes issue reports at http://jira.pcgen.org. I would call it a code issue.
Summary: SPELLLEVEL:CLASS requires the PC to be reloaded or level up to get access to the spells.

**Comment by BahamutDragon** [comment]
Fix is in. The spells now appear in the known section. The spell list still has the bug.

**Comment by vehrka** [comment]
Hi,

checked out and I can confirm that the Spell now appears only after reloading the Character.

Thanks for the advice!

Bests,
