### ISSUE TITLE
3.5e - book request for "Deities and Demigods"

### ISSUE THREAD

**Issue by Madx-com** [BahamutDragon/pcgen#215]
Hi I was wondering since I cannot figure out how to add this by myself if it is possible          to add the book dieties and gods from Wizards of the coast to the dataset with all its rules and such applied?

**Comment by BahamutDragon** [comment]
Deities and Demigods? Originally a 3rd edition supplement released in February 2002. I can see how easy it would be to add it in. Anything in particular you need from this source mate?

**Comment by BahamutDragon** [comment]
Book has been added.

**Comment by Madx-com** [comment]
Just needed it for a cleric I'm creating ;-)
Den 28/05/2015 21.53 skrev "Bahamut" <notifications@github.com>:
