### ISSUE TITLE
5e - Bard & Rogue Expertise need to grant Skill selections with bonuses

### ISSUE THREAD

**Issue by oehlberg** [BahamutDragon/pcgen#220]
When creating a Bard that has expertise, the option to select the two skills with expertise and are not there.  Same is true for rogues. The fact that the characters have expertise is listed in the character sheet, but the actual calculation and selection of said skills are missing.

**Comment by BahamutDragon** [comment]
Working now.

**Comment by oehlberg** [comment]
Sweet! Just in time for my game next week.

Thanks!
Mark
