### ISSUE TITLE
3.5e book request for "Tome of Magic"

### ISSUE THREAD

**Issue by Ethanrat** [BahamutDragon/pcgen#223]
Hi I was wonder since I am having issues doing it myself if it is possible for you to add more content from the Tome of Magic from wizards of the coast. In particular i am looking for the prestige classes anima mage and terebrous apostate.

**Comment by BahamutDragon** [comment]
Anima Mage and Terebrous Apostate coming up.

**Comment by BahamutDragon** [comment]
Requested content added, plus additional content.
