### ISSUE TITLE
request for Cstp erudite ACF

### ISSUE THREAD

**Issue by CyanideY** [BahamutDragon/pcgen#225]
One of my players is planing on playing a erudite with the alternate class feature Convert spell to power from from minds eye, expanded classes part 4. i played around trying to make it myself but could not find any way to effectively but I am relatively new to working with the back-end of PCGen

**Comment by CyanideY** [comment]
also here is a link the the mind's eye that contains the ACF if needed:
http://archive.wizards.com/default.asp?x=dnd/psm/20070629a

**Comment by BahamutDragon** [comment]
Added the erudite ACF's, and a couple of feats.
