### ISSUE TITLE
issue with CstP erudite ACF

### ISSUE THREAD

**Issue by CyanideY** [BahamutDragon/pcgen#226]
i am having a issue with convert spells to power alternate class feature. i have found that none of the ACF for the erudite are able to be used. when attempting to add one of the ACF it gives a error of "you cannot select any more abilities" . I've never used any of the ACF on a character before so I am unsure if it is user error,

**Comment by BahamutDragon** [comment]
Hi mate, grab the files again. Was missing the COST:0 to prevent that message.
