### ISSUE TITLE
Skill Proficiencies, Expertises not working

### ISSUE THREAD

**Issue by jason-allen-oneal** [BahamutDragon/pcgen#234]
I'm not sure if it's something you haven't gotten into yet, but I just thought I'd let you know that Skill Proficiencies and Expertises are not working. I'd be willing to work on these if you can point me in the general direction...

**Comment by BahamutDragon** [comment]
Which branch did you test against mate? 

The skill profs and expertise was tested and working for me in 6.04.01 branch.

**Comment by BahamutDragon** [comment]
Mate,

Level 5 rogue and adding all the necessary selections for Skill Proficiency and then adding Expertise.

![image](https://cloud.githubusercontent.com/assets/4307487/8607080/638b5f5a-2645-11e5-9606-aa0b2b3dff9f.png)


Expertise skills display +6, normal proficiency skills display +3. 

I am using the supplied 5e specific preview sheet.

PREVIEW and PDF export are the only fully support sheets at the moment. I believe you have also volunteered to work on the 5e HTM export.

Do you have a specific instance where the code is failing?

**Comment by jason-allen-oneal** [comment]
I'll have to recheck. I have a lvl 8 Rogue that it wasn't showing up on.
And yeah, I've got to get used to how the data dumps to the template, but
give me a few days, and I'll see if I can come up with a sample or two for
the HTML.

**Comment by jason-allen-oneal** [comment]
By the way, what is the file path for the character sheet used in the
screenshot?

**Comment by BahamutDragon** [comment]
That is the preview folder. 
pcgen\preview\d20\5e\standard.htm.ftl

Snippet of code here: https://gist.github.com/BahamutDragon/c2746424c6b826392655
or view it in code quote:
```
<!-- START Skills Table -->
   <table cellpadding="0" cellspacing="0" border="0" width="100%" summary="Skills Table">
    <tr>
     <td height="30" bgcolor="black"></td>
     <td height="30" bgcolor="black" align="center"><font style="font-size: small" color="white"><b>SKILLS</b></font></td>
     <td colspan="4" height="30" bgcolor="black" align="center"></td>
     <td height="30" bgcolor="black" align="right" ></td>
     <td height="30" bgcolor="black" align="center"><font style="font-size: x-small" color="white" >MAX<br />RANKS</font></td>
     <td colspan="2" height="30"  bgcolor="white" align="center" class="skl"><b>${pcstring('MAXSKILLLEVEL')}/${pcstring('MAXCCSKILLLEVEL')}</b></td>
    </tr>
    <tr>
     <td colspan="2" align="center" width="40%" class="border6">SKILL NAME</td>
     <td align="center" width="5%" class="border6">ABILITY</td>
     <td align="center" width="13%" colspan="1" class="border6">SKILL<br />MODIFIER</td>
     <td align="center" width="13%" colspan="2" class="border6">ABILITY<br />MODIFIER</td>
     <td align="center" width="13%" colspan="2" class="border6">PROFICIENCY <br />MODIFIER</td>
     <td align="center" width="13%" colspan="2" class="border6">MISC<br />MODIFIER</td>
    </tr>
<@loop from=0 to=pcvar('countdistinct("ABILITIES","CATEGORY=SkillExport","TYPE=SkillExport")-1') ; ability , ability_has_next>
<#if (ability % 2 = 0)><tr bgcolor="#DDDDDD"><#else><tr bgcolor="white"></#if>
     <td align="left" ><font style="font-size: x-small"><#if (pcvar("ABILITYALL.SkillExport.${ability}.TYPE=SkillExport.ASPECT.ProfBonus") >= 1)>&#9670;</#if></font></td>	
     <td align="left" class="font8">&nbsp;&nbsp;${pcstring('ABILITYALL.SkillExport.${ability}.TYPE=SkillExport')}</td>
     <td align="center" class="font8">${pcstring('ABILITYALL.SkillExport.${ability}.TYPE=SkillExport.ASPECT.KEYSTAT')}</td>
     <td align="center" class="borderbottom8" valign="bottom"><b>${pcstring('ABILITYALL.SkillExport.${ability}.TYPE=SkillExport.ASPECT.Total')}</b></td>
     <td align="center" valign="bottom" class="font8"><b>=</b></td>
     <td align="center" class="borderbottom8" valign="bottom">${pcstring('ABILITYALL.SkillExport.${ability}.TYPE=SkillExport.ASPECT.AbilityMod')}<br /></td>
     <td align="center" valign="bottom" class="font8"><b>+</b></td>
     <td align="center" class="borderbottom8" valign="bottom">${pcstring('ABILITYALL.SkillExport.${ability}.TYPE=SkillExport.ASPECT.ProfBonus')}<br /></td>
     <td align="center" valign="bottom" class="font8"><b>+</b></td>
     <td align="center" class="borderbottom8" valign="bottom">${pcstring('ABILITYALL.SkillExport.${ability}.TYPE=SkillExport.ASPECT.MiscBonus')}<br /></td>
    </tr>
</@loop>
   </table>
<div class="font6">&#9670; = Proficient</div>
<div class="font7"></div>
   <table width="100%" summary="Saving Throws">
     <tr>
	   <td align="left" valign="top" class="border8"><div class="font6">CONDITIONAL MODIFIERS:</div>
<@loop from=0 to=pcvar('countdistinct("ABILITIES","ASPECT=SkillBonus")-1') ; ability , ability_has_next>
	 ${pcstring('ABILITYALL.ANY.${ability}.ASPECT=SkillBonus.ASPECT.SkillBonus')}<br />
</@loop>
    </td>
    </tr>
   </table>
```

**Comment by jason-allen-oneal** [comment]
Okay, that's what I thought. Just wanted to be sure. A question about how
the program reads the HTML, though: I've noticed that the files are ftl.
This is the extension for FreeMarker Templating system, correct? Also, I'm
assuming the program is compiled from a Java source. Does the program have
the ability to utilize JavaScript? I've started on a simple layout, but
wanted to test some JavaScript within the page to have expandable sections,
perhaps, but can't seem to get the JS to fire correctly. Just wanted to see
if it was valid for the way the templates are parsed.

**Comment by BahamutDragon** [comment]
Mate,

Email follow up please to bahamutdragon2013@gmail.com. Discussion no longer represents the original issue reported. 

1) .ftl is the freemarker extension appended onto the real file format .xml.ftl and .htm.ftl are the formats I have witnessed. 
2) Program is java compiled. Anything to be asked beyond that should be directed to the pcgen team. I recall that javascript in the outputsheets was possible, but as I understand the reasoning, javascript is another language and was redundant to support having hardcoded objects in the sheets. Here is the pcgen web post back from Aug-2014:

> Hi Folks,

> Due to lack of javascript capable monkeys, and the advent of better temp 
bonus capabilities, I plan to remove all the javascript enabled htm 
sheets from the active releases. This was proposed a couple of years ago 
by Chuck Pint, and I think with the advent of moving to the newer 
Freemarker code, this is a good time to discontinue the minimal support 
those sheets have had.

> Cheers,

> Andrew

Closing issue.
