### ISSUE TITLE
35e - Green Ronin, APM Race Build Options

### ISSUE THREAD

**Issue by BahamutDragon** [BahamutDragon/pcgen#235]
Request for Race Options

**Comment by BahamutDragon** [comment]
@GamerGoddessDin this is now implemented.

**Comment by BahamutDragon** [comment]
This is a simple user self-police version. To use, navigate to the Feats & Abilities Tab, misc subtab. Under the Misc Options add the "Use Green Ronin Race Building Customization Option". Then switch to the RACE TRAIT tab. You will see Race Building Customization, and all the valid options in there. The final character sheet will have a tally of points spent or obtained for the three major groups. Again, this is user self policing to remain legal. Adding the versatility to restrict usage would take a bit more work. Only thing not implemented for your request is actual selection of a favored class - that is being investigated for proper implementation.

**Comment by GamerGoddessDin** [comment]
The Exotic Weapon Familiarity, at least with "Sword, Bastard", is not causing the relevant 1-handed weapon to be included in the Battle Sorcerer's Weapon Proficiency choice list.

Also, is it not possible to have the Favored Class choice list simply use the available classes from the loaded sources?

My loaded sources for these tests(35e Bahamut's game mode):
Advanced Players Manual
Complete Arcane
Dungeons and Dragons Core Books
PHB2
Unearthed Arcana

**Comment by BahamutDragon** [comment]
Favored Class: Yes, it is possible to select any currently loaded source list of classes. However, if you want it to actually have meaning in the code, then what I did is better for knowing the current coded options. (It actually sets a favored class by this method). Changing it to be for any base class is easily fixed, just will not actually set a favored class in all cases.

For the Bastard Sword, that is a tad trickier. PCGen only displays proficiency as the name of the item. I will insert the code to allow the weapon itself to be a one-handed option.

**Comment by GamerGoddessDin** [comment]
The class I'd like to select as a Favored Class is the Duskblade from PHB2.

Also, adding a "Custom"/"Blank" Race for people to be able to start without any racial mods might be useful for people.

Oh, and I can't seem to be able to remove the default racial items to replace them. (Tested on Human base)

PS: Thanks for being so quick to reply to these things and implement the stuff I'm wanting.

**Comment by BahamutDragon** [comment]
Progress made based upon the information presented:

1. Favored Class will now give you two options. Select any class loaded, but does not apply any actual Favored Class (Catch-all for anything not coded); or Select any Coded Class and apply Favored Class properly. Note: All PH2 classes have been added.

2. Custom Race made. Beware, this is truly a bare race. For the time being will default to Medium size and MOVE of 30. You will need to utilize the Assign Race Type and add things as you desire.

3. Remove All Race Traits is now visible under the misc options. This will remove everything except the languages, those have two separate options available to remove automatic and bonus languages. 

For the previous post:
Bastard Sword and Dwarven Axe now become one-handed when the familiarity option is selected.

I need to test the numerous changes before this is pushed in. Be a few minutes.

**Comment by BahamutDragon** [comment]
All tested for errors. Found errors in the PH2 and CAr unrelated and fixed those as well. Everything is pushed in. Test the changes for actual desired results.

You are welcome and thank you.

**Comment by GamerGoddessDin** [comment]
The default Human bonus skill points ability is missing from the options list. Most of the other PHB1 race abilities probably are as well. They're all listed in that section of the book though.

**Comment by BahamutDragon** [comment]
Goodness... I ignored those figuring they were just a default grant. I shall add them in. Be about another 30 more minutes of code time.

Some of those options will be a bit. Splitting the human skill bonus is... unpleasant. 

For sanity sake, I think I will just add a "No Traits" subrace selection to the PH races. Mixing the remove racial traits with a granting of a subrace will not work out otherwise.

**Comment by GamerGoddessDin** [comment]
I should probably put this in a separate issue but I'll put it here for now: The Draconic Selection for Draconic Heritage doesn't seem to do anything. It's not shown on the character sheet output in any way, and the related skill isn't added to the Class Skill list. I've not yet fully tested Draconic Resistance so I don't yet know whether it properly flags the element for that.

**Comment by BahamutDragon** [comment]
Separate issue please.

**Comment by GamerGoddessDin** [comment]
The Human Level 1 bonus Skill points ability is being added in before the Level 1 Skill Point Multiplier resulting in far larger numbers of skill points being added than there should be.

Simple fix: Change the internal modifier number from a 4 to a 1.

**Comment by GamerGoddessDin** [comment]
Bastard Sword still doesn't show up on the Battle Sorcerer Proficiency options list with Exotic Weapon Familiarity from the APM Race mods.

**Comment by GamerGoddessDin** [comment]
Energy Type Resistance mod should probably put something on the main page of the sheet near the HP and other core stats.

The entry on the sheet that lists the points spent appears to be counting the Human Skill point mods as being Ability Points rather than the Modifier Points they should be.

**Comment by BahamutDragon** [comment]
1. Battle Sorcerer Proficiency selection has Sword (Bastard) listed -
![image](https://cloud.githubusercontent.com/assets/4307487/8636583/36e6280a-281f-11e5-90b2-b05b894a5802.png)
Taking the Weapon Familiarity -
![image](https://cloud.githubusercontent.com/assets/4307487/8636608/61873404-2820-11e5-8093-b31d0569c2f9.png)
Equipping the Sword (Bastard) or Sword, Bastard -
![image](https://cloud.githubusercontent.com/assets/4307487/8636616/9b1d13be-2820-11e5-9f8b-f9f041cccbd0.png)

2. Variable tracking points corrected for Human Skill Points.

3. Skill Points fixed. 1 Granted at level 1 only that will be affected by the x4 level mod.

4. Energy Resistances (when implemented) display in the normal Special Qualities portion of the character sheet. Alterations to the character sheets are time consuming and not really within the field of expertise for this dragon.

![image](https://cloud.githubusercontent.com/assets/4307487/8636721/37b1cb9e-2825-11e5-865e-21ca6f81d3e8.png)

Finally, as a polite request for future issues. Please separate out each problem, request or bug into its own issue tracker. Piling multiple requests and bugs, even if related, into the same issue tracker is a sure guarantee to have an even slower resolution. Each problem raised must be evaluated and addressed before the issue can be deemed completed and closed. It is also more likely to have one aspect overlooked or incomplete. Trust me mate, from this side of the screen, dealing with five small requests is much more preferable than to one issue with five small issues inside.

All issues addressed... I think.
