### ISSUE TITLE
3.5e Spellwarped template missing

### ISSUE THREAD

**Issue by Unicorn437** [BahamutDragon/pcgen#236]
Spellwarped template from 3.5e is missing and I'd like to use it, shouldn't be too much work to add it, I might be able to do it myself if you could explain me where I can find the nescessary documentation, since I can't find one that explains how to create complex templates.
http://www.realmshelps.net/monsters/templates/spellwarped.shtml

Thanks in advance, 
Unicorn437

**Comment by BahamutDragon** [comment]
Mate,

Quick search to find that belongs in monster manual III.

Here is the base code - https://gist.github.com/BahamutDragon/b7b3ffd5929e6f6babb5
If you want the SR to actually display, simply add "SR:11+TL" to the special ability which follows standards, or standalone in the template. Both methods will give the desired results.

Now that you can view the snippet I coded up, what about the template led you to believe this was a 'complex' template? 

If you desire an insight on how I approach templates or anything for pcgen, I ask myself a basic question "Does this impact the character sheet?".

Here is a breakdown of using that question to come up with the following:
RACETYPE changes. Impacts character sheet? Yes, we output on the sheet. Gains Augmented Subtype. PCGen has code to automatically do that if the creature is coded up correctly. (Race must have a proper TYPE:RaceType entry.)

Natural AC increases by +2. Impacts the Armor Class output. BONUS:COMBAT|AC|2|TYPE=NaturalArmor or newer method is BONUS:VAR|AC_Natural_Armor|2

Two distinctive abilities are granted. These can be displayed simply using SAB: or creating the appropriate special abilities and granting them from the template.

Stat changes are extremely common, BONUS:STAT|StatAbbreviation|Value|TYPE=Racial to show it as a race change. For completeness, TYPE=Racial.STACK in case this race has defined stat bonuses outside the base, like a subrace. You can omit the TYPE=Racial, and the bonus will be reflected as a misc bonus instead.

Challenge Rating has a minor impact. BONUS:MISC|CR|1|PRELEVEL:MIN=x we have two entries reflecting two different times the CR is changed.

LEVELADJUSTMENT:3 handles the ECL portion.

Finally, as a matter of completeness, we use PRExxx to keep the template available only for the defined allowed race types. The template says Corporeal, which is opposite of Incorporeal. Incorporeal is a RACESUBTYPE, and we tell pcgen to avoid that using !PRERACETYPE:1,RACESUBTYPE=Incorporeal. Then it lists all the allowed race types, PRERACETYPE:1,y,y,y,y

Best,

**Comment by BahamutDragon** [comment]
Pushed to 6.04.01 branch
