### ISSUE TITLE
Complete Arcane Draconic Heritage bug.

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#237]
The Draconic Selection for Draconic Heritage doesn't seem to do anything. It's not shown on the character sheet output in any way, and the related skill isn't added to the Class Skill list. I've not yet fully tested Draconic Resistance so I don't yet know whether it properly flags the element for that.

**Comment by BahamutDragon** [comment]
1. Class Skill status is not updated on the skill tab. Simply add 1 rank and it refreshes to display correctly. (Raise a jira issue for the pcgen team to fix this. Not an issue I can address)

2. Resistance is currently displayed in a basic fashion on the ability. Added the five basic types to be displayed.
Corrected the display for the front page -
![image](https://cloud.githubusercontent.com/assets/4307487/8636624/fd37369c-2820-11e5-9875-8046ccdef140.png)
For the five basic resistances, a display like this will appear -
![image](https://cloud.githubusercontent.com/assets/4307487/8636630/4816d01e-2821-11e5-8fc9-a26349608c73.png)

Implemented or fixed.
