### ISSUE TITLE
High Elf Trait Cantrip, Cantrip can't be chosen

### ISSUE THREAD

**Issue by xorrizon** [BahamutDragon/pcgen#238]
> You know one cantrip of your choice from the wizard spell list. Intelligence is your spellcasting ability for it.

At the moment there is no way to select this cantrip.

I guess the expected behavior would be that a high elf can choose one "Wizard Cantrip" under Feats & Abilities regardless of the class and a wizard should be able to select 4 instead of 3 cantrips.

**Comment by BahamutDragon** [comment]
Hi mate,

For leveraging the wizard class, that is workable granting an extra cantrip to use. 

The non-wizard types though, granting the choice is going to amount to zero return on investment. Without the wizard base, that spell will fail to display. 

I could display an at will spell on the character sheet for the non-wizard. Be a bit more coding involved.
