### ISSUE TITLE
Green Ronin APM Spell like Ability not-implemented

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#239]
Not-implemented is a fairly obvious issue (assuming the High Elf Cantrip commit didn't change this). Any ETA on when it will be implemented?

PS: For ease of point calculations until it's fully implemented making it not add to the Ability Points used number would be nice.

**Comment by BahamutDragon** [comment]
Hi mate, 

The 5e High Elf Cantrip commit is unrelated.

There is no easy method to implement this request. LST syntax has some serious limitations with regards to more than one choice, and dealing with the spells.

ETA becomes a subjective matter. It really depends on your level of expectation.

With the system as stated, you have 10 x 10 = 100 combinations for Spell Level and Per Day. That would cover the point calculations. 10 Levels of Spells, and up to 10 usage combinations.

By far the easiest method to keep the numbers straight. Roughly 30 minutes give or take.

For having an actual spell choice, then refer to issue #76 which shows why such a feature is not easily obtained. 

If the desire is an actual spell-like entry with spell details, that is 11 manual entries per spell or power. Which has to be added to the spell origin source book. The time to implement grows with each book this feature is supposed to cover. Probably 3 minutes per spell for the 11 entries.

ETA working out the numbers is 30 minutes for a basic system, and about 180 minutes per book.

Best,

**Comment by GamerGoddessDin** [comment]
For making it show the proper number of spent points at least you could simply have it ask the user for the Spell/Power Level, and the number of uses per day (including at-will and continuous as options). That much should be easily doable right?

As for choosing the spell, are you able to add a category on the Spells tab that just lists all the included spells/powers as options to learn?

**Comment by BahamutDragon** [comment]
No, the ability may only take one chooser. Selecting Spell/Power Level is one choice, number of uses per day is a second choice.

For the last part, no. That is a user interface issue and well beyond anything I can manage. You would need to talk direct to the pcgen team to make any sort of changes in that manner.

Solution:
Add the Spell like Ability as before. A new category appears. You will select the appropriate ability, they are listed with both Level and use which will set the correct "cost". A user input dialog will appear to give the user a fill-in selection. It will say what level the spell is supposed to be.

This involved adding 111 new abilities. Took the 30 minutes estimated.
