### ISSUE TITLE
Green Ronin APM Racial Hit Dice adds skill points but doesn't allow them to be spent.

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#241]
The skill points appear on the Troubleshooting character sheet output but are not visible on the Skills tab.

**Comment by BahamutDragon** [comment]
This may be a pcgen team issue. Checking it out.

**Comment by BahamutDragon** [comment]
After some testing, this is beyond my capability.

The syntax is adding the race levels in a hidden state, which is granting HP, altering max skill ranks, and granting virtual skill points. This is going to have to be changed to user self-policing. Anything further would have to be addressed by the pcgen team.

**Comment by BahamutDragon** [comment]
Actually this is even worse than first reported. Adding the racial HD before any class levels messes up the class skills, causing them to convert to the racial class in theory. Tried with human, +2 racial HD and then 1 level of Barbarian. 

Only literacy was available as a class skill. Disabled the grants and moved this to user manual changes.
