### ISSUE TITLE
Green Ronin APM Bonus Feat can't be taken more than once.

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#242]
Title

Also, whenever you get around to implementing it tracking and enforcing racial trait costs please add an option to disable that and allow the addition of traits without their costs being tracked so that campaigns that give houseruled bonuses (such as the total of 3 extra feats given in the campaign that caused me to discover this bug.)

**Comment by BahamutDragon** [comment]
With these point customization style systems. It is far easier to make it user self-policing then to put together a restrictive system, and then build in a bypass. Tracking points spent by different categories is much easier. 
You have two pools to draw from, and then a wild card pool that can be used in either pool. With the wild card pool, it makes restricting the selections that much harder.
