### ISSUE TITLE
PHB 2: Duskblade Spell Power isn't applied.

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#246]
Title

**Comment by BahamutDragon** [comment]
Email me please - bahamutdragon2013@gmail.com.

 GamerGoddessDin wrote:
>
> Title
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BahamutDragon/pcgen/issues/246>.
>

-- 
~BD
https://github.com/BahamutDragon/pcgen
http://games.groups.yahoo.com/group/bd_games/

**Comment by GamerGoddessDin** [comment]
What exactly am I supposed to email you?

**Comment by BahamutDragon** [comment]
Implemented
