### ISSUE TITLE
Green Ronin APM Immunity to three energy types charging triple

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#247]
List price for immunity to three energy types is 30 Ability Points but is currently charging 90. I've not tested them yet but the one and two energy type versions may have been similarly miscoded.

**Comment by GamerGoddessDin** [comment]
Additionally, when the Immunity to three energy types trait is removed and the sheet refreshed the individual energy type immunity entries are still there. Might be easier to fix this thing by switching it to the same set up used for energy type resistances.

**Comment by BahamutDragon** [comment]
Fixed issue. 
SELECT:x with x being value other than 1 has the effect of acting as a multiplier to the var by that amount. Took recommended course of action and moved chooser into separate ability in a COST:1 pool.
