### ISSUE TITLE
Green Ronin APM Spell like ability SLA level 0/ At-will undercharging by 20 points

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#249]
Based on the formula of 5 x spell level (counting 0 as 0.5) x uses per day (at-will/continuous count as 10 per day listed in the book a spell level 0 at-will should charge 25 points, instead it's only charging 5.

Is this a "bug" caused by system limitations similar to why you can't have it actually show the spell description or simply an implementation error?

**Comment by BahamutDragon** [comment]
This is the code in place:

BONUS:VAR|RaceBuild_AbilityListPoints|1*0.5 
BONUS:VAR|RaceBuild_AbilityListPoints|2*0.5 
BONUS:VAR|RaceBuild_AbilityListPoints|3*0.5 
BONUS:VAR|RaceBuild_AbilityListPoints|4*0.5 
BONUS:VAR|RaceBuild_AbilityListPoints|5*0.5 
BONUS:VAR|RaceBuild_AbilityListPoints|6*0.5 
BONUS:VAR|RaceBuild_AbilityListPoints|7*0.5 
BONUS:VAR|RaceBuild_AbilityListPoints|8*0.5 
BONUS:VAR|RaceBuild_AbilityListPoints|9*0.5 
BONUS:VAR|RaceBuild_AbilityListPoints|10*0.5
BONUS:VAR|RaceBuild_AbilityListPoints|10*0.5

I will switch to x*1/2 and see if that gives the correct results.

**Comment by BahamutDragon** [comment]
I see I omitted the 5x portion of the formula. Helps if the formula is intact to get the correct results.
