### ISSUE TITLE
Complete Arcane Draconic Heritage giving wrong class skills

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#253]
Red is giving Appraise when it should be giving Intimidate
I'm pretty sure I remember Blue giving the wrong skill when I took it once before but didn't need it anyways but I can't remember what it was giving in place of Listen. So you might want to just check all of them just in case.

**Comment by BahamutDragon** [comment]
Interesting. Apparently feat changes depending on the book used.

Races of the Dragon (2006)
![image](https://cloud.githubusercontent.com/assets/4307487/9002766/c5d34a82-371c-11e5-805f-68a0439034ea.png)

Complete Arcane (2004)
![image](https://cloud.githubusercontent.com/assets/4307487/9002790/f87d449c-371c-11e5-9df2-3499b62b181a.png)

Races of the Dragon (Which was completed first) and Complete Arcane have the exact same feat with the exact same benefits, but completely different skills based upon the same chromatic dragon (The feat was copied from Races of the Dragon to save time). 

If Complete Arcane and Races of the Dragon are loaded together, then Races of the Dragon will win.

Will get this corrected.

**Comment by GamerGoddessDin** [comment]
Pretty sure I didn't have Races of the Dragon loaded. I wonder why they changed the Red dragon to Appraise instead of Intimidate though.

And here I hadn't ever noticed a Feat section in Races of the Dragon in the first place. I wonder if I actually need that level of Battle Sorcerer with that version...

Oh! It would be helpful if you could put the element, associated skill, and Draconic Legacy spells in the descriptions for the various Draconic Heritage selections.

**Comment by GamerGoddessDin** [comment]
Also, if possible can you set the Red, and any others that change between the two, up so that they show up separately in the list instead of overriding each other if both books are loaded together? If it requires different names then you could list the CA Red as "Red (Intimidate)" and the Races of the Dragon Red as "Red (Appraise)".

**Comment by BahamutDragon** [comment]
Requested enhancements added.
