### ISSUE TITLE
gnome alt subrace - races of stone

### ISSUE THREAD

**Issue by Doleman** [BahamutDragon/pcgen#258]
I cannot swap into Whisper Gnome subrace, it's a subrace within the races of stone. Every other subrace are properly added, but when I try to add 'Whisper Gnome' I get the error 'You cannot select any more abilities'

**Comment by BahamutDragon** [comment]
Added the missing "COST:0" to allow the subrace to be taken. Reviewed existing subrace selections and added the COST:0 to all of them.
