### ISSUE TITLE
3.5e Complete Arcane, Warlock Caster Level not working

### ISSUE THREAD

**Issue by BahamutDragon** [BahamutDragon/pcgen#259]
Email from Alex....

Hello, it seems, that class Warlock is not listed as arcane spellcaster (which he is) 

Examples - http://dndtools.pw/classes/warlock/

Warlocks benefit in a specific way from prestige classes that have "+1 level of existing arcane spellcasting class" or "+1 level of existing spellcasting class" as a level advancement benefit. A warlock taking levels in such a prestige class does not gain any of his class abilities, but he does gain an increased caster level when using his invocations and increased damage with his eldritch blast. Levels of prestige classes that provide +1 level of spellcasting effectively stack with the warlock's level to determine his eldritch blast damage (treat his combined caster level as his warlock class level when looking at the advancement table to determine eldritch blast damage) and his eldritch blast caster level (half his total caster level from his warlock levels and his levels in the prestige class that grant him an increased spellcasting level). A warlock also gains new invocations known at these prestige class levels as though he had gained a level in the warlock class.

noticed this, when i've tried to take Obtain Familiar feat for warlock character

--
Also the same thing with

Maximize Spell-Like Ability
Type: General   Can be taken more than once   Stacks
Requirements: at least 6 levels of SPELLCASTER

**Comment by BahamutDragon** [comment]
Fixed Caster level component; added ability focus support. Invocations now use the new caster level value. Added Eldritch blast to display damage.

**Comment by shadowfury** [comment]
Thanks a lot, works marvellous!  Though as i understand, looking at code
invocations themselves look like a lot of code and thinking to do, right?

**Comment by BahamutDragon** [comment]
Mate, not sure if that is an actual question. Invocations are not too complicated. Code was in place, just altered to handle the Ability Focus and caster level changes.
