### ISSUE TITLE
Implement Gestalt Classes for PH2

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#265]
Is it set up in such a way that I can do a Fighter/Duskblade Gestalt? If so, how do I do that? If not, can you make it so?

**Comment by GamerGoddessDin** [comment]
Never mind, figured it out.

**Comment by GamerGoddessDin** [comment]
Or at least I thought I had before I tried to add my second level and couldn't use my roll of 10 HP. How do I do this?

**Comment by BahamutDragon** [comment]
When implemented, the gestalt was only enabled for the core classes.
Anything else would need to be requested and implemented separately.

On 8/18/2015 12:59 PM, GamerGoddessDin wrote:
>
> Or at least I thought I had before I tried to add my second level and
> couldn't use my roll of 10 HP. How do I do this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BahamutDragon/pcgen/issues/265#issuecomment-132333068>.
>

-- 
~BD
https://github.com/BahamutDragon/pcgen
http://games.groups.yahoo.com/group/bd_games/
