### ISSUE TITLE
Draconic Creature Template from Draconomicon should (presumably in errata) add the Dragonblood subtype

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#266]
I base this on this list's mention of the Draconic Hobgoblin (even though it completely fails at referencing the source of the base race and the template): http://www.minmaxboards.com/index.php?PHPSESSID=f7h2tmbs6coe5s70bka5akkc24&topic=342.0  

Related: The template's Darkvision also includes Low Light Vision that isn't included in the version you have implemented.

**Comment by BahamutDragon** [comment]
Without a proper citation, it becomes house rules. 

I can fix the missing vision modes, since that is valid.

**Comment by BahamutDragon** [comment]
Size and Type: Animals with this template become magical beasts, but otherwise the creature type is unchanged. Size is unchanged.

**Comment by BahamutDragon** [comment]
Vision fixed in #267

**Comment by BahamutDragon** [comment]
Races of the Dragon 1/2006 has the updated version, which does include the Dragonblood subtype.

**Comment by BahamutDragon** [comment]
page 4 of Races of the Dragon:
THE DRAGONKIND RACES
Just as City of the Spider Queen expanded and enumerated the
various spiderkind races, Races of the Dragon defines several
existing races as dragonkind and adds some new ones. (Some
of the stranger creatures, such as the ravid and the spell weaver,
work very well as spawn of Tiamat—mortal enemies of the
dragon born who serve Bahamut.) The dragonkind races detailed
in various D&D books (some of them appearing in more
than one source) are as follows.
Races of the Dragon: Dragonborn, spellscale, kobold, draconic
creatures, half-dragons.
Draconomicon: Dragonkin, dragonnel, elemental drakes,
faerie dragon, fang dragon, spiked felldrake, landwyrms, planar
dragons, shadow dragon, storm drake, draconic creatures,
half-dragons.
Fiend Folio: Sea drake, sunwyrm.
Monster Manual: True dragons, behir, dragon turtle, kobold,
pseudodragon, ravid, wyvern.
Monster Manual II: Gem dragons, felldrakes, frost salamander,
hellfire wyrm, linnorms, spellweaver.
Monster Manual III: Ambush drake, dracotaur, dragon eel,
rage drake, ssvaklor.
DRAGONBLOOD SUBTYPE
If a race possesses the dragonblood subtype, it has a strong
affinity to dragons—which means that spells, effects, powers,
and abilities that affect or target dragons also affect it. The subtype
qualifies a creature to use magic items normally only usable
by dragons, and qualifies the creature to take feats that have the
subtype as a prerequisite. The dragonblood subtype also makes
creatures subject to harmful effects that affect dragons.
The dragonblood subtype does not confer the dragon type
or any traits associated with that type. For instance, it does not
give a creature frightful presence.
Dragons automatically qualify for any classes, prestige classes,
racial substitution levels, feats, powers, or spells that require
the dragonblood subtype. Races presented in this book that
have the dragonblood subtype include dragonborn, spellscale,
kobold, and draconic creatures. Should a creature acquire the
dragon type, it loses the dragonblood subtype.
DRAGON-DESCENDED RACES
This term refers to a narrower category of dragonkind races.
Dragon-descended races are those that use either the halfdragon
or draconic creature templates.
