### ISSUE TITLE
Request: [3.5] Double max skill ranks and spells per day options (Homebrew Requests)

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#268]
Was going to just use the Bypass Max Skill Ranks setting under House Rules in the PCGen settings but the 35e Bahamuts game mode apparently doesn't support that setting.

**Comment by BahamutDragon** [comment]
I see the same rule as for the 35e mode, no difference between the two.

**Comment by GamerGoddessDin** [comment]
Just tested it in the default PCGen made 35e game mode, the option is broken there too.

Any chance of you being able to look through their code and find where it's broken or do we have to just report it to them and wait for them to fix it?

**Comment by GamerGoddessDin** [comment]
The toggle is there but it still won't let you put more ranks in each class skill than 4 at level 1 even when the bypass is supposedly enabled.

**Comment by BahamutDragon** [comment]
You need to talk to the pcgen developers.

On 8/18/2015 1:09 PM, GamerGoddessDin wrote:
>
> The toggle is there but it still won't let you put more ranks in each
> class skill than 4 at level 1 even when the bypass is supposedly enabled.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BahamutDragon/pcgen/issues/268#issuecomment-132335173>.
>

-- 
~BD
https://github.com/BahamutDragon/pcgen
http://games.groups.yahoo.com/group/bd_games/
