### ISSUE TITLE
[3.5] When a character can learn more spells of a level than are on their class list the TODO list entry never goes away

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#270]
Just discovered this while building a character for a campaign the uses a 26/24/22/20/19/18 array (Yes, I know that's massive. Presumably that's what this DM's encounters are balanced for though.) So with the 26 INT and +8 INT mod I can learn 10 level 0 spells out of a list of 4.

Is there any way you can make it cap known spells at the number on the spell list?

**Comment by GamerGoddessDin** [comment]
A similar thing happens when characters of a race with a limited pool of Bonus Languages has more bonus languages than are available to their race.

**Comment by BahamutDragon** [comment]
You need to talk to the developers that maintain the actual pcgen program over at pcgen.org. I only code up the books.
