### ISSUE TITLE
5e - Barbarian AC calculation

### ISSUE THREAD

**Issue by quonic** [BahamutDragon/pcgen#274]
From what I've read, the barbarian's AC is supposed to be 10 + Dex + Con.

After adjusting the Dex, the AC changes.
After adjusting the Con, the AC doesn't change.

I've tried using the Players Handbook as the only source and looking in ph_abilities.lst. I don't see any obvious errors. Unless pcgen doesn't want to add AC_Ability_Score_Bonus for some reason.

If the DEX and CON are both 18. AC_Ability_Score_Bonus always calculates out to 4 and not 8. With a Shield it should total 20.

I've also selected Barbarian Unarmored Defense in the Armor Class Method.

Thanks for all the work that you have done and will do. :)

**Comment by BahamutDragon** [comment]
Fixed.

**Comment by BahamutDragon** [comment]
The AC should only appear in the ability. Let me check that first.

**Comment by BahamutDragon** [comment]
AC now alters accordingly.
