### ISSUE TITLE
Age changing stats in 5th edition

### ISSUE THREAD

**Issue by Wemes** [BahamutDragon/pcgen#280]
I noticed that the age categories look like they were just taken from 3.5e. Are there any rules at all in 5e about age changing stats or should those rules be eliminated altogether?

**Comment by BahamutDragon** [comment]
Stat alterations do not appear to exist in 5e based upon age categories. Simple fix is remove the alterations. The categories can remain for now.

**Comment by BahamutDragon** [comment]
Control over biosettings moved from gamemode into the PH set. Removed the stat alterations due to age category changes.
