### ISSUE TITLE
World of Warcraft (Revised edition)

### ISSUE THREAD

**Issue by BahamutDragon** [BahamutDragon/pcgen#292]
Implement a basis to work with, lay ground work for supplements.

**Comment by BahamutDragon** [comment]
@Talaren working through the major items. Did you want to begin adding the auto and bonus tags?

**Comment by Talaren** [comment]
@BahamutDragon OK sounds good.

**Comment by BahamutDragon** [comment]
@Talaren how goes your end?

**Comment by BahamutDragon** [comment]
Stable Warcraft set available. Still "alpha" with many small tasks available if any contributor wishes to dive in.
