### ISSUE TITLE
[Dnd 3.5] Warlock is not arcane caster

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#298]
- With the latest fix (that fixed previous issues, ty) Warlock is now not an Arcane caster and can't take feats like Obtain Familiar or Craft Contingent Spell (and almost any other Craft Feats) and a few prestige classes that required Arcane Caster level that kind of fit Warlock (progressed existing class level)

- Eldritch Blast Damage still does not stack it seems
- Also noticed, that Energy resistance that is added to warlock on 10th level adds 12 points of resistance instead of 5

**Comment by shadowfury** [comment]
Warlock's and Hellfire Warlock's Eldritch Blast damage progression still don't stack, can provide character file for easier tests

**Comment by BahamutDragon** [comment]
The specific issue was not clear. Eldritch Blast has two locations where a damage is listed, the one I fixed was the ability version. I can only consider the version you wanted was the spell version. Fix pushed in.
