### ISSUE TITLE
5e - Witch Hunter

### ISSUE THREAD

**Issue by BahamutDragon** [BahamutDragon/pcgen#305]
New Class for 5e.

**Comment by BahamutDragon** [comment]
Witch Hunter added

**Comment by Wemes** [comment]
Nice, I was hoping at one point to add these when I was done looking through the PHB. Are you intending on adding any of the other homebrew stuff they use? I know Matt Mercer has released the Gunslinger class already. I've asked and I'm hoping he'll share some of the other stuff he's made (the glacial blast spell and such).

**Comment by BahamutDragon** [comment]
I caught wind of the Witch Hunter and wanted to add it to my group. My mates are playing 5e. We do enjoy some nice variety in our mix. The Vin Diesel video is just a nice bonus. 

The spell support is questionable, but works for now. I might fine tune it later, but that is after I get my current task completed.

For additional materials for any system or source please in each request a separate issue. I would hope my track record proves I do include anything requested. The support might not be 100% though due to outside program issues beyond my capability to manage. 

I am currently finishing up World of Warcraft equipment. Then I need to find out where @Talaren is with his WoW updates before I begin back filling missing implementations.
