### ISSUE TITLE
 Heroes of Horror - Archivist Spells Available

### ISSUE THREAD

**Issue by RoninIchi** [BahamutDragon/pcgen#311]
Thanks again for adding the Archivist class. I had a couple of questions:

1. It seems as though only spells which are Divine and available to ALL classes are listed as available to learn. I believe that the Archivist should be able to learn Cleric spells by default and any Divine spell by copying scrolls/texts/etc. 

2. Is there a way to add spells from a scroll to a spell book?

Much appreciation!

**Comment by BahamutDragon** [comment]
Mate,

1. Sorry about that. Fixed the problem. Now the Archivists will allow spells from the divine classes currently available in the sources made: Cleric, Druid, Paladin, Ranger, Death Delver, Shugenja, Favored Soul, Spirit Shaman, and Blackguard.

2. I am not aware of such a mechanic.

**Comment by RoninIchi** [comment]
Thanks!!!
