### ISSUE TITLE
[Dnd 3.5] Ur-Priest does not have known spells (aside from ones with "ALL" identifier)

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#313]
Base spell list should have been cleric's spell list (created another character, now he has cleric's spell list, but is not able to add spell's to known list (as if he had low wisdom modifier that doe not allow to learn spell))

**Comment by BahamutDragon** [comment]
Added MEMORIZE:YES. Ur-priest now allows spells for each cast slot.

**Comment by shadowfury** [comment]
After update still was not able to learn any spells for Ur-Priest (was progressing it with Sacred Fist prestige)

Link to character with this bug - https://drive.google.com/file/d/0B-rR42mW0mRPdE93WFZTZV9GZnc/view?usp=sharing

Note: i've also tried to add and remove Ur-Priest. Perhaps it's problem with Sacred fist not progressing Ur-Prist, though i was not able to see 1st and 2nd level spells aswell

**Comment by BahamutDragon** [comment]
Mate,

SPELLLIST went missing. After you grab the update, remove the sacred fist and ur-priest levels, then re-add them. That resolves the issue on my side.

Best,

**Comment by shadowfury** [comment]
After doing that i do see Ur-priest spell list, but i can not add any spell at all to known spell list 
![image](https://cloud.githubusercontent.com/assets/2230015/14056787/5ac87174-f2f9-11e5-8ca7-473ab4543035.png)

**Comment by shadowfury** [comment]
Is it possible to fix this? I didn't found a way to add known spells number myself yet

**Comment by BahamutDragon** [comment]
Mate, MEMORIZE:YES corrects the error message. What I have not managed to correct is the lack of a spell list. SPELLLIST:1|Cleric should be populating the class with every cleric spell loaded. I have tried different approaches, but think this bug is beyond data and may be a pcgen team issue.

Are you willing to enter the issue on their official tracker?

**Comment by shadowfury** [comment]
Ok, i'll post bug in their jira. Also i found another bug for ur-priest - Turn level check for that character is calculated for turn level 0. When i have 2 levels of ur-priest and it should be 2 instead of 0

**Comment by BahamutDragon** [comment]
Other Ur-Priest issue handled: https://github.com/BahamutDragon/pcgen/issues/466

**Comment by shadowfury** [comment]
I've created issue in their JIRA - https://pcgenorg.atlassian.net/browse/CODE-3039 hopefully they will fix it somewhere in the future

**Comment by BahamutDragon** [comment]
PCGen program issue. Jira entered. Closing this issue.
