### ISSUE TITLE
[Dnd 3.5] Monk's Belt + Monk class Level + Sacred Fist total unarmed damage

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#314]
With having 2 levels of monk and 6 levels of Sacred fist and wearing Monk's Belt i have total unarmed damage 1d10 (as for monk 8 to 11th level), but total level is (2 (for monk) + 6 (for SF) and +5 (for Monk's Belt) to a total of 13, that is equal to 2d6 Unarmed damage

Looks like Monk's Belt bonus is not included

**Comment by BahamutDragon** [comment]
Updated to use new mechanic, removed old tags.
