### ISSUE TITLE
[Dnd 3.5] Sudden Strike is not displayed in Special Attacks

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#315]
It would be really handy to display aside from Sneak Attack things like Sudden Strike die (and perhaps Skirmish die?) for classes like Ninjia or Avenging Executioner

**Comment by BahamutDragon** [comment]
Mate,
When you list classes that already display the feature it leads me to believe this is a non-issue.

Skirmish and Sudden Strike are a shared class feature and is set up to display as a Special Attack and Special Quality. I removed the Special Quality type from both.

Actual Classes missing the shared feature:
Avenging Executioner
Dread Fang Of Lolth
Shadowblade
