### ISSUE TITLE
[Dnd 3.5] [Feature request] Knowledge checks about character

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#316]
It would be really handy to see what knowledge check are required to get additional info about character. So if there is a list of knowledge checks (based on classes and prestige classes) with DC and information that is known based on these checks would really help players to combat some characters based on classes. (Usually this checks are listed at the end of classes description)

I understand that there are a huge amount of classes to go over with, so it's kind of "if there is no other stuff to fix" thing

Thanks

**Comment by BahamutDragon** [comment]
Mate,

This looks like a GM tool request, and not really something useful for 
character generation or maintenance. I do not envision this being useful 
enough to take up valuable character sheet space constantly.

An alternative suggestion, use a spread sheet. List each class on a tab, 
and your DC table would work great.

I would be more than happy to host that as an extra tool.

Best,

On 10/27/2015:
>
> It would be really handy to see what knowledge check are required to 
> get additional info about character. So if there is a list of 
> knowledge checks (based on classes and prestige classes) with DC and 
> information that is known based on these checks would really help 
> players to combat some characters based on classes. (Usually this 
> checks are listed at the end of classes description)
>
> I understand that there are a huge amount of classes to go over with, 
> so it's kind of "if there is no other stuff to fix" thing
>
> Thanks
>
>

-- 
~BD
https://github.com/BahamutDragon/pcgen
http://games.groups.yahoo.com/group/bd_games/

**Comment by BahamutDragon** [comment]
Closing this issue mate. Not going to be a project I undertake. Too many actual data requests that will keep me busy enough as it is.

I will include a spreadsheet if one is made by yourself or another contributor.
