### ISSUE TITLE
[D&D 3.5] Academic Priest

### ISSUE THREAD

**Issue by RoninIchi** [BahamutDragon/pcgen#318]
Mate,

I was wondering if you might be able to add the Academic Priest feat. from Dragonlance?

Dragonlance Campaign Feats
Academic Priest [General] (Legends of the Twins)

Your path to faith is more scholarly than those of other clerics.

Prerequisites: Intelligence 13+

Benefit: For the purpose of determining bonus divine spells per day and maximum divine spell level, your primary spellcasting ability is Intelligence. If you have more than one divine spellcasting class, the bonus applies to only one of those classes. Your spell save DCs are not affected by this change.

Special: You may only take this feat as a 1st-level character. If you take this feat more than once, it applies to a different divine spellcasting class each time. You may take this feat even if you have no divine spellcasting classes yet.

I was trying to make it myself to apply to an Archivist character, but I was doing something wrong.

Much appreciated!

**Comment by BahamutDragon** [comment]
Mate,

Easily added.

Regarding the Archivist, I think you are thinking it will be a bonus and not a replacement.

> For the purpose of determining bonus divine spells per day and maximum divine spell level, your **primary** spellcasting ability is Intelligence

Let me illustrate with a cleric example:
Replace primary spellcasting ability of Wisdom with Intelligence.
If we give the Cleric a Wisdom of 10, and Intelligence of 20, then we have a net 10 point increase.

Now the Archivist. Replace the primary spellcasting ability of Intelligence with Intelligence. If we give the Archivist an Intelligence of 20. You would replace primary spellcasting ability of Intelligence (20) with Intelligence (20), which means a net change of zero. The Archivist is the living embodiment of the feat, plus includes the DC bonus. 

Here is the implementation blank: (Replace ClassName with the actual class name)
`ClassName	KEY:Academic Priest ~ ClassName	CATEGORY:Special Ability	TYPE:Academic Priest		BONUS:STAT|BASESPELLSTAT;Class=ClassName|AcademicPriest_ClassName		DEFINE:AcademicPriest_ClassName|0	BONUS:VAR|AcademicPriest_ClassName|INTSCORE-WISSCORE	BONUS:DC|CLASS.ClassName|-(AcademicPriest_ClassName/2)`

The key is INTSCORE (new Primary spellcasting ability) replaces WISSCORE (The old spellcasting ability). The formula reflects that with INTSCORE-WISSCORE.

Cleric example:
`Cleric	KEY:Academic Priest ~ Cleric		CATEGORY:Special Ability	TYPE:Academic Priest		BONUS:STAT|BASESPELLSTAT;Class=Cleric|AcademicPriest_Cleric			DEFINE:AcademicPriest_Cleric|0	BONUS:VAR|AcademicPriest_Cleric|INTSCORE-WISSCORE	BONUS:DC|CLASS.Cleric|-(AcademicPriest_Cleric/2)`

Archivist example:
`Archivist	KEY:Academic Priest ~ Archivist	CATEGORY:Special Ability	TYPE:Academic Priest		BONUS:STAT|BASESPELLSTAT;Class=Archivist|AcademicPriest_Archivist		DEFINE:AcademicPriest_Archivist|0	BONUS:VAR|AcademicPriest_Archivist|INTSCORE-INTSCORE	BONUS:DC|CLASS.Archivist|-(AcademicPriest_Archivist/2)`

Feat added with support for Cleric and Mystic.

**Comment by RoninIchi** [comment]
Much appreciated! I misunderstood what I was doing it looks like.

Thanks so much!

**Comment by Pvanduyse** [comment]
It is worth mentioning that the Archivist uses Int for divine spell level and Wis for bonus divine spells per day. Academic priest would change the bonus divine spells from Wis to Int, which is somewhat important.
