### ISSUE TITLE
Incorrect Armor Class Handling[5e]

### ISSUE THREAD

**Issue by Smackumz** [BahamutDragon/pcgen#324]
According to the PHB for 5e, Heavy armor doesn't let you add your Dexterity Modifier to your armor class, but t also doesn't penalize you if your Dexterity modifier is negative. p145

Currently a Paladin with Chain Mail and 9 Dex is registering a 14 armor class.  It should be 16.  The cause is the STAT modifier is -2, this should be 0 for heavy armor.

**Comment by BahamutDragon** [comment]
Mate, to get the full fix, you need to update the gamemode, along with the normal files.

Best,
