### ISSUE TITLE
6.05.06 and Master reported issues

### ISSUE THREAD

**Issue by BahamutDragon** [BahamutDragon/pcgen#326]
using todays release of 6.5.6 unstable, and with a fresh copy of your
latest master set, loading just the core rules set:

19:29:19.76 INFO main Main:145 Starting PCGen v6.05.06-dev
19:29:19.122 INFO main LanguageBundle:131 Initialising language bundle with
locale en_US.
19:29:52.38 INFO Thread-6 SourceFileLoader:518 Loading game 35e and sources
[Dungeons & Dragons - Core Books].
19:29:56.974 SEVERE Thread-6 CDOMFactory:124 Unconstructed Reference:
PCStat CHA
19:29:56.974 SEVERE Thread-6 TrackingReferenceContext:119 Was used in
file:/F:/Data/GitHub/pcgen/data/35e/wizards_of_the_coast/core/monster_manual/mm_skills.lst
in tokens: [plugin.lsttokens.skill.KeystatToken]
19:29:56.974 SEVERE Thread-6 TrackingReferenceContext:119 Was used in
file:/F:/Data/GitHub/pcgen/data/35e/wizards_of_the_coast/core/universal_rules/ur_kits.lst
in tokens: [plugin.lsttokens.kit.StatToken]
19:29:56.974 SEVERE Thread-6 TrackingReferenceContext:119 Was used in
file:/F:/Data/GitHub/pcgen/data/35e/wizards_of_the_coast/core/players_handbook/ph_classes.lst
in tokens: [plugin.lsttokens.pcclass.SpellstatToken]

**Comment by BahamutDragon** [comment]
@FerretDave I cannot replicate. Only issues I see are deprecation notices.

File that would be the cause of the issue is ph__stats.lst, which holds this:

`Charisma		SORTKEY:6	ABB:CHA	KEY:CHA	STATMOD:floor(SCORE/2)-5	DEFINE:MAXLEVELSTAT=CHA|CHASCORE-10	DEFINE:NormalMount|0	DEFINE:NormalFollower|0	BONUS:VAR|NormalMount,NormalFollower|1	DEFINE:SizeIncrease|0	DEFINE:SizeDecrease|0	DEFINE:BypassSizeMods|0`

**Comment by FerretDave** [comment]
And therein lies my problem... everytime I try and clone your repo, it
gives me the 6.4.1 version rather than master !
I can see the ph_stats.lst file in your repo, but cannot figure out how to
fork your master to get mine up to date...

**Comment by FerretDave** [comment]
and I think I now have it, I had run a PR to get my own repo up to date
with your master... I thought git sync took care of that...

I obviously don't use git enough to remember all the steps I need to work
through correctly to keep things in sync.

I can now load my campaign source with just handful SEVERE errors, but all
are related to PGTFAE data that I can clean up.
