### ISSUE TITLE
[5E] Incorrect # of (MC) Cleric Prepared Spells

### ISSUE THREAD

**Issue by wilmcontreras** [BahamutDragon/pcgen#328]
Hi,
According to PHB p. 58, Clerics prepare [Wis Mod] + Cleric Level spells, which for the attached character should be 3 (2 + 1). However, I'm unable to prepare more than 2, which it lists as the number allowed. Using 6.04.01.

[Sorcerer pcg.zip](https://github.com/BahamutDragon/pcgen/files/60353/Sorcerer.pcg.zip)

Thanks,

W

**Comment by BahamutDragon** [comment]
@Wemes looks like another wrench thrown in slot support. Patching this for now to support the Prepared Spells UI tab (which @wilmcontreras is referring to). We will have to re-evaluate how this works in a multiclass caster scenario. I think the multiclass scenario will have to either be self-policed, or we need an override. Need to examine the rules to come to a proper decision on this.
