### ISSUE TITLE
Unable to load Elemental Evil Player's Companion (Supplement)

### ISSUE THREAD

**Issue by wilmcontreras** [BahamutDragon/pcgen#329]
The in Sources --> Advanced,  source info lists the PHB 5E as a requirement, however, no matter what combination of 5E sources I load (including all of them), it claims it's still missing a required source (see screenshot). Using 6.04.01.

![screen shot 2015-12-12 at 21 52 56](https://cloud.githubusercontent.com/assets/15095683/11765750/ba7278e4-a11a-11e5-89fb-d043833bf65c.jpg)

**Comment by BahamutDragon** [comment]
Fixed. Requires gamemode update to complete proper migration.

**Comment by wilmcontreras** [comment]
How would I do this? I clicked Download Zip from the main page, merged the gameMode folder with the PCGen one, and still got the same error.

**Comment by mkeith01** [comment]
I am new to pcgen. What do you mean when you say requires gamemode update. I would like to use this but am experiencing the same issue. v6.06.01

**Comment by BahamutDragon** [comment]
Mate, did you download the master branch version, or the 6.06.x branch version?

Only the 6.06.x branch will work with 6.06.01. Master branch will work with the current 6.07.0x development branches. PCGen should include the proper 5e gamemode, which means you do not need the 5e gamemode provided any longer.
