### ISSUE TITLE
(MC) Cleric character sheet displaying all known spells (rather than prepared)

### ISSUE THREAD

**Issue by wilmcontreras** [BahamutDragon/pcgen#330]
See attached—only a few L1 spells prepared, but when exporting the character sheet, all cleric spells are displayed in the Spellbook/Cleric spells section (not sure if working as intended though?)

[Sorcerer pcg.zip](https://github.com/BahamutDragon/pcgen/files/60371/Sorcerer.pcg.zip)

**Comment by BahamutDragon** [comment]
Mate, that is intentional. If all is working proper you should see all available/known spells, and then should have a section that shows whatever is prepared. Did you do an export?

**Comment by wilmcontreras** [comment]
Gotcha, thanks for all the quick responses—you're pretty awesome!
