### ISSUE TITLE
Rogue cannot select expertise with thieves' tools

### ISSUE THREAD

**Issue by nebulans** [BahamutDragon/pcgen#331]
I'm trying to create a Dwarf Rogue character.  By the PHB (page 96), at level 1 I can take expertise in either two skills I'm proficient in or one skill and Thief's Tools.  As a Rogue, I should be automatically proficient in Thief's tools (page 95).  When I try to select them from the Character tab, it's highlighted red with the explanation `all of ( at least 1 Tool Proficiency ~ Thieves' Tools Internal )`, so I am unable to select it.

**Comment by BahamutDragon** [comment]
Fixed

**Comment by nebulans** [comment]
This isn't quite a fix, now Thief's Tools is available to take expertise in, but I'm not offered the chance to take expertise in anything at level 1 (I would expect to be able to take two choices at level 1)

**Comment by BahamutDragon** [comment]
Sorry mate, Fixed again. Accidentally removed the level tracker value from Rogue.
