### ISSUE TITLE
Load values gameMode reverted

### ISSUE THREAD

**Issue by HerzogAlDilKassach** [BahamutDragon/pcgen#333]
Just checked the master branch for the 5th edition gameMode
In the 2 october merge the 'load'  values  seem to have reverted to an earlier version.

Possibly other values have reverted as well? This just jumped out at me (because the test character I was working with was suddenly overencumbered with only minimal equipment)

**Comment by BahamutDragon** [comment]
October 3rd is the last change, and the values display correctly.

#SIZEMULT:F|1
#SIZEMULT:D|2
SIZEMULT:T|4
SIZEMULT:S|6
SIZEMULT:M|8
SIZEMULT:L|16
SIZEMULT:H|32
SIZEMULT:G|64
#SIZEMULT:C|128
LOAD:0|0
LOAD:1|0.625
LOAD:2|1.25
LOAD:3|1.875
LOAD:4|2.5
LOAD:5|3.125
LOAD:6|3.75
LOAD:7|4.375
LOAD:8|5
LOAD:9|5.625
LOAD:10|6.25
LOAD:11|6.875
LOAD:12|7.5
LOAD:13|8.125
LOAD:14|8.75
LOAD:15|9.375
LOAD:16|10
LOAD:17|10.625
LOAD:18|11.25
LOAD:19|11.875
LOAD:20|12.5
LOAD:21|13.125
LOAD:22|13.75
LOAD:23|14.375
LOAD:24|15
LOAD:25|15.625
LOAD:26|16.25
LOAD:27|16.875
LOAD:28|17.5
LOAD:29|18.125
LOAD:30|18.75
LOADMULT:4

ENCUMBRANCE:Light|1||0
ENCUMBRANCE:Medium|2||-3
ENCUMBRANCE:Heavy|3||-6
ENCUMBRANCE:OverHead|1||0
ENCUMBRANCE:OffGround|2||0
ENCUMBRANCE:PushDrag|5||0

**Comment by HerzogAlDilKassach** [comment]
I THINK sizemult isn't being applied.
Which pcgen version are you using? I'll upgrade to that and check again.

**Comment by HerzogAlDilKassach** [comment]
Never mind.
just noticed the sizemult 'keys' in my file stated 'Medium' etc. instead of 'M' as yours does.
Must have missed that somehow.
thanks!
