### ISSUE TITLE
[5th edition] Proficiency bonus not applied for racial weapons

### ISSUE THREAD

**Issue by HerzogAlDilKassach** [BahamutDragon/pcgen#335]
PCgen 6.05.06, 5th edition latest from master downloaded today
I'm creating a High Elf Warlock.
He's proficient with simple weapons (warlock) and with longsword, shortsword, longbow and shortbow(elf)

However, on the character preview proficiency bonus is only added for the simple weapons.

I'm not sure how this attack bonus is calculated, and I must confess 5th edition is pretty new to me, but I do believe the proficiency bonus should be applied to the attack of the racial weapons.

**Comment by BahamutDragon** [comment]
Fixed all missing racial weapons
