### ISSUE TITLE
Incorrect requirements for Ranger Multiclass?

### ISSUE THREAD

**Issue by wilmcontreras** [BahamutDragon/pcgen#340]
According to PHB, Dex 13 and Wis 13 are the pre-reqs, but when trying to add, get an error (see screenshot).

![screen shot 2015-12-23 at 22 16 48](https://cloud.githubusercontent.com/assets/15095683/11990468/ec5204dc-a9c2-11e5-9083-1433f585b11b.jpg)

**Comment by wilmcontreras** [comment]
So, if I remove all the Rogue/Monk levels, I can add Ranger levels, but when I add Ranger levels, I can't add levels of any other class.

**Comment by BahamutDragon** [comment]
Fixed
