### ISSUE TITLE
[3.5 tome of magic shadowcaster fundamentals] Fundamentals not selectable

### ISSUE THREAD

**Issue by HerzogAlDilKassach** [BahamutDragon/pcgen#341]
Hi mate!

I tried creating a shadowcaster, and could not select any fundamental mysteries.
Seems there is a mismatch between the abilitycategory (which lists shadowcasterfundamental as type)
and the fundamentals themselves (which list, among others, fundamental as type, but not shadowcasterfundamental)
Changine fundamental to shadowcasterfundamental seems to fix this (but I don't know the implications of this change)

HerzogAlDilKassach

**Comment by BahamutDragon** [comment]
Fixed.

**Comment by BahamutDragon** [comment]
The abilitycategory should have been "ShadowMagicFundamentalPath" which matches the pattern with the rest of the paths.

**Comment by HerzogAlDilKassach** [comment]
Ok, thanks!
