### ISSUE TITLE
[3.5 tome of magic shadowcaster bonus feats] 

### ISSUE THREAD

**Issue by HerzogAlDilKassach** [BahamutDragon/pcgen#342]
Choosing mystery paths doesn't increase ShadowMysteryPathsTaken

I added a bonus to ShadowMysteryPathsTaken for every first mystery of a path in my local copy, and found a second issue:
bonus feats should be increased by ShadowMysteryPathsTaken/2, not ShadowMysteryPathsTaken

**Comment by BahamutDragon** [comment]
Mate,

Any reason you did not just submit a Pull Request? If you have done all the work, no reason not to give you credit as a contributor.

**Comment by HerzogAlDilKassach** [comment]
To be honest, I still haven'thaven't got the hang of git. Hope to get some help with that during the holidays. If so, you might get some pull requests starting next week :-)

**Comment by BahamutDragon** [comment]
I use Windows. Install git, that is the base program. It is personal preference whether to use command line or grab a client. I use a client to speed things along. I have found tortoisegit to be a nice integrated shell program. It plugs into my editors handily. I know the pcgen team endorses SourceTree as a good program. It has advanced features like cherry pick if you manage multiple branches. For me, tortoisegit handles 99% of what I need, which is commit, push, pull, switch/checkout, merge, and fetch. If you use another operating system, then you will need to select a client appropriate to your system.

In your repo, which is where you personally edit your files, you commit your changes. You must choose a branch to do the commit. It is best to make the choice before doing any actual work. You can choose to work in a main branch, like 6.04.01 or master, but common convention is to work on each individual issue in its own branch. This allows for isolating problems, making corrections, and keeps things tidy. A very important item. If you choose to make a branch, make sure you branch from the correct branch you want to work on. If you are doing 6.04.01 work, then branch from there. Master is not compatible with 6.04.01. After you commit, you can push the changes to your remote repository - which is what github.com is, a remote repository. When you are happy with the changes, you can use the Pull Request to submit your changes to another remote repository. If you are doing master based work, when you go to submit the PR adjust the branch you want the PR to effect from default "6.04.01" to "master". That person gets a PR notification, and reviews the changes. They can ask for modifications, which you supply by pushing additional commits to the branch you have an active PR on, reject the PR, or accept the changes, which is now included in their remote repository. They then use the Pull command to bring those changes into their local repository.

It is important to Pull changes to your branches before doing any additional work. This keeps the integrity of the branch clean for you. As well as avoiding conflicts which could result in accidentally removing changes someone else has made. Take it from my experience mate, nothing ruins a day faster then fixing another persons foul up on work you have spent considerable time getting working.

Use PRs only for submitting things. It is not necessary to use a PR to update your remote or local repository. You can add remote repositories to choose from, which allows you to Pull directly from other repositories, or FETCH to get access to their branches, which you can switch or pull from. Just remember to PUSH to your remote repository if you plan on collaborating.

That should be enough information to get you up and running. I have made the changes you suggested and will push it in. 

Best,

**Comment by FerretDave** [comment]
Greetings
worth putting all the git notes below into your readme in the repo itself,
as a permanent reference , I have to refer back as I don't use it regularly
enough.
Noted that I'm not the only one to ask the same questions

cheers
Dave
