### ISSUE TITLE
Force Selection of AC Method

### ISSUE THREAD

**Issue by wilmcontreras** [BahamutDragon/pcgen#343]
A Monk with 20 Dex/Wis should have 20 AC, but only shows 15.

![screen shot 2015-12-24 at 16 05 15](https://cloud.githubusercontent.com/assets/15095683/11998538/3619a990-aa58-11e5-8d42-93f2fb041c30.jpg)

**Comment by BahamutDragon** [comment]
Mate, what is your AC preference set to? 

Monk Unarmored Defense
 or 
Base AC 10 + DEX or Armor

**Comment by wilmcontreras** [comment]
Oh sorry, I didn’t realise there was setting for that. Found it—maybe have it appear under Things to be Done, if a character has levels in Monk/Barbarian?

Thanks!

**Comment by BahamutDragon** [comment]
Requested feature added. Since there is always the option of Mage Armor, choice of AC is forced upon character creation. As a fall back, the AC of Armor or Dex is enabled by default behind the scenes.
