### ISSUE TITLE
Errors with Sorcerer spell sheets

### ISSUE THREAD

**Issue by wilmcontreras** [BahamutDragon/pcgen#346]
After taking a few levels of Sorcerer, the Spells Known for lower level spells gets set to 0 (see attached).

![screen shot 2015-12-28 at 13 39 14](https://cloud.githubusercontent.com/assets/15095683/12025953/b5d5df74-ad68-11e5-9bff-81445d0ff7bd.jpg)
![screen shot 2015-12-28 at 13 32 48](https://cloud.githubusercontent.com/assets/15095683/12025954/b5f2a226-ad68-11e5-88bd-7c9b3708f675.jpg)

**Comment by wilmcontreras** [comment]
Cantrips are fine, in the L18 Sorcerer image, it appears as 0 because I didn't pick any, but I have 6 to pick from, which is correct.

**Comment by wilmcontreras** [comment]
Never mind, just saw it was a way to allow/enforce spell replacements.

**Comment by wilmcontreras** [comment]
Actually, I think it's still an error, in the sense that you should be able to take lower-level spells when you have higher-level slots available, but instead you get an error.

![screen shot 2015-12-28 at 17 38 33](https://cloud.githubusercontent.com/assets/15095683/12028511/0e708e9e-ad8d-11e5-94f0-9fbd0207bee2.jpg)

**Comment by BahamutDragon** [comment]
Is the checkbox "Allow Use of Higher Level Slots" checked on that screen?

**Comment by wilmcontreras** [comment]
Oh. Is that a new thing? I’d built a bunch of high-level characters and had never touched that option—maybe I unchecked it by mistake? 

Thanks man, I only got this error after the last update, so, I thought it was related.
