### ISSUE TITLE
Lesser Aasimar not selectable

### ISSUE THREAD

**Issue by BahamutDragon** [BahamutDragon/pcgen#349]
Per @FerretDave,

Unable to select Lesser Aasimar when Aasimar is selected.

**Comment by BahamutDragon** [comment]
All the various subraces are lumped under a base race called "Planetouched". Sorting through the tangles.

**Comment by FerretDave** [comment]
Ah, I see some logic in that, however it does lose clarity.. having all the
'lesser' races under their respective 'full' race makes life easier in the
long run.

**Comment by BahamutDragon** [comment]
Clarity loss is quite abundant. MM has Aasimar in the list, Races of Destiny, Forgotten Realms Campaign Setting, and Players Guide all have same variant of that version. The Races of Faerun is the only version with the Planetouched race. Which is confusing to say the least. 

My solution. Aasimar, Tiefling and Genasi will be base races, the user will select standard MM, Forgotten Realms, or Lesser for the first two, and the Genasi will have its four subrace selections. Planetouched though the common race, will just phase out. 4e and 5e make these races separate, which makes sense to me.

**Comment by FerretDave** [comment]
:-) thank you.

Races of Faerun is (I *think*) the actual forgotten realms book for Lesser
Aasimar, but I'm not going to push that, as it sounds like you've got your
hands full already!

No plans to move to 4e or 5e around here - if we move from 3.5e we'll go
Pathfinder.

**Comment by BahamutDragon** [comment]
Lesser Planetouched - PGtF

**Comment by BahamutDragon** [comment]
Tiefling and Genasi will be later. This should handle the Aasimar portion.

**Comment by FerretDave** [comment]
Fab, thank you.

I get errors on loading though, a couple of missing Ability categories? As
below.
Also, the Aasimar from Rac now needs to be disabled/removed as I get two
entries on the race tab for it.
I can select the 'Aasimar' from MM, and then can add the Lesser Aasimar

Thank you !

23:32:48.377 INFO main Main:145 Starting PCGen v6.05.06-dev
23:32:48.461 INFO main LanguageBundle:131 Initialising language bundle with
locale en_US.
23:33:15.727 INFO Thread-6 SourceFileLoader:518 Loading game 35e and
sources [Campaign: Petes Tuesday night game].
23:33:28.703 SEVERE Thread-6 AbilityCategory:719 Unconstructed Reference:
Ability Category Internal Race Traits ~ Genasi
23:33:28.703 SEVERE Thread-6 TrackingReferenceContext:119   Was used in
file:/F:/Data/GitHub/pcgen/data/35e/wizards_of_the_coast/campaign_settings/forgotten_realms/players_guide_to_faerun/pg_races.lst
in tokens: [plugin.lsttokens.AbilityLst]
23:33:28.703 SEVERE Thread-6 AbilityCategory:719 Unconstructed Reference:
Ability Category Internal Tiefling Subrace ~ Standard
23:33:28.703 SEVERE Thread-6 TrackingReferenceContext:119   Was used in
file:/F:/Data/GitHub/pcgen/data/35e/wizards_of_the_coast/core/monster_manual/mm_abilities.lst
in tokens: [plugin.lsttokens.AbilityLst]
23:33:29.289 LSTERROR Thread-6 CategoryToken:83 Ability Tiefling Subrace ~
Standard did not have a Category specified.  A Category is required for an
Ability. File was
file:/F:/Data/GitHub/pcgen/data/35e/wizards_of_the_coast/core/monster_manual/mm_abilities.lst

**Comment by FerretDave** [comment]
now only get:
22:56:36.761 SEVERE Thread-6 AbilityCategory:719 Unconstructed Reference:
Ability Category Internal Race Traits ~ Genasi

There is an ability for that commented out, but if I uncomment it it just
added more errors, so I backed off - apologies, need to refresh my memory
on how race/subrace and all the various abilities are configured...

**Comment by BahamutDragon** [comment]
completed - Lesser Planetouched now a template

**Comment by FerretDave** [comment]
Thank you for this, great work and much appreciated.

Now, I'm getting a negative level for my lesser aasimar, so it looks like
the: TEMPLATE:Level Adjustment +1 on the 'standard' Aasimar in mm_abilities
is not taking affect, so the override of TEMPLATE:Level Adjustment -1 on
the Lesser Planetouched in pg_templates is too much?

I can disable the latter, but cannot confirm whether the former is
appropriate for use elsewhere...

Cheers
Dave

**Comment by BahamutDragon** [comment]
Despite the tests not confirming this, I completely redesigned the level adjustment system. My tests show this is working too. Best,

**Comment by FerretDave** [comment]
Greetings,
My apologies, I still had the problem, had to rebuild the character from
scratch to fix it.
It must have been something saved into the pcg from prior configurations
(when Lesser was still a race maybe) that confused.

Got it working now, thank you.

I've just pushed some further updates to fix the other bits that now need
to reference the corrected race KEY

Cheers
Dave
