### ISSUE TITLE
[3.5] [Query] Is there any way to have the Duskblade's Arcane Attunement in the Spells tab?

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#350]
Maybe add an Arcane Attunement "Spell Level" to the list above the 0 slot or something like that?

Oh yeah, and other classes with similar features would probably like such things too.

**Comment by BahamutDragon** [comment]
SPELLS tag implemented for Duskblade.

The rest of the request is too open ended or vague.
