### ISSUE TITLE
Cleric's not getting full turn chart?

### ISSUE THREAD

**Issue by Nylanfs** [BahamutDragon/pcgen#352]
Heya, I just created a cleric and the turn chart doesn't seem to be working quite right. There isn't the hit die affected when check is 10+.
[Alejandro Matrone.zip](https://github.com/BahamutDragon/pcgen/files/83522/Alejandro.Matrone.zip)

**Comment by BahamutDragon** [comment]
Mate, I think this one is outside my influence. Cleric turn code in the core sets is identical to the rsrd cleric turn code that pcgen provides. Quick test shows the exact same issue with a generic rsrd created cleric of level 12 on the standard preview sheet.

The pcgen team is best to handle this issue.

Best,

**Comment by BahamutDragon** [comment]
Something to pass along. The interpreter does not like the .INTVAL at 0 or higher values, but requires it for negative math functions.

Here is the corrected code.

     <tr>
      <td align="center" class="font8"><b>Up to 0</b></td>
      <td align="center" class="font8"><b>${pcstring('((ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnLevel)-4).INTVAL')}</b></td>
      <td bgcolor="black" align="right"><font color="white" style="font-size: x-small">TURNING CHECK</font></td>
      <td class="border9" align="center"><b>1d20${pcstring('ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnCheck.INTVAL.SIGN.NOZERO')}</b></td>
     </tr>
     <tr>
      <td bgcolor="gray" align="center" class="font8"><b>1 - 3</b></td>
      <td bgcolor="gray" align="center" class="font8"><b>${pcstring('((ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnLevel)-3).INTVAL')}</b></td>
      <td bgcolor="black" align="right"><font color="white" style="font-size: x-small">TURNS/DAY</font></td>
      <td class="border9" align="center"><b>${pcstring('ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnTimes.INTVAL')}</b></td>
     </tr>
     <tr>
      <td align="center" class="font8"><b>4 - 6</b></td>
      <td align="center" class="font8"><b>${pcstring('((ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnLevel)-2).INTVAL')}</b></td>
      <td colspan="2" class="border" align="center"><font style="font-size: small">
        <@loop from=0 to=pcstring('ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnTimes.INTVAL')?number-1> &#9744; </@loop></font>
      </td>
     </tr>
     <tr>
      <td bgcolor="gray" align="center" class="font8"><b>7 - 9</b></td>
      <td bgcolor="gray" align="center" class="font8"><b>${pcstring('((ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnLevel)-1).INTVAL')}</b></td>
      <td colspan="2" rowspan="6" class="border8" valign="top">${pcstring('ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnNotes')}
     </tr>
     <tr>
      <td align="center" class="font8"><b>10 - 12</b></td>
      <td align="center" class="font8"><b>${pcvar('((ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnLevel))')}</b></td>
     </tr>
     <tr>
      <td bgcolor="gray" align="center" class="font8"><b>13 - 15</b></td>
      <td bgcolor="gray" align="center" class="font8"><b>${pcvar('((ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnLevel)+1)')}</b></td>
     </tr>
     <tr>
      <td align="center" class="font8"><b>16 - 18</b></td>
      <td align="center" class="font8"><b>${pcvar('((ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnLevel)+2)')+2}</b></td>
     </tr>
     <tr>
      <td bgcolor="gray" align="center" class="font8"><b>19 - 21</b></td>
      <td bgcolor="gray" align="center" class="font8"><b>${pcvar('((ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnLevel)+3)')}</b></td>
     </tr>
     <tr>
      <td align="center" class="font8"><b>22+</b></td>
      <td align="center" class="font8"><b>${pcvar('((ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnLevel)+4)')}</b></td>
     </tr>

**Comment by Nylanfs** [comment]
Hmm, so it's in the output sheet not a code issue. 
 
Paul A. Grosse 

    On Saturday, January 9, 2016 1:38 AM, Bahamut <notifications@github.com> wrote:
 

 Something to pass along. The interpreter does not like the .INTVAL at 0 or higher values, but requires it for negative math functions.Here is the corrected code. <tr>
  <td align="center" class="font8"><b>Up to 0</b></td>
  <td align="center" class="font8"><b>${pcstring('((ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnLevel)-4).INTVAL')}</b></td>
  <td bgcolor="black" align="right"><font color="white" style="font-size: x-small">TURNING CHECK</font></td>
  <td class="border9" align="center"><b>1d20${pcstring('ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnCheck.INTVAL.SIGN.NOZERO')}</b></td>
 </tr>
 <tr>
  <td bgcolor="gray" align="center" class="font8"><b>1 - 3</b></td>
  <td bgcolor="gray" align="center" class="font8"><b>${pcstring('((ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnLevel)-3).INTVAL')}</b></td>
  <td bgcolor="black" align="right"><font color="white" style="font-size: x-small">TURNS/DAY</font></td>
  <td class="border9" align="center"><b>${pcstring('ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnTimes.INTVAL')}</b></td>
 </tr>
 <tr>
  <td align="center" class="font8"><b>4 - 6</b></td>
  <td align="center" class="font8"><b>${pcstring('((ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnLevel)-2).INTVAL')}</b></td>
  <td colspan="2" class="border" align="center"><font style="font-size: small">
    <@loop from=0 to=pcstring('ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnTimes.INTVAL')?number-1> &#9744; </@loop></font>
  </td>
 </tr>
 <tr>
  <td bgcolor="gray" align="center" class="font8"><b>7 - 9</b></td>
  <td bgcolor="gray" align="center" class="font8"><b>${pcstring('((ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnLevel)-1).INTVAL')}</b></td>
  <td colspan="2" rowspan="6" class="border8" valign="top">${pcstring('ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnNotes')}
 </tr>
 <tr>
  <td align="center" class="font8"><b>10 - 12</b></td>
  <td align="center" class="font8"><b>${pcvar('((ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnLevel))')}</b></td>
 </tr>
 <tr>
  <td bgcolor="gray" align="center" class="font8"><b>13 - 15</b></td>
  <td bgcolor="gray" align="center" class="font8"><b>${pcvar('((ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnLevel)+1)')}</b></td>
 </tr>
 <tr>
  <td align="center" class="font8"><b>16 - 18</b></td>
  <td align="center" class="font8"><b>${pcvar('((ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnLevel)+2)')+2}</b></td>
 </tr>
 <tr>
  <td bgcolor="gray" align="center" class="font8"><b>19 - 21</b></td>
  <td bgcolor="gray" align="center" class="font8"><b>${pcvar('((ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnLevel)+3)')}</b></td>
 </tr>
 <tr>
  <td align="center" class="font8"><b>22+</b></td>
  <td align="center" class="font8"><b>${pcvar('((ABILITYALL.Special Ability.${turncount}.ASPECT=TurnType.ASPECT.TurnLevel)+4)')}</b></td>
 </tr>

**Comment by BahamutDragon** [comment]
Did you get this resolved on your end?

**Comment by Nylanfs** [comment]
I haven't seen it happen in the latest two versions so i think it's taken care of. Was just an issue in 6.04.01

Sent from Yahoo Mail on Android 
 
  On Wed, Jan 20, 2016 at 12:25 AM, Bahamut<notifications@github.com> wrote:   
Did you get this resolved on your end?
