### ISSUE TITLE
"Greater Flurry" Not Showing up (ph_abilities.lst | ph_classes.lst)

### ISSUE THREAD

**Issue by Dhraiden** [BahamutDragon/pcgen#356]
<h3>Issue: The level 11 Monk class feature 'Greater Flurry' does not show up, and can not be added, as of 6.05.03.</h3>

Problem File(s) & Line(s):
ph_classes.lst: No line entry for feature under Monk Block (line 180), has to be manually added:
<table>
    <tr>
        <td><pre><code>
11	ABILITY:Monk Class Feature|AUTOMATIC|Monk ~ Greater Flurry|!PREABILITY:1,CATEGORY=ACF,TYPE.MonkGreaterFlurry</code></pre></td>
    </tr>
</table>
ph_abilities.lst: Line 485 
<table>
    <tr>
        <td><pre><code>ABILITY:Monk Class Feature|AUTOMATIC|Monk ~ Greater Flurry|!PREABILITY:1,CATEGORY=ACF,TYPE.MonkGreaterFlurryofBlows|PREVARGTEQ:GreaterFlurry,1</code></pre></td>
    </tr>
</table>

TYPE should be just MonkGreaterFlurry

ph_abilities.lst: Line 504
<table>
    <tr>
        <td><pre><code>DEFINE:FlurryAttacks|0</code></pre></td>
    </tr>
</table>

FlurryAttacks|1 adds the extra, second attack granted by Greater Flurry.

**Comment by BahamutDragon** [comment]
This:

|!PREABILITY:1,CATEGORY=ACF,TYPEMonkGreaterFlurry

vs.
|
|!PREABILITY:1,CATEGORY=ACF,TYPE.MonkGreaterFlurry

|I will verify and patch it tonight.

-- 
~BD
https://github.com/BahamutDragon/pcgen
http://games.groups.yahoo.com/group/bd_games/

**Comment by BahamutDragon** [comment]
Removed the fake ability, all calculations are back in the parent ability where they belong.
