### ISSUE TITLE
[ dnd 3.5 ] Uncanny Trickster

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#357]
Uncanny Trickster is impossible to take - as it seems because of "at least 4 ranks in TYPE=Standard=8" outdated syntax.

And it seems it is impossible to select a class you want to continue progressing

**Comment by BahamutDragon** [comment]
Are you using an autobuild created after 	03/Jan/16 3:20 PM?

That issue was reported and the syntax approved according to this jira: https://pcgenorg.atlassian.net/projects/CODE/issues/CODE-2963

**Comment by BahamutDragon** [comment]
Just an update, all the prexxx for Uncanny Trickster were broken. Skill Tricks was not working for me nor was the Skill selections

I sent a quick update to Andrew, who updated the tracker referenced. I fixed the issues on my end.

**Comment by shadowfury** [comment]
I was not updating sources for a while, but didn't saw any changes in commits related to this, though might have missed some. Skilltricks worked for me, but one needed to save and reload character after investing skill points into SkillTricks. After that they do appear in features

Thanks for the fix, will test it out soon
