### ISSUE TITLE
Program freezes while attempting to load 3.5e MM kits

### ISSUE THREAD

**Issue by Skarrux156** [BahamutDragon/pcgen#358]
Just downloaded 6.07 dev, using the github desktop app to keep my files fresh, etc etc. Suddenly with 6.07 I can't load the sources. The entire app goes unresponsive while it's loading the kits supplied by the monster manual. Wasn't sure where to post this but hey, this seems like a good spot. I was having another issue that may be connected; I believe it was the kits from UA, but I'm not sure, that would cause PCGen to become unable to load the campaign. But that was no longer a problem because, well, the MM issue occurs before that as far as I can tell. If I need to post logs or anything please let me know.
Thanks,
 Michael

**Comment by BahamutDragon** [comment]
I have not had any positive experiences with the github app. 

Are you pulling the master branch files or the 6.04.01 branch files?

The pcgen program has a pcgen.log. Should be an error or two listed in there. Can you post that here?

Best,

**Comment by Skarrux156** [comment]
What would you prefer instead as a client? I'm open to suggestions.

And I'm pulling master. I double checked to make sure I wasn't getting 6.04.

I just opened the log file and it's got nothing exept for information about what language it's being used in....AKA nothing about any errenous activity.

**Comment by Skarrux156** [comment]
I'm still not able to make any headway with PCGen...I'm not sure what to even look for in the event log.

**Comment by BahamutDragon** [comment]
That tells me you are running out of memory. Loading pretty much every available book will do that. You need to allocate more memory.

`Dungeons & Dragons - Core Books, Arms and Equipment Guide, Book of Exalted Deeds, Book of Vile Darkness, Cityscape: An Essential Guide to Urban Adventuring, Complete Adventurer, Complete Arcane, Complete Champion, Complete Divine, Complete Mage, Complete Warrior, Deities and Demigods, Dragon Magic, Drow of the Underdark, Dungeon Master's Guide II, Dungeonscape, Epic Level Handbook, Expanded Psionics Handbook, Fey Feature, Fiend Folio, Fiendish Codex II, Frostburn, Heroes of Horror, Libris Mortis: The Book of the Dead, Magic Item Compendium, Magic of Incarnum, Miniatures Handbook, Monster Manual II, Player's Handbook II, Sandstorm, Savage Species, Spellbook Archive, Spell Compendium, Stormwrack, The Mind's Eye, Tome of Battle: The Book of Nine Swords, Tome of Magic, Unearthed Arcana (Complete), Weapons of Legacy, Complete Psionic, Complete Scoundrel, Draconomicon, Player's Guide to Faerun, Champions of Ruin, Champions of Valor, City of Splendors: Waterdeep, Lost Empires of Faerun, Magic of Faerun, Monster Compendium: Monsters of Faerun, Races of Faerun, Shining South, Unapproachable East, Underdark, Eberron Campaign Setting, Races of Destiny, Races of Eberron, Races of Stone, Races of the Dragon, Races of the Wild`

If you use a windows machine, you can use this to run pcgen. This is best as a .bat file.

`java.exe -Dswing.aatext=true -jar pcgen.jar`

I recommend loading only the books you actually use during your games. Reduces the memory required. Fixing the errors will help a bit. 

Best,

**Comment by Skarrux156** [comment]
Oh man, I feel dumb. Thanks man. I'll get right on that.

**Comment by BahamutDragon** [comment]
Further - https://git-scm.com/download/gui/linux for a list of git clients

I prefer sourcetree and tortoisegit for normal operations.
