### ISSUE TITLE
Issue with Tome of Battle

### ISSUE THREAD

**Issue by Ethanrat** [BahamutDragon/pcgen#359]
There appears to be a issue with initiator level when mutliclassing. When taking a level in a initiator class you add 1/2 a level to your initiator level for every level you have in another class (pg. 39 ToB under Initiator Level). I attempted to build a character earlier but this feature seemed to not be working.

**Comment by Skarrux156** [comment]
I have a similar issue. Crusader would not gain initiator levels either....there was also an issue with ToB prestige classes not adding initiator levels a while back but that was patched and implemented. It seems to be a case by case scenario for now until we figure out what's going on with ToB.

**Comment by BahamutDragon** [comment]
Fixes Missing Combat and Saves for a few prestige classes
Fixes the formula to grant the same initiator levels, including non-initiator classes correctly
Moves Initiator class formulas into abilities
