### ISSUE TITLE
Single-Class Crusader not receiving first level stances/maneuvers

### ISSUE THREAD

**Issue by Skarrux156** [BahamutDragon/pcgen#366]
Selecting Crusader as my 1st class for 1 level doesn't do much for it either.
I'm not qualified for any stances/maneuvers. Should I attach the character file?

**Comment by BahamutDragon** [comment]
Mate,

Feats and Abilities tab?

What message is it giving?

Best,

-- 
~BD
https://github.com/BahamutDragon/pcgen
http://games.groups.yahoo.com/group/bd_games/

**Comment by Skarrux156** [comment]
Attaching screens of both stance and maneuver output window.
![screenshot_2](https://cloud.githubusercontent.com/assets/12634401/12601092/ffaa1b26-c463-11e5-82d5-790a1767d796.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/12634401/12601091/ffa8733e-c463-11e5-89f2-592975d99023.png)

**Comment by BahamutDragon** [comment]
Mate,

Do you have the latest updates?

3a5ad68

or the Tome of Battle update? 2115cea

Best,

On 1/26/2016 5:35 PM, Skarrux156 wrote:
>
> Attaching screens of both stance and maneuver output window.
> screenshot_2
> <https://cloud.githubusercontent.com/assets/12634401/12601092/ffaa1b26-c463-11e5-82d5-790a1767d796.png>
> screenshot_3
> <https://cloud.githubusercontent.com/assets/12634401/12601091/ffa8733e-c463-11e5-89f2-592975d99023.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BahamutDragon/pcgen/issues/366#issuecomment-175333032>.
>

-- 
~BD
https://github.com/BahamutDragon/pcgen
http://games.groups.yahoo.com/group/bd_games/

**Comment by Skarrux156** [comment]
Fixed.
Smartgit wasn't working right, somehow - not quite sure how. Just ended up completely redoing it all. Cloning the repo again, etc.

I feel dumb even though I had the right repo cloned and had tried pulling it again already.


Thanks,
Michael
