### ISSUE TITLE
5e Update?

### ISSUE THREAD

**Issue by MatchesxMalone** [BahamutDragon/pcgen#367]
I recently downloaded the D&D 5e update from http://pcgen.org/2016/01/13/i-hear-you-like-5e-so-do-we/

Upon installation of the new version of PCGen and loading the 5e information, I noticed that not everything is there. I'm working on a few different builds and I'm curious if there's another place to download it from or if I'm able to download what is here on GitHub somehow? Thanks in advance!

**Comment by Skarrux156** [comment]
Hey there.

What seems to be missing exactly of note?

**Comment by BahamutDragon** [comment]
The 5e material supplied by the pcgen team is the SRD5. It lacks quite a bit as you have seen. You can grab the repository here which holds the full versions. The instructions on obtaining this information and using it in pcgen is on the main page here: https://github.com/BahamutDragon/pcgen

**Comment by MatchesxMalone** [comment]
A lot of archetypes were missing. There isn't a way to edit skills. I don't
know if that is just by design though. In past versions, I was able to add
or subtract skill points.

**Comment by MatchesxMalone** [comment]
I'm very new to github.

**Comment by BahamutDragon** [comment]
Mate,

1. The concept of skill points does not exist in 5e. For the skills, all you get is your stat bonus, and then if you selected a skill as proficient, it gains the proficiency bonus. Nothing to alter there.

2. The PCGen team uses the official SRD5. I include the actual books. To explain this difference I will quote from their own guru regarding this matter:

> The Player's Handbook and the SRD5 are completely different animals. I cannot include anything from outside the OGL of the SRD5 documentation.
> The SRD5 has enough information to get you started, but unlike the SRD and RSRD of 3rd and 3.5e, these are not full copies missing just the closed content. Instead, these are pared / redacted documents that have enough to get you interested in the game, and if you want more, you need to purchase the books.
> 
> If you compare the SRD5 against the Player's handbook, you'll also note that each class is represented, but only has a single Archetype choice at level 3, there is only one single Feat to select, there is only one background. They include all the races, but only include a single subrace selection. The SRD also removes several popular attack spells.
> 
> In short, the SRD5 is the same game system, but less options than the official core books.
> 
> In any case, this is not a bug, but an imposed restriction. I cannot act outside the confines of the license.

If you want all the archetypes, backgrounds, subraces and feats, then grab this repository, and follow the directions to get it working for you.

Best,

**Comment by MatchesxMalone** [comment]
I think I actually got it figured out earlier today. Thank you for
responding so quickly to my questions. It is greatly appreciated. I'm just
getting into 5e after being used to 3.5 and Pathfinder. Thanks for your
hard work!
