### ISSUE TITLE
Genasi not functioning correctly

### ISSUE THREAD

**Issue by Skarrux156** [BahamutDragon/pcgen#368]
The genasi cannot select a planetouched region as their home region, due to the requirement being stated as "either ( race: Planetouched (Aasimar) at least 1, race: Planetouched (Tiefling) at least 1, race: Planetouched (Genasi) at least 1 )"

They are also not getting racial ability score adjustments.

At this time I know for a fact that the tiefling are functioning correctly.

Will look into the code and bring back any finds I make.

**Comment by BahamutDragon** [comment]
Fixed
