### ISSUE TITLE
[ dnd 3.5 ] Hexblade Caster level incorrectly coded (two requests for conditionals)

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#371]
- Hexblade does not have his Resistance ability (that adds Cha bonus to saves vs spells and spell-like abilities)
- Hexblade does not have correct caster level (if Hexblade is 4th or higher level, he should have caster level equal to 1/2 oh his hexblade level)  
Also feat Force of Personality (CAdv) does not shows in conditional bonuses

**Comment by BahamutDragon** [comment]
The first and third issue appear to be requests for Conditional inclusion. 

The second sounds like a bug.

**Comment by shadowfury** [comment]
Well, Resistance is basically on of the most important Hexblade ability (aside from Hexblade curse), and it is never mentioned - not in abilities section and not in Conditional section

For the third - well basically that is all that feat gives and it is not shown anywhere, it's description also does not describe what you get against what spells. So it would have been quiet nice seeing that info

**Comment by BahamutDragon** [comment]
Changed Arcane Resistance class feature to display the feature name, and not the bonus. Changed the ASPECT to the proper conditional.

**Comment by shadowfury** [comment]
Thanks!

**Comment by shadowfury** [comment]
It seems that even after this fix hexblade 8 still has 1 as his caster level (instead of 4) and in conditional modifiers section i have +1 vs spells and spell-like abilities instead of actual charisma bonus ( +7).

Do i need to create a new character for this fix to work?

**Comment by BahamutDragon** [comment]
Was missing the crucial DEFINE to get the correct value.
Grab the update from either master or 6.06.x
