### ISSUE TITLE
Planetouched / Genasi broken

### ISSUE THREAD

**Issue by guyrish** [BahamutDragon/pcgen#379]
The new Planetouched / Genasi race revision has broken a few things...

Example: Genasi (Fire Genasi) race fails to match up regional feats like Bloodline of Fire (Player's Guide to Faerun) which does not correctly recognize the Genasi race. Likewise with other feats like Healing Flames (Races of Faerun) which are broken as well.

Seems like is a bigger impact that just sorting out a race/subrace adjustment in one file. A bigger sweep through the books is needed.
Player's Guide to Faerun
   - pg_feats
   - pg_races
   - pg_templates
Races of Faerun
   - rac_feats

Rollback 'til fixed?

**Comment by BahamutDragon** [comment]
That should resolve the issues.
