### ISSUE TITLE
Spells not showing

### ISSUE THREAD

**Issue by karlomango** [BahamutDragon/pcgen#386]
For the 3.5e the spells will not show at all for any class, I am using this sources.
 Arms and Equipment Guide
Complete Mage
Dungeons & Dragons - Core Books
Expanded Psionics Handbook
Monster Manual II
Monster Manual III
Player's Handbook II
Spellbook Archive
Spell Compendium

**Comment by BahamutDragon** [comment]
Mate,

That is a bit puzzling. 

Questions:

- Are you using the 6.04.01 data branch or the master branch when you attempt to make a character?
- Are you observing a red stop sign in the bottom right corner of the pcgen screen?
- Do you have any errors logged in the pcgen log?

**Comment by karlomango** [comment]
Hello,

Yeah I'm not quite sure whatever I am a beginner with the system I am going
in through the the advanced method, the thing is I do get an error when I
try to load too many of the files,specifically any of the complete series
 like complete adventurer and divine

**Comment by BahamutDragon** [comment]
I see.

Can you grab the latest version of pcgen and see if that corrects the problem?

**Comment by BahamutDragon** [comment]
Unable to reproduce using pcgen version 6.06.00RC2

**Comment by karlomango** [comment]
Hello,

Very sorry for the late reply, I have the latest version of PCgen but like
I mentioned I'm still new to the system, now when you set up the location
for the files where are you putting them? I just placed the folder in my
desktop and placed the location for the PCGen homebrew data directory as
the master data and the books are showing up just no spells, I have also
attached a picture of what I am stating so that it hopefully clarifies
things.

**Comment by BahamutDragon** [comment]
Hi mate,

Picture not appearing.

Simple locations:
pcgen is installed at 
c:\pcgen
homebrew is installed at
c:\pcgenhomebrew

You can get fancy if you do a lot of house rules or play with a lot of the pcgen project

c:\xtools\pcgen.
pcgen
homebrew
vendordata

Drop the houserules in vendordata, have my sets in homebrew, and the main program in pcgen.

Or if you do external hard drives or outside of c drive, 
z:\rpgtools\
pcgen
homebrew
vendordata

The location does not actually matter. Nothing you have mentioned lends itself to a file not found issue. If you can load the additional books in the advanced load window then you should have access to the spells. The only block to using spells that pcgen enforces is a minimal stat value for the primary casting stat. d20 rules default to 10 + spell level to use. If you create a character with a stat value of 9 or less, then you will have zero spells showing on your character. This does not appear to update until you reload or level up the character.

Wizard needs Intelligence, Bards and Sorcerers use Charisma, Divine casters typically use Wisdom.

A good method to see if it is an issue, try creating a regular pcgen default supplied rsrd wizard. If the spells issue is present there, then that is beyond me and you need to contact the pcgen developers.

Upload your picture to a site that hosts pictures and link to it here.

Best,
