### ISSUE TITLE
[dnd 3.5] Complete Mage, Metamagic School Focus, should be available to specialists

### ISSUE THREAD

**Issue by marcalff** [BahamutDragon/pcgen#387]
Using branch 6.04.01
Game mode 35e, Complete Mage,
Feat: Metamagic School Focus,

According to WoC CM page 45, the prerequisites are:
- (a) Spell Focus (chosen school)
OR
- (b) specialist wizard (chosen school)

I tried to pick this feat as a transmuter lvl 1, and could not, because it seems only (a) is implemented.
(b) is not working.

**Comment by BahamutDragon** [comment]
Mate,

(b) is not implemented. Will require some work though.

**Comment by BahamutDragon** [comment]
Fixed
