### ISSUE TITLE
5e - Magic Item Attunement

### ISSUE THREAD

**Issue by Agnard** [BahamutDragon/pcgen#398]
Magic items don't change any stats after attuned.
ex. Ring of Protection attuned doesn't improve AC or Saving Throws

**Comment by BahamutDragon** [comment]
My group has not needed this yet. The pdf I have is not copy and paste friendly. Adding the proper changes in will take some time.

Best,

**Comment by BahamutDragon** [comment]
Did you need anything in particular now? Going through and adding the items in the correct spot will be a bit.

**Comment by BahamutDragon** [comment]
- [ ] Add Abilities which contain the correct bonuses when attuned
- [ ] Make sure SPROP triggers correct information when attuned

**Comment by Agnard** [comment]
Right now only a Ring of Protection and a Ring of Jumping (the later doesn't change anything just adds Jump spell as bonus action targeting self).

Sending a - hopefully - friendlier pdf to your email.

**Comment by BahamutDragon** [comment]
That should cover the request. All items that are attuned have at the minimum a descriptive that will change when attuned. Factual numerical changes such as AC or attacks were added.

**Comment by mkeith01** [comment]
how do you attune items in pcgen. I dont see an option to do so.

**Comment by BahamutDragon** [comment]
Have the item equipped, then go to the feats & abilities tab, look at the character sub tab. Select the group Item Attunement, your item will be available for selection from the list.
