### ISSUE TITLE
[Request] +3 on class skills for 3.5

### ISSUE THREAD

**Issue by Unicorn437** [BahamutDragon/pcgen#401]
I know you told me before, but I can't find it anymore :(
We're using Pathfinder skill progression for 3.5 and I can't remember how to do the [is class skill] +3 trick and how to remove the skill limits. Mind to enlighten me?
I'd also love to put all that into one houserule, but have no experience how to do that. So far I changed the  mscinfo.lst of the 3.5 gamemode so that it states
 SKILLMULTIPLIER:1
SKILLCOST_EXCLUSIVE:1
#SKILLCOST_CROSSCLASS:SKILL_COST_CROSSCLASS
SKILLCOST_CROSSCLASS:1  
SKILLCOST_CLASS:1

**Comment by BahamutDragon** [comment]
Includes gameMode and rule is found in the homebrew requests data set. Covers skills found in the PH.
