### ISSUE TITLE
[dnd 3.5] [6.06.00 RC2] Maester not getting bonus item creation feats.

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#405]
Maester (CAdv) does not provide bonus feat selection at first level of this class

**Comment by BahamutDragon** [comment]
the above text does not match the initial post.

> Warlock 9 character can not take Maester for CAr as prestige class (it requires arcane caster 5) and for some reason warlock 9 is not considered as arcane caster in this case

I spent yesterday looking into the issue and then see the text is changed. Please do not alter the issue after submission. If it is a mistake, say so and close it.

**Comment by shadowfury** [comment]
Thanks, sorry mate, gonna avoid edits next time
