### ISSUE TITLE
[3.5] Dragon Magic Dragonfire Adept doesn't get Dragontouched Bonus Feat properly

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#440]
Title

The Class Features section has an entry that says it should receive the feat accurately but in the Feats section it doesn't show up like bonus feats usually do.

(Using PCGen 6.06 and the Master branch if it matters)

**Comment by GamerGoddessDin** [comment]
No Breath Effect selector is available with the second level in the class either. Once again there is an entry for the feature in the Class Feature's section for it though.

**Comment by GamerGoddessDin** [comment]
I'm pretty sure the Draconic Skin Feat should add to the Scales class feature before the comparison between it and the Draconic Template's Natural Armor bonus resulting in a total of a +3 Nat Armor between Class Levels 2 and 8 but it's only showing a 2.

**Comment by BahamutDragon** [comment]
Fixed by @myrlyn
