### ISSUE TITLE
[3.5] Force of Personality is missing from Complete Adventurer

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#441]
Title

PCGen 6.06, Master Branch

**Comment by myrlyn** [comment]
the ABILITY: tag to includes feats is missing in the pcc file

**Comment by BahamutDragon** [comment]
@myrlyn for the issue to pick up the fixes, github looks for "#n" in the commit and PR requests. I usually include the whole header to make catching the fix.

" [3.5] Force of Personality is missing from Complete Adventurer #441 "
