### ISSUE TITLE
[3.5] Dragon Magic Dragonfire Adept's Scales feature bug

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#454]
At Level 2 the Dragonfire Adept should have a +2 Natural Armor bonus from the Scales feature but they're only being given a +1 Natural Armor bonus.

**Comment by BahamutDragon** [comment]
Fixed formula. Sets to 2 instead of 1.8 at second level.

**Comment by GamerGoddessDin** [comment]
Pulled the fix from Master, restarted PCGen 6.06 and the Natural Armor Bonus is still only a +1. I even made a fresh character without any other sources of Natural Armor to be sure it wasn't a misinteraction.

**Comment by BahamutDragon** [comment]
It appears github has made some changes. I have not altered any settings.
