### ISSUE TITLE
[3.5] [Request] Thistledown Padding

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#457]
An optional crafting component from Races of the Wild.

**Comment by BahamutDragon** [comment]
Not sure what the request here is.

Armor:
`Thistledown				PROFICIENCY:ARMOR|Padded		TYPE:Container.Armor.Light.ArmorProfLight.ArmorType_Light.Suit.Nonmetal							CONTAINS:UNLIM|Armor Crystal=1	COST:255	WT:5						ACCHECK:0		EQMOD:CLOTH.MWORKA							MAXDEX:10				SOURCEPAGE:RotW 168	SPELLFAILURE:0																																								BONUS:COMBAT|AC|1|TYPE=Armor					BONUS:SKILL|Hide|2|TYPE=Circumstance
`
Only thing I can do with that is change the name to the chart version of 'Thistledown Padded'

> Thistledown:
>  This lightweight fabric gets its name from
> its soft feel and dove-gray color. Elves have made padded
> armor from this material for centuries, and it is well liked
> by arcane spellcasters.
> Thistledown padded armor weighs only half as much as
> normal padded armor. It grants its wearer a +2 circumstance
> bonus on Hide checks in areas of darkness or shadowy
> illumination, as it blends in with the dim background. It is
> treated as masterwork armor (the masterwork cost is included
> in the armor’s given cost).

The other entry is the equipment modification version:
`Thistledown Suit				KEY:Thistledown Suit			TYPE:Armor				COST:250	VISIBLE:QUALIFY	SOURCEPAGE:p.168	PREMULT:1,[PRETYPE:2,Light,Metal],[PRETYPE:1,Medium,Heavy]						PRETYPE:1,Armor																																																																			BONUS:EQMARMOR|ACCHECK|-1	BONUS:EQMARMOR|SPELLFAILURE|-5
`

> Thistledown 
>  Suit: Long used in the creation of lightweight
> padded armor by elven crafters, the silken fabric
> known as thistledown (see Special Armor Materials, below)
> has recently been used in other armors as well by inventive
> halfling armorsmiths.
> Any armor that normally incorporates an underlying
> layer of quilted fabric (including chain shirts, as well as
> any medium or heavy armor normally made of metal) can
> substitute a thistledown suit for the normal layer of fabric.
> This alteration increases the armor’s armor check penalty
> by 1 (because of the added bulk) but reduces its arcane spell
> failure chance by 5% (because the quilted thistledown makes
> the armor less restrictive for somatic gestures).
> A thistledown suit requires a DC 15 Craft (tailoring) check
> to create and costs 250 gp. It adds no weight to a suit of armor.
> 
>

**Comment by GamerGoddessDin** [comment]
It's already there? It wasn't showing up in the list for customizing a Chain Shirt last night/this morning...

**Comment by GamerGoddessDin** [comment]
Just checked again, it's not appearing for me when customizing either Chain Shirts or Full Plate. Both of which should qualify for having Thistledown applied to them.

**Comment by BahamutDragon** [comment]
Works when the file is actually loaded. Pull the updated changes.

**Comment by GamerGoddessDin** [comment]
Don't you just hate it when you forget to do the simplest yet most important thing like Include a key library for your project?
