### ISSUE TITLE
DM Fiat Bonus Feat/Language/etc.

### ISSUE THREAD

**Issue by ccrvincent** [BahamutDragon/pcgen#468]
The PCGen 3.5 data sets allow recording that the GM awarded bonus feats and skill ranks/modifiers. (See https://pcgenorg.atlassian.net/browse/DATA-2251 )

Would it be too much to ask for a similar feature in the BahamutDragon set?

**Comment by BahamutDragon** [comment]
As requested, now includes everything that the PCGen team includes from their Pathfinder set:

- +1 Bonus Feat	
- +1 Skill Rank	
- +1 Skill Bonus	
- +1 Hit Point	
- +1 Spell per Day	
- +1 Spell Known	
- Add Language

**Comment by ccrvincent** [comment]
Thank you so much!  Nice to have a record as to why those values don't add up instead of just being "wrong".

**Comment by GamerGoddessDin** [comment]
Having the ability to add extra available options to any choice pool might be nice. Some of them like Invocations can be worked around by just using the bonus feat option to give them the Extra Invocation feat but others like the Dragonfire Adept's Breath Effects don't have such feats available.

(If it would be a lot of work it's no big deal.)
