### ISSUE TITLE
[5e] [Beast Master] Cannot choose Companion Animal

### ISSUE THREAD

**Issue by vbigiani** [BahamutDragon/pcgen#469]
As per the title, I'm creating a 5e Beast Master ranger, but cannot seem to be able to choose his companion beast.

**Comment by BahamutDragon** [comment]
Only able to support the PH races, MM races are not finished.

**Comment by BahamutDragon** [comment]
Now supported:
Bat
Black Bear
Boar
Cat
Mastiff
Mule
Owl
Panther
Poisonous Snake
Rat
Raven
Wolf

**Comment by vbigiani** [comment]
Thanks for the prompt response. However, attacks and skill bonuses appear to be computed incorrectly. Test case: Panther on a level 5 ranger (+3 proficency).

attack should be +4 +prof to hit (total +7), damage 1d6+2 + prof (claw) or 1d4 + 2 + prof (bite), instead if I equip an "Unarmed Strike" I get +9 to hit, 1 + 2 

Perception and Stealth should be respectively +4 + prof and +6 + prof, I get +2 to both.

**Comment by BahamutDragon** [comment]
Create a new issue please.
