### ISSUE TITLE
Book of Exalted deeds

### ISSUE THREAD

**Issue by SaintSteel** [BahamutDragon/pcgen#470]
There are some issues with Prestige Classes and templates. The 1st issue is The Fist of Raizel is correct with the information, just not the reqs to take it. and I cannot seem to find the Saint template to add on to my char, I would love to use the PCgen to keep track of things but as of now I have to get up monk levels to make it into a paladin class :(

**Comment by BahamutDragon** [comment]
You mention multiple issues, but I only see the one report... 

> There are some issues with Prestige Classes and templates.  The 1st issue...

Was there more or is that it?

**Comment by SaintSteel** [comment]
Oh I did not know I had to make a report for each error sorry. 1 which was
the first one was the prestige class error. 2 the second one is the same
template was not accessible as it was not on the list of templates

**Comment by BahamutDragon** [comment]
Different issues should equal different reports

Same issue, with multiple points of problems, one report.

**Comment by BahamutDragon** [comment]
Issue 1 is resolved. The Saint Template does not seem to be related to the Fist Prereqs. That would be a separate report/request.

**Comment by BahamutDragon** [comment]
Saint Template added

**Comment by SaintSteel** [comment]
Dude you are awesome with the fist of raziel and that I'm set do I have to
re-download the master zip?

**Comment by BahamutDragon** [comment]
Why would you download the entire master again? Set up git and save bandwidth. The instructions to do that are on the main page. Though if you are in a hurry, you can certainly grab master as a zip. (git is better, practically instant update).

**Comment by SaintSteel** [comment]
Thank you I will have to look for that, I'm not to computer savvy I'm
pretty old and used to the paper and pencil way this whole new pcgen thing
is kind of knew I didn't even try it out when 3.5 first came out but people
are tell me how I'm saving it is
