### ISSUE TITLE
[dnd 3.5] Core, equipement, bracers of armor +2 to +8 gives only +1 AC

### ISSUE THREAD

**Issue by marcalff** [BahamutDragon/pcgen#472]
File data/35e/wizards_of_the_coast/core/dungeon_masters_guide/dmg_equip.lst,
entries for "Bracers or Armor +2" to +8 all have:
BONUS:COMBAT|AC|1|TYPE=Armor

Expecting AC|2, AC|3 ... AC|8

**Comment by BahamutDragon** [comment]
Master is unaffected; 6.06 is missing the patch.

**Comment by BahamutDragon** [comment]
Fixed Sortkey for both.
