### ISSUE TITLE
Fist of Raizel

### ISSUE THREAD

**Issue by SaintSteel** [BahamutDragon/pcgen#473]
Fist of Raziel Type: Prestige   HD: d10   Spell Type: null   Base Stat: None Requirements: Alignment exactly LG and Base Attack at least 6 and **at least 3 of ( at least 1 Power Attack FEAT, at least 1 Servant of the Heavens FEAT )**( that part is in red) and all of ( at least 5 ranks in Diplomacy, at least 5 ranks in Knowledge (religion) ) Source: Wizards of the Coast - Book of Exalted Deeds, p.62

In the book it says only need the power attack, and Servant of the heaves for the Feats, It will not let me take the class I meet every other pre req

**Comment by BahamutDragon** [comment]
Fixed. 3 should be a 2
