### ISSUE TITLE
Marshal Class

### ISSUE THREAD

**Issue by SaintSteel** [BahamutDragon/pcgen#474]
I loaded the Minatures Book in looking for the Marshal class did not find that in the class section

**Comment by BahamutDragon** [comment]
Mate,

The source book status list:  https://github.com/BahamutDragon/pcgen/wiki/Book-Statuses

Has Miniatures Handbook listed as - "Miniatures Handbook 20% (Spells only)"

Only the spells exist currently. Do you need it today? I can have a skeleton version in 20 minutes, but the numbers and actual bonuses will be a bit longer.

**Comment by BahamutDragon** [comment]
Class added

**Comment by SaintSteel** [comment]
Wow thank you very much :-) I will make sure to spread GitHub around my
friends
