### ISSUE TITLE
[5e] [Beast Master] Incorrect stats for Beastmaster Companion

### ISSUE THREAD

**Issue by vbigiani** [BahamutDragon/pcgen#477]
Attacks and skill bonuses appear to be computed incorrectly for the Beastmaster Companion.

Test case: Panther on a level 5 ranger (+3 proficency).

The PHB panther gets:
12 AC
Claw attack at +4 to hit for 1d6+2 damage
Bite attack at +4 to hit for 1d4+2 damage
+4 Perception (as if it had Proficiency, given +2 WIS)
+6 Stealth (as if it had Proficiency and Expertise, given +2 DEX)
no special saves

The PHB states "Add your proficiency bonus to the beast’s AC, attack rolls, and damage rolls, as well as to any saving throws and skills [the beast] is proficient in". As such, I expected the following stats:

15 AC
Claw attack at +7 to hit for 1d6+5 damage
Bite attack at +7 to hit for 1d4+5 damage
+7 Perception (as if it had Proficiency, given +2 WIS)
+9 Stealth (as if it had Proficiency and Expertise, given +2 DEX)

instead, after equipping an Unarmed Strike, I got the following stats:

15 AC
Unarmed attack at +9 to hit for 1+2 damage
+2 Perception
+2 Stealth

**Comment by BahamutDragon** [comment]
Panther fixed, other companions will need more work.

**Comment by Lithial** [comment]
I'm working on that. If you look at my fork i've got the basic stats for all the companions that i started last night
