### ISSUE TITLE
[dnd 3.5] Core, equipement, Belt of Giant Strength +6 gives only +4 STR

### ISSUE THREAD

**Issue by marcalff** [BahamutDragon/pcgen#478]
File data/35e/wizards_of_the_coast/core/dungeon_masters_guide/dmg_equip.lst,
entries for "Belt of Giant Strength +6" has:
BONUS:STAT|STR|4|TYPE=Enhancement

Expecting STR|6
Verified in master and 6.06.x

**Comment by BahamutDragon** [comment]
Fixed
