### ISSUE TITLE
[d&d 3.5] [Magic Of Incarnum] Double Chakra can't be taken more than once.

### ISSUE THREAD

**Issue by Taiolu** [BahamutDragon/pcgen#482]
The double chakra feat is supposed to be able to be taken multiple times, one time for each chakra. (And only maximum one per chakra)

I've tried adding to my own version:
`STACK:NO	MULT:YES CHOOSE:Totem|Crown|Feet|Hands|Arms|Brow|Shoulders|Throat|Waist|Heart|Soul`

But I think something else needs to be done as it isn't applying.

**Comment by BahamutDragon** [comment]
There, give that a go mate. (master branch)
