### ISSUE TITLE
[dnd 3.5] Complete Champion, Church, implement The Ruby Temple

### ISSUE THREAD

**Issue by marcalff** [BahamutDragon/pcgen#483]
Feature request.
Implement basic support for churches.
Implement The Ruby Temple church, p.20

**Comment by BahamutDragon** [comment]
Took some time: Here is a sample of re-using the same category and using the KEY and TYPE: http://pastebin.com/KJM0XLsY

**Comment by marcalff** [comment]
Got it. Reworking the patch.

**Comment by BahamutDragon** [comment]
Much better.
