### ISSUE TITLE
Aasimar race to be in PC section at A.

### ISSUE THREAD

**Issue by SaintSteel** [BahamutDragon/pcgen#493]
Please to add aasimar race from mm1 thank you

**Comment by BahamutDragon** [comment]
Mate,

MM1 (3.5e) already includes 'Aasimar'. If not D&D 3.5e, please be a
little more specific.

Under Halfling and before Tiefling on the summary page, or in the "p"
section on the race tab, though the Search feature brings it right up.

Best,

On 4/26/2016 3:32 PM, SaintSteel wrote:
>
> Please to add aasimar race from mm1 thank you
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BahamutDragon/pcgen/issues/493>
>

-- 
~BD
https://github.com/BahamutDragon/pcgen
http://games.groups.yahoo.com/group/bd_games/

**Comment by FerretDave** [comment]
That reminds me, it's 'Planetouched (Aasimar)', so appears under 'P' in the
ordering, things like that always annoyed me and is now why I always search
instead of scrolling through the alphabetical listings...

Would be nice if there was a way to get it appear under A, possibly even
*as well as* P... but that would be an enhancement for the program.

On 26 April 2016 at 23:58, Bahamut <notifications@github.com> wrote:

> Mate,
>
> MM1 (3.5e) already includes 'Aasimar'. If not D&D 3.5e, please be a
> little more specific.
>
> Under Halfling and before Tiefling on the summary page, or in the "p"
> section on the race tab, though the Search feature brings it right up.
>
> Best,
>
> On 4/26/2016 3:32 PM, SaintSteel wrote:
> >
> > Please to add aasimar race from mm1 thank you
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/BahamutDragon/pcgen/issues/493>
> >
>
> --
> ~BD
> https://github.com/BahamutDragon/pcgen
> http://games.groups.yahoo.com/group/bd_games/
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BahamutDragon/pcgen/issues/493#issuecomment-214913025>
>



-- 
            oxxxxxxx{;;;;;;;;;;;;;;;;;;;;;;;;;;;;;>

**Comment by BahamutDragon** [comment]
Implemented

**Comment by SaintSteel** [comment]
Thank you sir
