### ISSUE TITLE
5e: Possible to load conflicting core rule books (Play test, Basic Rules, PH and Multiset Core Rule Books)

### ISSUE THREAD

**Issue by matteocorti** [BahamutDragon/pcgen#497]
I have a strange issue: if I use the PHB I get almost anything but some skills are missing. I can for example choose two "fighter skills" but they are not shown in the character sheet.

If I load the SRD, than I have the sills but I also have a lot of "double" stuff (for example a base AC of 20).

**Comment by BahamutDragon** [comment]
Mate,

I do not handle the SRD, that is a pcgen issue, which needs to be brought to the pcgen maintainers attention. I only deal with the items I have available here.

You need to be more specific on the fighter skills, the two I selected show up just fine.

**Comment by matteocorti** [comment]
OK than, it is correct that I have not to load the SRD.

I have here an example:

[Adalwulf PHB.pcg.txt](https://github.com/BahamutDragon/pcgen/files/240090/Adalwulf.PHB.pcg.txt)

I am using the following sources

    CAMPAIGN:Dungeons & Dragons 5e - Core Books|CAMPAIGN:Basic Rules 5e|CAMPAIGN:5e - Player's Handbook|CAMPAIGN:D&D Next Play Test

 * I get 1 "Skill Proficiency" but the list is empty
 * I choose two fighter skills but they are not shown in the character sheet

```
ABILITY:Fighter Skill|TYPE:NORMAL|CATEGORY:Internal|KEY:Animal Handling|TYPE:
ABILITY:Fighter Skill|TYPE:NORMAL|CATEGORY:Internal|KEY:Intimidation|TYPE:
USERPOOL:Fighter Skill|POOLPOINTS:0.0

```

**Comment by BahamutDragon** [comment]
Mate,

Which system do you want to play?
You have the D&D Next Play Test, and the Basic Rules. Both of which are different. On top of that you are attempting to load the Player's Handbook with the Core Rule books, which has been the Player's Handbook, the Dungeon Master's Guide and the Monster Manual.

The end result is a confusing mess. Remove the Play Test, and Basic Rules. Load only the Core Rulebooks along with the supplemental sources you want, and you should find your character displaying things correctly. 

Though I will add the restrictions to prevent this mistake from happening again.

**Comment by BahamutDragon** [comment]
Conflicted books will no longer be possible with the sources available. I will ask the pcgen team to do the same with the srd they have.

**Comment by BahamutDragon** [comment]
There, shows with a minor tweak the character is now working.
[Adalwulf.pdf](https://github.com/BahamutDragon/pcgen/files/240911/Adalwulf.pdf)
[Adalwulf.PHB.pcg.txt](https://github.com/BahamutDragon/pcgen/files/240913/Adalwulf.PHB.pcg.txt)

**Comment by matteocorti** [comment]
Thanks!
