### ISSUE TITLE
Errors loading 5e sources

### ISSUE THREAD

**Issue by jagbear** [BahamutDragon/pcgen#498]
I received the following in 6.06.00 when loading the 5e sources:
Dungeons & Dragons 5e - Core Books 5e - Elemental Evil Player's Companion 5e - Sword Coast Adventurer's Guide Unearthed Arcana (Psionics)

17:40:41.570 INFO main Main:145 Starting PCGen v6.06.00
17:40:41.617 INFO main LanguageBundle:131 Initialising language bundle with locale en_US.
17:41:59.980 INFO Thread-6 SourceFileLoader:518 Loading game 5e and sources [Dungeons & Dragons 5e - Core Books, Elemental Evil Player's Companion, Sword Coast Adventurer's Guide, Unearthed Arcana: Psionics].
17:41:59.995 LSTERROR Thread-6 CDOMControlLoader:146 Unsure what to do with line with prefix: DEFAULTVARIABLEVALUE.  Line was: DEFAULTVARIABLEVALUE:STRING| in file: file:/C:/Users/jagbe/Documents/PCGen/PCGen60600/data/5e/homebrew/core/universal_rules/ur__datacontrols.lst
17:41:59.995 LSTERROR Thread-6 CDOMControlLoader:146 Unsure what to do with line with prefix: DEFAULTVARIABLEVALUE.  Line was: DEFAULTVARIABLEVALUE:BOOLEAN|False in file: file:/C:/Users/jagbe/Documents/PCGen/PCGen60600/data/5e/homebrew/core/universal_rules/ur__datacontrols.lst
17:41:59.995 LSTERROR Thread-6 CDOMControlLoader:146 Unsure what to do with line with prefix: DEFAULTVARIABLEVALUE.  Line was: DEFAULTVARIABLEVALUE:ORDEREDPAIR|0,0 in file: file:/C:/Users/jagbe/Documents/PCGen/PCGen60600/data/5e/homebrew/core/universal_rules/ur__datacontrols.lst
17:41:59.995 LSTERROR Thread-6 CDOMControlLoader:146 Unsure what to do with line with prefix: DEFAULTVARIABLEVALUE.  Line was: DEFAULTVARIABLEVALUE:NUMBER|0 in file: file:/C:/Users/jagbe/Documents/PCGen/PCGen60600/data/5e/homebrew/core/universal_rules/ur__datacontrols.lst

**Comment by BahamutDragon** [comment]
Mate, 

> Many of the latest features will require you to utilize the latest version (unstable if necessary) of pcgen. I try to use the latest fixes and improvements found in the development line, if you grab the master branch be sure to use the latest developmental version of PCGen. 

That means one of these two options is advised:
1. Download the autobuild of 6.07.x from pcgen http://www.pcgen.org/autobuilds/download.html (Latest Updates, fixes and features), so you can continue using the master branch
or
2. Switch to 6.06.x branch which is meant only for 6.06.00 of pcgen.

Just as of right now, the 6.07.00-dev has 258 bug and feature improvements logged. A few of those benefit 5e use directly, some indirectly. It also means a new formula parser is up and running, requiring 'DEFAULVARIABLEVALUE' tags to work. 

The reason this particular issue has cropped up was deity support. FACT:Domain. Once we broke from the default methods supplied, it forced us to use the new tags.

Now, you are certainly free to edit out the changed file and comment out those entries so you may continue to use master with 6.06.00, but I would advise against that. You would not want to accidentally commit that change and reverse progress and development, and if more changes happen (which they likely will), you do not want to lose your change.

Once I see the PCGen team merging in the new formula system in their own data, I will be following suit with mine. Several systems, such as star wars edge and mutants and masterminds, are limping along that would greatly benefit from the new system.

Best,
