### ISSUE TITLE
3.5e: High Elf not proficient with all composite bows

### ISSUE THREAD

**Issue by dmcbride** [BahamutDragon/pcgen#514]
pcgen thinks that the elf cannot use "Longbow, Composite" from PH, but can use the "Longbow (Composite)" ones from MM2 or the "Longbow (+x Mighty/Composite/Aquatic)" bows from Races of Faerun or even the Elven Greatbow from Epic Level Handbook.  Similarly, she cannot use the "Shortbow, Composite" also from PH.

This conflicts with the statement under the Elf Race Trait / Weapon Proficiency.

**Comment by BahamutDragon** [comment]
Fixed

**Comment by BahamutDragon** [comment]
Part of the massive fix from UA where Composite versions are a separate proficiency.

**Comment by dmcbride** [comment]
Can this be cherrypicked into 6.06.x?  Thanks.

**Comment by BahamutDragon** [comment]
Later tonight I will. You can also reset to the commit before the UA
Weapon Group patch to get the proficiencies all working correctly till then.

Best,


-- 
~BD
https://github.com/BahamutDragon/pcgen
http://games.groups.yahoo.com/group/bd_games/

**Comment by BahamutDragon** [comment]
Cherry picked to 6.06.x
