### ISSUE TITLE
3.5e: Seeker of the Song prereq isn't met

### ISSUE THREAD

**Issue by dmcbride** [BahamutDragon/pcgen#516]
Trying to add a Seeker of the Song level to an 11th level bard, but the prereqs aren't met.  The part in red says "all of ( at least 1 Bardic Music Special Ability )" -- which seems odd.  I do see "Bardic Music" in the "Bard Class Feature" tree under class features.

**Comment by BahamutDragon** [comment]
The pre req needs to be PREABILITY:1,CATEGORY=Special
Ability,TYPE.Bardic Music. Be tonight after work to get it fixed.

-- 
~BD
https://github.com/BahamutDragon/pcgen
http://games.groups.yahoo.com/group/bd_games/

**Comment by dmcbride** [comment]
Sounds good.  I'm not in a hurry, I just am finding things and reporting them (or, if I have the know-how, submitting a PR) :)

**Comment by BahamutDragon** [comment]
Fixed
