### ISSUE TITLE
3.5e: Complete Adventurer feats: Versatile Performer doesn't have skill selection

### ISSUE THREAD

**Issue by dmcbride** [BahamutDragon/pcgen#517]
> Pick a number of Perform categories equal to your Intelligence bonus (minimum 1)."

There is no picker here, so whether the bonus from this feat applies or not is unknown.

> if you later add additional ranks in your highestranked Perform category"

There should be a dash between "highest" and "ranked"

> In addition, you gain a +2 bonus on a combined Perform check when using two or more forms of performance at the same time, such as a bard strumming a lyre while singing.

Not sure if this situational modifier can be done.

**Comment by BahamutDragon** [comment]
Fixed
