### ISSUE TITLE
[3.5] [Request] Implement Dragon 318 3.5 errata updates to Hengeyokai

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#523]
Or maybe even just outright change it's default to the Dragon 318 version. Changes made byy this 3.5 update for the 3rd edition race are replacing the obsolete "Shapechanger" type with "Humanoid (Shapechanger)" and remove their LA.

**Comment by BahamutDragon** [comment]
Implemented

**Comment by GamerGoddessDin** [comment]
Just updated to the newest commit and started a new Hengeyokai. It's now wanting me to choose 2 animals and 2 forms and is also not switching my speed to the appropriate value for the Dog Hybrid form. (Other Hybrid forms may also be effected in a similar fashion by the changes, I've not tested them.)

**Comment by BahamutDragon** [comment]
The last commit would not have altered any of that, the double selections existed well before that. Note that the status of Oriental Adventures is Alpha, which means it lacks any testing and is very much buggy.

**Comment by BahamutDragon** [comment]
Dog has no hybrid movement mode change according to the table on page 11. Other hybrid forms have the table already implemented. 

Best,

**Comment by GamerGoddessDin** [comment]
Hybrid Dog still shows 10 ft land speed shown.

**Comment by GamerGoddessDin** [comment]
Additionally it doesn't give me a Level 1 feat with my first level in a class. (Class used in testing: Dragonfire Adept)
