### ISSUE TITLE
lst writer

### ISSUE THREAD

**Issue by nevarim** [BahamutDragon/pcgen#529]
where i can find lst editor for to create homebrew class and other features?
in the wiki i haven't found link

**Comment by FerretDave** [comment]
There isn't a lst editor, they are text files that you can edit with any text editor.
Look on the main PCGen help for homebrew classes.

**Comment by BahamutDragon** [comment]
Mate,

Not sure if you realize this, but this is a homebrew repository with unofficial data sets. If you want official PCGen support, their repository is PCGen/pcgen and their website is pcgen.org.

For editing lst file, just use a text editor that you enjoy using. If you use one the volunteers use, then you can get syntax highlighting support for it.

Most of the documentation would be by the pcgen team - http://wiki.pcgen.org/Text_Editors

They also have youtube videos - http://pcgen.org/get-help/videos/

I can answer lst coding questions, but you will find faster responses through the official pcgen communication channels. 

Best,
