### ISSUE TITLE
unable to create new character after install

### ISSUE THREAD

**Issue by nevarim** [BahamutDragon/pcgen#530]
i have an error
unable to create a new character after a clean install of pcgen, i follow step by step the instructions (apart java newer instead 1.6 as suggested)

can be java? i charged only core after install bahamut
[error.txt](https://github.com/BahamutDragon/pcgen/files/266819/error.txt)

**Comment by nevarim** [comment]
p.s. i installed master branch 6.06x

**Comment by BahamutDragon** [comment]
Mate,

Your version is declared as PCGen v6.04.01. You will not have any
success using master branch or 6.06.x branch with 6.04.01. I recommend
that you update to 6.06.00 and use the 6.06.x branch. The latest
versions of pcgen are found at  http://pcgen.org/download/

master is only for those intending to actively support new development
by using the latest autobuilds.

Best,

On 5/16/2016 12:29 PM, nevarim wrote:
>
> p.s. i installed master branch 6.06x
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BahamutDragon/pcgen/issues/530#issuecomment-219522109>
>

-- 
~BD
https://github.com/BahamutDragon/pcgen
http://games.groups.yahoo.com/group/bd_games/

**Comment by nevarim** [comment]
thanks for help i made a noob question i know :(

i'll try to contribute if i reach to use syntax editor :D

2016-05-17 6:46 GMT+02:00 Bahamut <notifications@github.com>:
