### ISSUE TITLE
[dnd 3.5] Maester prestige class has incorrect entry requirements

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#531]
Warlock (CAr) cannot take Maester (CAdv) because Warlock is not considered as Arcane Caster.
And when i selected "bypass class prerequisites" and took 5 levels of Maester anyway, i received zero new invocations and Eldritch Blast damage also didn't change. While it should progress both invocations and Eldritch blast for classes with "+1 level of existing spellcasting class".

**Comment by BahamutDragon** [comment]
Adjusted Warlock Eldritch Blast to account for increases from Caster Level. Fixed Maester to accept 5th level arcane caster instead of 5th level arcane spells. Corrected Maester to increase an existing spellcasting class starting at level 2.

**Comment by shadowfury** [comment]
Thanks!
