### ISSUE TITLE
[D&D 3.5e] UA Rage Variants not displayed

### ISSUE THREAD

**Issue by nevarim** [BahamutDragon/pcgen#533]
hi if you select barbarian level 7 link tell me to choose rage variant, but window is empty
![image](https://cloud.githubusercontent.com/assets/19359560/15391554/081cb1bc-1dc2-11e6-9316-83c384c714df.png)

**Comment by FerretDave** [comment]
You may need to click on the 'Barbarian Rage Variant' in the right hand
pane to activate it?

**Comment by nevarim** [comment]
i click on barbarian rage variant but nothing happens :(

**Comment by BahamutDragon** [comment]
Fixed
