### ISSUE TITLE
[dnd 3.5] Arcane Spell Power feature of Ultimate Magus (CM) does not work

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#536]
Arcane Spell Power feature of Ultimate Magus (CM) does not work

Example:

Beguiler 1 / Wizard 4 / Ultimate Magus 7 ,  feat practiced spellcaster (CD) (Beguiler) , due to practiced spellcaster, wizard's level is lower or equal to beguiler until UM 7.

Expected caster levels:
Beguiler: 1 + 4 (practiced spellcaster) + 4 (both to wizard and beguiler) + 1 (7th level of ultimate magus) + 3 (Arcane spell power) = 13
Wizard: 4 + 6 (Ultimate magus) + 3 (Arcane spell power) = 13
Actual:
Beguiler: 10
Wizard: 10

**Comment by BahamutDragon** [comment]
Implemented
