### ISSUE TITLE
[3.5e] Implement Automatic Fund Generation

### ISSUE THREAD

**Issue by nevarim** [BahamutDragon/pcgen#537]

**Comment by BahamutDragon** [comment]
Mate,
What is the intention of this report? Is this supposed to be a request?

**Comment by nevarim** [comment]
yes is wrong place?

**Comment by BahamutDragon** [comment]
Mate,

No, just lacks the phrasing to make it understandable. Bugs are reported as "Feature x does not do function y". Features are phrased "Please implement function x". And then a description to provide details. The summary submitted is phrased as a bug without details.

I do not know what the intentions are when requests and reports are left vague. Meaning lack details and clarifying information.

From the updated title I can only infer you desire NPCs to have some sort of funds. Which game system is this supposed to address? What are the rules governing the request? Can you cite a source book and page number? 

Best,

**Comment by nevarim** [comment]
![funds](https://cloud.githubusercontent.com/assets/19359560/15569446/3589bcb6-2331-11e6-8668-bcc3033c3876.png)
sure in dm book there is a list for every level before level 20 with initial fund for to create png

so looking for character level you have an initial amount of gold to spend :)

**Comment by BahamutDragon** [comment]
Implemented.
