### ISSUE TITLE
[dnd 3.5] Eldritch Blast progression is off by 1 level.

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#538]
Condition "var: EldritchBlastDice at least 2" is never satisfied, probably variable was renamed

**Comment by BahamutDragon** [comment]
Mate, I looked into this and I either fixed this doing some other work, or it is not an issue with a standard 4th level Warlock. The var passes the condition of EldritchBlastDice at least 2. If you were using a prestige class, then perhaps that was the problem. If so, I need to know the exact conditions to replicate the problem.

**Comment by shadowfury** [comment]
Warlock gets 2d6 on Eldritch Blast on 3rd level. I was wizard 3/warlock 3 when i tried to take this prestige

**Comment by BahamutDragon** [comment]
Fixed
