### ISSUE TITLE
3.5e CW improved familiar companion list missing selections

### ISSUE THREAD

**Issue by nevarim** [BahamutDragon/pcgen#539]
with improved familiar selected list of familiar doesn't change 
this is list for familiar to choose
Krenshar Neutral 3rd +3
Worg Neutral evil 3rd +3
Blink dog Lawful good 5th +5
Hell hound Lawful evil 5th +5
Hippogriff Neutral 7th +7
Howler Chaotic evil 7th +7
Winter wolf Neutral evil 7th +7

**Comment by BahamutDragon** [comment]
Which system?

**Comment by BahamutDragon** [comment]
While the information is better, missing crucial information such as game system and book cited, makes the turn around for a fix slower.

**Comment by nevarim** [comment]
ah sorry
 Source: Wizards of the Coast - Complete Warrior, p.100
bahamut 3.5
