### ISSUE TITLE
[dnd 3.5] Sublime Chord (CAr) has caster level 1 for her spells

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#544]
While it should be like this:
"A sublime chord’s caster level for both her sublime chord spells and the spells she gains from other arcane spellcasting classes is determined by adding her sublime chord level to her level in another arcane spellcasting class. If she had more than one arcane spellcasting class before becoming a sublime chord, she must choose to which class to add her sublime chord levels for the purpose of determining her sublime chord spellcaster level."

**Comment by shadowfury** [comment]
For some reason caster level was not affected by this change, it still count only Sublime Chord level + level of prestiges applied to Sublime Chord

**Comment by BahamutDragon** [comment]
Which class did you select?

**Comment by shadowfury** [comment]
It's the same character as in previous bug. Prior to Sublime Chord i've added Virtuoso levels to bard and after to Sublime Chord. Hence - bard spells are 9th level and Sublime Chord has caster level 3. (Though even when i first take Sublime chord, its Caste level should be 10th)

[willy.zip](https://github.com/BahamutDragon/pcgen/files/333848/willy.zip)

**Comment by BahamutDragon** [comment]
Your character clearly shows that you never chose a class to increase. As soon as I select Bard, the Sublime Chord caster level correctly displays as 12. The only thing I altered was now your Highest Arcane caster will display based upon the total Sublime Chord bonuses, and not the straight class.

**Comment by shadowfury** [comment]
Sorry didn't notice Sublime Chord in Class Features tab, works as expected now, thanks a lot for these epic Bard fixes!
