### ISSUE TITLE
[35e] Inspire Courage temporary bonus doesn't work.

### ISSUE THREAD

**Issue by LiaungYip** [BahamutDragon/pcgen#545]
Applying the `Bardic Inspire Courage ~ Not The Bard` temporary bonus has no effect.

This was fixed in [PCGen issue DATA-2453](https://pcgenorg.atlassian.net/browse/DATA-2453).

I attempted to:

  * take the Inspire Courage code from PCGen 6.0.7 nightly, `data/35e/wizards_of_the_coast/rsrd/rsrd_abilities_class.lst`
  * Put that code into into this repository's `ph_template.lst`

However I didn't get a working result.

**Comment by BahamutDragon** [comment]
Fixed

**Comment by LiaungYip** [comment]
Thanks for the fast fix!
