### ISSUE TITLE
Sources not loading

### ISSUE THREAD

**Issue by SaintSteel** [BahamutDragon/pcgen#547]
I went and got the updated virsion like I was told, it did not have all the 3.5e books. So I downloaded the master file and just copied the data file over and they show in the Select Sources part for the program but when I chose the core books 1-3 it wont let me load the rest they all stay red and then tell me This source cannot be selected yet as it relies on other sources : includesbooktype=core35e

**Comment by BahamutDragon** [comment]
The 3.5e books in this repo will only work with one of the following sources added:
Dungeons & Dragons - Core Books 
Player's Handbook - Core Rulebook I v.3.5
