### ISSUE TITLE
[dnd 3.5] Lyric Thaumaturge (CM) bonus spell ability does not work

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#549]
I've noticed that i do not get extra spells per day as per their Bonus Spell feature. 
Example - bard 7 / Lyric Thaumaturge 2 with 20 Cha i get 5 for 1 level and 4 for second level spells per day. Which is basically Bard amount + extra spells from high Charisma

**Comment by BahamutDragon** [comment]
Specific code implemented to handle request
