### ISSUE TITLE
2 Loading errors when selecting the Core book

### ISSUE THREAD

**Issue by AVellucci** [BahamutDragon/pcgen#552]
Lines 12 to 16 are commented incorrectly in this file. Causing 2 errors to appear in the logs upon loading.
` pcgen/data/35e/wizards_of_the_coast/core/players_handbook/ph__datacontrols.lst `

**Comment by BahamutDragon** [comment]
Branch 6.06 -

> ###Block - Formula Parser
> #DEFAULTVARIABLEVALUE:ORDEREDPAIR|0,0
> #DEFAULTVARIABLEVALUE:NUMBER|0
> #
> #
> 

Branch master -

> ###Block - Formula Parser
> DEFAULTVARIABLEVALUE:ORDEREDPAIR|0,0
> DEFAULTVARIABLEVALUE:NUMBER|0
> #
> #

Both cases, loaded without error.

Are you using the latest version of the file?

**Comment by AVellucci** [comment]
I loaded the Master Branch in my 6.06 PCGen, that may be the reason. I'll pull the 6.06 branch instead.

**Comment by BahamutDragon** [comment]
Closing this.
