### ISSUE TITLE
Goliath data missing ability bonuses

### ISSUE THREAD

**Issue by nigelboid** [BahamutDragon/pcgen#553]
I believe line 54
in pcgen/data/5e/wizards_of_the_coast/supplement/elemental_evil_players_companion/eepc_abilities.lst

should be:

Ability Score Increase	KEY:Goliath ~ Ability Score Increase	CATEGORY:Special Ability	SORTKEY:1_Race	TYPE:Race Trait.Goliath Trait.Base Goliath Trait.SpecialQuality	DESC:Your Strength score increases by 2, and your Constitution score increases by 1.  BONUS:STAT|STR|2|TYPE=Racial	  BONUS:STAT|CON|1|TYPE=Racial

I've attached an updated file...
[eepc_abilities.lst.txt](https://github.com/BahamutDragon/pcgen/files/356378/eepc_abilities.lst.txt)

**Comment by BahamutDragon** [comment]
Fixed

**Comment by nigelboid** [comment]
Sorry, but I just noticed that the Athletics skill is also missing the tags at the end of the appropriate line.

Line 55 should be:

Natural Athlete		KEY:Goliath ~ Natural Athlete			CATEGORY:Special Ability	SORTKEY:1_Race	TYPE:Race Trait.Goliath Trait.Base Goliath Trait.SpecialQuality	DESC:You have proficiency in the Athletics skill. ABILITY:Skill Proficiency|AUTOMATIC|Athletics

By the way, if you would like to give me appropriate permissions, I can just submit changelists as I notice and correct issues.

**Comment by BahamutDragon** [comment]
Mate,

You did not look at my commit, or else you would realize I fixed that too (along with about a half dozen other improvements). 

As far as permissions, github has made it easy to fork/clone, commit to your own fork, and submit Pull Requests. That is the standard practice and one I follow, since it allows for peer review.

**Comment by nigelboid** [comment]
Yeah, sorry, I did not think to look.

On the fork thing, I tried exactly that last night but got permission errors. So, I thought you disabled something. I'll try again.

**Comment by BahamutDragon** [comment]
I have no control over the permissions of your own repo. You need to grant yourself proper access. Most people use the SSH public/private key. With github, you have complete and total control over your own repo.
