### ISSUE TITLE
Stat for AC is 3 instead of 4 after latest update, DnD 5e

### ISSUE THREAD

**Issue by jagbear** [BahamutDragon/pcgen#556]
After pulling the latest changes, the AC for my character is now showing as 14 instead of 15.  It seems to be taking the stat modifier as 3 instead of 4 which is the Dex modifier.
I've tried looking in the code to see what changed, but can't find anything so far.
Any help would be appreciated.
![acpic](https://cloud.githubusercontent.com/assets/15275167/16876877/5ce2019a-4a6b-11e6-8441-34a55d636bbf.jpg)

**Comment by BahamutDragon** [comment]
Mate,

I cannot normally debug issues based by screenshots alone.

I can make an educated guess though. I will lay odds your character has a medium encumbrance. Wood Elves have a speed of 35, not 25 like a smaller race. Using a custom gamemode means nothing I do would address the issue. Your load file needs to be updated.

SIZEMULT:T|0.5
SIZEMULT:S|1
SIZEMULT:M|1
SIZEMULT:L|2
SIZEMULT:H|4
SIZEMULT:G|8
LOAD:0|0
LOAD:1|15
LOAD:2|30
LOAD:3|45
LOAD:4|60
LOAD:5|75
LOAD:6|90
LOAD:7|105
LOAD:8|120
LOAD:9|135
LOAD:10|150
LOAD:11|165
LOAD:12|180
LOAD:13|195
LOAD:14|210
LOAD:15|225
LOAD:16|240
LOAD:17|255
LOAD:18|270
LOAD:19|285
LOAD:20|300
LOAD:21|315
LOAD:22|330
LOAD:23|345
LOAD:24|360
LOAD:25|375
LOAD:26|390
LOAD:27|405
LOAD:28|420
LOAD:29|435
LOAD:30|450
LOADMULT:15

ENCUMBRANCE:Light|1||0
ENCUMBRANCE:Medium|1||0
ENCUMBRANCE:Heavy|1||0
ENCUMBRANCE:OverHead|1||0
ENCUMBRANCE:OffGround|2||0
ENCUMBRANCE:PushDrag|2||0



On a purely GM observational side note, that character is overpowered for a standard 5e game. Level 4 with the lowest stat being 16 and the highest 19.

Best,
