### ISSUE TITLE
unable to load automatic feat in custom class

### ISSUE THREAD

**Issue by nevarim** [BahamutDragon/pcgen#559]
i cannot understand where i making wrong code in my class, when i load custom class level feats are not loaded

thanks
Neva
[issue.zip](https://github.com/BahamutDragon/pcgen/files/367047/issue.zip)

**Comment by BahamutDragon** [comment]
Simple, you are missing the abilitycategory of "Magus Dei Draghi Gemmati Class Feature"

Which you are requiring to exist with the class level code of "ABILITY:Magus Dei Draghi Gemmati Class Feature|AUTOMATIC|". Your zip folder also lacks a .pcc file that controls what files are loaded. Class and abilities will not be available if you are not loading them.

**Comment by nevarim** [comment]
now is updated with also the file pcc
[_wainar.zip](https://github.com/BahamutDragon/pcgen/files/367071/_wainar.zip)

what you mean that i miss abilitycategory ?
what i must add to file abilities?

**Comment by BahamutDragon** [comment]
You need to load an abilitycategory file with the definition. For instance:

ABILITYCATEGORY:Barbarian Class Feature	VISIBLE:QUALIFY	EDITABLE:YES	EDITPOOL:NO		CATEGORY:Special Ability	TYPE:Barbarian Class Feature	PLURAL:Barbarian Class Features	DISPLAYLOCATION:Class Features

In your case:

ABILITYCATEGORY:Magus Dei Draghi Gemmati Class Feature	VISIBLE:QUALIFY	EDITABLE:YES	EDITPOOL:NO		CATEGORY:Special Ability	TYPE:Magus Dei Draghi Gemmati Class Feature	PLURAL:Magus Dei Draghi Gemmati Class Features	DISPLAYLOCATION:Class Features

**Comment by nevarim** [comment]
nothing to do maybe there is sometrhingw wrong

Assorbimento Inferiore			ABILITYCATEGORY:Magus Dei Draghi Gemmati Class Feature VISIBLE:QUALIFY EDITABLE:YES EDITPOOL:NO CATEGORY:Special Ability TYPE:Magus Dei Draghi Gemmati Class Feature PLURAL:Magus Dei Draghi Gemmati Class Features DISPLAYLOCATION:Class Features:Magus Dei Draghi Gemmati ~ Assorbimento Inferiore			SORTKEY:Class ~ Magus Dei Draghi Gemmati		CATEGORY:Special Ability	TYPE:Class Feature.Magus Dei Draghi Gemmati Class Feature.SpecialQuality																		DESC:....

**Comment by nevarim** [comment]
understood where is the problem
