### ISSUE TITLE
create spell focus like feat

### ISSUE THREAD

**Issue by nevarim** [BahamutDragon/pcgen#562]
i want to create a feat connected to a level of a cdp that improve CD of a school

this is the ability

Incantesimi Inarrestabili			KEY:Magus Dei Draghi Gemmati ~ Incantesimi Inarrestabili				CATEGORY:Special Ability	TYPE:SpecialQuality.Magus Dei Draghi Gemmati Class Feature.Extraordinary	SOURCEPAGE:p.1

and this is the part of the feat spell focus

	STACK:NO	MULT:YES	CHOOSE:SCHOOLS|ALL	BONUS:DC|SCHOOL.%LIST|1|TYPE=SpellFocus

why when i levelup the cdp i haven't the choose of the school?

**Comment by BahamutDragon** [comment]
Mate, 

I do not mind giving out advice, but I am not the official channel for PCGen support questions. If you are having issues with the PCGen program, the people to talk to are the PCGen developers. The website to reach them is pcgen.org.

I am a homebrewer that is sharing my effort to those in my gaming group, and also the broader pcgen community. The issue tracker here is a method to request fixes or improvements to what I already offer. It is not meant to be a personal support request method.

Your issue though is a simple mistake. CHOICE POP UP DIALOG BOXES cannot be linked to automatically granted abilities. The proper method is BONUS what they call an ability pool, and then select the choice laden ability that way.

Example: Add this to your Level granted ability 'BONUS:ABILITYPOOL|Spell Focus Like Choice|1'

Which means you need to create in an abilitycategory file:

ABILITYCATEGORY:Spell Focus Like Choice
CATEGORY:Special Ability
TYPE:Spell Focus Like Choice
DISPLAYLOCATION:Class Features
VISIBLE:QUALIFY
EDITABLE:YES
EDITPOOL:NO

Which needs an ability to select:

My Choice Ability
TYPE:Spell Focus Like Choice
CATEGORY:Special Ability
STACK:NO
MULT:YES
CHOOSE:SCHOOLS|ALL
BONUS:DC|SCHOOL.%LIST|1|TYPE=SpellFocus

Best,

**Comment by nevarim** [comment]
many thanks for your support unfortunally i didn't know where to ask

i will have to try this evening

Neva
