### ISSUE TITLE
Shade in Darkness issue

### ISSUE THREAD

**Issue by SaintSteel** [BahamutDragon/pcgen#575]
Trying to use the Shade in Darkness as a template 
Shade (in darkness) Modifier: CON:4 CHA:4 AC BONUS:4SR:11 Requirements: either ( Alignment exactly LE, Alignment exactly NE, Alignment exactly CE ) and race: RACESUBTYPE=Shade at least 1 Source: Wizards of the Coast - Forgotten Realms Campaign Setting

I took the Shade  at least 1 and its still red

The char will be cloaked in darkness at all times but i cannot click it

**Comment by SaintSteel** [comment]
and iirc shade have a +4 LA.

**Comment by BahamutDragon** [comment]
Hodgepodge mess for Shades. There are two Shade templates, and two different templates, for the shade being in Darkness.

You should see just a "Shade" template. It includes all the abilities and adjustments, except for the Level Adjustment of +5. Player's Guide to Faerun should override the Races of Faerun version, which is less coded properly. It includes a Temp Bonus to activate the "In shadows" abilities.

Be a few minutes to get the Player's Guide version squared away.

**Comment by BahamutDragon** [comment]
That should fix the problem.

**Comment by SaintSteel** [comment]
That's fine I'll just increase the stats manually and then just pencil
other other stuff that I need don't want to put you through a headache
