### ISSUE TITLE
[ 3.5 e] Ordained Champion (Complete Champion) turn level does not stack with Cleric

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#576]
As per 

Continued Advancement  
[Wizards of the Coast - Complete Champion, p.90] 
     Levels in ordained champion stack with levels of other appropriate classes for the purpose of turning or rebuking undead, and for all level-dependent domain granted powers. 

Turn Undead level of Cleric 4 / OC 1 should be 5, but it's 4
![image](https://cloud.githubusercontent.com/assets/2230015/18367087/0ad16a34-7622-11e6-820b-4e31202ae671.png)

**Comment by BahamutDragon** [comment]
Try now, e02b480 should resolve the problem.

**Comment by shadowfury** [comment]
Fixed, now it's 5th level as it should, thanks!
