### ISSUE TITLE
No languages available in 3.5e

### ISSUE THREAD

**Issue by Boreeas** [BahamutDragon/pcgen#582]
When creating a new character, after assigning a race, no languages become available. The character does not even speak Common. 

[Example](https://gyazo.com/5465d4f564a2182f628f150a1b715f80)

The following source books have been loaded.

[Source Books](https://gyazo.com/3fc255386721a773c852d2e6d75b794d)

#535 seems to suggest that adding a human subrace feat would fix this problem, but the human subrace feat doesn't have any available choices.

**Comment by BahamutDragon** [comment]
Mate,

There is no "feat", there should be a subrace selection under Race Traits subtab.  

![humansubrace](https://cloud.githubusercontent.com/assets/4307487/18654357/546a5130-7e95-11e6-8b4e-a024df9ef56c.JPG)

Which allows a bonus language selection:
![humansubracelang](https://cloud.githubusercontent.com/assets/4307487/18654382/84ee8a06-7e95-11e6-8f4b-e7e0eb905d46.JPG)


Does your pcgen version match the branch downloaded? 6.06.01 with 6.06.x or 6.07.00 with master?

**Comment by Boreeas** [comment]
Sorry, I wasn't clear enough. That subrace tab is what I meant. But there's nothing to pick from for me:

![Human Subrace](https://gyazo.com/e27c6cc8d41914f36360068b4f2a8b03)
