### ISSUE TITLE
Gestalt BAB

### ISSUE THREAD

**Issue by MidnightsFist** [BahamutDragon/pcgen#587]
I have a gestalt character with 12 levels of fighter class / 3 Dwarf Paragon + 3 Bloodline + 5 cleric; the CAB does not seem to calculate correctly - I'm getting 2 attacks at +7/+2.

Is this a known issue or something I'm doing wrong?

**Comment by BahamutDragon** [comment]
Mate,

Can you provide the character *.pcg file? It will be easier to investigate where the problem is.

**Comment by BahamutDragon** [comment]
Mate,

Reflecting on this, I believe the set up only included the base PHB, and PHB II Classes, additional books would only be supported on a request basis.

Gestalt means 2 levels per level. Your total levels is 23.

**Comment by MidnightsFist** [comment]
Hi, 

Thanks for getting back to me. It's a bit of a learning process!

Think I've got how it works now. Cheers!

Jon
