### ISSUE TITLE
[Dnd 3.5] Focused Specialist ACF

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#599]
Can you please modify for Focused Specialist from BONUS:VAR|WizardSpecialtyKnownSpells|1 to BONUS:VAR|WizardSpecialtyKnownSpells|2 (in cm_abilities.lst) ? Otherwise focused specialist does not make sense (you loose 1 spell and you get 1 specialist spell in return, while it should be 2 such spells)

**Comment by BahamutDragon** [comment]
Fixed

**Comment by shadowfury** [comment]
Thanks! Any chance that Immediate Magic ACF from ph2_abilities.lst can be fixed some day? Now allows you to select ability from spell pool instead of predefined abilities. I can't figure out how to implement this.
I suppose it relates to this - CHOOSE:SPELLS|CLASSLIST=Wizard[LEVELMAX=1;LEVELMIN=0] where istead of spells there should be abilities list?

**Comment by BahamutDragon** [comment]
Mate, until you bring up an issue, I cannot know it needs to be fixed. That is now fixed. 

Each item should be a separate issue.
