### ISSUE TITLE
[Dnd 3.5e] Immediate Magic ACF form player handbook 2

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#600]
Immediate Magic ACF from ph2_abilities.lst does not work as intended. Now allows you to select ability from spell pool instead of predefined abilities. I can't figure out how to implement this.
I suppose it relates to this - CHOOSE:SPELLS|CLASSLIST=Wizard[LEVELMAX=1;LEVELMIN=0] where instead of spells there should be abilities list?

![image](https://cloud.githubusercontent.com/assets/2230015/20041150/d57260ee-a46d-11e6-8960-d8d0803dd34f.png)

**Comment by BahamutDragon** [comment]
fixed - https://github.com/BahamutDragon/pcgen/commit/e7b0aac6c0671aa6d10fb6578c247f25ff245b7a
