### ISSUE TITLE
Issue with selecting a subrace

### ISSUE THREAD

**Issue by scottz657** [BahamutDragon/pcgen#608]
whenever I try to select a subrace for races that allow it (Half-Elf, Dhampir, Skinwalker, etc.) There are no options for it. This is both in the release version, and the dev build.

**Comment by BahamutDragon** [comment]
Mate, I think you have the wrong repository. This is a homebrew support repository for non-PCGen supported sources.

Perhaps you should talk to the official PCGen guys over at https://github.com/pcgen/pcgen/
