### ISSUE TITLE
Volo's Guide Support

### ISSUE THREAD

**Issue by alec-parks** [BahamutDragon/pcgen#609]
Request for Volo's Guide integration.

**Comment by alec-parks** [comment]
I'm working on this currently in my spare time. The first race was slow going. I don't know if this is duplicated effort or not.

I will end up entering in a PR once it's done, but I have no particular time frame. I will be adding it to my repository in the next couple days, probably week.

**Comment by BahamutDragon** [comment]
I do not have a copy of the book. No one is working on this to my knowledge.

**Comment by alec-parks** [comment]
Cool. I'll keep plugging away at it then.

I've run into a small issue if you have any guidance on it. Aasimar is updated from the DMG, so if that book is selected, it defaults to the DMG implementation of it. Is there a way around this?

**Comment by danlangford** [comment]
@alec-parks how is this going? could i possibly help?

**Comment by alec-parks** [comment]
@danlangford Yeah... It kind of stalled once I got a few of them working. Other things ended up taking priority. Feel free to fork my work from https://github.com/alec-parks/pcgen

I've got Kenku working, Firbolg, and Goliath. Aasimar is working, but it conflicts with the DMG and I'm not certain how to represent it.

Last thing I was working on was Lizardfolk and getting their damned AC to work...

**Comment by BahamutDragon** [comment]
alec-parks, you can always ask for help when you hit a stumbling block like that. No shame in saying you need another pair of claws, or eyes. I apologize though, as I missed your request for help. That will teach me to not skim email notices during holiday.  

Did you still want guidance, or would you prefer it if danlanngford or myself tackle the remaining issues you listed out? 

Finally, does this mean you are no longer actively working on this source or did you get those other priorities sorted and coming back to it shortly? 

Best,

**Comment by BahamutDragon** [comment]
@alec-parks how is this going?

**Comment by BahamutDragon** [comment]
Other than spells, this source is near completion.

**Comment by BahamutDragon** [comment]
Source is complete (No Monster support at this time)
