### ISSUE TITLE
create spell tattoo

### ISSUE THREAD

**Issue by nevarim** [BahamutDragon/pcgen#613]
spell compendium 

prerequisites are bad descripted

prerequisites : var: DisableSpellCompendiumSpells exactly 0

**Comment by BahamutDragon** [comment]
Mate, 

Spell Compendium does not contain any feats.

**Comment by BahamutDragon** [comment]
Helps if the name is referenced correctly.

Create Magic Tattoo. The Prereq is fine. That exists in case the spells need to be disabled for whatever reason. It is nothing to be addressed.
