### ISSUE TITLE
[5e] Unable to add companions

### ISSUE THREAD

**Issue by Proxxy0** [BahamutDragon/pcgen#615]
Recently, in a campaign I was in, we tamed three baby lizards, but I am unable to add them into our character sheets

**Comment by BahamutDragon** [comment]
Mate,

I think you need to understand a "bug" report - "_Unable to accomplish x with y_", versus a "request" - "_Can you please add the method to include a new creature our GM allowed us to get? The stats are from here www.somewebsite.com_". A request is asking me to include something extra for you, a bug is you finding a flaw in what already exists. (Lack of tame baby lizards is not a flaw, unless they exist in a book I have included, and they have a deficiency)

This is worded as bug, and the urgency that this is missing, when in fact baby lizards are not coded up and I have no obvious reference. 

This bloke is not a mind-reader, your GM, or the players who acquired these creatures. This means I actually have no idea what you want or any frame of reference to this request. Which makes this a moving target with the odds of me achieving any success slim to none. 

Are you requesting actual companions, an equipment item called "tamed baby lizard", or something else completely?

If you want a companion, what rules is it following? Is it just attached for show, or is there more to it?
If you want a race, can you supply the complete write up (proper 5e statblock)?
If you want a piece of equipment what name do you want, how much does it weigh, and what is the market value?

With me, you will find that well-worded requests will garner the results you desire. Until I have an answer, I cannot do anything with this request. 

Best,

**Comment by Proxxy0** [comment]
For this, I meant that we captured baby lizards and tamed them. The companions that our characters have are lizards, whose stats can be seen from this comprehensive list (http://www.enworld.org/forum/showthread.php?358676-Beast-Master-Ranger-List-of-Animal-Companions). I understand that these companions are meant for a Beast Master Ranger, but I was hoping that it would be possible to add them to our characters. Sorry for the misunderstanding.

**Comment by BahamutDragon** [comment]
Race is added now. Granted the ability to add a mount or follower. Not sure what else you want here.
