### ISSUE TITLE
[Dnd 3.5e] Complete Mage ACF - Focused Specialist highest level spell

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#620]
When you select this feature - it removes one generalist slot and adds 2 additional specialist slot. On levels when you gain new spell level (3 or 5 or 7 or 9 etc) if wizard does not have additional generalist slot due to high Intellect, pcgen counts as if wizard did not gain new level at all.

[master transmogrifist.zip](https://github.com/BahamutDragon/pcgen/files/752522/master.transmogrifist.zip)

**Comment by BahamutDragon** [comment]
Mate, 

I am at a loss on what to do. That is programming, which I do not handle. The ACF code grants 2 specialist slots, in place of 1 regular slot. PCGen treats a 0 for a given level as unable to cast, which is where you are encountering the issue.

The only thing I can change is when that -1 is applied, but then the character will have one additional slot not technically allowed.

I would suggest opening this bug with the pcgen team.

**Comment by BahamutDragon** [comment]
Only removes the slot if there would be 2 or more available.
