### ISSUE TITLE
5e EEPC Deep Gnome should have DEX+1, not DEX-1

### ISSUE THREAD

**Issue by craig-sanders** [BahamutDragon/pcgen#621]
A trivial fix, not worth forking and submitting a merge request for.  Just a quick edit of line 10 of `data/5e/wizards_of_the_coast/supplement/elemental_evil_players_companion/eepc_abilities.lst`:

`Deep Gnome			KEY:Gnome Subrace ~ Deep		CATEGORY:Internal			TYPE:GnomeSubrace																TEMPLATE:Subrace ~ Deep		ABILITY:Gnome Trait|AUTOMATIC|TYPE=Deep Gnome Trait							BONUS:STAT|INT|2|TYPE=Racial	BONUS:STAT|DEX|1|TYPE=Racial`

See EEPC page 7: "Ability Score Increase. Your Intelligence score increases by 2, and your Dexterity score increases by 1."

Also SCAG page 115: "Ability Score Increase. Your Dexterity score increases by 1."

**Comment by BahamutDragon** [comment]
Fixed
