### ISSUE TITLE
[Dnd 3.5E] Impossible to take Energy Admixture Feat (Complete Arcane)

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#622]
It seems, for some reason pcgen expects Spell School and not String (Acid in this case)

![image](https://cloud.githubusercontent.com/assets/2230015/22813320/7a29389e-ef53-11e6-9a93-29f0516564cd.png)

**Comment by BahamutDragon** [comment]
Fixed mate.

**Comment by shadowfury** [comment]
Thanks a lot!
