### ISSUE TITLE
Errors when loading 3.5e Core Books

### ISSUE THREAD

**Issue by Ogmund** [BahamutDragon/pcgen#625]
Hello, here's the log file text.

13:39:22.343 INFO main Main:145 Starting PCGen v6.06.01
13:39:22.905 INFO main LanguageBundle:131 Initialising language bundle with locale en_US.
13:40:42.185 INFO Thread-6 SourceFileLoader:518 Loading game 35e and sources [Dungeons & Dragons - Core Books].
13:40:42.216 LSTERROR Thread-6 CDOMControlLoader:146 Unsure what to do with line with prefix: DEFAULTVARIABLEVALUE.  Line was: DEFAULTVARIABLEVALUE:ORDEREDPAIR|0,0 in file: file:/C:/Games/Dungeons%20and%20Dragons/pcgen/data/35e/wizards_of_the_coast/core/players_handbook/ph__datacontrols.lst
13:40:42.216 LSTERROR Thread-6 CDOMControlLoader:146 Unsure what to do with line with prefix: DEFAULTVARIABLEVALUE.  Line was: DEFAULTVARIABLEVALUE:NUMBER|0 in file: file:/C:/Games/Dungeons%20and%20Dragons/pcgen/data/35e/wizards_of_the_coast/core/players_handbook/ph__datacontrols.lst
13:41:32.807 INFO AWT-EventQueue-0 DebugDialog:402 Memory used after manual GC, Heap: 85,383,168, Non heap: 28,315,344

**Comment by BahamutDragon** [comment]
Mate,

Why are you using the master branch with 6.06.01?  Master branch is only designed to be compatible with the pcgen development branch. You need an autobuild of the dev build, or the latest version of the released development line. I believe that would be 6.07.01. Alternatively, you can download the 6.06.01 branch which should load fine with 6.06.01.

Best,

**Comment by Ogmund** [comment]
Thanks for the information Bahamut, I'm new to using PCGen and your work. I just downloaded PCGen 6.07.01 full (unstable), and am going to try it out with the master branch.

**Comment by Ogmund** [comment]
I had to use the 6.06.x branch with 6.06.01, When I tried using 6.07.01 with the master branch, it would crash on startup.

**Comment by Ogmund** [comment]
Using the Dungeons & Dragons - Core Books, I noticed that bolts cost nothing and weigh nothing.
