### ISSUE TITLE
Armor Extras, price and weight.

### ISSUE THREAD

**Issue by Ogmund** [BahamutDragon/pcgen#633]
PCGen Source: D&D Core Book 3.5e
PCGen version: 6.06.01
Bahamut, Source Branch: 6.06.x

Currently these items cost and weight nothing. The information below is from the 3.5 Player's Handbook (page 123).
**Extras**
Armor spikes - Cost: +50gp, Weight: +10lb.
Gauntlet, Locked - Cost: 8gp, Weight: +5lb.
Shield spikes - Cost: +10gp, Weight: +5lb.

**Comment by BahamutDragon** [comment]
Mate, I will remove the equipment entries since those do nothing, and are just old placeholders. You need to customize the equipment, and add those extras to the item of your choice.

**Comment by Ogmund** [comment]
Okay, thanks man.
