### ISSUE TITLE
Monk AC incorrect

### ISSUE THREAD

**Issue by Nylanfs** [BahamutDragon/pcgen#641]
The html doesn't add in the Monk's Unarmored bonus which is Dex & Wis.

**Comment by BahamutDragon** [comment]
Mate,

I am using the html sheet provided by pcgen. The numbers are combined correctly for me. Chances are, if this is an older character, there may be corruption in a calculation, or an object that is missing. Are you able to replicate the problem with a brand new monk?

**Comment by Nylanfs** [comment]
There must be something on my end, andrew opened the character and exported it fine. I have yet to dig into it.
 
Paul A. Grosse 

    On Monday, February 27, 2017 11:19 PM, Bahamut <notifications@github.com> wrote:
 

 Mate,I am using the html sheet provided by pcgen. The numbers are combined correctly for me. Chances are, if this is an older character, there may be corruption in a calculation, or an object that is missing. Are you able to replicate the problem with a brand new monk?—

**Comment by BahamutDragon** [comment]
Closing this out as I cannot reproduce on my end. Best,

**Comment by OmegaDarkMatter** [comment]
if your carry weight is in medium, your ac gets reduced

**Comment by BahamutDragon** [comment]
Mate,

That is according to the rules of the game. 

Monk AC class feature stipulates the penalty on page 40,

> AC Bonus (Ex):...**She loses these bonuses when she is immobilized or helpless, when she wears any armor, when she carries a shield, or when she carries a medium or heavy load.**"

Then again you also have the oft-forgotten encumbrance rules regarding Max Dexterity bonuses and movement for a Medium load or Medium Armor, which gets worse for Heavy load and Heavy Armor.

> Table 9–2: Carrying Loads
![image](https://user-images.githubusercontent.com/4307487/52112934-d8081b00-25bc-11e9-9bb1-23fb06499526.png)
