### ISSUE TITLE
Purple Dragon Knight With incorrect pre-reqs

### ISSUE THREAD

**Issue by iwalucas** [BahamutDragon/pcgen#644]
The Purple Dragon Knight has a class defined like this:

CLASS:Purple Dragon Knight/FR	PREALIGN:LG,LN,NG,TN	PREABILITY:2,CATEGORY=FEAT,Leadership,Mounted Combat	PREMULT:1,[PRESKILL:1,TYPE=KnowledgeLocal=8=1],[PREREGION:1,Cormyr]	PRESKILL:1,Diplomacy=1,Intimidate=1	PRESKILL:3,Listen=2,Ride=2,Spot=2	PRETEXT:Must be a member of the Purple Dragons	PRETOTALAB:4

The PREREGION is wrong. It should be PREREGION:Cormyr, instead of PREREGION:1,Cormyr

I fixed locally and it worked.

Could you add this fix?

**Comment by BahamutDragon** [comment]
Fix added.
