### ISSUE TITLE
[dnd 3.5] War Domain and Favored Weapon (Longbow/Composite Longbow)

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#646]
Page 119 of the PHB, second column, first paragraph:

"For purposes of weapon proficiency and similar feats, a composite longbow is treated as if it were a longbow. Thus if you have Weapon Focus (longbow), that feat applies to both longbows and composite longbows."

Right now, deities with longbow as Favored weapon does not give proficiency and weapon focus for Longbow Composite. For example - Shevarash, The Silver Flame, Solonor Thelandira, Mayaheine.

I assume, it's the same for short bows as well. In general, Weapon Focus also do not respects this.

**Comment by BahamutDragon** [comment]
Required a bit of rework, but this should now work as intended.
