### ISSUE TITLE
[dnd 3.5] Corellon Larethian is not listed that he has Elf Domain

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#648]
![image](https://cloud.githubusercontent.com/assets/2230015/24081429/d3a929c6-0cbb-11e7-9751-836dcaa90099.png)
![image](https://cloud.githubusercontent.com/assets/2230015/24081435/fbc9366c-0cbb-11e7-9ffb-e1c51b059ee1.png)

**Comment by BahamutDragon** [comment]
Fixed
