### ISSUE TITLE
[dnd 3.5] Bad Interaction in Extra domain granting classes

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#649]
Ordained Champion (CC) , Cloister Cleric (UA) and Seeker of Misty Isle (CD) interact in a bad way:

- Ordained Champion grants extra domain only if 2 were selected previously (does not grant extra domain for Cloister Cleric for instance)
- Seeker of Misty Isle does not grant Travel Domain

- Additionally, feature that was implemented previously for swapping domain feats for devotions is missing or not working - https://github.com/BahamutDragon/pcgen/commit/6ac16a407b5fd0e1de2983ba50facc2bf6feb9b5

attaching save file to test, if consider this worth fixing

[Zen Archer.zip](https://github.com/BahamutDragon/pcgen/files/853235/Zen.Archer.zip)

**Comment by BahamutDragon** [comment]
Mate, always best to separate out issues, much easier to close out.
Ordained Champion now grants extra domain for Cloistered Cleric
Seeker of the Misty Isle now gains Travel (1st) and Magic (at 7th)
The missing feature still exists, it may not be available because it is a "domain" that none of the deities grant, I can rectify that.

**Comment by shadowfury** [comment]
Thanks a lot for your fixes, mostly they worked marvelously, usually it took a lot to add up numbers in mind and now it just works! Sorry for piling on several troubles here, i thought they were connected. I attached load logs and character file (i've created new one in case fixes were not retroactive). 
- I've noticed, that Travel Domain is not added, when you take Seeker of Misty Isles. 
- And judging by logs, these seems, that there is a few issues with syntax in several bows / weapon focuses
- It cannot recognize token COST for  Remove Domain for Devotion Feat which may be why i do not see this feature
- and there is strange string "Ignoring unknown domain info: !PREABILITY:1,CATEGORY=Internal,Remove Domain Power" about Ordained champion i think

Again sorry to pile up a few things together. Would you prefer for me to attach logs and character to their corresponding issues?

[logs.txt](https://github.com/BahamutDragon/pcgen/files/853810/logs.txt)
[ZenArcher2.zip](https://github.com/BahamutDragon/pcgen/files/853815/ZenArcher2.zip)

**Comment by BahamutDragon** [comment]
* New character or existing? Sometimes the fix will not apply retroactively for level based class grants. Such is the case with the Misty Isle class.
* Likely broke anything looking for a composite bow. Composite bows are treated the same per the rules, but undoing the feats and classes that granted composite versions will be another sweep or two before those references are all cleaned up.
* The Domain swap for Devotion Feats are under the misc tab under Optional Rules, no longer part of the domain set up. 
* Odd, I will look at that.

**Comment by BahamutDragon** [comment]
Your log shows you are using the development branch (master) with a production release of 6.06.01. These two are incompatible. You should use 6.07.01 or a development autobuild if you plan on using the master branch.

**Comment by shadowfury** [comment]
Oh, so sorry, for added confusion with my old pcgen version, will install new pcgen version and check again, thanks a lot for fixes! Even in current version looks great

**Comment by shadowfury** [comment]
After upgrading to new pcgen, it adds extra domains, interacts well with Cloister cleric and works fantastic!

the only issue i see is when i load character (i created a new one for test purposes after upgrade):
![image](https://cloud.githubusercontent.com/assets/2230015/24105927/2632721e-0d8f-11e7-92d5-fc0549ba2d8e.png)

Logs and character attached:
[Unnamed 1.zip](https://github.com/BahamutDragon/pcgen/files/855391/Unnamed.1.zip)
[logs.txt](https://github.com/BahamutDragon/pcgen/files/855394/logs.txt)
