### ISSUE TITLE
[REQUEST] Bad Karma Games - d20 One Piece System Setting

### ISSUE THREAD

**Issue by BahamutDragon** [BahamutDragon/pcgen#650]
Requested source setting

**Comment by StupidUsernames48** [comment]
Wow! That's so cool, I'm so excited for the release of this!

**Comment by BahamutDragon** [comment]
Still a ways to go mate.

**Comment by BahamutDragon** [comment]
Uploaded some initial draft work. In case you would like to assist in the creation. This is strictly a non-loadable version at the moment.

**Comment by BahamutDragon** [comment]
Set loads without errors. Ready for testing, and implementing finer details.

**Comment by BahamutDragon** [comment]
Requested book implemented. Will need play testers to flesh out any further fixes or features.
