### ISSUE TITLE
Dungeon & Dragons: Core Books 3.5

### ISSUE THREAD

**Issue by Jigokusaru** [BahamutDragon/pcgen#652]
While I select the races, i haven't checked all of them, but the ones i do, like Elf from the core books, It does not give me the +2 DEX -2 CON. Is this on purpose, or is it a mistake?

**Comment by BahamutDragon** [comment]
Did you select the Elf Subrace?

**Comment by Jigokusaru** [comment]
I selected no subrace because i want to yous the default from the PHB but it gave me no langues or stats of any kind.

**Comment by BahamutDragon** [comment]
The default subrace is the High Elf. That is the one from Player's Handbook.

**Comment by Jigokusaru** [comment]
Oh, i didnt realize that. thank you
