### ISSUE TITLE
Whisper Gnome (Races of Stone) does not get Speed of 30

### ISSUE THREAD

**Issue by weirdgyn** [BahamutDragon/pcgen#654]
Hallo I have a problem with races of stone dataset (I think) the Whisper Gnome entry is buggy and when I create a new PC of such race I found it with a -6 malus on Jump Skill . I'm using the latest version of PCGEN and the last version of BhamutDragon dataset.

![cattura](https://cloud.githubusercontent.com/assets/6094578/25066199/118d539c-2220-11e7-9c88-c7bb7f545866.PNG)

**Comment by weirdgyn** [comment]
Here's the PC file.

**Comment by BahamutDragon** [comment]
Mate, that is not a race specific issue, that is the actual rules based upon speed, found in the Player's Handbook, page 77: 

> Your Jump check is modified by your speed. If your speed is 30
> feet (the speed of an unarmored human), then no modifier based on
> speed applies to the check. If your speed is less than 30 feet, you take
> a –6 penalty for every 10 feet of speed less than 30 feet. If your speed
> is greater than 30 feet, you gain a +4 bonus for every 10 feet beyond
> 30 feet. For instance, if you have a speed of 20 feet, you take a –6
> penalty on your Jump checks. If, on the other hand, your speed is 50
> feet, you gain a +8 bonus.

**Comment by shadowfury** [comment]
But Whisper gnome speed is 30, not 20

**Comment by BahamutDragon** [comment]
Fixed the speed issue for the Whisper Gnome.

**Comment by weirdgyn** [comment]
Thnx!
