### ISSUE TITLE
Monster Manual III, Warforged Scout

### ISSUE THREAD

**Issue by Jigokusaru** [BahamutDragon/pcgen#656]
Does Monster Manual III have warforged scout? I Didnt see it in races. or anything off the sort.

Edit: Also, can you make the "Mithrial Body" feat an item so it gives the normal bonuses to AC, and penalties?

**Comment by BahamutDragon** [comment]
Warforged Scout does not exist yet mate. The only two creatures that exist are the Rakshasa (Naztharune), and the Gnoll (Flind).

I think if I create the Warforged, I would equip it with a basic armor that would change based upon the feats taken. A little simpler that way.

**Comment by Jigokusaru** [comment]
I see when you have the time, please add these things, I am making a warforged (scout?) for a game im in and my DM wants a copy of sheets on his computer~

**Comment by BahamutDragon** [comment]
8 hours of work for this.  Warforged are extremely complicated blokes.

This should everything expected from a warforged.

**Comment by BahamutDragon** [comment]
Just a note: You will need to update the GameMode to make full use of this change.

**Comment by Jigokusaru** [comment]
update the GameMode? sorry my int is a simple 6.

**Comment by BahamutDragon** [comment]
Depending on how you are set up, there is one file that is part of the system/gamemode folder, https://github.com/BahamutDragon/pcgen/blob/43635482763ea4479830d9b82deba158874716be/system/gameModes/Bahamut35e/equipmentslots.lst

Without that, the character will not work. The rest is inside the data folder as usual.

The tree is set up to mimic the pcgen folder directories.

**Comment by Jigokusaru** [comment]
Ok, thank you just making sure, use your 3.5e not the "35e".
