### ISSUE TITLE
Darkwood Buckler AC Issue

### ISSUE THREAD

**Issue by DivertedCircle** [BahamutDragon/pcgen#657]
The Darkwood Buckler from the 3.5 Dungeon Master's Guide is imposing a -1 AC penalty however per the description of the shield it imposes no AC penalty.

http://dnd.arkalseif.info/dndtools/items/dungeon-masters-guide-v35--4/darkwood-buckler--98/

"This nonmagical light wooden shield is made out of darkwood and often favored by rogues and wizards. It has no enhancement bonus, but its construction material makes it lighter than a normal wooden shield. It weighs 2-1/2 pounds and **has no armor check penalty**."

**Comment by BahamutDragon** [comment]
Not able to reproduce. When I test I get the correct results.

**Comment by BahamutDragon** [comment]
Did some minor corrections to allow a buckler to take Darkwood. No issue found with original report.
