### ISSUE TITLE
[Dnd 3.5e] Invisible Blade (complete warrior)

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#665]
- Dagger sneak attack is not added to special attacks
- Unfettered defense (Int bonus to AC when unarmored) is not added

Character to reproduce - [daringAssassin2.zip](https://github.com/BahamutDragon/pcgen/files/933142/daringAssassin2.zip)

**Comment by BahamutDragon** [comment]
Mate, I really need to get you trained up in LST so you can fix and contribute these yourself.

**Comment by BahamutDragon** [comment]
Requested items implemented

**Comment by shadowfury** [comment]
Thanks for fixing, mate. If you can point me to place where i could docs find for accessing different areas within char-sheet? I tried to fix it myself but something did not click together in the end
