### ISSUE TITLE
[Dnd 3.5e] Hexblade from (CW)

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#666]
Arcane Resistance bonus is always to 1. While it should be equal to Max(Cha, 1) according to description of class feature. Can you please change

in cw_abilities.lst
ASPECT:SaveBonus|+%1 bonus against spells/spell-like effects|min(1,CHA)
to
ASPECT:SaveBonus|+%1 bonus against spells/spell-like effects|max(1,CHA)

**Comment by BahamutDragon** [comment]
Fixed the Hexblade formula
