### ISSUE TITLE
[Dnd 3.5e] feat Able Learner (Races of Destiny)

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#671]
feat Able Learner (Races of Destiny) does not work - it should make cross-class skills cost 1, but you still get 0.5 of a skill point for 1 (cross class skills still cost 2)

**Comment by BahamutDragon** [comment]
Mate, that is a PCGen Team issue. They removed the ability to manipulate skill cost, which in turn means I have no method to adjust skill cost. I could make a nasty hack if that is preferred. But note I say nasty, it will not be pretty.

**Comment by shadowfury** [comment]
Huh, this is nasty.

Can this be solved without pcgen changes? Some logic like adding/substracting extra skill point every time cross skill is selected to that skill?

**Comment by BahamutDragon** [comment]
You are using 3.5 materials. How would the hack know what is a cross-class skill vs. class skill when the skill pool(s) are based upon the specific class? Imagine taking a Fighter/Wizard, Spellcraft is Class for Wizard, but Cross-Class for Fighter. What logic would you propose?

If this were pathfinder, then the logic would be easier, but then again Pathfinder does not impose a 0.5 cost, it does 1 for 1, caps the cross-class and class to current level, then grants a +3 bonus to any class skill with a rank.

The easiest hack would be to create three fake GUI visible skills only, allow you to buy ranks in those which in turn grant points into a pool. From the pool you can grant full ranks to any skill you want. Ugly, but would work.

**Comment by shadowfury** [comment]
I've been thinking about this for a bit. Can this be solved instead of reducing costs we can try to expand class skills by adding class skills. For example:

Level 1 : Wizard (wizard skills)
Level 2 : Fighter (wizard + fighter skills)
Level 3 : Cleric (wizard + fighter + cleric skills)

etc. Is this possible? I know that similar functionality like this exists. Knowledge devotion forever adds Knowledge to class skills, Knowledge Domain adds to Cleric Levels all Knowledge skills to class skill list.

**Comment by BahamutDragon** [comment]
I am not sure I understand your proposal. In 3.5 the only defining method to declare a skill as Class for a given Class is the CSKILL tag is placed on the actual Class object (found in the class file). If CSKILL tag is invoked in any other location that skill is not a Class skill for a specific class, but a global class skill. The only exception is the DOMAIN CSKILL, which places the Class Skill flag on the class that grants the domain. In most cases this is the Cleric.

**Comment by shadowfury** [comment]
Well, i was proposing to add skills of previous class level to current class level. As what able learner effectively does - it makes every skill cost 1 skill point and your max level in that skill is the same as in your class skills.

As you've mentioned that changing cost of skill point is not an option - can we try to add skills to class list instead? 

I propose following formula for skill list of character with level N

Class Skills N (with Able learner) = Class Skills N + Class Skills N-1 (while N > 1)

As i mentioned i've met several feats where class skill list was expanded (Feats like Apprentice, Knowledge Devotion, cleric Domains)

**Comment by shadowfury** [comment]
It will be almost perfect to add skill to global class skill with only exception - skills received in latest classes should not be considered class skills for previous class levels. 

But on the other hand - alternative proposed (adding a copy of skills where user should spend his additional skills),

I think making skills of all classes that character has as global class skill might be best solution

**Comment by shadowfury** [comment]
Sorry mate, it seems my memory failed me for this feat description and i forgot that character can also spend 1 skill points for even skills that are not on any of hit classes lists..

All skill ranks cost 1 skill point for you to purchase, even if the skill is cross-class for you. The maximum number of ranks you can purchase in a cross-class skill remains the same. This feat does not affect the skill point cost to learn a language or to gain literacy (for a barbarian or other illiterate character).

Your solution is the only possible if chabging cost of skill is bit possible. Sorry for trouble
