### ISSUE TITLE
Core35e human skill points & languages

### ISSUE THREAD

**Issue by murzuphle** [BahamutDragon/pcgen#672]
Hello,

I downloaded PCGen 6.06.01 and this repository. I'm using "Dongeons & Dragons - Core Books" (data/35e/wizards_of_the_coast/core/_core_books.pcc) only.
When I create a human cleric, I jave the following issues :
- I don't have the extra skill point per level (human race).
- The "common" language is not preselected and I'm not able to select any bonus language.

I don't have these issues with the SRD 3.5 included with PCGen.

I downloaded this repository and pointed PCGen vendor data to it.
Could you help me?

Thanks.

**Comment by shadowfury** [comment]
You need to select subrace first to obtain benefits of your race on Feats & Abilities -> Race Traits tab. And you usually want to select sub-race before level 1 as bonuses for instance for humans are not retro active (skill points)

**Comment by murzuphle** [comment]
Thanks! It's working now.
Is there anything else I should set before adding levels (which isn't retroactive)?

**Comment by shadowfury** [comment]
In default setting Languages should be selected at 1st level. And be careful with skills - remove levels only when you remove all skill points added by level you want to remove - otherwise at some point either app gonna crash or you would encounter un-removable amount of skills just stuck there

**Comment by BahamutDragon** [comment]
This looks resolved. Closing.
