### ISSUE TITLE
Warforged errors

### ISSUE THREAD

**Issue by guyrish** [BahamutDragon/pcgen#679]
I've merged the MMIII warforged entries and now PCGen is kicking a variety of curious exceptions in the log.

mm3_abilities.lst line 50: NullPointerException
mm3_races.lst line unknown line: !PREFACT:1,ABILITIES,DISABLERACEATTRIBUTESDEFAULT=TRUE, unknown FACT

**Comment by BahamutDragon** [comment]
What version of pcgen are you using?

**Comment by BahamutDragon** [comment]
Assumption that MASTER branch is used with non-development version of PCGen to attain those errors.
