### ISSUE TITLE
Worforged in MMIII and Eberrom confuses PCG

### ISSUE THREAD

**Issue by Jigokusaru** [BahamutDragon/pcgen#681]
When I have Both MMIII and Ebrrom books at the same time the MMIII aditions u made arnt there untill i remove Eberrom

**Comment by BahamutDragon** [comment]
I believe Eberron is coded as the newer source book, which takes precedence over "older" source books, depending on the preference settings. I would need to port the new Warforged changes to the Eberron setting to correct that problem. As the request was focused on MM III, I did not concern myself overly with the Eberron setting.

**Comment by Jigokusaru** [comment]
Ok, i apologize, that was just what book those things were from, and the setting had other stuff in it like Components.

**Comment by BahamutDragon** [comment]
Added Warforged Enhancements to Eberron.
