### ISSUE TITLE
Penetrating Strike (ACF)

### ISSUE THREAD

**Issue by SillyPyro** [BahamutDragon/pcgen#682]
When adding the Penetrating Strike Rogue alternate class feature it should remove Trap Sense, instead it appears to remove Trapfinding.

**Comment by BahamutDragon** [comment]
Mate, what version of pcgen, and which repo branch are you using?

Quick review, and nothing seems incorrect. Do you have a character that shows this happening? (Attach it here for review). 

Best,

**Comment by SillyPyro** [comment]
On second check it looks like it just displays wrong in the Class feats pane at first. The character sheet tab displays it properly and after saving the character, closing and re-opening PCGen the Class feat pane shows correctly too.

Sorry about that.

Regards.
