### ISSUE TITLE
[3.5e] Human should select default "Human" subrace to avoid confusion for new users.

### ISSUE THREAD

**Issue by Ziechael** [BahamutDragon/pcgen#702]
Hi, first off thanks for everyones work on this data set, saves me having to dig through my bookshelf every time i want to throw an NPC together! Secondly, apologies if I don't do this right but I'm a technically able person with all the coding knowledge of a level 0 troglodyte with brain damage.
Using the latest stable release of PCGen (6.06.01) and a fresh download of the repo branch (pcgen-master) I seem to be getting issues with new characters.
When selecting a race they seem to default to having -1 feats and 1 first level feat which means when selecting human they start with 0 feats and 1 first level feat instead of 1 of each?

This is likely a conflict in my huge amount of loaded data but I never used to get it. I currently load the majority of the WotC 3.5 material as well as the Dragon Compendium/Magazine content from Paizo.

I'm aware that this isn't like the most useful post so please advise on what I should do to further diagnose so that clever people like <insert readers name here> can fix the issue or tell me what I'm doing wrong when creating a new character!

Thanks

**Comment by myrlyn** [comment]
If you look in the feats tab, there is now a second listing for first level feat - it is essentially a separate type of Ability used to manage those feats that may only be take an first level.  If you select the "+1 to feat pool" option there, this should fix the issue you are seeing.

**Comment by Ziechael** [comment]
Thanks, but as I mentioned doing that would still just result in a human having a single feat at first level as they are starting with -1 in the main feat pool... choosing human makes that a 0 and then selecting first level feat (+1 to main pool) results in a single feat whereas humans should have 2 at first level.

It also means that all other races are starting with -1 feats in the main pool and selecting the +1 in the first level feat option is resolved to 0 feats at first level.
![screen shot 2017-05-20 at 14 52 46](https://cloud.githubusercontent.com/assets/11630410/26276272/0dff1258-3d6c-11e7-84a5-827a745c0fc0.png)

**Comment by shadowfury** [comment]
You need to select subrace to receive full benefits. For human to function properly, onyle must select subrace before adding level 1. There were a lot of similar bug reports before, does it makes sense to  select default subrace to avoid such issues in future?

**Comment by Ziechael** [comment]
Ah, I get it now, thanks... I thought I'd tried all the variations to get it working right but was consistently selecting 'no subrace' instead of 'human'!

Thanks for explaining and sorry for any inconvenience, i did search previous bug reports before posting but my search-fu failed!!

Keep up the great work everyone!

**Comment by BahamutDragon** [comment]
Mate, you will run into issues if you are using the Master Branch with a production version of pcgen. 6.06.01 and Master are not fully compatible. You should use 6.07.0x (whatever the most recent release is, in this case 6.07.01). 

@shadowfury - We can default select the base human to avoid these reports. Did you want to tackle that?

**Comment by BahamutDragon** [comment]
Oh, and selecting "No Subrace" means you get a blank slate to use. Some variations homebrew games do not use the +1 Feat and +1 Skill Point and that was the way to incorporate those requests to drop it.

**Comment by BahamutDragon** [comment]
All core races now grant the PH default version of the race (subrace) without prompting.

**Comment by shadowfury** [comment]
I was just looking at these though was not able to find where to look for and more importantly, what syntax should i use. Can you direct me, where i can find some readmes about how one can access different areas of pcgen tabs and/or areas on Char sheet? In what format does it parses?
