### ISSUE TITLE
[5e] Sword Coast - Half Elf Sub-Races (Not obvious how to use)

### ISSUE THREAD

**Issue by Camdin03** [BahamutDragon/pcgen#717]
Having the Sword Coast Adventurer's Guide book selected as a source for 5e adds support for Half-Elf "Elf Parentage Race" but the benefits of choosing a sub-race do not translate into results.  For example choosing Moon or Sun should give the choice between "High Elf Weapon Training or Cantrip" but no choice is given and the Elf Parentage Race doesn't even show up on the character sheet.  Attached I've included a sample .pcg character file for a sample Half-Elf build.
[Nailo.zip](https://github.com/BahamutDragon/pcgen/files/1066638/Nailo.zip)

**Comment by BahamutDragon** [comment]
Fixed
