### ISSUE TITLE
3.5e Elemental Savant

### ISSUE THREAD

**Issue by davidgvh** [BahamutDragon/pcgen#722]
When you select Elemental Savant (Complete Arcane) as an available prestige class, you see the below dialog for prohibited schools. The box is empty. If anything, it should ask for an energy type instead of prohibited school in the same fashion that Energy Substitution (Complete Arcane) does.

You can click cancel to continue. Only generic information shows in the feat listing. Perhaps that is intentional and acceptable. Regardless, displaying prohibited schools is confusing since it is irrelevant to the prestige class. Since clicking cancel does not cancel the level addition, the button is misleading too for the dialog. Not sure if that is a PCGen issue though.

![image](https://user-images.githubusercontent.com/2607868/27805655-9765d8ea-5ffb-11e7-86c4-db341b20866b.png)

**Comment by davidgvh** [comment]
After a slew of PCGen bugs, I am now seeing the elemental savant automatically specialized with specific information on the character sheet. The prohibited school dialog still displays though.

**Comment by BahamutDragon** [comment]
Reworked how the class works. That should handle the issue with choices.
