### ISSUE TITLE
spell Invisibility, Superior(Spell Compendium, p. 125) dont work

### ISSUE THREAD

**Issue by psychomantys** [BahamutDragon/pcgen#728]
Spell lvl on description show only the spell from complete arcana, and duplicated.

If you like, a can upload a *.pcg with a test case for spell search...

Ideal:
* If Complete Arcane loaded, show 9th spell (Superior Invisibility)
* If Spell Compendium loaded, show 8th level spell (Invisibility, Superior)
* If both, show both

![shot1](https://user-images.githubusercontent.com/2066648/28799347-99e75966-761e-11e7-8785-e2d19826865b.png)
![shot2](https://user-images.githubusercontent.com/2066648/28799348-99eb73c0-761e-11e7-8b26-73836ac7efa6.png)

**Comment by BahamutDragon** [comment]
Fixed

**Comment by psychomantys** [comment]
tks!

:D :D
