### ISSUE TITLE
[Player's Guide to Faerun] Race selection freeze

### ISSUE THREAD

**Issue by jonovotny** [BahamutDragon/pcgen#748]
I am having problems creating Gnome characters with the Player's Guide to Faerun loaded. A soon as I select Gnome on the Summary or Race tab PcGen freezes. I tried to capture log output to fix it myself, but the logger seems frozen as well. Here is what I get before I do the selection:

```
01:19:57.750 INFO main Main:140 Starting PCGen v6.07.04
01:19:57.797 INFO main LanguageBundle:133 Initialising language bundle with locale en_US.
01:19:58.592 SEVERE main Main:440 Unexpected exception loading fonts fo print p
java.io.IOException: Can't read C:\Users\novotny\PcGenData\pcgen\outputsheets\fonts\NotoSans\NotoSans-Regular.ttf
	at java.awt.Font.createFont(Font.java:1054)
	at pcgen.system.Main.initPrintPreviewFonts(Main.java:433)
	at pcgen.system.Main.startupWithGUI(Main.java:234)
	at pcgen.system.Main.main(Main.java:161)

01:19:59.395 WARNING Plugin-loading-thread PluginClassLoader:153 Plugin not found in Function-GETFACT.jar
01:20:13.315 INFO Thread-6 SourceFileLoader:555 Loading game 35e and sources [Dungeons & Dragons - Core Books, Player's Guide to Faerun].
```
 

Also tested it with v6.0.0 with the same result. Other races work without freezing.

**Comment by BahamutDragon** [comment]
Mate, 

Looks like you have a corrupt font file. You should grab a fresh download or their zip folder and try again. 

Best,

**Comment by jonovotny** [comment]
Just tried it again with a fresh install on a different system (6.07.04 win installer on Win10 64 + Git clone of the books). Did not get the font error this time, but PcGen still freezes as soon as i select gnome as race with the player's guide loaded. With only core everything works fine.

**Comment by BahamutDragon** [comment]
Fixed
