### ISSUE TITLE
[5e] Incorrect race movement speed for Aasimar.

### ISSUE THREAD

**Issue by Proxxy0** [BahamutDragon/pcgen#749]
I have not checked if any of the other races have the correct movement speed, but I noticed that the movement speed for the Aasimar race, when selected, is 20 ft. I then looked in the race tab, to see that the movement speed was set to walk 0. Once I saw this, I looked through the racial files, trying to fix this issue client side. I had to change 5 different files before anything happened to my character's movement speed. These files were: vgm_races.lst and races_x.lst from both the main 5e volo directory and the custom sources volo directory, and mm_races.lst from the main 5e monster manual directory. I have not looked to see if any other stats were incorrect, or if any other race had the same issue.

**Comment by BahamutDragon** [comment]
Mate,

Base Aasimar comes up with 30' movement loading Volo and Core.  Anything else special going on? Wearing armor, weighed down by gear, or anything else?

**Comment by Proxxy0** [comment]
I'm loading all of the available books that can be loaded together, and I'm wearing light and medium armor. Other than that, nothing special. I reinstalled all the files, in case I was working on an older version, but on the Race menu, it still says that the Aasimar race has a 0 ft walk speed, and the character sheet shows a 20 ft walk speed.

![image](https://user-images.githubusercontent.com/24647397/32138713-a1ceb7c8-bc05-11e7-9bbd-cfdf4b5ca963.png)


![image](https://user-images.githubusercontent.com/24647397/32138720-bf019f68-bc05-11e7-80ab-1cc1ffc12611.png)

**Comment by BahamutDragon** [comment]
Mate,

Can you post the character file for me?

The race tab is correct. The initial 0 is for customization. The actual race grants 30.
