### ISSUE TITLE
[5e - Request] Pegasus Mount.

### ISSUE THREAD

**Issue by Proxxy0** [BahamutDragon/pcgen#750]
For the current game I'm running, one of the players managed to receive a Pegasus mount. I was hoping to be able to use the mounts section of the companions tab to add the said mount to the player, but since this race is still one of the races in progress, I was unable to do so. Is there any way that this might be given some priority over some of the other races in the 'in progress' races of the monster manual?

**Comment by BahamutDragon** [comment]
Added.
