### ISSUE TITLE
[35e] Heroes of Horror's Dread Necromancer's Advance Learning Spells Aren't Appearing

### ISSUE THREAD

**Issue by Patcheresu** [BahamutDragon/pcgen#753]
PCGen 6.06.01

"At 4th level, a dread necromancer can add a new spell to her list, representing the result of personal study and experimentation. The spell must be a cleric or wizard spell of the necromancy school, and of a level no higher than that of the highest-level spell the dread necromancer already knows."

![image](https://user-images.githubusercontent.com/12682917/32360522-ebaee806-c02c-11e7-9d77-e558bf60c4c6.png)

I only end up ever getting these three as choices when the choices should be, all Necromacy spells, Clr or Wiz, whose level are basically Dread Necromancer Level/2 at most.

**Comment by BahamutDragon** [comment]
Fixed.

**Comment by Patcheresu** [comment]
Thanks so much for doing this so fast!

**Comment by Patcheresu** [comment]
Thanks for your fast fix on this, but I think you may have made an error.

The 20th Level Advance Learning should have enough CL (a normal Dread Necro 18 should) to access a 9th Spell Slot Advance Learning, but yours is hard coded to go to 8 tops.

**Comment by BahamutDragon** [comment]
Corrected the typo.

**Comment by Patcheresu** [comment]
Thanks a lot, man!
