### ISSUE TITLE
Armor Class 5e 

### ISSUE THREAD

**Issue by rwm2406** [BahamutDragon/pcgen#755]
Hello BahamutDragon, 
I have a 4th level Human variant Life Domain Cleric, with a Dexterity score of 16 (+3 mod), a shield (+2 mod)  and a Breastplate (base 14 + Dex modifier (max 2) so for me 16. All total my AC should only be 18 (14+2 Dex+2 Shield) but when I look at my character sheet on PC gen, it says my AC is 30, with a base of 20, with +4 from my Armor, +4 from my Stat Bonus, and +2 Shield Bonus. 

 believe I have installed all the files to the correct locations, and I have no trouble with the AC in the 3.5 or Final Fantasy home brews you provided, but in 5e the AC values are all wrong.  I'm not sure what's wrong. 

Also, on the spells tab, and on the character sheet, the Cantrips, or 0-level spells are displayed twice in the "Spells Known" subsection

**Comment by BahamutDragon** [comment]
I am unable to reproduce the AC issue. It correctly displays 18 for me.

I can remove the extra cleric 0th level spells.
