### ISSUE TITLE
GM award - Bonus Cantrip

### ISSUE THREAD

**Issue by jagbear** [BahamutDragon/pcgen#758]
My GM has awarded me a bonus cantrip.  I've tried using the GM award code from the 35e setting, and I'm able to get it shown on the MISC screen, but I'm not able to actually add the cantrip.  Any help in adding this cantrip would be appreciated.

Thank you!

**Comment by BahamutDragon** [comment]
Mate, the 3.5e code is not set up to support 5e in any form.  Added a method to add cantrips based upon the class you desire.

Best,

**Comment by jagbear** [comment]
I have been trying for the past 12 days to try to find out where this code appears in the screens.  I see the code in the files, but I'm not seeing it as something I can add.  Not even the existing code such as the adding an extra feat or hit point.  Can you tell me where in the screens this is located?  Maybe I'm missing something.
