### ISSUE TITLE
Fix for expanded knowledge feat please

### ISSUE THREAD

**Issue by TheBigDee** [BahamutDragon/pcgen#76]
The "Expanded Knowledge" feat (Expanded Psionics Handbook): "You can choose any power, including powers from another discipline's list or even from another class's list".

BD, the change you implemented earlier doesn't appear to have fixed it. I'm pretty sure I've got your change as the bonus feat at level 5 is now appearing as per the other issue that you fixed earlier but I can't see any change to this feat.

Cheers,
G.

**Comment by BahamutDragon** [comment]
Still not working.

**Comment by LegacyKing** [comment]
For easy reference: http://jira.pcgen.org/browse/CODE-2626
CODE-2626
CHOOSE:SPELLS|SPELLTYPE= providing empty list

**Comment by BahamutDragon** [comment]
Sill unresolved by PCGen team. Notation in data set added.
