### ISSUE TITLE
Wrong PREALIGN for Kord in 35e Player's Handbook Deities

### ISSUE THREAD

**Issue by esb** [BahamutDragon/pcgen#760]
In file  pcgen/data/35e/wizards_of_the_coast/core/players_handbook/ph_deities.lst, Kord listed as

```
Kord				KEY:Kord			DOMAINS:Chaos,Good,Luck,Strength|PREALIGN:NG,CG,NG			DEITYWEAP:Greatsword			ALIGN:CG	FACTSET:Pantheon|Base|PH					SOURCELONG:Player's Handbook	SOURCESHORT:PH		SOURCEPAGE:p.107	SORTKEY:Gods_a
```
PREALIGN should be 'LG,CG,NG'

**Comment by BahamutDragon** [comment]
Mate, looks like there is a typographical issue, but the PREALIGN should not include "LG". That would be two steps from CG - Chaos -> Neutral -> Lawful. CG can have CN, NG, and the base of CG.

**Comment by BahamutDragon** [comment]
Fixed.
