### ISSUE TITLE
[Dnd 3.5] Wizard Feat category is incomplete

### ISSUE THREAD

**Issue by marcalff** [BahamutDragon/pcgen#761]
According to the PHB 3.5, Wizard class, p57,
Bonus feats are:
- Spell Mastery
- Any item creation feat
- Any metamagic feat

In particular, metamagic feats from books other that the PHB, such as:
- twin spell (Complete Arcane)
- rapid spell (Complete Divine)
- etc

should be available as bonus feats to a wizard at levels 5, 10, 15 and 20.

**Comment by BahamutDragon** [comment]
Issue corrected
