### ISSUE TITLE
5e pdf export doesn't print the campaign history

### ISSUE THREAD

**Issue by jagbear** [BahamutDragon/pcgen#764]
Not sure if this is pcgen or the datafiles from here.  I'm raising a question on pcgen.org as well.   When I go to export the character to pdf, the campaign history is missing.  I've tried exporting and printing to a pdf.  I've tried several different templates and the campaign history still doesn't show even though the last few entries are selected to be included on the character sheet.

**Comment by BahamutDragon** [comment]
Mate, I do not control the features of the pcgen UI and subsequent export. That would be best directed to the pcgen project volunteers. I mainly concern myself with book content.

Best,
