### ISSUE TITLE
5E unable to load campaigns - NPE

### ISSUE THREAD

**Issue by princeorion** [BahamutDragon/pcgen#776]
looks like same issue as 3.5e, but with 5e files

<details>
  <summary>Click to expand</summary>
  11:59:37.741 INFO Thread-8 SourceFileLoader:555 Loading game 5e and sources [Blood Hunter Class, Gunslinger Class, Tal'Dorei Campaign Setting, Witch Hunter Class, D&D Wiki, DMG - Kitsune, DMG - Lightborn, Dungeon Master's Guild (Full), Homebrew Support, Adventure - Out of the Abyss, Adventure - Tyranny of Dragons, Sword Coast Adventurer's Guide, Dungeons & Dragons 5e - Core Books, Elemental Evil Player's Companion, Plane Shift: Innistrad, Unearthed Arcana: Feats, Unearthed Arcana: Psionics, Unearthed Arcana: Feats for Skills, Unearthed Arcana: Waterborne Adventures, Unearthed Arcana - Artificer, Unearthed Arcana - Barbarian Primal Paths, Unearthed Arcana - Eberron, Unearthed Arcana - That Old Black Magic, Volo's Guide to Monsters, Xanathar's Guide To Everything].
11:59:40.664 SEVERE Thread-8 CDOMFactory:118 Unconstructed Reference: SizeAdjustment G
11:59:40.664 SEVERE Thread-8 TrackingReferenceContext:123   Was used in null in tokens: [?]
11:59:40.664 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/monster_manual/mm_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
11:59:40.664 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/universal_rules/ur_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
11:59:40.664 SEVERE Thread-8 CDOMFactory:118 Unconstructed Reference: SizeAdjustment H
11:59:40.664 SEVERE Thread-8 TrackingReferenceContext:123   Was used in null in tokens: [?]
11:59:40.664 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/monster_manual/mm_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
11:59:40.664 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/universal_rules/ur_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
11:59:40.664 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/monster_manual/mm_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
11:59:40.664 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
11:59:40.664 SEVERE Thread-8 CDOMFactory:118 Unconstructed Reference: SizeAdjustment L
11:59:40.664 SEVERE Thread-8 TrackingReferenceContext:123   Was used in null in tokens: [?]
11:59:40.664 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/monster_manual/mm_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
11:59:40.664 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/universal_rules/ur_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
11:59:40.664 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/monster_manual/mm_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
11:59:40.664 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
11:59:40.664 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/players_handbook/ph_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
11:59:40.664 SEVERE Thread-8 CDOMFactory:118 Unconstructed Reference: SizeAdjustment M
11:59:40.664 SEVERE Thread-8 TrackingReferenceContext:123   Was used in null in tokens: [?]
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/universal_rules/ur_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/monster_manual/mm_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/critical_role/gunslinger_fighter_archetype/gfa_equip.lst in tokens: [plugin.lsttokens.equipment.SizeToken]
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/players_handbook/ph_equipmods.lst in tokens: [plugin.lsttokens.equipmentmodifier.SpropToken]
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/supplement/elemental_evil_players_companion/eepc_equip.lst in tokens: [plugin.lsttokens.equipment.SizeToken]
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/dungeon_masters_guide/dmg_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/dungeon_masters_guild/kitsune/kit_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_equip.lst in tokens: [plugin.lsttokens.equipment.SizeToken]
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/players_handbook/ph_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/supplement/elemental_evil_players_companion/eepc_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/dungeon_masters_guild/lightborn/lb_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/players_handbook/ph_equip.lst in tokens: [plugin.lsttokens.equipment.SizeToken]
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/waterborne_adventures/ua_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/artificer/ua_art_equip.lst in tokens: [plugin.lsttokens.equipment.SizeToken]
11:59:40.680 SEVERE Thread-8 CDOMFactory:118 Unconstructed Reference: SizeAdjustment S
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in null in tokens: [?]
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/universal_rules/ur_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/monster_manual/mm_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
11:59:40.680 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
11:59:40.696 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/players_handbook/ph_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
11:59:40.696 SEVERE Thread-8 CDOMFactory:118 Unconstructed Reference: SizeAdjustment T
11:59:40.696 SEVERE Thread-8 TrackingReferenceContext:123   Was used in null in tokens: [?]
11:59:40.696 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/universal_rules/ur_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
11:59:40.696 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/monster_manual/mm_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
11:59:40.696 SEVERE Thread-8 TrackingReferenceContext:123   Was used in file:/C:/Users/NXF18836/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/players_handbook/ph_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
11:59:41.618 SEVERE Thread-8 IsdefaultsizeToken:81 Did not find a default size
11:59:41.618 LSTWARN Thread-8 SizeNumToken:106 SizeAdjustment items must have a SIZENUM
11:59:42.71 SEVERE Thread-8 SourceFileLoader:545 Exception loading files.
java.lang.NullPointerException
	at pcgen.cdom.reference.CDOMDirectSingleRef.<init>(CDOMDirectSingleRef.java:60)
	at pcgen.cdom.reference.CDOMDirectSingleRef.getRef(CDOMDirectSingleRef.java:198)
	at pcgen.cdom.enumeration.FormulaKey$1.getDefault(FormulaKey.java:91)
	at pcgen.cdom.base.CDOMObject.getSafe(CDOMObject.java:209)
	at plugin.lsttokens.NaturalattacksLst.process(NaturalattacksLst.java:419)
	at plugin.lsttokens.NaturalattacksLst.process(NaturalattacksLst.java:61)
	at pcgen.rules.context.LoadContextInst.processPostRes(LoadContextInst.java:264)
	at pcgen.rules.context.LoadContextInst.resolvePostDeferredTokens(LoadContextInst.java:246)
	at pcgen.rules.context.RuntimeLoadContext.resolvePostDeferredTokens(RuntimeLoadContext.java:20)
	at pcgen.persistence.SourceFileLoader.finishLoad(SourceFileLoader.java:768)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:507)
	at pcgen.persistence.SourceFileLoader.execute(SourceFileLoader.java:243)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:73)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:41)
	at pcgen.gui2.util.SwingWorker$1.run(SwingWorker.java:160)
	at java.lang.Thread.run(Thread.java:748)
</details>

If it was something i did wrong please let me know

**Comment by princeorion** [comment]
Small update - tried uninstalling and reinstalling and loading just the SRD, same result

**Comment by BahamutDragon** [comment]
Looks like the PCGen team altered the GameMode on their end. Let me update the files.

**Comment by BahamutDragon** [comment]
Fixed
