### ISSUE TITLE
Monkey Grip 

### ISSUE THREAD

**Issue by ColdStubby** [BahamutDragon/pcgen#777]
The Monkey Grip feat in 3.5e doesn't appear to work. After selecting the feat and buying a large weapon for a medium character I am unable to equip the weapon as it is tagged as TooLarge. All I have the option to do is carry it. Surely this weapon should be equippable?

**Comment by ColdStubby** [comment]
I meant to add that this is a 2-handed weapon (greatsword in this instance), as a one handed weapon would be equipped as 'both hands' which is also wrong with this feat. I have tried this in the 6.04 and 6.06 versions of PCGen with your additions. Many thanks for your efforts on this, I find it an incredibly useful tool!

**Comment by BahamutDragon** [comment]
Mate, this will work with Two-Handed weapons now. If I do One-Handed, then they will become Light.
