### ISSUE TITLE
Dwarven Urgrosh display is off for two-weapon fighting block.

### ISSUE THREAD

**Issue by dmcbride** [BahamutDragon/pcgen#780]
The urgrosh, when equipped, is showing damage as "1d8+4/+1" (as an example for urgrosh +1;- and STR 16). It should show up as "1d8+4/1d6+1" or similar.

![image](https://user-images.githubusercontent.com/1534589/36408225-687b0d3a-15c1-11e8-9d90-82e0f27478e8.png)

**Comment by BahamutDragon** [comment]
Mate, that appears to be an PCGen team output sheet problem, not a data problem on my end.

**Comment by draconswan** [comment]
From my knowledge of PCGen output sheets, the default display of weapons read from a single WEAPON.DAMAGE variable:
http://pcgen.org/autobuilds/pcgen-docs/outputsheetpages/tokens/outputsheettokensweapon.html#weapon

Looking at the preview file (preview\d20\5e\Standard.htm.ftl), it doesn't appear to be coded to read the ALTDAMAGE, ALTCRIT, and ALTMULT variables for double weapons.  An updated to all of the preview/output sheets would be needed to properly detect and display properties for double weapons

**Comment by BahamutDragon** [comment]
PCGen team has addressed this issue.
