### ISSUE TITLE
Favored Soul Feat issues in 6.06.01

### ISSUE THREAD

**Issue by Anaerin** [BahamutDragon/pcgen#781]
Trying to create a favored soul using these data files in 6.06.01 and PCGen is giving strange "+1 to Feat Ability Pool" feats (that only create more of themselves if you try and delete them) and is not allowing existing actual feats (like Power Attack, for instance) to be removed.

**Comment by BahamutDragon** [comment]
Mate,

Are you using the older 6.06.01 data files with pcgen 6.06.01? Or are you using the latest files in the master?

**Comment by Anaerin** [comment]
I'm using the master branch. But now I see it, I should probably be using the 6.06.x branch.
