### ISSUE TITLE
Xanathar's Guide: Bards Colleges missing?

### ISSUE THREAD

**Issue by Faldrian** [BahamutDragon/pcgen#782]
Hi!

I recently tried to create a bard and wanted to use the College of Swords, but only the colleges from the Players Handbook are listed.
I know that it is "alpha" - is there a good manual how to edit those listing-files? The only thing I found on the pcgen side was a wall of text with some hints to perl scripts or something... is there a userfriendly tutorial or guide how to get started editing those files and check them for sanity before starting pcgen?

Sorry to make this a ticket that seems slightly offtopic... I just didn't know how to get in touch in another way. But I'm happy to help, if the book can be made more complete. :)

**Comment by BahamutDragon** [comment]
Mate, looks like the colleges were missing the proper type. Corrected that oversight. Best,

**Comment by Faldrian** [comment]
Thank you for the quick response :)
I now coul choose the college, but as a lvl 3 bard, I should gain Bonus Proficiencies ("medium armor", "scimitar"), Fighting Style (with a choice between "Dueling" and "Two-Weapon Fighting") and Blade Flourish.
Maybe there are more keys missing or these features are not yet implemented? :)

**Comment by BahamutDragon** [comment]
Hi mate, 

Yes, looks like most of that is just text blocks. Great excuse to get others involved to flesh that out. I enabled the proficiencies and the fighting style choice.  If you want to work on other parts of the book, feel free. All are welcome to participate.

**Comment by Faldrian** [comment]
I would really like to... is there a reasonable understandable help text to get working on the file format and validity-checking done on linux? As in: What tools are there and how do I understand that file format and dependencies / possibilities within it?
