### ISSUE TITLE
Xanathar's Guide: Spells not populating

### ISSUE THREAD

**Issue by TempusRimeblood** [BahamutDragon/pcgen#784]
When trying to create a character using the Xanathar's Guide To Everything supplement, not all spells that are available for the class populate.

Example:

Creating a Warlock, the cantrips "Create Bonfire" and "Infestation" are not available.  Nor are any other spells, of any level, that are available solely through Xanathar's Guide.  I have seen that the spells are in the .lst file, I'm just not sure of how to implement them.

**Comment by BahamutDragon** [comment]
Sorry about that mate. Fixed.
