### ISSUE TITLE
[Dnd 3.5] Complete Arcane, Mage Armor (Greater), missing temporary bonus

### ISSUE THREAD

**Issue by marcalff** [BahamutDragon/pcgen#785]
In PC gen, under tab Temporary Bonus, under Spell,
the "Mage Armor" spell is available, but the "Mage Armor, Greater" spell is not available.

Suggested fix:
In data/35e/wizards_of_the_coast/supplement/complete_arcane/car_spells.lst,
add this to the Mage Armor (Greater) entry:
TEMPBONUS:ANYPC|COMBAT|AC|6|TYPE=Armor

**Comment by BahamutDragon** [comment]
Feature added.
