### ISSUE TITLE
6.07.06 compatibility issue

### ISSUE THREAD

**Issue by draconswan** [BahamutDragon/pcgen#786]
I'm trying to load just the D&D 5e Core Books PCC file and it's giving me a FNF exception for this file:
C:\store\pcgen-6.07.06\data\_universal\races.lst (The system cannot find the path specified).

I extracted the latest data set from here and copied it into the data\homebrew folder.  I don't see any folders named _universal at all in pcgen, either in the extracted dataset of PCGen's install.

**Comment by BahamutDragon** [comment]
Mate, the file will exist when the pcgen team releases the next version. They are making some serious changes that will break things if not addressed at that time. If you want the folder and files, it is here: https://github.com/PCGen/pcgen/tree/master/data
