### ISSUE TITLE
Seeker of the Misty Isle

### ISSUE THREAD

**Issue by ajohnson-ventera** [BahamutDragon/pcgen#787]
I ran into three issues, two were easy to fix in the reference data.

1) Seeker of the Misty Isle's requirements are incorrect. They should be `knowledge (religion) 4` and `survival 8` and is a quick fix.

2) SotMI allows you to progress arcane spellcasting, which also seems to cause another issue with spell levels. But if you change `ADD:SPELLCASTER|ANY` to `ADD:SPELLCASTER|Divine` this will be corrected on both fronts.

3) While the domain list reflects the correctly added `Travel` domain, the spells are not added to the spell list.

**Comment by BahamutDragon** [comment]
All 3 issues should now be fixed mate.

Best,
