### ISSUE TITLE
5E Unearthed Arcana - Artificer 'Gunsmith' not granted Class Features

### ISSUE THREAD

**Issue by SanityAwol** [BahamutDragon/pcgen#790]
@Wemes @BahamutDragon Sorry this is my first time dropping an issue I don't even know I I am supposed to put it here If not I am sorry. I was creating an Artificer from Unearthed Arcana in 5th edition and I noticed that the  Artificer doesn't have a weapon proficiency in the Thunder Cannon so it inaccurately displays the To-Hit value.  Not a huge deal But I noticed and thought you might like to know.

**Comment by BahamutDragon** [comment]
Mate, you should find the Artificer Gun Smith a lot more interesting to play with all the class features added. 

Best,

**Comment by SanityAwol** [comment]
Thank you very much.
