### ISSUE TITLE
[3.5] Righteous Might - temporary bonuses

### ISSUE THREAD

**Issue by ajohnson-ventera** [BahamutDragon/pcgen#792]
Natural Armor: Righteous might is currently granting 8 Natural Armor, it should only grant `2 size natural armor` and `2 enhancement natural armor`. The natural armor AC should not stack with an enhancement bonus from a piece of equipment.

Strength: Righteous Might is bumping strength by 8 and temporary strength 16. It should only grant `4 size bonus to strength`

Constitution: Righteous Might is bumping constitution by 4 and temporary constitution by 8. It should only grant `2 size bonus to constitution`

Damage Reduction: Righteous Might is granting `5/good` for an 11th level caster that channels positive energy. That situation should result in a `3/evil`, a 12th level cleric should get `6/evil`.

**Comment by BahamutDragon** [comment]
Mate, 

You'll need to cite the rules change if you want me to alter what the spell already says, and how it operates. This is the text from the spell:

_"Your height immediately doubles, and your weight increases by a factor of eight. This increase changes your size category to the next larger one, and you **gain a +8 size bonus to Strength and a +4 size bonus to Constitution. You gain a +4 enhancement bonus to your natural armor**. You gain damage reduction 5/evil [if you normally channel positive energy] or damage reduction 5/good [if you normally channel negative energy]. At 12th level this damage reduction becomes 10/evil or 10/good, and at 15th level it becomes 15/evil or 15/good [the maximum]. Your size modifier for AC and attacks changes as appropriate to your new size category. This spell doesn't change your speed.  Determine space and reach as appropriate to your new size. If insufficient room is available for the desired growth, you attain the maximum possible size and may make a Strength check [using your increased Strength] to burst any enclosures in the process. If you fail, you are constrained without harm by the materials enclosing you- the spell cannot crush you by increasing your size. All equipment you wear or carry is similarly enlarged by the spell. Melee and projectile weapons deal more damage. Other magical properties are not affected by this spell. Any enlarged item that leaves your possession [including a projectile or thrown weapon] instantly returns to its normal size. This means that thrown weapons deal their normal damage [projectiles deal damage based on the size of the weapon that fired them]. Multiple magical effects that increase size do not stack."_

_

**Comment by ajohnson-ventera** [comment]
http://www.d20srd.org/srd/spells/righteousMight.htm

**Comment by ajohnson-ventera** [comment]
Looks like it was errata.

http://archive.wizards.com/default.asp?x=dnd/news/20040910news

**Comment by ajohnson-ventera** [comment]
Either way it looks like the affects are being applied twice. Sorry I didn't realize that there was a change that impacted it.

**Comment by BahamutDragon** [comment]
Applied the effects of the spell, disabled the normal size changes.

**Comment by ajohnson-ventera** [comment]
Cheers!
