### ISSUE TITLE
[3.5] UA - Whirling Frenzy Variant

### ISSUE THREAD

**Issue by ajohnson-ventera** [BahamutDragon/pcgen#795]
I can select the whirling frenzy variant in the class features, but I don't seem to have any way to apply it. The normal rage shows up as a `Temporary Bonus` and applies correctly. But there is no `Frenzy`, `Whirling Frenzy` or anything else that looks similar.

I know its probably easy enough to add the strength, dodge ac, and reflex increases, but the application of the flurry template is probably a lot more complicated.

**Comment by ajohnson-ventera** [comment]
Also, it looks like having that rage variant disqualifies you for rage feats like `Extend Rage` and `Extra Rage`. As far as I can tell, you still are raging, its just a variant of rage.

**Comment by BahamutDragon** [comment]
The temp bonus was never granted. And some of the tags were incorrect. Frenzy type was missing to qualify for the feats. Should be fixed now.
