### ISSUE TITLE
Xanathars Feats not showing up in Feat Lists

### ISSUE THREAD

**Issue by Kaiuskain** [BahamutDragon/pcgen#796]
im trying to use the prodigy feat and its not showing up in the list the lst file says Not Implimented in the Desc. I dont know if removing that will let it be used or not im not a coder or what ever just a avid dnd player wanting better character gen.

**Comment by Kaiuskain** [comment]
its all of the Feats not just Prodigy FYI

**Comment by BahamutDragon** [comment]
Implemented.
