### ISSUE TITLE
Forge Cleric Proficiency's

### ISSUE THREAD

**Issue by Kaiuskain** [BahamutDragon/pcgen#798]
Sorry to bother you again but The Domains for the Clerics from Xanathar's don't give the Proficiency's they offer and their Spells aren't separated in to Domain spells specifically and i had a hard time finding them at first they weren't in the Domain list  but i don't know if that's just  pcgen things. Thank you again

**Comment by BahamutDragon** [comment]
Mate,

This is going to be quite an undertaking. Re-reading the rules, you are correct, we need to define the domain spells since they are always prepared. I need to ponder a proper solution and check in with the pcgen team on how they would address it.

**Comment by Kaiuskain** [comment]
mk What about the Profeciency in Heavy armor and Smith tools? ask the team about that as well?

**Comment by BahamutDragon** [comment]
Granting proficiency is the same as elsewhere. Just adding the correct tags.
