### ISSUE TITLE
[PF] Monk - Master of Many Styles

### ISSUE THREAD

**Issue by ajohnson-ventera** [BahamutDragon/pcgen#799]
Master of Many Styles should replace Monk Bonus Feats, but it seems like selection for both exist at level 1 and level 2.

Also, I think there is a weird interaction if you take level 1 of brawler, and then add a level of monk. I think it grants you 2 levels worth of bonus feats.

Finally, I'm not sure if this is an issue or not, but is there any way to enable the affects of a combat style?

**Comment by BahamutDragon** [comment]
Mate,

I do not edit the official pcgen files, nor am I part of their team. I am just a humble role-playing gamer that enjoys using pcgen and creating data for my own gaming group. I just happen to share my work here to allow them easy access. As a bonus, that means it is available to anyone who wishes to enjoy the labor I have done.

The only pathfinder I have in my repo is the Granny Drake, Wyrd of Questhaven, Book of the Faithful, and some homebrew support for Final Fantasy.

Best,

**Comment by ajohnson-ventera** [comment]
You are totally correct, I noticed it wasn't in yours later and didn't put it together. Super sorry about that. You do great work, thanks.
