### ISSUE TITLE
5e Racial Feats from Xanathar's Guide

### ISSUE THREAD

**Issue by jagbear** [BahamutDragon/pcgen#800]
The racial feats don't appear in the feats list and I can't figure out how to get them to appear.  I can  help get the rest coded and implemented, I just can't figure out how to get them to appear so I can test them.

If one can be done, I can work on the rest.

Thank you!

**Comment by BahamutDragon** [comment]
They appear in the feat list. The method I am aware of is taking the alternate human, removing the stat bonus for a feat. Alternatively, on the feat tab, you can grant yourself any number of feats. My group has never used feats, which is why I have not implemented the bonuses til now.

**Comment by jagbear** [comment]
I think I see what's happened, the changes have been made, but after I downloaded the set.  I'll check this weekend and download the latest version.

Thank you!

**Comment by BahamutDragon** [comment]
No further updates from OP. Closing this out as resolved.
