### ISSUE TITLE
Error messages about Campaigns with Same Name in Different Locations

### ISSUE THREAD

**Issue by juneauej** [BahamutDragon/pcgen#805]
If I load Advanced>5e>Wizards of the Coast>Dungeons & Dragons 5e - Core Books, there are some errors about duplicate file names in different locations (log file below). I think this happens on other rule books too.

`20:13:41.525 INFO main Main:140 Starting PCGen v6.07.08
20:13:41.597 INFO main LanguageBundle:134 Initialising language bundle with locale en_GB.
20:13:50.425 SEVERE main Globals:533 Loaded Campaigns with matching names (5e ~ Gunslinger Class) at different Locations: file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/data/5e/critical_role/gunslinger_fighter_archetype/_gunslinger_fighter_archetype.pcc file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/critical_role/gunslinger_fighter_archetype/_gunslinger_fighter_archetype.pcc
20:13:50.436 SEVERE main Globals:533 Loaded Campaigns with matching names (5e ~ Tal'Dorei Campaign Setting) at different Locations: file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/data/5e/critical_role/Tal'Dorei_Campaign_Setting/Tal'Dorei_Campaign_Setting.pcc file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/critical_role/Tal'Dorei_Campaign_Setting/Tal'Dorei_Campaign_Setting.pcc
20:13:50.443 SEVERE main Globals:533 Loaded Campaigns with matching names (5e ~ Witch Hunter Class) at different Locations: file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/data/5e/critical_role/witch_hunter/_witch_hunter.pcc file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/critical_role/witch_hunter/_witch_hunter.pcc
20:13:50.459 SEVERE main Globals:533 Loaded Campaigns with matching names (5e - D&D Wiki) at different Locations: file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/data/5e/dndwiki/_dndwiki.pcc file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/dndwiki/_dndwiki.pcc
20:13:50.468 SEVERE main Globals:533 Loaded Campaigns with matching names (5e - CR - Blood Hunter Class - Order of the Lycan) at different Locations: file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/data/5e/dungeon_masters_guild/blood_hunter/order_of_the_lycan/_order_of_the_lycan.pcc file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/dungeon_masters_guild/blood_hunter/order_of_the_lycan/_order_of_the_lycan.pcc
20:13:50.479 SEVERE main Globals:533 Loaded Campaigns with matching names (5e - CR - Blood Hunter Class) at different Locations: file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/data/5e/dungeon_masters_guild/blood_hunter/_blood_hunter.pcc file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/dungeon_masters_guild/blood_hunter/_blood_hunter.pcc
20:13:50.486 SEVERE main Globals:533 Loaded Campaigns with matching names (5e - DMG - Dragon Knight Class) at different Locations: file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/data/5e/dungeon_masters_guild/dragon_knight/_dragon_knight.pcc file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/dungeon_masters_guild/dragon_knight/_dragon_knight.pcc
20:13:50.494 SEVERE main Globals:533 Loaded Campaigns with matching names (5e - DMG - Kitsune) at different Locations: file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/data/5e/dungeon_masters_guild/kitsune/kitsune.pcc file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/dungeon_masters_guild/kitsune/kitsune.pcc
20:13:50.506 SEVERE main Globals:533 Loaded Campaigns with matching names (5e - DMG - Lightborn) at different Locations: file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/data/5e/dungeon_masters_guild/lightborn/_.pcc file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/dungeon_masters_guild/lightborn/_.pcc
20:13:50.520 SEVERE main Globals:533 Loaded Campaigns with matching names (5e - Dungeon Master's Guild) at different Locations: file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/data/5e/dungeon_masters_guild/_dungeon_masters_guild.pcc file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/dungeon_masters_guild/_dungeon_masters_guild.pcc
20:13:50.531 SEVERE main Globals:533 Loaded Campaigns with matching names (5e - Homebrew Support) at different Locations: file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/data/5e/homebrew/_.pcc file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/homebrew/_.pcc
20:13:51.256 SEVERE main FacadeFactory:130 Campaign file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/critical_role/gunslinger_fighter_archetype/_gunslinger_fighter_archetype.pcc lists GAMEMODE:5e multiple times.
20:13:51.257 SEVERE main FacadeFactory:130 Campaign file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/critical_role/Tal'Dorei_Campaign_Setting/Tal'Dorei_Campaign_Setting.pcc lists GAMEMODE:5e multiple times.
20:13:51.257 SEVERE main FacadeFactory:130 Campaign file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/critical_role/witch_hunter/_witch_hunter.pcc lists GAMEMODE:5e multiple times.
20:13:51.257 SEVERE main FacadeFactory:130 Campaign file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/dndwiki/_dndwiki.pcc lists GAMEMODE:5e multiple times.
20:13:51.258 SEVERE main FacadeFactory:130 Campaign file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/dungeon_masters_guild/blood_hunter/order_of_the_lycan/_order_of_the_lycan.pcc lists GAMEMODE:5e multiple times.
20:13:51.258 SEVERE main FacadeFactory:130 Campaign file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/dungeon_masters_guild/blood_hunter/_blood_hunter.pcc lists GAMEMODE:5e multiple times.
20:13:51.258 SEVERE main FacadeFactory:130 Campaign file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/dungeon_masters_guild/dragon_knight/_dragon_knight.pcc lists GAMEMODE:5e multiple times.
20:13:51.259 SEVERE main FacadeFactory:130 Campaign file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/dungeon_masters_guild/kitsune/kitsune.pcc lists GAMEMODE:5e multiple times.
20:13:51.259 SEVERE main FacadeFactory:130 Campaign file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/dungeon_masters_guild/lightborn/_.pcc lists GAMEMODE:5e multiple times.
20:13:51.259 SEVERE main FacadeFactory:130 Campaign file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/dungeon_masters_guild/_dungeon_masters_guild.pcc lists GAMEMODE:5e multiple times.
20:13:51.259 SEVERE main FacadeFactory:130 Campaign file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/homebrew/_.pcc lists GAMEMODE:5e multiple times.
20:14:14.523 INFO Thread-6 SourceFileLoader:567 Loading game 5e and sources [Dungeons & Dragons 5e - Core Books].
20:14:16.182 LSTERROR Thread-6 LstUtils:166 SPELLLEVEL arguments uses double separator || : DOMAIN|Tempest Domain=1|Fog Cloud,Thunderwave||Tempest Domain=2|Gust of Wind,Shatter|Tempest Domain=3|Call Lightning,Sleet Storm|Tempest Domain=4|Control Water,Ice Storm|Tempest Domain=5|Destructive Wave,Insect Plague (Source: file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/wizards_of_the_coast/core/players_handbook/ph_domains.lst )
20:14:16.183 LSTERROR Thread-6 LstUtils:166 Failed in parsing typeStr: SPELLLEVEL DOMAIN|Tempest Domain=1|Fog Cloud,Thunderwave||Tempest Domain=2|Gust of Wind,Shatter|Tempest Domain=3|Call Lightning,Sleet Storm|Tempest Domain=4|Control Water,Ice Storm|Tempest Domain=5|Destructive Wave,Insect Plague for pcgen.core.Domain Tempest Domain
20:14:16.183 LSTERROR Thread-6 LstUtils:166 Illegal Token 'SPELLLEVEL' 'DOMAIN|Tempest Domain=1|Fog Cloud,Thunderwave||Tempest Domain=2|Gust of Wind,Shatter|Tempest Domain=3|Call Lightning,Sleet Storm|Tempest Domain=4|Control Water,Ice Storm|Tempest Domain=5|Destructive Wave,Insect Plague' for pcgen.core.Domain Tempest Domain in file:/C:/Users/Eric/AppData/Local/PCGen/6.07.08/vendordata/5e/wizards_of_the_coast/core/players_handbook/ph_domains.lst
`

**Comment by BahamutDragon** [comment]
Mate, that looks like you have duplicates in your vendordata and data folders locations. That is something you need to address.  I cannot find any double pipes in the current data.
