### ISSUE TITLE
[5e] [REQUEST] Tiefling Subraces - MTOF

### ISSUE THREAD

**Issue by mestevesf** [BahamutDragon/pcgen#808]
Could you add the Tiefling Subraces from mordenkainen's tome of foes? 

Thanks and keep up the awesome work!

**Comment by BahamutDragon** [comment]
Initial upload. Does not negate base race stats, and spells are not implemented.

**Comment by BahamutDragon** [comment]
Okay mate, that should fulfill the request, and alter the other reliant sets to the new methods.

**Comment by mestevesf** [comment]
Thanks Mate!

Keep you the good work! Will try to contribute with the project as soon as I find out how to create content to PC Gen.

cheers
