### ISSUE TITLE
"Amanuesis" name typo

### ISSUE THREAD

**Issue by dmcbride** [BahamutDragon/pcgen#812]
Amanuensis is in Magic of Faerun. From what I can see, this looks all correct. There is the same spell in the Spell Compendium book, but the data set spells it as "Amanuesis" (missing an "n" before "sis").

This misspelling also shows up in sc_equip.lst, although it's commented out there. (Any temptation to uncomment it would result in the typo being used, so either fix the spelling or remove it.)

Mind you, maybe PCGen would complain about the spell changing levels here between the two versions of what looks like the exact same spell.

**Comment by BahamutDragon** [comment]
Fixed
