### ISSUE TITLE
Released Basic Rules

### ISSUE THREAD

**Issue by Berahthraben** [BahamutDragon/pcgen#815]
I'd like to use the D&D 5th Edition (Basic Rules), but it says it's dependency is:  "less than 2 of ( BOOKTYPE=Core Rules, less than 1 of 5e - Basic must be already selected )". Can you tell me how to solve this, please?

**Comment by BahamutDragon** [comment]
Mate, I think your issue is with PCGen team:

My 5e set for basic is:
CAMPAIGN:D&D 5th edition (Basic Rules)
KEY:Basic Rules 5e

Why are you not using the complete rules - Players and Dungeon Master complete books?
Basic is an early rule set.

**Comment by Berahthraben** [comment]
Yeah, I got it working, but thanks haha.
