### ISSUE TITLE
Precocious Apprentice feat

### ISSUE THREAD

**Issue by ColdStubby** [BahamutDragon/pcgen#816]
D&D3.5: Adding the Precocious Apprentice feat from Complete Arcane to a 1st level Bard does not work correctly. Only get the option to add another 0 level cantrip, when should be able to add a single second level spell that can be cast. This should also later become an additional 2nd level spell slot once 2nd level spells are castable by the bard character.

**Comment by BahamutDragon** [comment]
Altered system, now have to manually add for any new caster classes. Support for:
Bard	
Cleric
Wizard
Sorcerer
Wu Jen
Warmage
