### ISSUE TITLE
[5E] Implement Plane Shift supplements

### ISSUE THREAD

**Issue by silasary** [BahamutDragon/pcgen#822]
- [x] [Plane Shift: Zendikar](https://magic.wizards.com/en/articles/archive/feature/plane-shift-zendikar-2016-04-27)
- [x] [Plane Shift: Innistrad](http://www.dragonmag.com/5.0/#!/article/106375/102161027)
- [x] [Plane Shift: Kaladesh](https://magic.wizards.com/en/articles/archive/feature/plane-shift-kaladesh-2017-02-16)
- [x] [Plane Shift: Amonkhet](https://magic.wizards.com/en/articles/archive/feature/plane-shift-amonkhet-2017-07-05)
- [x] [Plane Shift: Ixalan](https://magic.wizards.com/en/articles/archive/feature/plane-shift-ixalan-2018-01-09)
- [x] [Plane Shift: Dominaria](https://magic.wizards.com/en/articles/archive/feature/plane-shift-dominaria-2018-07-31)

**Comment by BahamutDragon** [comment]
All implemented.

**Comment by silasary** [comment]
Awesome, thankyou 😊
