### ISSUE TITLE
[5E] Lizardfolk Barbarian AC not calculating correctly

### ISSUE THREAD

**Issue by Joram316** [BahamutDragon/pcgen#824]
I made a level 1  Lizardfolk Barbarian and took the  Barbarian unarmored defense. My barbarian has a Dex: 16 (+3) and a Con: 19 (+4). according to the PHB  he should have an AC of 17 ( 10 + dex mod + con mod.).
I got an AC fo 13 which is less than the lizardfolk's natural Ac which is 13+ dex mod (16). 
I made a human Barbarian with the same stats and the AC calcuated correctly

![bar ac](https://user-images.githubusercontent.com/42596342/44440915-4d94a780-a598-11e8-83d7-a224f94ab849.png)

**Comment by BahamutDragon** [comment]
![image](https://user-images.githubusercontent.com/4307487/44443075-ab21f780-a58a-11e8-9838-dcee5849d917.png)

Works for me mate.

**Comment by BahamutDragon** [comment]
The character Sheet you are using looks off. 5e does not use Base Attack. Are you using the latest version?

![image](https://user-images.githubusercontent.com/4307487/44443150-25527c00-a58b-11e8-9279-e84b12d35be8.png)

**Comment by Joram316** [comment]
I figured out what I did. I installed the data folder wrong. I still have the base attack box on the sheet but I get a correct calculation for AC. sorry to have bothered you with this

**Comment by Joram316** [comment]
I found the problem, the starting equipment plus what I get from the outlander and the lizardfolk hunter backgrounds put me into the medium encumberance range. as soon as I got rid of some of it it went back to normal.
