### ISSUE TITLE
5e UA Stone Sorcerer

### ISSUE THREAD

**Issue by YoFizz** [BahamutDragon/pcgen#825]
Can we get UA Stone Sorcerer added? Thank you so much, love all the work you do.

**Comment by BahamutDragon** [comment]
Added.

**Comment by YoFizz** [comment]
looks great, the only problem i'm seeing is stone's durability doesn't seem to be calculating right? it stops at +3 as your modifier so if I have 18 or 20 con it still only counts to 3

**Comment by BahamutDragon** [comment]
Works fine for me. Are you encumbered or wearing armor?

![image](https://user-images.githubusercontent.com/4307487/44621110-54037780-a855-11e8-85eb-15ce99b8525d.png)

**Comment by YoFizz** [comment]
oops i'm dumb, it was medium encumberment. i always forget thats a thing, sorry about that. and thank for doing this, i appreciate all the effort you've put into the project as a whole. built my first character ever on pcgen with your stuff.

**Comment by BahamutDragon** [comment]
I will reach out to the PCGen team and ask if the encumberance rule indicator can be added to the preview sheet. That might avoid these issues. You are the second person to run afoul of that rule within the last week or two.
