### ISSUE TITLE
Fey Sprite(Grig) ECL

### ISSUE THREAD

**Issue by FerretDave** [BahamutDragon/pcgen#837]
This is more of a query than an issue (I will fix and submit a PR if things need changing).
I have a 'Sprite(Grig)' as a player character, and it has one level of 'Fey' as it's first class, and then has character levels.

The Fey adds 1 level, and Grig adds ECL 3 - so without the character levels I'm showing this as a level 4 character. Is that right ?
Should the Grig ECL therefore be only 2, to offset this? or should the Fey class define an ECL of MINUS one, and all the fey races define at least an ECL 1 ?

Or, for a player character, should I *not* be selecting 'Fey' as the first class ? (but then, without character levels, that would not be usable at all I guess?)

**Comment by BahamutDragon** [comment]
Mate, 

The Monster Manual entry for that race is plain. You get 1/2 d6+1 (Level 1 of Fey), for any PC race, it adds +3 Level Adjustment. You are treated as a 4th level character. 

![image](https://user-images.githubusercontent.com/4307487/45600438-85cdb100-b9b1-11e8-88e0-0a701f380a82.png)

**Comment by FerretDave** [comment]
Thanks for confirming, it was the '1 level of Fey' that I wasn't sure about, guess I need to re-read the MM about that, Savage Species also confirms 4 levels before any PC class levels. Just my understanding of that 'racial class' level effect.
