### ISSUE TITLE
domain ability error on load

### ISSUE THREAD

**Issue by FerretDave** [BahamutDragon/pcgen#842]
having created a cleric (chaotic evil/deity Grummsh) and selected the 'evil' domain (works for 'war' and possibly others too), I get an error on load of that character:

Ignoring unknown domain info: !PREABILITY:1,CATEGORY=Internal,Remove Domain Power (Evil).

This is related to 
Evil»---»-------¶
»-------PREALIGN:LE,NE,CE»------»-------»-------»-------»-------¶
»-------ABILITY:Domain|AUTOMATIC|Evil»--»-------¶
»-------SOURCEPAGE:p.186¶
»-------DESC:You cast evil spells at +1 caster level.|!PREABILITY:1,CATEGORY=Internal,Remove Domain Power (Evil)»

in ph_domains.lst, so there's something wrong with this:
Remove Domain Power»----CATEGORY:Internal»------TYPE:Remove Domain Power»-------CHOOSE:ABILITY|Domain|PC[TYPE=Domain]»--MULT:YES»-------STACK:NO¶

in ph_abilities.lst ?

**Comment by BahamutDragon** [comment]
This should load error free now.
