### ISSUE TITLE
I get FACT errors when loading T20

### ISSUE THREAD

**Issue by mjmeans** [BahamutDragon/pcgen#856]
I tried T20 with last months' version of PCGen, (i.e. not the Java 10 version that just came out). It will not load. Gives several FACT errors. I copied the T20 data and gamemodes folders into the PCGen data and gamemodes folders.

Also, your main readme talks about the autoload links. Those haven't worked since march 2017, a year and a half ago.

**Comment by BahamutDragon** [comment]
Fixed.
