### ISSUE TITLE
"Illegal token" error when loading eepc supplement

### ISSUE THREAD

**Issue by SlidingHorn** [BahamutDragon/pcgen#858]
[pcgen.log](https://github.com/BahamutDragon/pcgen/files/2537468/pcgen.log)

I wanted to load the eepc supplement because it has spells I wanted to make available for a druid character that aren't available in the srd files.  When I go to load the source, I get the errors shown in the attached log.

I'd love to try to fix it, but unfortunately, I'm brand new at this and don't quite get it.  Looking at the PCGen documentation for lst files didn't provide much insight.

I'm running PCGen 6.07.08 on Ubuntu MATE, if that provides any helpful clues.

**Comment by BahamutDragon** [comment]
Mate, 

02:35:44.584 SEVERE main Globals:533 Loaded Campaigns with matching names (5e - Universal Rules) at different Locations: 
file:/home/ryan/pcgen/data/5e/wizards_of_the_coast/universal_rules/_universal_rules.pcc 
file:/home/ryan/pcgen/data/homebrew/5e_customized/wizards_of_the_coast/universal_rules/_universal_rules.pcc

That is your own issue. I cannot fix that for you. Rest should work now.

Best,
