### ISSUE TITLE
Adding Cleric spells to Divine Soul?

### ISSUE THREAD

**Issue by wilfredom** [BahamutDragon/pcgen#865]
Not sure if it's an issue, but I couldn't find how to add Cleric spells to Divine Souls. Am I missing something is it a pending feature?

**Comment by BahamutDragon** [comment]
Mate,

The feature now implemented for PH and XGtE. Any other books will need to be requested.

Best,

**Comment by wilfredom** [comment]
Thanks for the prompt reply--I was referring to XGtE. I'm using 6.08.00 RC2, and I don't see where I can add Cleric spells, after loading Xanathar's and choosing Divine Soul as the sorcerous origin. I select the Magic Affinity and can see that spell in the Prepared Spells section, but nothing else.

**Comment by wilfredom** [comment]
I saved, reloaded, leveled up, and created a new char--no dice. This is my setup at the moment, with  6.08.00 RC2:

![capture](https://user-images.githubusercontent.com/15095683/50058270-b5b06000-012a-11e9-937e-e4023c60723e.JPG)
![capture2](https://user-images.githubusercontent.com/15095683/50058272-ba751400-012a-11e9-8891-b64f30f60754.JPG)

Are those the right files?

**Comment by BahamutDragon** [comment]
Mate,

Did you download and replace the existing data files with the ones I updated? I see Bane which would be working in the original set, but the new spells will only be available if you replace the file with my update.

Your file should have this update: https://github.com/BahamutDragon/pcgen/commit/3917ecd826dfe153920ca786e9ac4f26893f851d
