### ISSUE TITLE
[DnD 3.5] Grace ability spelled as Grave + issue with ability

### ISSUE THREAD

**Issue by sholafsson** [BahamutDragon/pcgen#867]
Complete Warrior ability Grace is misspelled in cw_abilities.lst line 37 "ASPECT:NAME|Grave +%1|Grace_Bonus". Also character gets "Cannot use this ability" even though it has no armour and nothing carried. But bonus seems to show up in Saves, Reflex, Misc

**Comment by BahamutDragon** [comment]
Fixed both reported issues mate.

**Comment by sholafsson** [comment]
Thanks for the extremely quick response! There also seem to be similar pre-req issues with other Swashbuckler abilities such as Insightful Strike and Dodge. In addition the dodge bonus is for some reason incorrectly calculated (is always 0)

**Comment by BahamutDragon** [comment]
New reports for other issues. Keeps the logs clean mate.
