### ISSUE TITLE
Generic Classes in Unearthed Arcana 35e

### ISSUE THREAD

**Issue by Thorngage** [BahamutDragon/pcgen#872]
Was trying to use the Generic Classes from Unearthed Arcana (Warrior, Expert and Spellcaster) but they appear to not work, they have no class skills and it doesn't prompt you to choose any, also they should be labeled as (UA) after the name of the class to make them different from the same classes by the same name in the DMG. Also none of the classes seem to recieve their bouns Feat. I would correct this myself, but I really don't know how to use git to commit changes and I fear I might mess up comething.

I wouldn't personally know how to use their bonus feat to choose class features if not by creating new feats that give class features (i.e. Sneak attack) with pre-req beign an expert/warrior/Spellcaster

Also, this is Unrelated, but when adding the "remove default bonus languages" ability in feat & abilities>misc>override default languages no language becomes actually selectable, it gets stuck

**Comment by Thorngage** [comment]
Not sure what you mean by rekey, but based on what gut says I believe it's a bug you're working on? Thank you anyway. Should I signal bugs here for the 3.5 or would it be just a pain in the a#% if I do? I really appreciate this massive work you did and I don't want to sound whiny

**Comment by Thorngage** [comment]
I've seen the mods you did for the generic classes, they all seem to work fine now (they appear in the class drop down menu as CG_expert eccetera)

Only thing is, the spellcasters don't seem to have acces to spell, you're prompted to choose your spells, but none are selectable, also they don't count as spellcasters for feats (I cannot select Craft wondrous Items)

One of these days i'll learn how to change the codes myself and how to push changes via git... any tutorials you'd reccomend to learn (I'm using github desktop to update the projects)

**Comment by BahamutDragon** [comment]
This patch should address the lack of spells and count as a spellcaster.

**Comment by BahamutDragon** [comment]
Google is how I learned the git. Not sure if I could help you more than the existing tutorials out there mate.

**Comment by BahamutDragon** [comment]
Have you had a chance to retest this?

**Comment by Thorngage** [comment]
Spellcaster now function correctly, The language thing is still bugging

**Comment by BahamutDragon** [comment]
Mate, the remove default bonus language is a tool to completely remove all the race selectable bonus languages. Unless you have explicitly programmed in a replacement, then all it does is remove any bonus language selection that would be available due to high intelligence. The only place this is used is for the Faerun races.

That said, I believe we can close this out.
