### ISSUE TITLE
Permission for Git

### ISSUE THREAD

**Issue by Thorngage** [BahamutDragon/pcgen#877]
I know, I'm a big ol' pain. But since 3.5 is quite old and not many people still play it I want to contribute myself without wasting your time Bahamut!
I'm learning to use gitHub so that I can make changes myself. I made some changes to the binder, to add some stuff, I checked they were working, created my own branch of the project and wanted to create a pull request, but git tells me I need to publish the branch first. But it says I need Permission to do so 
![immagine](https://user-images.githubusercontent.com/46561511/51468306-e78e9500-1d6e-11e9-8936-2fdde00a0d83.png)
Is that something you think you can do?

**Comment by silasary** [comment]
you want to create a fork, then push your branch there

You can then make a pull request from your fork to the main repository

>

**Comment by Thorngage** [comment]
Ok I think I got it

**Comment by BahamutDragon** [comment]
Believe or not, most of the people coming here still use the 3.5 edition materials. It's a good mix of 3.5e and 5e players based upon the requests and reports I see. The other esoteric systems do not see any use to my knowledge since we lack the character sheets for them.
