### ISSUE TITLE
Lizardfolk Subrace not applying

### ISSUE THREAD

**Issue by Thorngage** [BahamutDragon/pcgen#882]
I'm making a Lizardfolk character and it prompts me to choose a subrace, one option is viletooth, from dragon magic, and it works, the other option is standard lizardfolk, from MM... But it seems like nothing happens if I select it, the pool doesn't get to 0 and no subrace gets added. As said, the Viletooth seems to be working fine
https://media.discordapp.net/attachments/501257389794787348/541347355438612490/unknown.png

I've brought this up on Discord to try and fix it myself, wasn't able to. The issue itself is very stupid and does not actually cause any real problem (not selecting anything is the same as selecting lizardfolk) but the summary will keep asking me to select a subrace, and in this specific instance, the character specifically one of the few standard Lizardfolk in a Viletooth Tribe

**Comment by BahamutDragon** [comment]
I believe I have fixed this. Please give it a test mate.

**Comment by Thorngage** [comment]
Yep, everything works fine on my end now!
