### ISSUE TITLE
[5e]  Elemental Evil Backgrounds not Available

### ISSUE THREAD

**Issue by CobaltEcho** [BahamutDragon/pcgen#884]
I see Elemental Evil has been added, loaded the sources, restarted PCGen, etc.  However, not seeing the Elemental Evil Character Backgrounds.

Ref: http://dndadventurersleague.org/wp-content/uploads/2015/04/Mulmaster-Bonds-and-Backgrounds.pdf

List:
Caravan Specialist
Earthspur Miner
Harborfolk
Mulmaster Aristocrat
Phlan Refugee

Am I missing something?

![screenshot](https://user-images.githubusercontent.com/26211498/52368675-005ca300-2a1d-11e9-8150-33dbcf788f38.jpg)

**Comment by BahamutDragon** [comment]
I have the 25-page Elemental Evil Player's Companion, and there are no backgrounds listed.  Is that from a supplement sheet or from another source perhaps? 

That pdf you linked lacks page numbers and does not have any markings to authenticate it as an official WotC source, the typographical errors and inconsistent font and page layout lead me to suspect that is a homebrew supplement. 

Here is a page from that EEPC just for comparison:

![image](https://user-images.githubusercontent.com/4307487/52393305-5f8cd880-2a5a-11e9-9368-8d2f150bd891.png)
