### ISSUE TITLE
Unable to Create Character [Starwars D20]

### ISSUE THREAD

**Issue by Jasoneagle** [BahamutDragon/pcgen#886]
I am Currently Unable to Create a New Character in the Starwars d20 Setting. returns error is null.

**Comment by mechkit** [comment]
Same for 5e.

**Comment by grimreaper** [comment]
Hey - can you give me more test details on https://pcgenorg.atlassian.net/browse/CODE-3368? I am able to get an exception but it appears to have been broken since at least 
```
commit 21ffe1ff0fa5ebde9c0dbb8f3971b50fcda92d56 (HEAD)
Merge: 78ae17cf3f 7ca51e0056
Author: Martijn Verburg <martijnverburg@gmail.com>
Date:   Wed Apr 25 22:30:49 2018 +0100
```

I need to know what changed if something broke - or if its always been broken and some logic is wrong.

**Comment by BahamutDragon** [comment]
@grimreaper to my knowledge, all my sets worked fine with 6.06.01. There has been a lot of changes during the lead up to the 6.08.x series release. It has been a whirlwind of debugging to keep all the sets compatible with each iteration release.

**Comment by LegacyKing** [comment]
Hey, file missing from the gamemode is the culprit. Add 'codeControl' which needs these entries:

`# This is a YES/NO code control to enable "Alignment" throughout a game mode
ALIGNMENTFEATURE:YES

# This is a YES/NO code control to enable "Domain" throughout a game mode
DOMAINFEATURE:YES
`

**Comment by BahamutDragon** [comment]
Thanks for the info. Correcting and testing on my end.
