### ISSUE TITLE
Melee and Range Attack Table preview/output

### ISSUE THREAD

**Issue by drklassen** [BahamutDragon/pcgen#890]
In both the preview and the output sheet the block for Melee and Ranged Attack Bonus is all zeros.  The preview sheet uses the variables ATTACK.x.y where x=MELEE and RANGED and y=TOTAT, STAT, SIZE, and MISC.  All of these are zeroes as if nothing is ever setting them.

**Comment by BahamutDragon** [comment]
Which game system are you running? 

Is TOTAT a typo mate, or is that taken directly from the sheet?

**Comment by drklassen** [comment]
Sorry, forgot about mode...  5e loading Dungeons & Dragons 5e - Core Books and  5e - Xanathar's Guide To Everything.  TOTAT was a typo for TOTAL.
