### ISSUE TITLE
Cannot Create Whisper Gnome - PCGen v6.06.01

### ISSUE THREAD

**Issue by dialdial** [BahamutDragon/pcgen#892]
Hello.  I am having a problem creating a Whisper Gnome for D&D 3.5e.  

I'm using the latest stable version of PCGen (v6.06.01) and the last version of the BhamutDragon Dataset (Master - downloaded April 7, 2019).

The Whisper Gnome subrace is not listed in the Race tab of PCGen, and neither are two other races from Races in Stone, Chaos Gnome or Dream Dwarf. Feral Gargun, Goliath, and Stonechild are available.

I also have an odd issue, which might be more to the root of the matter.  I've added all of the books in the **Select Source - Advanced** tab necessary to create a Whisper Gnome Rogue / Swashbuckler / Swordsage; however, when I Save Source Selection and return to the **Select Source - Basic** tab, there are several requirements in red, even though they are included in the list, and everything was black in the Advanced tab.

I will include the list below, and the errors I am receiving below that.  I apologize if I am taking up your time with something that is very simple and avoidable.  Thank you for your help, and all of your hard work.  This is an awesome resource.

**Books: Select Source - Advanced tab**
Champions of Ruin
Complete Adventurer
Complete Warrior
Dungeon Master's Guide II
Dungeons & Dragons - Core Books
Expanded Psionics Handbook
Lords of Madness
Monster Manual II
Monster Manual III
Player's Guide to Faerun
Player's Handbook II
Races of Stone
Races of the Wild
Spell Compendium
Tome of Battle: The Book of Nine Swords

**Errors: Select Source - Basic tab**
Races of Stone - Requirements: INCLUDESBOOKTYPE=Core35e

Complete Warrior - Requirements: INCLUDESBOOKTYPE=Core35e

Tome of Battle: The Book of Nine Swords - Requirements: INCLUDESBOOKTYPE=Core35e

Spell Compendium - Requirements: INCLUDESBOOKTYPE=Core35e

Player's Guide to Faerun - Requirements: INCLUDESBOOKTYPE=Core35e

Champions of Ruin - Requirements: INCLUDES=Player's Guide to Faerun and INCLUDES=Spell Compendium

Complete Adventurer - Requirements: INCLUDESBOOKTYPE=Core35e

Lords of Madness - Requirements: all of ( INCLUDESBOOKTYPE=Core35e, INCLUDES=Monster Manual II )

Races of the Wild - Requirements: INCLUDESBOOKTYPE=Core35e

Dungeon Master's Guide II - Requirements: INCLUDESBOOKTYPE=Core35e

Expanded Psionics Handbook - Requirements: INCLUDESBOOKTYPE=Core35e

Monster Manual II - Requirements: INCLUDESBOOKTYPE=Core35e and INCLUDES=Expanded Psionics Handbook

Monster Manual III - Requirements: INCLUDESBOOKTYPE=Core35e

Player's Handbook II - Requirements: INCLUDESBOOKTYPE=Core35e

**Comment by BahamutDragon** [comment]
You will not find subraces under the race tab. You need to select the base race "Gnome" and then under Feats and Abilities select the Subrace.
