### ISSUE TITLE
[Book Request] PF1 Kemonomimi races by Amora Game

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#895]
http://www.d20pfsrd.com/races/3rd-party-races/amora-game/kemonomimi/

**Comment by BahamutDragon** [comment]
Do you have the PDF you can send me? Websites can alter names, and do not have proper reference points for clarification.

**Comment by GamerGoddessDin** [comment]
https://drive.google.com/file/d/1U4fzunM9kHoqCq1LHrSnL0aMoNrfzTla/view?usp=sharing

I was able to spare the $3. Here you go.

**Comment by BahamutDragon** [comment]
Added the book.
