### ISSUE TITLE
Case, Crossbow bolt can not take 20 bolts

### ISSUE THREAD

**Issue by Glassboy** [BahamutDragon/pcgen#898]
Equipping a Case, Crossbow bolt does not make it available as a container for Crossbow Bolts (20).  However other items such as a sheet of parchment can be added to it.

**Comment by Glassboy** [comment]
Actually you can only add parchment to a crossbow bolt case as replicates a map case "CONTAINS:UNLIM|Total=10|Paper=10|Documents=10|Scroll=10	COST:1	WT:1"

**Comment by BahamutDragon** [comment]
Corrected.

**Comment by Glassboy** [comment]
This does allow the case to take crossbow bolts, but now you can add 400 which is 380 more than the max :-)
