### ISSUE TITLE
Massive Errors in Logs & Memory

### ISSUE THREAD

**Issue by Menethoran** [BahamutDragon/pcgen#902]
Please see attached log file in text form...
Also, this may be an error that I myself am causing, but do not know why or how as ive set up your kit several times and this is the first time im seeing these errors...

[errors-PCGen.txt](https://github.com/BahamutDragon/pcgen/files/3225151/errors-PCGen.txt)

**Comment by BahamutDragon** [comment]
Mate, are you using the master branch with the 6.08 version of PCGen?

**Comment by Menethoran** [comment]
Holy Crap, I didn't even realize the PCGen version...

Will move back to 6.05 and test... My bad :)

**Comment by Menethoran** [comment]
OK... so, cleaned out old PCGen install, installed 6.06... still have a slew of errors popping in log.

[New Text Document.txt](https://github.com/BahamutDragon/pcgen/files/3227895/New.Text.Document.txt)

**Comment by BahamutDragon** [comment]
I think you misunderstand. Branch 6.08 is for 6.08. If you have a 6.09.x then you use Master.

I would recommend 6.08.x uses branch 6.08.

**Comment by Menethoran** [comment]
Still having the same massive errors log generate when loading sources...
Verified 6.08 install, 6.08 branch...
(I tried 6.09, but for some reason, I cant left click on any popup windows with 6.09… so went back to 6.08...)
Please see attached log...
[6.08errors.txt](https://github.com/BahamutDragon/pcgen/files/3232734/6.08errors.txt)

**Comment by BahamutDragon** [comment]
Don't load Epic or Matt Mercer Campaign. That patch should address those, but just avoid those 2 sets and the rest of the errors should be reduced.
