### ISSUE TITLE
[4e] Warlock automatic At-Will powers not showing up

### ISSUE THREAD

**Issue by fish-face** [BahamutDragon/pcgen#904]
Using PCGen 6.08.00 RC6 on the 6.08 branch, if I create a Lvl 1 Warlock and select an Eldritch Pact, I can add Daily and Encounter Powers, but not At-Wills. I then realised from reading the source data that these should be showing up automatically, but they are not. You can't add them, however - though you *can* add the At-Wills for the wrong pacts, because the "Remaining" number of At-Wills is still shown as 2.

**Comment by BahamutDragon** [comment]
Should be fixed now.
