### ISSUE TITLE
LSTERRORS Xanathar's guide to everything

### ISSUE THREAD

**Issue by woofdunlap** [BahamutDragon/pcgen#908]
Branch 6.08

$ ./pcgen.sh 
Available memory: 554336 kB
There is less than 1 GB of free memory available. Will keep default memory limits
min: 256 MB, max: 512 MB
10:13:54.492 INFO main Main:138 Starting PCGen v6.08.00 RC6
10:13:54.660 INFO main LanguageBundle:134 Initialising language bundle with locale en_US.
10:14:08.376 INFO Thread-2 SourceFileLoader:534 Loading game 5e and sources [Player's Handbook, Dungeon Master's Guide, Monster Manual, Sword Coast Adventurer's Guide, Xanathar's Guide To Everything].
10:14:09.151 LSTERROR Thread-2 LstUtils:147 First token of SPELLLEVEL must be CLASS or DOMAIN:KNOWN|Ranger=1|Protection From Evil And Good|PRECLASS:1,Ranger=3 (Source: file:/home/woof/Library/pcgenbd/data/5e/homebrew/bahamutdragon/5e/wizards_of_the_coast/supplement/xanathars_guide_to_everything/xgte_abilities.lst )
10:14:09.151 LSTERROR Thread-2 LstUtils:147 Failed in parsing typeStr: SPELLLEVEL KNOWN|Ranger=1|Protection From Evil And Good|PRECLASS:1,Ranger=3 for pcgen.core.Ability MONSTER SLAYER MAGIC
10:14:09.152 LSTERROR Thread-2 LstUtils:147 Illegal Token 'SPELLLEVEL' 'KNOWN|Ranger=1|Protection From Evil And Good|PRECLASS:1,Ranger=3' for pcgen.core.Ability MONSTER SLAYER MAGIC in file:/home/woof/Library/pcgenbd/data/5e/homebrew/bahamutdragon/5e/wizards_of_the_coast/supplement/xanathars_guide_to_everything/xgte_abilities.lst

Found that there was duplicates in the lst.
Here is the git diff

diff --git a/data/5e/wizards_of_the_coast/supplement/xanathars_guide_to_everythi
index b1516b0..4443ddb 100644
--- a/data/5e/wizards_of_the_coast/supplement/xanathars_guide_to_everything/xgte
+++ b/data/5e/wizards_of_the_coast/supplement/xanathars_guide_to_everything/xgte
@@ -198,7 +198,7 @@ DISTANT STRIKE              KEY:Ranger Archetype ~ HORIZON W
 SPECTRAL DEFENSE               KEY:Ranger Archetype ~ HORIZON WALKER ~ SPECTRAL
 
 # Ranger Archetype ~ MONSTER SLAYER
-MONSTER SLAYER MAGIC   KEY:Ranger Archetype ~ MONSTER SLAYER ~ MONSTER SLAYER M
+MONSTER SLAYER MAGIC   KEY:Ranger Archetype ~ MONSTER SLAYER ~ MONSTER SLAYER M
 HUNTER'S SENSE         KEY:Ranger Archetype ~ MONSTER SLAYER ~ HUNTER'S SENSE  
 SLAYER'S PREY          KEY:Ranger Archetype ~ MONSTER SLAYER ~ SLAYER'S PREY   
 SUPERNATURAL DEFENSE   KEY:Ranger Archetype ~ MONSTER SLAYER ~ SUPERNATURAL DEF
~

**Comment by BahamutDragon** [comment]
SPELLKNOWN tags removed.
