### ISSUE TITLE
REQ: [5e] Increase ability score and maximum

### ISSUE THREAD

**Issue by thirteenwings** [BahamutDragon/pcgen#909]
Request: For 5th ed, a way to increase an ability score and its maximum value, to reflect the use of a book item that increases an ability score, such as a Manual of Bodily Health. These items increase by 2 both the ability score and its maximum value, allowing scores greater than 20. There's a book for each of the 6 ability scores.

**Comment by BahamutDragon** [comment]
Added.

**Comment by thirteenwings** [comment]
Thank you!
