### ISSUE TITLE
5e first level cleric is not able to prepare both domain spells

### ISSUE THREAD

**Issue by sculpepper** [BahamutDragon/pcgen#913]
Creating a  new dragon born cleric with +2 wisdom. I am not able to prepare both domain spells and 3 additional spells. I am only able to add 2 non domain spells and 1 domain spell.

**Comment by BahamutDragon** [comment]
This is a PCGen Code request. I am unaware of how to alter the number of Domain spells to prepare.

**Comment by thirteenwings** [comment]
In 5e, all domain spells are automatically and always prepared, you shouldn't even have to prepare them.
Ref: PHB p 58:
Domain Spells
Each domain has a list of spells—its domain spells—that you gain at the cleric levels noted in the domain description. Once you gain a domain spell, you always have it prepared, and it doesn’t count against the number of spells you can prepare each day.
If you have a domain spell that doesn’t appear on the cleric spell list, the spell is nonetheless a cleric spell for you.

**Comment by BahamutDragon** [comment]
Thanks for the rules clarification. Closing this.
