### ISSUE TITLE
Missing a couple UA files (Lore Wizard and Undying Light Warlock)

### ISSUE THREAD

**Issue by Ed-Zero** [BahamutDragon/pcgen#914]
I'm not seeing the UA files for Lore Wizard or Warlock of the Undying Light unless I'm just missing them?

Lore Wizard: https://media.wizards.com/2017/dnd/downloads/20170213_Wizrd_Wrlck_UAv2_i48nf.pdf

Warlock of the Undying Light: https://media.wizards.com/2015/downloads/dnd/02_UA_Underdark_Characters.pdf

**Comment by BahamutDragon** [comment]
Added sources.
