### ISSUE TITLE
HANDED error in log

### ISSUE THREAD

**Issue by Glassboy** [BahamutDragon/pcgen#917]
LSTERROR Thread-2 CDOMControlLoader:146 DEFAULTVARIABLEVALUE found an unsupported format: HANDED (Source: file:/opt/pcgen-6.08.00RC6/vendordata/pcgen.git/data/5e/wizards_of_the_coast/core/universal_rules/ur__datacontrols.lst )

**Comment by BahamutDragon** [comment]
Are you pulling the 6.08 branch mate? I just checked and HANDED is not in the file for the 6.08 branch.

Best,

**Comment by Glassboy** [comment]
I'm pulling "master".  Is that not the right one?

**Comment by BahamutDragon** [comment]
6.08 branch for the 6.08 version of PCGen. Master is for the development version.
