### ISSUE TITLE
catfolk lep +1 is not handled

### ISSUE THREAD

**Issue by nevarim** [BahamutDragon/pcgen#918]
catfolk in races of the wild lep +1 is not handled, if i make a rogue catfolk level 4 must be on sheet of level 5

**Comment by DennisLoos** [comment]
What template do you use ? It works for my character: 

![2019-08-21_07-57-06](https://user-images.githubusercontent.com/2235012/63406207-7ccb3800-c3e9-11e9-9294-35178a262e4e.jpg)

**Comment by nevarim** [comment]
no template, which one do you use?

**Comment by DennisLoos** [comment]
I use the export function to export to PDF and select the csheet_fantasy_blue.xslt template.

**Comment by BahamutDragon** [comment]
Looks like this is working properly. Can you confirm @nevarim ?

**Comment by BahamutDragon** [comment]
Appears to be functioning correctly. Closing.
