### ISSUE TITLE
Ghostwise halfling 

### ISSUE THREAD

**Issue by snoopyreed79** [BahamutDragon/pcgen#921]
in 3.5 I can't seem to get the Ghostwise halfling to work I set the region to Chondalwood and the Ghostwise is still in red telling me I have not meet the requirements of either selecting channath vale or the Chondalwood.

**Comment by BahamutDragon** [comment]
Fixed for 6.08. Test and confirm, please.

**Comment by BahamutDragon** [comment]
Disregard... One moment...

**Comment by BahamutDragon** [comment]
Okay, using the actual region helps. Tested locally and it works for me. Please confirm.

**Comment by snoopyreed79** [comment]
it works now thanks for your time
