### ISSUE TITLE
3.5e forgotten realms feats

### ISSUE THREAD

**Issue by snoopyreed79** [BahamutDragon/pcgen#923]
When you are selecting say moon elf you and say silverymoon region you get a feat blooded, education, smooth talk,and survivor. 

I see they are in the players_guide_to_faerun/pg_feats.lst line 23 they just don't show up in pcgen when all the requirements have been made. I even hit the tab to show unqualified and tried typing in the feat name with no luck. did I miss something?

**Comment by BahamutDragon** [comment]
You should have a First Level Only Feat choice... That is where you select the Regional Feat.
