### ISSUE TITLE
[5e - Request] Way of Astral Self | Monk Path (Playtest)

### ISSUE THREAD

**Issue by Proxxy0** [BahamutDragon/pcgen#928]
I am playing in a campaign currently and we had decided to build all of our characters using PCGen, using this overhaul. One of the players wanted to make a monk using the fairly new playtest content for monks, mainly that of _Way of the astral self_. Would it be possible to add this playtest content?

Here is a link to the content: https://media.wizards.com/2019/dnd/downloads/UA-WildAstral.pdf

Thanks for constantly updating things!

**Comment by BahamutDragon** [comment]
Playtest material added to master.
