### ISSUE TITLE
[5e] Use default carrying capacity instead of variant encumbrance

### ISSUE THREAD

**Issue by thirteenwings** [BahamutDragon/pcgen#929]
[5th Ed] The dataset currently applies the variant encumbrance rules and corresponding penalties, with no option to revert to the default and more lenient PHB carrying capacity rules.
Also, the Push/Drag value should be 30*STR, not 25*STR.
Ref: PHB page 176

**Comment by BahamutDragon** [comment]
Mate, the encumbrance rule is as the default. The PCGen program is using the rules directly from the book. Each point of strength corresponds to 15lbs of carrying capacity. 

LOAD:0|0
LOAD:1|15
LOAD:2|30
LOAD:3|45
LOAD:4|60
LOAD:5|75
LOAD:6|90
LOAD:7|105
LOAD:8|120
LOAD:9|135
LOAD:10|150

This code is using twice the value present:
ENCUMBRANCE:PushDrag|2||0

And this code is saying nothing happens till you hit the cap:
ENCUMBRANCE:Light|1||0
ENCUMBRANCE:Medium|1||0
ENCUMBRANCE:Heavy|1||0

That is in the pcgen default. I do not provide a gamemode for 5e.  By default, it is using the more lenient system. If you want those changed, you need to ask the PCGen team.

**Comment by thirteenwings** [comment]
I tried a fresh install, pcgen RC7 and the latest master. Only copied the data\5e folder into pcgen\homebrew instead of everything (including game modes, previews and sheets). I see where the problem is -- the "simple" character sheets display 5e correctly, the "std" sheets do not. This minimal install doesn't even give the std sheets as options for 5th ed, I haven't tried PF or 35e.
