### ISSUE TITLE
[5e] Character sheet does not mark proficient saves

### ISSUE THREAD

**Issue by thirteenwings** [BahamutDragon/pcgen#930]
[5th Ed] Exported to PDF character sheets do not indicate proficient saving throws.

**Comment by BahamutDragon** [comment]
Technically this should be directed towards the PCGen team. They have full control of the output sheets.

**Comment by thirteenwings** [comment]
I tried a fresh install, pcgen RC7 and the latest master. Only copied the data\5e folder into pcgen\homebrew instead of everything (including game modes, previews and sheets). I see where the problem is -- the "simple" character sheets display 5e correctly, the "std" sheets do not. This minimal install doesn't even give the std sheets as options for 5th ed, I haven't tried PF or 35e.
