### ISSUE TITLE
[5e] Weapon attack stats are computed incorrectly

### ISSUE THREAD

**Issue by thirteenwings** [BahamutDragon/pcgen#931]
[5th Ed] On the character sheet, weapon to-hit and damage stats are incorrectly calculated for offhand attacks and 2 weapon fighting. It appears that the penalties from 3.5 are being applied.

Also, ranges are shown incorrectly. All weapons display "Range: 0 ft.", range increments from 3.5 are displayed, and ranges beyond maximum are shown. It should simply show Range: short/maximum, TH, and damage.

**Comment by BahamutDragon** [comment]
Since that is OS - pdf and htm, I will see if the pcgen team can handle this request.

**Comment by thirteenwings** [comment]
I tried a fresh install, pcgen RC7 and the latest master. Only copied the data\5e folder into pcgen\homebrew instead of everything (including game modes, previews and sheets). I see where the problem is -- the "simple" character sheets display 5e correctly, the "std" sheets do not. This minimal install doesn't even give the std sheets as options for 5th ed, I haven't tried PF or 35e.
