### ISSUE TITLE
Erudite Isn't Properly Psionic

### ISSUE THREAD

**Issue by AriMatt2** [BahamutDragon/pcgen#934]
As the title says. The Erudite (at least for Elan, Human, and Synad characters) doesn't have a Psionic Caster level. This doesn't affect a whole lot of things, but there are a few things where needing Psionic Caster level does interfere with feat selection.

**Comment by BahamutDragon** [comment]
Can you list a few feats to help debug?

**Comment by BahamutDragon** [comment]
Well, I think that might fix the issue. Give it a shot.

**Comment by BahamutDragon** [comment]
Closing for now. Let me know if there is still an issue.
