### ISSUE TITLE
5e Unearthed Arcana - Bard and Barbarian latest options

### ISSUE THREAD

**Issue by jagbear** [BahamutDragon/pcgen#935]
Is there a way to get the latest Unearthed Arcana options, especially for Bard and Barbarian included?  I can help with fleshing them out, it's getting the datasets started that I'm having difficulty with.

Thank you!

**Comment by BahamutDragon** [comment]
Link to file?

**Comment by BahamutDragon** [comment]
If there are options otherwise missing please specify the file and what you want. That should be the "latest" Bard and Barbarian according the schedule I see.
