### ISSUE TITLE
3.5: Magic of Faerun - Energy Substitution type

### ISSUE THREAD

**Issue by dmcbride** [BahamutDragon/pcgen#936]
When I have both MoF and CArc loaded, Energy Substitution doesn't give Sonic as one of the choices, probably because CArc doesn't offer it as an energy type though MoF does.

**Comment by BahamutDragon** [comment]
Try that, not sure if it will work.

**Comment by dmcbride** [comment]
Seems to, thanks! (I was expecting this in master rather than 6.08, but whatever)
