### ISSUE TITLE
PCGen 608 gives SEVERE AGESET errors.

### ISSUE THREAD

**Issue by FerretDave** [BahamutDragon/pcgen#942]
Loading in any of the datasets: 3.5 core books, forgotten realms players guide, races of faerun,  expanded psionics handbook gives an error:

SEVERE: Thread blah Found second (non-identical) AGESET in Bio Settings file:
for Region: None Index: 0 using the existing 0|Adulthood
(and further errors for the other AGESETS), also indicates 'Incompatible index for AGESET ... 3 and 5 for Venerable

and lists the appropriate biosettings files as below.

35e/wizards_of_the_coast/
core/universal_rules/ur_biosettings.lst
campaign_settings/forgottten_realms/players_guide_to_faerun/pg_biosettings.lst
campaign_settings/forgottten_realms/races_of_faerun/rac_biosettings.lst
supplement/expanded_psionics_handbook/xph_biosettings.lst

The AGESET definitions within all look ok

Loading the standard RSRD source using the same style of AGESET (albeit using 0 for Adulthood) does not error.

**Comment by FerretDave** [comment]
and somehow, this is preventing me from having a valid adult Half-Orc !14 is 'Old' while any value 0-13 is 'Middle Aged' (with stat modifiers...), a negative age is flagged as adult!

**Comment by BahamutDragon** [comment]
Are you loading 35e or my 35e game system?

**Comment by FerretDave** [comment]
Greetings

*your* dnd core 35e

**Comment by FerretDave** [comment]
Greetings

Retract that, game mode _TBC

**Comment by FerretDave** [comment]
Right, sorry, reloading using your gamemode (and now using 6.08.00RC7 rather than 6.07.08!), I just get the *one* AGESET error, but do now get some others as below, I can now see what the issue is with the xph bio_settings and will fix that now.
Can you advise on the ALIGNMENTFEATURE and DOMAINFEATURE? Do I need to be running v6.09.01 for those? (which I've tried, but currently get lots of FEAT deprecated issues that I'll need to work through).

17:43:32.885 INFO main Main:138 Starting PCGen v6.08.00 RC7
17:43:32.973 INFO main LanguageBundle:134 Initialising language bundle with locale en_GB.
17:43:36.692 LSTERROR main LstUtils:147 Illegal Token 'ALIGNMENTFEATURE' 'YES' for pcgen.cdom.inst.CodeControl Controller in file:/C:/Utils/PCGen/6.08.00RC7/system/gameModes/Bahamut35e/codeControl.lst
17:43:36.693 LSTERROR main LstUtils:147 Illegal Token 'DOMAINFEATURE' 'YES' for pcgen.cdom.inst.CodeControl Controller in file:/C:/Utils/PCGen/6.08.00RC7/system/gameModes/Bahamut35e/codeControl.lst
17:44:00.232 INFO Thread-2 SourceFileLoader:534 Loading game Bahamut35e and sources [Campaign: Petes Thursday night game].
17:44:12.143 SEVERE Thread-2 BioSet:634 Found second (non-identical) AGESET in Bio Settings file:/C:/Utils/GIT/pcgen/data/35e/wizards_of_the_coast/supplement/expanded_psionics_handbook/xph_biosettings.lst for Region: None Index: 3 using the existing 3|Middle-Aged

**Comment by LegacyKing** [comment]
Hi, just reading all these emails flooding my inbox. 
6.09.x introduced those tags. You need to use 6.09.x to avoid that error. 

Also, not sure if you knew this, but BD's repo is structured to make version selection easier. Master is using the 6.09 features, while the 6.08 branch is designed to work with 6.08.x

I have to remember to switch branches when debugging people's issues on the pcgen discord. It's a commonly missed thing.

Good luck with your game!

**Comment by FerretDave** [comment]
Thank you, 6.0.9 gives different (but more workable!) errors 😀

**Comment by BahamutDragon** [comment]
Mate, have you updated the gamemode system files recently? I have tested and came back good for 6.09 against the master branch.

Unless you are using a symlink set up, you need to recopy the updated gamemode files to your pcgen system directory in the correct corresponding folder. The latest commit - 41df8e24c395acadcdbf016b75408f976e2e05c6 addresses all the fixes required to the gamemodes I made.

**Comment by FerretDave** [comment]
Greetings,

OOps, have copied the gamemode out now and submitted a PR for the
XPH_biosettings, getting no errors now, thanks.

Cheers
Dave

**Comment by ctwardy** [comment]
Thanks for your effort!

I'm getting something very similar in branch 6.08, pcgen 6.08.  I'm new to pcgen, so it's likely I made a mistake somewhere -- when I began, I had cross-wired pcgen 6.08 with your master branch.  I think I've put everything in synch, but I'm still seeing 2-3 issues. 

1. AGESET errors from `ur_biosettings.lst` for `Region: None`.  Indices 0 - 3.
2. AGESET incompatible indices: 2 & 4 for Old, 3 & 5 for Venerable
3. Trying to equip my character, clicking items generates IndexOutOfBoundsException.

Partial error log at the bottom. The character loads and prints (yay!), but perhaps I've left some scar in the character file?  

### My Config (OS X)
I'm on a Mac.  I'm running Java 13.0.1 (which took some finagling).  From the pcgen folder:
```
$ java -version
java version "13.0.1" 2019-10-15
...
$ which java
/Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home/bin/java
```
PCgen and BD Installation:
* pcgen in `~/Desktop/pcgen 6.08`, installed from zip
* BD in `~/GitHub/BahamutPCgen`, installed via 
```
git clonehttps://github.com/BahamutDragon/pcgen.git
git checkout 6.08
```
* Copied `BahamutPCgen/system/gameModes/Bahamut35e` to `Desktop/pcgen 6.08/system/gameModes/Bahamut35e` 
* In pcgen, 
  * Set Homebrew Data Directory to `/Users/**********/GitHub/BahamutPCgen`
  * Source: "Game" is set to "35e Bahamut's"
  * Books (screenshot):
![books](https://user-images.githubusercontent.com/925782/70856891-8efa4600-1eb2-11ea-9ba5-f8be3e654a6a.png)



### Key Console Errors
```
SEVERE Thread-4 BioSet:634 Found second (non-identical) AGESET in Bio Settings file:/Users/ctwardy/GitHub/BahamutPCgen/data/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst for Region: None Index: 0 using the existing 0|Adulthood
19:48:13.707 SEVERE Thread-4 BioSet:634 Found second (non-identical) AGESET in Bio Settings file:/Users/ctwardy/GitHub/BahamutPCgen/data/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst for Region: None Index: 1 using the existing 1|Middle Age	STAT|STR,CON,DEX|-1	STAT|INT,WIS,CHA|1
19:48:13.708 SEVERE Thread-4 BioSet:634 Found second (non-identical) AGESET in Bio Settings file:/Users/ctwardy/GitHub/BahamutPCgen/data/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst for Region: None Index: 2 using the existing 2|Old	STAT|STR,CON,DEX|-3	STAT|INT,WIS,CHA|2
19:48:13.709 SEVERE Thread-4 BioSet:634 Found second (non-identical) AGESET in Bio Settings file:/Users/ctwardy/GitHub/BahamutPCgen/data/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst for Region: None Index: 3 using the existing 3|Venerable	STAT|STR,CON,DEX|-6	STAT|INT,WIS,CHA|3
19:48:13.710 SEVERE Thread-4 BioSetLoader:97 Incompatible Index for AGESET in Bio Settings file:/Users/ctwardy/GitHub/BahamutPCgen/data/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst: 2 and 4 for Old
19:48:13.711 SEVERE Thread-4 BioSetLoader:97 Incompatible Index for AGESET in Bio Settings file:/Users/ctwardy/GitHub/BahamutPCgen/data/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst: 3 and 5 for Venerable



19:48:18.487 INFO AWT-EventQueue-0 CharacterManager:197 Loaded character Tim the Enchanter - /Users/ctwardy/Desktop/pcgen 6.08/characters/Tim the Enchanter.pcg
19:51:47.764 SEVERE AWT-EventQueue-0 Main:484 Uncaught error - ignoring
java.lang.IndexOutOfBoundsException: Index: -2
```

**Comment by FerretDave** [comment]
Greetings.
This is the same problem I had - you need to copy the gamemode files (
system/gamemode/Bahamut35e directory ) from the git download into the
relevant pcgen app directory (and repeat every time you install a new pcgen
version).

Then you need to *use* gamemode Bahamut35e - it's compatible with standard
35e but loads in the AGESET stuff to fix those errors.
NOTE - existing PCG files will have a 'gamemode' line in them, manually
edit that and change to Bahamut35e instead of 35e.
For any custom PCC files, you'll also have a gamemode, but there you can
set it to equal "35e|Bahamut35e" so it can be loaded in either gamemode...

Cheers
Dave
