### ISSUE TITLE
Volo Lizardfolk abilities not loading, also language and "hungry jaws" not inplemented on LST

### ISSUE THREAD

**Issue by v13jf9** [BahamutDragon/pcgen#949]
i cant get Volos Lizardfolk anything to load in, also looking at the lst it language and Hungry jaws racial abilites arent inplemented
![Lizardfolk](https://user-images.githubusercontent.com/7107774/69930002-d500e400-1486-11ea-99e2-d128753db988.png)

**Comment by v13jf9** [comment]
[Aryte.pdf](https://github.com/BahamutDragon/pcgen/files/3909384/Aryte.pdf)

**Comment by v13jf9** [comment]
let me know what else you need to diag but also Barbarians Path of Ancestral Guardians Ancestral Protectors descriptions arent in there on the output sheet, but regardless i attempted to make corrections to the LST but idk if it helped can i get a review on it as well (modified and original LST included)
[vgm_abilities - modified.txt](https://github.com/BahamutDragon/pcgen/files/3909400/vgm_abilities.-.modified.txt)
[vgm_abilities - Original.txt](https://github.com/BahamutDragon/pcgen/files/3909401/vgm_abilities.-.Original.txt)

**Comment by BahamutDragon** [comment]
Bite and Languages implemented.

**Comment by BahamutDragon** [comment]
Primal path should now display.
