### ISSUE TITLE
Book of Exalted Deeds-3.5e

### ISSUE THREAD

**Issue by gwav** [BahamutDragon/pcgen#951]
Found an error with **WildShapeLVL**.  You need to be level 8 for the Exulted Wild Shape, in all the leveling of a Druid (for example) the **WildShapeLVL** is always 1.  In the book p.40 it describes the prerequisite as "Wild shape class ability, wild shaping class level 8th".
Hope this helps.
Thank you so very much for all the hard work you have done, I personally do appreciate it.
Gary

**Comment by BahamutDragon** [comment]
Missing DEFINE added. Fixed now.
