### ISSUE TITLE
Iron Ward Diamond (Greater) does not grant DR 5/- when sloted in the armor e35

### ISSUE THREAD

**Issue by swtrse** [BahamutDragon/pcgen#953]
If you equiped the Ward Diamond (Greater) in the Crystal slot of the armor no DR is granted.
The workarount is not to slot the crystal in the armor but to put it in the inventory as equipped.

**Comment by BahamutDragon** [comment]
Yeah, I am not a PCGen Code monkey. That would be an issue to raise over on their official channels. I just do my best with the program restrictions.

**Comment by swtrse** [comment]
I just got confirmation that this is a known bug in PCGen. However due to the lack of Java Developers this bug will most likeley never be fixed.
Source: https://pcgenorg.atlassian.net/browse/CODE-3500
