### ISSUE TITLE
Customisation of Deck of Many Things not possible e35

### ISSUE THREAD

**Issue by swtrse** [BahamutDragon/pcgen#954]
I used tu create custon version of the Deck of Many Things to represent the specific cards a character has drawn. With the current sources it is only possible to add modifier "Add Type" or "Intelligent Item".
With the default sources of PCGen 6.06 it was possible to add all kind of different modifiers.

For example I created an Item
Deck of Many Things (Throne) with an Skill bonus of +6 to diplomacy.

This is currently not possible.

**Comment by BahamutDragon** [comment]
Add the new item "Custom Magic" and you will see a new slew of options.
