### ISSUE TITLE
Monk - Unarmed Strike

### ISSUE THREAD

**Issue by jagbear** [BahamutDragon/pcgen#955]
For a monk's unarmed strike, I'm seeing the damage as 1d4+1 and the attack bonus as +3, The strength is 16 and the Dex is 18.   The level is 4 and the proficiency bonus is +2.  Shouldn't the attack bonus be +6 and the damage be 1d4+4?   I am using 6.08 RC8 and the files from the 6.08 branch.
[Eithan Arelius.pdf](https://github.com/BahamutDragon/pcgen/files/4008070/Eithan.Arelius.pdf)

**Comment by BahamutDragon** [comment]
Tested and now works.
