### ISSUE TITLE
Warlock Hexblade Patron Expanded Spell List Spell Spells don't show up at lvl 1

### ISSUE THREAD

**Issue by Vaol95** [BahamutDragon/pcgen#957]
When creating a Warlock and pick a patron at first level the spells gainign by the extended spell list won't show up 'till leveling up to level 2. Is this a known problem or is there any workaround to this problem.

Downloaded sources yesterday.
Following sorces are loaded:
Adventure - Lost Mine of Phandelver; Out of the Abyss; Tyranny of Dragons
Dungeons & Dragons 5e - Core Books
Elemental Evil Players Companion
Mordekeinen's Tome of Foes
Plana Shift: Ammoreth; Dominaria; Innistrad; Ixalan; Kaladesh; Zendikar
Sword Coast Adventurer's Guide
Unearthed Arcana: Feats; Feats for Skilld; Light Dark Underdark; Psionic; Revised Ranger; Sorcerer; Warlock and Wizard; Waterborne Adventures; Artificer; Barbarian and Monks; Barbarian Primal Paths; Bard and Paladin (2019-09-18); Eberron; Races of Eberron; The Old Black Magic; Volo's Guide to Monsters; Xanathar's Guide to Everything
PCGen Builds in use: v6.08.00 RC7 & v6.08.00 RC8

**Comment by BahamutDragon** [comment]
Known issue. Besides leveling, you can save then reload the character.
