### ISSUE TITLE
Temporary Bonuses

### ISSUE THREAD

**Issue by drklassen** [BahamutDragon/pcgen#958]
My character was recently affected by a Night Hag so has a loss of max hit points until he can get Greater Restoration.  I went to the Temporary Bonuses tab to see if there was something there to let me note this, but find that area completely empty.  Is there some setting I need to use to get the standard temp bonuses to show up?

**Comment by BahamutDragon** [comment]
Which game system? 3e, 3.5e, 4e, 5e or something else?

**Comment by drklassen** [comment]
Sorry, 5e.

I just don't see anything on that tab at all.

**Comment by BahamutDragon** [comment]
Updated for both master and 6.08. I hope that helps!
