### ISSUE TITLE
Critical Role

### ISSUE THREAD

**Issue by OmegaDarkMatter** [BahamutDragon/pcgen#965]
Can we get the Taldori source book working again

**Comment by BahamutDragon** [comment]
I do not recall having this set ever working before. It was a fun little tinkering project before my group stopped playing. Glancing it over, it should reasonably work with maybe a few errors as-is. 

To have it appear in your list, simply remove the '#' from before the gamemode tag in the *.pcc file.

**Comment by BahamutDragon** [comment]
This is now available. No additional work has been made. Closing this issue.
