### ISSUE TITLE
Healer Class

### ISSUE THREAD

**Issue by Aknagtor** [BahamutDragon/pcgen#966]
Hey Mate,
I know youre only at 25% of the Miniatures Handbook. Wanna know if youre still gonna update it or should i do it manually?

**Comment by BahamutDragon** [comment]
Generally, unless asked for something specific, I have stopped working on most of the books. I have a book request still outstanding that I want to eventually finish.  If you are willing to do the work and submit that to the community, awesome!  If not, I can add that to the list of requests.

**Comment by Aknagtor** [comment]
Im no good at coding, so it would be nice if you add it to your list.

**Comment by BahamutDragon** [comment]
Looking at this now.

**Comment by BahamutDragon** [comment]
Basic Healer set up. Companion is not set up.

**Comment by BahamutDragon** [comment]
Healer and Companion should be working. However, due to limitations, there is no method to choose the higher of Master Saves and Companion saves.
