### ISSUE TITLE
is there a way to convert a pcg file to etools chr ?

### ISSUE THREAD

**Issue by beppe9000** [BahamutDragon/pcgen#967]

**Comment by BahamutDragon** [comment]
I am not aware of the requirements necessary to make this happen. E-tools and PCGen are completely separate programs with different data I would imagine. The pcg files is a pointer and repository of fact to recreate that character in PCGen's format.  Most character creation programs are easy to use and recreating a favorite character is not a hard task.  The best you could hope to do would be to export ALL the data from the character into a file format (htm or text) that would potentially be readable by E-Tools. But again, I do not have that program and cannot help you in this matter.

**Comment by beppe9000** [comment]
I realized etools can't import the XML format it exports to... and the chr file is binary content (most likely the xml encoded in some way like zip). 

[I attach an example for the sake of completeness...](https://github.com/BahamutDragon/pcgen/files/4343694/SkanderExport.zip)

But yeah, it's probably easier to just transcribe sheets.
