### ISSUE TITLE
Strange bug with wizard

### ISSUE THREAD

**Issue by beppe9000** [BahamutDragon/pcgen#970]
Yesterday I made a lvl10 d&d 3.5 wizard it had negative 18 jump modifier in the rightmost column (for other modifiers)

**Comment by BahamutDragon** [comment]
Modifiers to Jump are based upon speed. Was the character encumbered or otherwise without a speed value?

**Comment by beppe9000** [comment]
I might have missed that, most likely that is the cause... 
I  don't remember setting the speed, but I did set the race (Elf). I will check the encumbrance, I probably shopped too many bolts...

**Comment by beppe9000** [comment]
indeed it was that. I also found this 😆 
![image](https://user-images.githubusercontent.com/6625123/77248184-c3ab3580-6c37-11ea-889d-fe4e83306545.png)

**Comment by BahamutDragon** [comment]
There is no rule override for the Jump modifier using speed. The encumbrance house rule is broken.

Create Magic Tatoo vs Tattoo. Good catch.
