### ISSUE TITLE
"Cannot load campaign"

### ISSUE THREAD

**Issue by Menethoran** [BahamutDragon/pcgen#971]
Hey Bahamut,

Getting significant crashes when loading custom data... PCGen will not allow me to load your mods... AM I doing something wrong?

here are my logs:
https://pastebin.com/Ch3xhRcn

**Comment by Menethoran** [comment]
OK, cleared that up... needed a different set of Basic rules (the PHB Beta) to allow the epic levels to seem to load... but theres still no way to do anything with the epic levels stuff... any advice?

Here is a new paste of my logs with only loading PHB Beta rules and Epic levels... still throws lots of errors:

https://pastebin.com/x8hwDGaD

**Comment by Menethoran** [comment]
OK, so... While I still have lots of errors in the logs that I'd like to clean up... it does appear that the epic stuff does, indeed, carry through... Theres no way to change the XP table it uses, so, XP stops at 355,000... BUT, the epic benefits do appear to be appearing on the character sheet (ie: lvl 21 paladin gets improved lay on hands)…

any help is appreciated...

**Comment by BahamutDragon** [comment]
Looking at this now.

**Comment by BahamutDragon** [comment]
Fixed. Loads without error on Master with latest PCGen 6.09.03-DEV. Back ported the fix to 6.08

**Comment by BahamutDragon** [comment]
The XP will need to be updated next...

**Comment by BahamutDragon** [comment]
A note was sent to a pcgen developer. They will handle the XP.
