### ISSUE TITLE
Unable to load sources

### ISSUE THREAD

**Issue by TwistedFaith84** [BahamutDragon/pcgen#975]
So I just downloaded the newest nightly version of pcgen and you master data for it. The problem I'm having (which I thing was the same problem I had b4 and just went back to HeroForge) is I have all the sources I wanna use selected and when i go to load it stops loading at file name "mm_kits.lst" I'm including my log on [here](https://pastebin.com/6mm7jbJh)

**Comment by TwistedFaith84** [comment]
Hello???

**Comment by BahamutDragon** [comment]
That is a lot of errors. Working through them.

**Comment by BahamutDragon** [comment]
That should cover the NPEs and majority of the errors.

**Comment by TwistedFaith84** [comment]
Ok so I completely uninstalled and reinstalled everything and Still getting stuck at the same place when trying to load sources.
[https://pastebin.com/2Uvd4dF9](pastebiin)

**Comment by TwistedFaith84** [comment]
Should I try with PCGens Latest Stable Version and your version that goes with that and see if that works?

**Comment by TwistedFaith84** [comment]
Ok so doing a little testing by having all books added and then removing them 1x1 as soon as I remove Monster Manual II everything becomes red (unable to load) I'm guessing that that might have something to do with it (ie maybe Monster Manual II is loading like its Monster Manual) so Monster Manual II kits might accidently be misnamed mm_kits as well instead of mm2_kits or something like that

**Comment by BahamutDragon** [comment]
I have corrected the load errors in your log, but I would strongly advise against loading different campaign settings, and not load Complete Divine with Oriental adventures.
