### ISSUE TITLE
Book Request Kingdoms Of Kalamar 3.5 (Single Book)

### ISSUE THREAD

**Issue by TwistedFaith84** [BahamutDragon/pcgen#976]
I dont know what there situation is as far as OpenGL or whatnot but can you add the Kingdoms Of Kalamar books for 3e and 3.5. I know they were/are official books for D&D; Hackmaster [what the company is known as now] did team up with WotC to make that Campaign Setting for 3e/3.5, I think 4th (not sure if hack mast wanted nothing to do with 4th like so many of us or not), and 5th

**Comment by TwistedFaith84** [comment]
@BahamutDragon

**Comment by BahamutDragon** [comment]
I would have to see if I have those books in my collection.

**Comment by TwistedFaith84** [comment]
If you want or need PDF's you can try [TheTrove](http:\\thetrove.net)

**Comment by BahamutDragon** [comment]
3.5 is completed.

**Comment by BahamutDragon** [comment]
If you want other books or editions, please open them in a separate request.

**Comment by TwistedFaith84** [comment]
If I may ponder which book was added and where exactly (in the data folder) is it located

**Comment by TwistedFaith84** [comment]
NVM found it
