### ISSUE TITLE
Support Background Customization Rules

### ISSUE THREAD

**Issue by monyarm** [BahamutDragon/pcgen#979]
The PHB let's you create a custom background, choosing proficiencies, a name, and a feature from any background feature.

**Comment by BahamutDragon** [comment]
That is quite the request. I do not have the bandwidth for a project that massive currently.

Phase 0: Toggle Custom Background selection vs. standard backgrounds.
Phase 1: Redo all existing Class Features to be selectable from a master selector
Phase 2: Toggle a master Proficiency selector (How many is allowed?)
Phase 3: Redo the OS sheets/Preview sheet to accept a custom name
Phase 4: Set up the Custom Name

Estimate about 6 hours' worth of labor in this small request.

**Comment by TwistedFaith84** [comment]
Shouldn't this request be more for the guys and gals over at PCGen themselves?

**Comment by BahamutDragon** [comment]
If you can convince the PCGen team to tackle this then I would be able to follow suit. I still would have a lot of work to make this request work though.
