### ISSUE TITLE
Please add Awesome Smite Feat from Complete Champion

### ISSUE THREAD

**Issue by crobibero** [BahamutDragon/pcgen#980]
Using PCGEn 6.08
Game: 3.5e

Sources Loaded: 
Complete Adventurer
Complete Arcane
Complete Champion
Complete Divine
Complete Warrior
Dungeons & Dragons - Core Books

9 Ranks in Paladin

Awesome Smite:
Requirements: all of (at least 1 TYPE Smite Special Ability)

Paladin has Smite Evil as a class feat

**Comment by BahamutDragon** [comment]
Added and addressed.
