### ISSUE TITLE
[5e] Minotaur and Simic Hybrid Races from Guildmaster's Guide to Ravnica

### ISSUE THREAD

**Issue by jagbear** [BahamutDragon/pcgen#984]
Particularly the minotaur and Simic Hybrid races.

Thank you!

**Comment by BahamutDragon** [comment]
PDF link would help...

**Comment by jagbear** [comment]
https://drive.google.com/file/d/13XkerGIe5XEA_jSwh8LQZYiHFTnlw3uE/view?usp=sharing

**Comment by BahamutDragon** [comment]
Races added
