### ISSUE TITLE
Human Feats and languages

### ISSUE THREAD

**Issue by teddwyer** [BahamutDragon/pcgen#986]
When I create a Human the additional feat is unavailable to the new character. I think I have found a workaround by selecting other in feats and forcing an additional feat.. but the primary screen shows that there are too many feats selected.  Same with additional Languages...  When I build a character using the non home-brew then load them with the home-brew they are indicating these two issues.

**Comment by BahamutDragon** [comment]
Humans either get the Stat boost (Typical) or the feat. How are you making the character?

**Comment by BahamutDragon** [comment]
No follow up from OP. Closing.

**Comment by teddwyer** [comment]
sorry, this went to my spam folder the character was made before I
downloaded the homebrew... and when I loaded it with the homebrew it
indicated that I had too many feats... I had selected the feat option and
not the stat-boost.
