### ISSUE TITLE
Unearthed Arcana Request

### ISSUE THREAD

**Issue by INUYAHA** [BahamutDragon/pcgen#987]
Unearthed Arcana Subclasses released 1/14/20, 2/6/20, 2/24/20.

I would do it myself but I dont even know where to begin.

https://media.wizards.com/2020/dnd/downloads/UA2020-Subclasses01.pdf
https://media.wizards.com/2020/dnd/downloads/UA2020_02_06_Subclasses2.pdf
https://media.wizards.com/2020/dnd/downloads/UA2020-Subclasses03_0224.pdf

**Comment by BahamutDragon** [comment]
Text editor and mainly lots of copying and pasting. This might be a bit to get to as there are a couple of other requests I need to clear off the queue.

**Comment by BahamutDragon** [comment]
2020-01 completed

**Comment by BahamutDragon** [comment]
This is completed.
