### ISSUE TITLE
Death Knell as a spell effect (3.5e)

### ISSUE THREAD

**Issue by cernenwein** [BahamutDragon/pcgen#988]
Can someone add this spell to the ongoing spell effects?

https://www.d20srd.org/srd/spells/deathKnell.htm#:~:text=Necromancy%20%5BDeath%2C%20Evil%5D&text=Upon%20casting%20this%20spell%2C%20you,a%20%2B2%20bonus%20to%20Strength.

You draw forth the ebbing life force of a creature and use it to fuel your own power. Upon casting this spell, you touch a living creature that has -1 or fewer hit points. If the subject fails its saving throw, it dies, and you gain 1d8 temporary hit points and a +2 bonus to Strength. Additionally, your effective caster level goes up by +1, improving spell effects dependent on caster level. (This increase in effective caster level does not grant you access to more spells.) These effects last for 10 minutes per HD of the subject creature.

**Comment by BahamutDragon** [comment]
It already exists. Are you unable to activate it with your caster?

**Comment by cernenwein** [comment]
as a Class ability as a Blood Magus, I cannot find it

**Comment by BahamutDragon** [comment]
Should now be accessible.
