### ISSUE TITLE
Request: Xanathar's Monk Archetypes

### ISSUE THREAD

**Issue by woofdunlap** [BahamutDragon/pcgen#989]
Would you please add the Monk archetypes from Xanathar's Guide to Everything?
Way of the Kensei
Way of the Drunken Master
Way of the Sun Soul

to the 6.08 branch

Thank you

**Comment by BahamutDragon** [comment]
Mate, I just checked and everything in Xanathar's Guide to Everything, including the archetypes, present on Master are in the 6.08 branch.

**Comment by woofdunlap** [comment]
Sorry, I guess I was expecting more then just DESC

**Comment by BahamutDragon** [comment]
Ah, you wanted them to do something. List the ones that have an impact and I will tackle that tonight.

**Comment by woofdunlap** [comment]
Kensei is the one I am really look for.

Thank you

**Comment by BahamutDragon** [comment]
Kensei fleshed out.

**Comment by woofdunlap** [comment]
Thank you!!!
