### ISSUE TITLE
Issue with Revised Ranger

### ISSUE THREAD

**Issue by Connorathomson121297** [BahamutDragon/pcgen#990]
When I choose the Revised Ranger and try to add a level, the program bugs out and doesn't add the and then freezes. 
Edit: when looking at the log it throws this at me
[pcgen.log](https://github.com/BahamutDragon/pcgen/files/4793667/pcgen.log)

**Comment by BahamutDragon** [comment]
The log indicates you are using the 6.08.RC4 version of PCGen with the Master Branch data.

Please download the 6.08 Branch data to have the program function properly.
