### ISSUE TITLE
Leadership lack

### ISSUE THREAD

**Issue by liquidspeaker** [BahamutDragon/pcgen#991]
This is a beautiful repo for people, you're awesome, i was just wondering if there was any plan of adding some of the supplemental feat sets like HOB extra followers and whatnot?

**Comment by liquidspeaker** [comment]
Sorry, I'm talking about 3.5s extra followers, assemble the horde, even epic leadership doesnt make your leadership epic. Just throwing some feedback atcha.

**Comment by BahamutDragon** [comment]
Do you have the PDF? Or perhaps the book name(s)? Or are you asking for the existing items to be implemented?

**Comment by liquidspeaker** [comment]
as of now just trying to see the level on followers brought up to epic, which already exists, just isn't implemented. as well as the implementation of great diplomat which is the same.

**Comment by liquidspeaker** [comment]
My apologies for not throwing out that it was in 3.5e. Here's the break down:
Epic Leadership: A present feat that is not functioning correctly. It's not calculating epic level amount of followers.Found in the epic level handbook on table 1-33 at the top of page 37.
Great Diplomat is a current feat that is not adding a second cohort. found on page 63 of Oriental adventures.
Extra Followers feat on page 97 of heroes of battle is not adding followers though it is currently pick-able.
My apologies again for not getting everything out correctly in the first post, further posts will be more efficient.

**Comment by BahamutDragon** [comment]
Epic Leadership implemented on 6.08 now. The others need investigation.

**Comment by BahamutDragon** [comment]
GREAT DIPLOMAT [ANCESTOR]
You are descended from Asako, one of the companions of the
first Phoenix, a great healer, diplomat, and warrior.
Clan : Phoenix.
Benefit: You gain a +2 bonus on Diplomacy checks, and
your Leadership score (see the DUNGEON MASTER's Guide) is increased
by 2.

**Comment by BahamutDragon** [comment]
I have implemented the listed feats as requested.
