### ISSUE TITLE
Sun Elfes Race Adjustment

### ISSUE THREAD

**Issue by snoopyreed79** [BahamutDragon/pcgen#996]
Right now Race adjustment is -2 dexterity and +2 intelligence. It should be -2 constitution and +2 intelligence 
Thanks for your time

**Comment by snoopyreed79** [comment]
This is forgotten realms 3.5e

**Comment by BahamutDragon** [comment]
Send a character file. What I have is -2 Con and +2 Int in the code.

**Comment by snoopyreed79** [comment]
her is a sun elf i just put together hope it helps

**Comment by BahamutDragon** [comment]
Looks like you sent an email reply. I do not see any attachment here.

**Comment by snoopyreed79** [comment]
[sun elf test.zip](https://github.com/BahamutDragon/pcgen/files/4921667/sun.elf.test.zip)


ok lets see if this worked lol

**Comment by BahamutDragon** [comment]
Fixed for both 6.08 and master.

**Comment by snoopyreed79** [comment]
Thanks for your time
