### ISSUE TITLE
Gloamings Movement

### ISSUE THREAD

**Issue by snoopyreed79** [BahamutDragon/pcgen#997]
When making the gloaming i noticed the walk speed, fly speed, and that the flight is average maneuverability is not being inputted. without that it makes the jump skill have a -20. 

thanks for you time 
S. Reed

**Comment by BahamutDragon** [comment]
I shall have to rectify this oversight.

**Comment by snoopyreed79** [comment]
I have also been getting the character load failed. The error was:  pcgen.core.ablilty reference portal sensitive  has not been resolved

**Comment by BahamutDragon** [comment]
Movement rates were already present - Walk 20, Fly 40. Added the maneuverability for fly though.

**Comment by BahamutDragon** [comment]
Added all the missing feats, though no actual benefits coded for those.
