### ISSUE TITLE
Dragonblood Sorcerer replacement level doesn't count as a sorcerer for draconic feats

### ISSUE THREAD

**Issue by nukestarmaster** [BahamutDragon/pcgen#999]
When the 3.5e dragonblood sorcerer first level substitution from races of the dragon is used the requirement "var: SorcererLevelForDraconicFeat at least 1" highlights red for all draconic feats requiring sorcerer levels (even including the draconic heritage feat which the level substitution gets instead of a familiar).

**Comment by BahamutDragon** [comment]
This should now be fixed. 

As a side note, the substitution class dialog appears to be broken in the 6.09.x line of PCGen.
